### PR TITLE
Convert Chat Service to non-blocking kitteh irc

### LINKED ISSUE #1391: Chat test are a nightmare
REALLY bad things are going on with tests inside the `chat` package. Wether tests succeed or fail depends on wether other tests in that package run and in which order. These dependencies exist across classes, which means execution of some test classes affects tests in other classes. Same goes for log output.

if tests are not executed in certain orders, some tests may hang indefinitely.

The cause of these problems seem to have a lot to do with:
- `AbstractChatTabControllerTest`
- `PrivateChatTabControllerTest`

### LINKED ISSUE #1892: Crazy memory spikes when running for a long time
[Issuehunt badges](https://issuehunt.io/r/FAForever/downlords-faf-client/issues/1892)

98c35a63-08a9-45d5-9e23-7a40c128a76b

---

<details>
<summary>
<b>IssueHunt Summary</b>
</summary>

### Backers (Total: $60.00)

- [1-alex98 1-alex98](https://issuehunt.io/u/1-alex98) ($20.00)
- $40.00 have been anonymously funded.
### Submitted pull Requests
- [#2126 Convert Chat Service to non-blocking kitteh irc](https://issuehunt.io/r/FAForever/downlords-faf-client/pull/2126)
---

### Tips

- Checkout the [Issuehunt explorer](https://issuehunt.io/r/FAForever/downlords-faf-client/) to discover more funded issues.
- Need some help from other developers? [Add your repositories](https://issuehunt.io/r/new) on IssueHunt to raise funds.
</details>

### LINKED ISSUE #1925: User list empty chat
**Describe the bug**
On startup chat user list stays empty

**To Reproduce**
Probably a race condition

**Log or error message**
This is my log file:
```
Exception in thread "JavaFX Application Thread" java.lang.NullPointerException
	at com.sun.javafx.collections.ObservableListWrapper.removeAll(ObservableListWrapper.java:173)
	at com.faforever.client.chat.ChannelTabController.lambda$onUserLeft$37(ChannelTabController.java:554)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:428)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:427)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run$$$capture(InvokeLaterDispatcher.java:96)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java)
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(WinApplication.java:174)
	at java.base/java.lang.Thread.run(Thread.java:832)
```
**Expected behavior**
The chat controllers are loaded before these kind of events.

**OS**
Linux or Windows

**Wanna have the bug fixed quickly?**
Visit Issue hunt...
[Issue hunt](https://issuehunt.io/r/FAForever/downlords-faf-client)

### PR DESCRIPTION
**Pull request by Sheikah45**
This changes the chat service implementation to use kitteh irc library which utilizes netty and is non-blocking. I have observed decreases in both cpu and gpu load with this implemented. 

Also in my opinion this gives us more flexible and straightforward way to interact with the irc vs pircbotx

This also allows us to move away from the modified pircbotx library

---

<details>
<summary>
<b>IssueHunt Summary</b>
</summary>

### Referenced issues

This pull request has been submitted to:
- [#1892: Crazy memory spikes when running for a long time](https://issuehunt.io/repos/32919066/issues/1892)
---
</details>

### CODE REVIEW

**Comment by Sheikah45** [comment]
This should also definitely close #1892

**Comment by Sheikah45** [comment]
Hmm it is lower at over time but am running into a high startup cost for some reason

File: src/main/java/com/faforever/client/chat/ChatChannel.java [hunk 1]
```diff
@@ -14,14 +14,14 @@
 import java.util.List;
 import java.util.Optional;
 
-public class Channel {
+public class ChatChannel {
```
Comment (Brutus5000) [inline src/main/java/com/faforever/client/chat/ChatChannel.java:16]: If everything is immutable consider making it a lombok `@Value` class

File: src/main/resources/i18n/messages.properties [hunk 2]
```diff
@@ -118,7 +118,7 @@ statusBar.taskWithoutMessage.format={0}
 statusBar.taskWithMessage.format={0}: {1}
 news.authoredFormat={0} on {1,date}
 chat.noOpenChats=No chats are open
-chat.joinAChannel=Join a channel
+chat.joinAChannel=Join a chatChannel
```
Comment (Brutus5000) [inline src/main/resources/i18n/messages.properties]: Derp all across this file xD

File: src/main/resources/i18n/messages_ru.properties [hunk 3]
```diff
@@ -99,7 +99,7 @@ statusBar.taskWithoutMessage.format = {0}
 statusBar.taskWithMessage.format = {0}\: {1}
 news.authoredFormat = {0} в {1,date}
 chat.noOpenChats = Нет открытых чатов
-# i assume channel == chat
+# i assume chatChannel == chat
```
Comment (Brutus5000) [inline src/main/resources/i18n/messages_ru.properties]: derp

File: src/main/resources/theme/chat/channel_tab.fxml [hunk 4]
```diff
@@ -61,7 +61,7 @@
             </VBox>
 
             <VBox fx:id="channelTabScrollPaneVBox" maxHeight="1.7976931348623157E308"
-                  styleClass="chat-channel-users-pane" SplitPane.resizableWithParent="false" minWidth="300.0">
+                  styleClass="chat-chatChannel-users-pane" SplitPane.resizableWithParent="false" minWidth="300.0">
```
Comment (Brutus5000) [inline src/main/resources/theme/chat/channel_tab.fxml]: probably unintended

File: src/main/resources/theme/chat/private_chat_tab.fxml [hunk 5]
```diff
@@ -8,7 +8,7 @@
 <?import javafx.scene.layout.VBox?>
 <?import javafx.scene.web.WebView?>
 <Tab xmlns:fx="http://javafx.com/fxml/1" fx:id="privateChatTabRoot" xmlns="http://javafx.com/javafx/8.0.111"
-     fx:controller="com.faforever.client.chat.PrivateChatTabController" styleClass="private-channel-tab">
+     fx:controller="com.faforever.client.chat.PrivateChatTabController" styleClass="private-chatChannel-tab">
```
Comment (Brutus5000) [inline src/main/resources/theme/chat/private_chat_tab.fxml]: probably unintended

File: src/main/java/com/faforever/client/chat/TrustAllTrustManagerFactory.java [hunk 6]
```diff
@@ -0,0 +1,41 @@
...
+
+import javax.net.ssl.ManagerFactoryParameters;
+import javax.net.ssl.TrustManager;
+import javax.net.ssl.TrustManagerFactory;
+import javax.net.ssl.TrustManagerFactorySpi;
+import javax.net.ssl.X509TrustManager;
+import java.security.KeyStore;
+import java.security.cert.X509Certificate;
+
+public class TrustAllTrustManagerFactory extends TrustManagerFactory {
```
Comment (Brutus5000) [inline src/main/java/com/faforever/client/chat/TrustAllTrustManagerFactory.java]: TrustAllTrust? Weird name :D
Maybe TrustEverony or TrustUntrusted

File: src/main/java/com/faforever/client/chat/KittehChatService.java [hunk 7]
```diff
@@ -0,0 +1,539 @@
...
+      default -> ChatUserCategory.OTHER;
+    };
+  }
+
+
+  private ChatChannelUser getOrCreateChatUser(User user, String channelName) {
+    String username = user.getNick();
+
+    boolean isModerator = client.getChannel(channelName).stream()
+        .flatMap(channel -> channel.getUserModes(user).stream().flatMap(Collection::stream))
```
Comment (Brutus5000) [inline src/main/java/com/faforever/client/chat/KittehChatService.java]: Instead of double flatmap maybe split it into 2 lines

File: src/main/java/com/faforever/client/chat/KittehChatService.java [hunk 8]
```diff
@@ -0,0 +1,539 @@
...
+  }
+
+  @Handler
+  private void onPrivateMessage(PrivateMessageEvent event) {
+    User user = event.getActor();
+    log.debug("Received private message: {}", event);
+
+    ChatChannelUser sender = getOrCreateChatUser(user.getNick(), user.getNick(), false);
+    if (sender != null
+        && sender.getPlayer().isPresent()
```
Comment (Brutus5000) [inline src/main/java/com/faforever/client/chat/KittehChatService.java]: you can skip this check if you use .map(Player::getSocialStatus) on the optional and then `== Optional.of(SocialStatus.FOE)`

**Review by Brutus5000 — CHANGES_REQUESTED** [review]

File: src/main/resources/i18n/messages.properties (hunk 2 above)
Comment (Sheikah45) [reply src/main/resources/i18n/messages.properties]: ah missed the refactor by intellij

**Comment by Sheikah45** [comment]
Was able to fix the high startup. It was querying who for every channel on join and I just set the logic to do that to false.

**Comment by Katharsas** [comment]
Nice!
