### PR TITLE
Don't omit coop maps from the local map list

### LINKED ISSUE #1560: Replay file not showing/working for all coop maps
I joined a random guy to play coop on "Black Day".
Local replay file for coop game does not exist, log does not show anu error.
Online replay exist but shows "on an unknown map" as map and cannot be viewed (throws error).

I can reproduce this on Black Day and Dawn (didnt test others) so i guess this affects all coop maps.
Client version 1.1.2

Replay id: 10893152
https://content.faforever.com/faf/vault/replay_vault/replay.php?id=10893152


<details>
  <summary>Error thrown when clicking on watch:</summary>

```
java.util.concurrent.CompletionException: java.io.FileNotFoundException: https://content.faforever.com/faf/vault/maps/none.zip
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(Unknown Source)
	at com.faforever.client.task.CompletableTask.lambda$new$1(CompletableTask.java:17)
	at javafx.base/com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(Unknown Source)
	at javafx.base/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(Unknown Source)
	at javafx.base/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(Unknown Source)
	at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at javafx.base/com.sun.javafx.event.EventUtil.fireEventImpl(Unknown Source)
	at javafx.base/com.sun.javafx.event.EventUtil.fireEvent(Unknown Source)
	at javafx.base/javafx.event.Event.fireEvent(Unknown Source)
	at javafx.graphics/javafx.concurrent.EventHelper.fireEvent(Unknown Source)
	at javafx.graphics/javafx.concurrent.Task.fireEvent(Unknown Source)
	at javafx.graphics/javafx.concurrent.Task.setState(Unknown Source)
	at javafx.graphics/javafx.concurrent.Task$TaskCallable.lambda$call$2(Unknown Source)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$9(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$10(Unknown Source)
	at javafx.graphics/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(Unknown Source)
	at javafx.graphics/com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at javafx.graphics/com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.io.FileNotFoundException: https://content.faforever.com/faf/vault/maps/none.zip
	at java.base/jdk.internal.reflect.GeneratedConstructorAccessor100.newInstance(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.base/java.lang.reflect.Constructor.newInstance(Unknown Source)
	at java.base/sun.net.www.protocol.http.HttpURLConnection$10.run(Unknown Source)
	at java.base/sun.net.www.protocol.http.HttpURLConnection$10.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getChainedException(Unknown Source)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(Unknown Source)
	at com.faforever.client.map.DownloadMapTask.call(DownloadMapTask.java:54)
	at com.faforever.client.map.DownloadMapTask.call(DownloadMapTask.java:21)
	at javafx.graphics/javafx.concurrent.Task$TaskCallable.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	... 1 more
Caused by: java.io.FileNotFoundException: https://content.faforever.com/faf/vault/maps/none.zip
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getHeaderField(Unknown Source)
	at java.base/java.net.URLConnection.getHeaderFieldLong(Unknown Source)
	at java.base/java.net.URLConnection.getContentLengthLong(Unknown Source)
	at java.base/java.net.URLConnection.getContentLength(Unknown Source)
	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getContentLength(Unknown Source)
	at com.faforever.client.map.DownloadMapTask.call(DownloadMapTask.java:50)
	... 6 more

```

</details>

<details>
  <summary>Downlords log (whne game was played):</summary>

```
2020-01-19 01:09:17.505  WARN 9580 --- [Thread-12] c.f.client.remote.FafServerAccessorImpl  : Lost connection to Server

java.net.SocketTimeoutException: Read timed out
	at java.base/java.net.SocketInputStream.socketRead0(Native Method)
	at java.base/java.net.SocketInputStream.socketRead(Unknown Source)
	at java.base/java.net.SocketInputStream.read(Unknown Source)
	at java.base/java.net.SocketInputStream.read(Unknown Source)
	at java.base/java.net.SocketInputStream.skip(Unknown Source)
	at java.base/java.io.BufferedInputStream.skip(Unknown Source)
	at java.base/java.io.DataInputStream.skipBytes(Unknown Source)
	at com.faforever.client.remote.io.QDataInputStream.skipBlockSize(QDataInputStream.java:55)
	at com.faforever.client.remote.AbstractServerAccessor.blockingReadServer(AbstractServerAccessor.java:38)
	at com.faforever.client.remote.FafServerAccessorImpl$1.call(FafServerAccessorImpl.java:250)
	at com.faforever.client.remote.FafServerAccessorImpl$1.call(FafServerAccessorImpl.java:221)
	at javafx.graphics/javafx.concurrent.Task$TaskCallable.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at javafx.graphics/javafx.concurrent.Service.lambda$executeTask$6(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at javafx.graphics/javafx.concurrent.Service.lambda$executeTask$7(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)

2020-01-19 01:09:17.536  WARN 9580 --- [Thread-12] c.f.client.remote.ReconnectTimerService  : Lost connection to FAF server, trying to reconnect in 2s
2020-01-19 01:09:19.710  INFO 9580 --- [Thread-12] c.f.client.remote.FafServerAccessorImpl  : Trying to connect to FAF server at lobby.faforever.com:8001
2020-01-19 01:09:19.777  INFO 9580 --- [Thread-12] c.f.client.remote.FafServerAccessorImpl  : FAF server connection established
2020-01-19 01:09:19.810  INFO 9580 --- [Thread-12] c.f.client.remote.FafServerAccessorImpl  : FAF session initiated, session ID: 2081961675
2020-01-19 01:09:22.398  INFO 9580 --- [Thread-12] c.f.client.remote.FafServerAccessorImpl  : FAF login succeeded
2020-01-19 02:05:09.698  INFO 9580 --- [JavaFX Application Thread] com.faforever.client.game.GameService    : Joining game: 'Anyones welcome' (10893152)
2020-01-19 02:05:19.792  INFO 9580 --- [pool-3-thread-53] c.f.c.patch.GameBinariesUpdateTaskImpl   : Updating binaries to 3709
2020-01-19 02:05:20.352  INFO 9580 --- [pool-3-thread-52] c.faforever.client.map.DownloadMapTask   : Downloading map x1ca_coop_001.v0024 from https://content.faforever.com/faf/vault/maps/x1ca_coop_001.v0024.zip
2020-01-19 02:05:20.658  INFO 9580 --- [Thread-1265] c.f.client.fa.relay.ice.IceAdapterImpl   : Starting ICE adapter with command: [c:\program files\downlord's faf client\jre\bin\java.exe, -jar, C:\Program Files\Downlord's FAF Client\natives\faf-ice-adapter.jar, --id, 112345, --login, Katharsas, --rpc-port, 57228, --gpgnet-port, 13293]
2020-01-19 02:05:22.269  INFO 9580 --- [Thread-1265] c.f.client.fa.ForgedAllianceService      : Starting Forged Alliance with command: [C:\ProgramData\FAForever\bin\ForgedAlliance.exe, /init, init.lua, /nobugreport, /log, C:\ProgramData\FAForever\logs\game.log, /gpgnet, 127.0.0.1:13293, /mean, 1264.39, /deviation, 95.2934, /savereplay, gpgnet://127.0.0.1:57396/10893152/Katharsas.SCFAreplay, /country, , /numgames, 406] in directory: C:\ProgramData\FAForever\bin
2020-01-19 02:14:47.361  WARN 9580 --- [Thread-1264] c.f.client.replay.ReplayServerImpl       : Connection to replay server lost (Connection reset by peer: socket write error)
2020-01-19 03:05:47.252  WARN 9580 --- [JJsonPeer] c.f.client.fa.relay.GpgClientCommand     : Unknown lobby action: EnforceRating
2020-01-19 03:32:28.419  WARN 9580 --- [JJsonPeer] c.f.client.fa.relay.GpgClientCommand     : Unknown lobby action: EnforceRating
2020-01-19 03:32:50.053  WARN 9580 --- [JJsonPeer] c.f.client.fa.relay.GpgClientCommand     : Unknown lobby action: OperationComplete
2020-01-19 03:33:01.997  INFO 9580 --- [Thread-1264] c.f.client.replay.ReplayFileWriterImpl   : Writing replay file to C:\ProgramData\FAForever\replays\10893152-Katharsas.fafreplay (1.0 MiB)
2020-01-19 03:33:14.937  INFO 9580 --- [Thread-1265] c.f.client.fa.relay.ice.IceAdapterImpl   : ICE adapter terminated normally
2020-01-19 03:33:15.413  INFO 9580 --- [pool-3-thread-53] com.faforever.client.game.GameService    : Forged Alliance terminated with exit code 0
2020-01-19 03:38:36.402  WARN 9580 --- [JavaFX Application Thread] c.f.client.fa.relay.ice.IceAdapterImpl   : Ignoring call to ICE adapter as we are not connected: quit([])
2020-01-19 03:38:36.408  INFO 9580 --- [JavaFX Application Thread] com.faforever.client.config.AsyncConfig  : Shutting down ExecutorService 'taskExecutor'
2020-01-19 03:38:36.410  INFO 9580 --- [JavaFX Application Thread] o.s.s.c.ThreadPoolTaskScheduler          : Shutting down ExecutorService 'taskScheduler'
2020-01-19 03:38:36.425 ERROR 9580 --- [pool-3-thread-3] org.pircbotx.PircBotX                    : --- PircBotX interrupted during read, aborting reconnect loop and shutting down ---
2020-01-19 03:38:41.378  INFO 11228 --- [JavaFX-Launcher] o.s.boot.SpringApplication               : Starting application on JansNB with PID 11228 (started by Jan in C:\Program Files\Downlord's FAF Client)
2020-01-19 03:38:41.381  INFO 11228 --- [JavaFX-Launcher] o.s.boot.SpringApplication               : The following profiles are active: windows,prod
2020-01-19 03:38:43.188  INFO 11228 --- [JavaFX-Launcher] trationDelegate$BeanPostProcessorChecker : Bean 'asyncConfig' of type [com.faforever.client.config.AsyncConfig$$EnhancerBySpringCGLIB$$fad8ba40] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2020-01-19 03:38:43.324  INFO 11228 --- [JavaFX-Launcher] trationDelegate$BeanPostProcessorChecker : Bean 'cacheConfig' of type [com.faforever.client.config.CacheConfig$$EnhancerBySpringCGLIB$$5c176d86] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2020-01-19 03:38:43.937  INFO 11228 --- [JavaFX-Launcher] o.s.s.c.ThreadPoolTaskScheduler          : Initializing ExecutorService 'taskScheduler'
2020-01-19 03:38:45.000  INFO 11228 --- [JavaFX-Launcher] c.f.c.map.generator.MapGeneratorService  : Deleting leftover generated maps...
2020-01-19 03:38:45.381  WARN 11228 --- [pool-3-thread-2] com.faforever.client.map.MapService      : Map could not be read: debug

com.faforever.client.map.MapLoadException: Map folder does not contain a *_scenario.lua: C:\Users\Jan\Documents\My Games\Gas Powered Games\Supreme Commander Forged Alliance\maps\debug
	at com.faforever.client.map.MapService.lambda$readMap$10(MapService.java:268)
	at java.base/java.util.Optional.orElseThrow(Unknown Source)
	at com.faforever.client.map.MapService.readMap(MapService.java:268)
	at com.faforever.client.map.MapService.addSkirmishMap(MapService.java:242)
	at com.faforever.client.map.MapService.access$200(MapService.java:78)
	at com.faforever.client.map.MapService$1.call(MapService.java:226)
	at com.faforever.client.map.MapService$1.call(MapService.java:210)
	at javafx.graphics/javafx.concurrent.Task$TaskCallable.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
```
</details>

<details>
  <summary>Game log:</summary>

```
info: mounting maps from: C:\Users\Jan\Documents\My Games\Gas Powered Games\Supreme Commander Forged Alliance\maps\
info: checking C:\Users\Jan\Documents\My Games\Gas Powered Games\Supreme Commander Forged Alliance\maps\
info: Found map sounds in: SCCA_Coop_E05_v01
info: mounting maps from: C:\ProgramData\FAForever\bin\..\user\My Games\Gas Powered Games\Supreme Commander Forged Alliance\maps\
info: checking C:\ProgramData\FAForever\bin\..\user\My Games\Gas Powered Games\Supreme Commander Forged Alliance\maps\
info: checking C:\Users\Jan\Documents\My Games\Gas Powered Games\Supreme Commander Forged Alliance\mods
info: checking C:\ProgramData\FAForever\bin\..\user\My Games\Gas Powered Games\Supreme Commander Forged Alliance\mods
info: checking C:\ProgramData\FAForever\bin\..\gamedata\*.nxt
info: checking C:\ProgramData\FAForever\bin\..\gamedata\*.nx2
info: not safe C:\ProgramData\FAForever\bin\..\gamedata\A01_VO.nx2
info: not safe C:\ProgramData\FAForever\bin\..\gamedata\A02_VO.nx2
info: not safe C:\ProgramData\FAForever\bin\..\gamedata\A03_VO.nx2
info: not safe C:\ProgramData\FAForever\bin\..\gamedata\A04_VO.nx2
info: not safe C:\ProgramData\FAForever\bin\..\gamedata\A05_VO.nx2
info: not safe C:\ProgramData\FAForever\bin\..\gamedata\A06_VO.nx2
info: not safe C:\ProgramData\FAForever\bin\..\gamedata\C01_VO.nx2
info: not safe C:\ProgramData\FAForever\bin\..\gamedata\C02_VO.nx2
info: not safe C:\ProgramData\FAForever\bin\..\gamedata\C03_VO.nx2
info: not safe C:\ProgramData\FAForever\bin\..\gamedata\C04_VO.nx2
info: not safe C:\ProgramData\FAForever\bin\..\gamedata\C05_VO.nx2
info: not safe C:\ProgramData\FAForever\bin\..\gamedata\C06_VO.nx2
info: not safe C:\ProgramData\FAForever\bin\..\gamedata\E01_VO.nx2
info: not safe C:\ProgramData\FAForever\bin\..\gamedata\E02_VO.nx2
info: not safe C:\ProgramData\FAForever\bin\..\gamedata\E03_VO.nx2
info: not safe C:\ProgramData\FAForever\bin\..\gamedata\E04_VO.nx2
info: not safe C:\ProgramData\FAForever\bin\..\gamedata\E05_VO.nx2
info: not safe C:\ProgramData\FAForever\bin\..\gamedata\E06_VO.nx2
info: not safe C:\ProgramData\FAForever\bin\..\gamedata\FAF_TUT_Common_VO.nx2
info: not safe C:\ProgramData\FAForever\bin\..\gamedata\FAF_TUT_FourLeaf_BO_VO.nx2
info: not safe C:\ProgramData\FAForever\bin\..\gamedata\FAF_TUT_Loki_BO_VO.nx2
info: not safe C:\ProgramData\FAForever\bin\..\gamedata\FAF_TUT_SummerDuel_BO_VO.nx2
info: not safe C:\ProgramData\FAForever\bin\..\gamedata\Prothyon16_VO.nx2
info: not safe C:\ProgramData\FAForever\bin\..\gamedata\TCR_VO.nx2
info: checking C:/Program Files (x86)/Steam/steamapps/common/Supreme Commander Forged Alliance\gamedata\*.scd
info: checking C:\ProgramData\FAForever\bin\..\gamedata\*_VO.nx2
info: DISK: AddSearchPath: 'c:\users\jan\documents\my games\gas powered games\supreme commander forged alliance\maps\10 the pass', mounted as '/maps/10 the pass/'
info: DISK: AddSearchPath: 'c:\users\jan\documents\my games\gas powered games\supreme commander forged alliance\maps\10_you_shall_not_pass.v0002', mounted as '/maps/10_you_shall_not_pass.v0002/'
info: DISK: AddSearchPath: 'c:\users\jan\documents\my games\gas powered games\supreme commander forged alliance\maps\12 the pass', mounted as '/maps/12 the pass/'
info: DISK: AddSearchPath: 'c:\users\jan\documents\my games\gas powered games\supreme commander forged alliance\maps\12_the_pass_v6_wv13.v0006', mounted as '/maps/12_the_pass_v6_wv13.v0006/'
info: DISK: AddSearchPath: 'c:\users\jan\documents\my games\gas powered games\supreme commander forged alliance\maps\12_ultimate_you_shall_not_pass.v0001', mounted as '/maps/12_ultimate_you_shall_not_pass.v0001/'
info: DISK: AddSearchPath: 'c:\users\jan\documents\my games\gas powered games\supreme commander forged alliance\maps\12_ultinate_you_shall_not_pass.v0001', mounted as '/maps/12_ultinate_you_shall_not_pass.v0001/'
info: DISK: AddSearchPath: 'c:\users\jan\documents\my games\gas powered games\supreme commander forged alliance\maps\12_you_shall_not_pass.v0001', mounted as '/maps/12_you_shall_not_pass.v0001/'
info: DISK: AddSearchPath: 'c:\users\jan\documents\my games\gas powered games\supreme commander forged alliance\maps\14_you_shall_not_pass.v0002', mounted as '/maps/14_you_shall_not_pass.v0002/'
info: DISK: AddSearchPath: 'c:\users\jan\documents\my games\gas powered games\supreme commander forged alliance\maps\16_you_shall_not_pass.v0001', mounted as '/maps/16_you_shall_not_pass.v0001/'
info: DISK: AddSearchPath: 'c:\users\jan\documents\my games\gas powered games\supreme commander forged alliance\maps\2v2 boogie-woogie.v0002', mounted as '/maps/2v2 boogie-woogie.v0002/'
info: DISK: AddSearchPath: 'c:\users\jan\documents\my games\gas powered games\supreme commander forged alliance\maps\3v3 sand box.v0001', mounted as '/maps/3v3 sand box.v0001/'
info: DISK: AddSearchPath: 'c:\users\jan\documents\my games\gas powered games\supreme commander forged alliance\maps\5iver_survival_land_oxtreme.v0008', mounted as '/maps/5iver_survival_land_oxtreme.v0008/'
info: DISK: AddSearchPath: 'c:\users\jan\documents\my games\gas powered games\supreme commander forged alliance\maps\6vs6 battle of thermopylae v5', mounted as '/maps/6vs6 battle of thermopylae v5/'
info: DISK: AddSearchPath: 'c:\users\jan\documents\my games\gas powered games\supreme commander forged alliance\maps\abhor.v0004', mounted as '/maps/abhor.v0004/'
info: DISK: AddSearchPath: 'c:\users\jan\documents\my games\gas powered games\supreme commander forged alliance\maps\adaptive_hilly_plateau.v0002', mounted as '/maps/adaptive_hilly_plateau.v0002/'
info: DISK: AddSearchPath: 'c:\users\jan\documents\my games\gas powered games\supreme commander forged alliance\maps\adaptive_metir.v0002', mounted as '/maps/adaptive_metir.v0002/'
info: DISK: AddSearchPath: 'c:\users\jan\documents\my games\gas powered games\supreme commander forged alliance\maps\adaptive_monument_valley.v0002', mounted as '/maps/adaptive_monument_valley.v0002/'
info: DISK: AddSearchPath: 'c:\users\jan\documents\my games\gas powered games\supreme commander forged alliance\maps\adaptive_setons_clutch.v0002', mounted as '/maps/adaptive_setons_clutch.v0002/'
info: DISK: AddSearchPath: 'c:\users\jan\documents\my games\gas powered games\supreme commander forged alliance\maps\adaptive_syrtis_major.v0001', mounted as '/maps/adaptive_syrtis_major.v0001/'
info: DISK: AddSearchPath: 'c:\users\jan\documents\my games\gas powered games\supreme commander forged alliance\maps\adaptive_theta_passage.v0006', mounted as '/maps/adaptive_theta_passage.v0006/'
info: DISK: AddSearchPath: 'c:\users\jan\documents\my games\gas powered games\supreme commander forged alliance\maps\adaptive_twin_rivers.v0002', mounted as '/maps/adaptive_twin_rivers.v0002/'
info: DISK: AddSearchPath: 'c:\users\jan\documents\my games\gas powered games\supreme commander forged alliance\maps\adaptive_wonder.v0001', mounted as '/maps/adaptive_wonder.v0001/'
info: DISK: AddSearchPath: 'c:\users\jan\documents\my games\gas powered games\supreme commander forged alliance\maps\adaptive_wonder_open.v0002', mounted as '/maps/adaptive_wonder_open.v0002/'
info: DISK: AddSearchPath: 'c:\users\jan\documents\my games\gas powered games\supreme commander forged alliance\maps\anchor.v0011', mounted as '/maps/anchor.v0011/'
info: DISK: AddSearchPath: 'c:\users\jan\documents\my games\gas powered games\supreme commander forged alliance\maps\anchor_ultimate.v0002', mounted as '/maps/anchor_ultimate.v0002/'
info: DISK: AddSearchPath: 'c:\users\jan\documents\my games\gas powered games\supreme commander forged alliance\maps\apchui.v0003', mounted as '/maps/apchui.v0003/'
info: DISK: AddSearchPath: 'c:\users\jan\documents\my games\gas powered games\supreme commander forged alliance\maps\aperture.v0001', mounted as '/maps/aperture.v0001/'
info: DISK: AddSearchPath: 'c:\users\jan\documents\my games\gas powered games\supreme commander forged alliance\maps\arcane.v0001', mounted as '/maps/arcane.v0001/'
info: DISK: AddSearchPath: 'c:\users\jan\documents\my games\gas powered games\supreme commander forged alliance\maps\astro crater battles v3', mounted as '/maps/astro crater battles v3/'
info: DISK: AddSearchPath: 'c:\users\jan\documents\my games\gas powered games\supreme commander forged alliance\maps\astrobunker.v0001', mounted as '/maps/astrobunker.v0001/'
info: DISK: AddSearchPath: 'c:\users\jan\documents\my games\gas powered games\supreme commander forged alliance\maps\astro_crater_ac_4v4_v2.v0002', mounted as '/maps/astro_crater_ac_4v4_v2.v0002/'
info: DISK: AddSearchPath: 'c:\users\jan\documents\my games\gas powered games\supreme commander forged alliance\maps\astro_crater_ac_4v4_v2_rich_verison.v0002', mounted as '/maps/astro_crater_ac_4v4_v2_rich_verison.v0002/'
info: DISK: AddSearchPath: 'c:\users\jan\documents\my games\gas powered games\supreme commander forged alliance\maps\astro_crater_batlles_5vs5.v0005', mounted as '/maps/astro_crater_batlles_5vs5.v0005/'
info: DISK: AddSearchPath: 'c:\users\jan\documents\my games\gas powered games\supreme commander forged alliance\maps\astro_crater_battles', mounted as '/maps/astro_crater_battles/'
info: DISK: AddSearchPath: 'c:\users\jan\documents\my games\gas powered games\supreme commander forged alliance\maps\astro_crater_battles4x4v2', mounted as '/maps/astro_crater_battles4x4v2/'
info: DISK: AddSearchPath: 'c:\users\jan\documents\my games\gas powered games\supreme commander forged alliance\maps\astro_crater_battles4x4v2_recolor.v0001', mounted as '/maps/astro_crater_battles4x4v2_recolor.v0001/'
info: DISK: AddSearchPath: 'c:\users\jan\documents\my games\gas powered games\supreme commander forged alliance\maps\astro_crater_battles_4x4_rich_v2.v0001', mounted as '/maps/astro_crater_battles_4x4_rich_v2.v0001/'
info: DISK: AddSearchPath: 'c:\users\jan\documents\my games\gas powered games\supreme commander forged alliance\maps\astro_crater_battles_5vs5.v0001', mounted as '/maps/astro_crater_battles_5vs5.v0001/'
info: DISK: AddSearchPath: 'c:\users\jan\documents\my games\gas powered games\supreme commander forged alliance\maps\astro_crater_revolution.v0007', mounted as '/maps/astro_crater_revolution.v0007/'
info: DISK: AddSearchPath: 'c:\users\jan\documents\my games\gas powered games\supreme commander forged alliance\maps\astro_crater_sandstorm.v0004', mounted as '/maps/astro_crater_sandstorm.v0004/'
info: DISK: AddSearchPath: 'c:\users\jan\documents\my games\gas powered games\supreme commander forged alliance\maps\astro_crater_water.v0001', mounted as '/maps/astro_crater_water.v0001/'
info: DISK: AddSearchPath: 'c:\users\jan\documents\my games\gas powered games\supreme commander forged alliance\maps\azeron_planet.v0005', mounted as '/maps/azeron_planet.v0005/'
info: DISK: AddSearchPath: 'c:\users\jan\documents\my games\gas powered games\supreme commander forged alliance\maps\a_procyon5.v0001', mounted as '/maps/a_procyon5.v0001/'
info: DISK: AddSearchPath: 'c:\users\jan\documents\my games\gas powered games\supreme commander forged alliance\maps\balvery mountains v2.v0001', mounted as '/maps/balvery mountains v2.v0001/'
info: DISK: AddSearchPath: 'c:\users\jan\documents\my games\gas powered games\supreme commander forged alliance\maps\big_bang_gaps.v0001', mounted as '/maps/big_bang_gaps.v0001/'
info: DISK: AddSearchPath: 'c:\users\jan\documents\my games\gas powered games\supreme commander forged alliance\maps\big_bang_lake.v0004', mounted as '/maps/big_bang_lake.v0004/'
info: DISK: AddSearchPath: 'c:\users\jan\documents\my games\gas powered games\supreme commander forged alliance\maps\broken_vows.v0008', mounted as '/maps/broken_vows.v0008/'
info: DISK: AddSearchPath: 'c:\users\jan\documents\my games\gas powered games\supreme commander forged alliance\maps\canis 4v4 spezial edition.v0002', mounted as '/maps/canis 4v4 spezial edition.v0002/'
info: DISK: AddSearchPath: 'c:\users\jan\documents\my games\gas powered games\supreme commander forged alliance\maps\canis 5v5  fixed edition', mounted as '/maps/canis 5v5  fixed edition/'
info: DISK: AddSearchPath: 'c:\users\jan\documents\my games\gas powered games\supreme commander forged alliance\maps\cauldron small v1b', mounted as '/maps/cauldron small v1b/'
info: DISK: AddSearchPath: 'c:\users\jan\documents\my games\gas powered games\supreme commander forged alliance\maps\cobalt valley v1', mounted as '/maps/cobalt valley v1/'
info: DISK: AddSearchPath: 'c:\users\jan\documents\my games\gas powered games\supreme commander forged alliance\maps\comet catcher.v0001', mounted as '/maps/comet catcher.v0001/'
info: DISK: AddSearchPath: 'c:\users\jan\documents\my games\gas powered games\supreme commander forged alliance\maps\cool_maze_survival_close_spawn.v0018', mounted as '/maps/cool_maze_survival_close_spawn.v0018/'
info: DISK: AddSearchPath: 'c:\users\jan\documents\my games\gas powered games\supreme commander forged alliance\maps\crashing_waves.v0005', mounted as '/maps/crashing_waves.v0005/'
info: DISK: AddSearchPath: 'c:\users\jan\documents\my games\gas powered games\supreme commander forged alliance\maps\creepy.v0016', mounted as '/maps/creepy.v0016/'
info: DISK: AddSearchPath: 'c:\users\jan\documents\my games\gas powered games\supreme commander forged alliance\maps\crimson_feud', mounted as '/maps/crimson_feud/'
info: DISK: AddSearchPath: 'c:\users\jan\documents\my games\gas powered games\supreme commander forged alliance\maps\debug', mounted as '/maps/debug/'
info: DISK: AddSearchPath: 'c:\users\jan\documents\my games\gas powered games\supreme commander forged alliance\maps\desert arena.v0002', mounted as '/maps/desert arena.v0002/'
info: DISK: AddSearchPath: 'c:\users\jan\documents\my games\gas powered games\supreme commander forged alliance\maps\desert joust.v0001', mounted as '/maps/desert joust.v0001/'
info: DISK: AddSearchPath: 'c:\users\jan\documents\my games\gas powered games\supreme commander forged alliance\maps\desert planet ii.v0002', mounted as '/maps/desert planet ii.v0002/'
info: DISK: AddSearchPath: 'c:\users\jan\documents\my games\gas powered games\supreme commander forged alliance\maps\desert_storm_mission_2.v0003', mounted as '/maps/desert_storm_mission_2.v0003/'
info: DISK: AddSearchPath: 'c:\users\jan\documents\my games\gas powered games\supreme commander forged alliance\maps\diversity.v0008', mounted as '/maps/diversity.v0008/'
info: DISK: AddSearchPath: 'c:\users\jan\documents\my games\gas powered games\supreme commander forged alliance\maps\dualgap_fix_adaptive.v0005', mounted as '/maps/dualgap_fix_adaptive.v0005/'
info: DISK: AddSearchPath: 'c:\users\jan\documents\my games\gas powered games\supreme commander forged alliance\maps\dualgap_fix_adaptive.v0006', mounted as '/maps/dualgap_fix_adaptive.v0006/'
info: DISK: AddSearchPath: 'c:\users\jan\documents\my games\gas powered games\supreme commander forged alliance\maps\dualgap_fix_adaptive.v0007', mounted as '/maps/dualgap_fix_adaptive.v0007/'
info: DISK: AddSearchPath: 'c:\users\jan\documents\my games\gas powered games\supreme commander forged alliance\maps\dualgap_reborn.v0003', mounted as '/maps/dualgap_reborn.v0003/'
info: DISK: AddSearchPath: 'c:\users\jan\documents\my games\gas powered games\supreme commander forged alliance\maps\dual_gap_epv4.v0002', mounted as '/maps/dual_gap_epv4.v0002/'
info: DISK: AddSearchPath: 'c:\users\jan\documents\my games\gas powered games\supreme commander forged alliance\maps\dual_gap_ep_version_5.v0005', mounted as '/maps/dual_gap_ep_version_5.v0005/'
info: DISK: AddSearchPath: 'c:\users\jan\documents\my games\gas powered games\supreme commander forged alliance\maps\dual_gap_fix.v0001.v0001', mounted as '/maps/dual_gap_fix.v0001.v0001/'
info: DISK: AddSearchPath: 'c:\users\jan\documents\my games\gas powered games\supreme commander forged alliance\maps\dual_gap_fix.v0002.v0002', mounted as '/maps/dual_gap_fix.v0002.v0002/'
info: DISK: AddSearchPath: 'c:\users\jan\documents\my games\gas powered games\supreme commander forged alliance\maps\dual_gap_fix.v0004.v0004', mounted as '/maps/dual_gap_fix.v0004.v0004/'
info: DISK: AddSearchPath: 'c:\users\jan\documents\my games\gas powered games\supreme commander forged alliance\maps\dual_gap_v5.6.v0001', mounted as '/maps/dual_gap_v5.6.v0001/'
info: DISK: AddSearchPath: 'c:\users\jan\documents\my games\gas powered games\supreme commander forged alliance\maps\dual_gap_v5.7_beta_2.v0001', mounted as '/maps/dual_gap_v5.7_beta_2.v0001/'
info: DISK: AddSearchPath: 'c:\users\jan\documents\my games\gas powered games\supreme commander forged alliance\maps\dual_of_god_v1.v0001', mounted as '/maps/dual_of_god_v1.v0001/'
info: DISK: AddSearchPath: 'c:\users\jan\documents\my games\gas powered games\supreme commander forged alliance\maps\duel gap 5v5.v0014', mounted as '/maps/duel gap 5v5.v0014/'
info: DISK: AddSearchPath: 'c:\users\jan\documents\my games\gas powered games\supreme commander forged alliance\maps\emerald_crater.v0001', mounted as '/maps/emerald_crater.v0001/'
info: DISK: AddSearchPath: 'c:\users\jan\documents\my games\gas powered games\supreme commander forged alliance\maps\esgaroths ruins', mounted as '/maps/esgaroths ruins/'
info: DISK: AddSearchPath: 'c:\users\jan\documents\my games\gas powered games\supreme commander forged alliance\maps\faf_coop_fort_clarke_assault.v0017', mounted as '/maps/faf_coop_fort_clarke_assault.v0017/'
info: DISK: AddSearchPath: 'c:\users\jan\documents\my games\gas powered games\supreme commander forged alliance\maps\faf_coop_fort_clarke_assault.v0018', mounted as '/maps/faf_coop_fort_clarke_assault.v0018/'
info: DISK: AddSearchPath: 'c:\users\jan\documents\my games\gas powered games\supreme commander forged alliance\maps\faf_coop_havens_invasion.v0003', mounted as '/maps/faf_coop_havens_invasion.v0003/'
info: DISK: AddSearchPath: 'c:\users\jan\documents\my games\gas powered games\supreme commander forged alliance\maps\faf_coop_havens_invasion.v0004', mounted as '/maps/faf_coop_havens_invasion.v0004/'
info: DISK: AddSearchPath: 'c:\users\jan\documents\my games\gas powered games\supreme commander forged alliance\maps\faf_coop_operation_tha_atha_aez.v0010', mounted as '/maps/faf_coop_operation_tha_atha_aez.v0010/'
info: DISK: AddSearchPath: 'c:\users\jan\documents\my games\gas powered games\supreme commander forged alliance\maps\faf_coop_operation_tha_atha_aez.v0011', mounted as '/maps/faf_coop_operation_tha_atha_aez.v0011/'
info: DISK: AddSearchPath: 'c:\users\jan\documents\my games\gas powered games\supreme commander forged alliance\maps\faf_coop_operation_uhthe_thuum_qai.v0001', mounted as '/maps/faf_coop_operation_uhthe_thuum_qai.v0001/'
info: DISK: AddSearchPath: 'c:\users\jan\documents\my games\gas powered games\supreme commander forged alliance\maps\faf_coop_prothyon_16.v0016', mounted as '/maps/faf_coop_prothyon_16.v0016/'
info: DISK: AddSearchPath: 'c:\users\jan\documents\my games\gas powered games\supreme commander forged alliance\maps\faf_coop_prothyon_16.v0017', mounted as '/maps/faf_coop_prothyon_16.v0017/'
info: DISK: AddSearchPath: 'c:\users\jan\documents\my games\gas powered games\supreme commander forged alliance\maps\faf_coop_theta_civilian_rescue.v0012', mounted as '/maps/faf_coop_theta_civilian_rescue.v0012/'
info: DISK: AddSearchPath: 'c:\users\jan\documents\my games\gas powered games\supreme commander forged alliance\maps\fancylands.v0004', mounted as '/maps/fancylands.v0004/'
info: DISK: AddSearchPath: 'c:\users\jan\documents\my games\gas powered games\supreme commander forged alliance\maps\fields of thunder v2', mounted as '/maps/fields of thunder v2/'
info: DISK: AddSearchPath: 'c:\users\jan\documents\my games\gas powered games\supreme commander forged alliance\maps\final rush pro3 4v4.v0012', mounted as '/maps/final rush pro3 4v4.v0012/'
info: DISK: AddSearchPath: 'c:\users\jan\documents\my games\gas powered games\supreme commander forged alliance\maps\final_rush_pro_5.10.v0001', mounted as '/maps/final_rush_pro_5.10.v0001/'
info: DISK: AddSearchPath: 'c:\users\jan\documents\my games\gas powered games\supreme commander forged alliance\maps\final_rush_pro_5.11.v0001', mounted as '/maps/final_rush_pro_5.11.v0001/'
info: DISK: AddSearchPath: 'c:\users\jan\documents\my games\gas powered games\supreme commander forged alliance\maps\final_rush_pro_5.3.v0001', mounted as '/maps/final_rush_pro_5.3.v0001/'
info: DISK: AddSearchPath: 'c:\users\jan\documents\my games\gas powered games\supreme commander forged alliance\maps\final_rush_pro_5.6.v0001', mounted as '/maps/final_rush_pro_5.6.v0001/'
info: DISK: AddSearchPath: 'c:\users\jan\documents\my games\gas powered games\supreme commander forged alliance\maps\final_rush_pro_5.7.v0001', mounted as '/maps/final_rush_pro_5.7.v0001/'
info: DISK: AddSearchPath: 'c:\users\jan\documents\my games\gas powered games\supreme commander forged alliance\maps\final_rush_pro_5.9.v0002', mounted as '/maps/final_rush_pro_5.9.v0002/'
info: DISK: AddSearchPath: 'c:\users\jan\documents\my games\gas powered games\supreme commander forged alliance\maps\final_rush_pro_5.v0020', mounted as '/maps/final_rush_pro_5.v0020/'
info: DISK: AddSearchPath: 'c:\users\jan\documents\my games\gas powered games\supreme commander forged alliance\maps\flat (1mexeach)v1', mounted as '/maps/flat (1mexeach)v1/'
info: DISK: AddSearchPath: 'c:\users\jan\documents\my games\gas powered games\supreme commander forged alliance\maps\flat 512', mounted as '/maps/flat 512/'
info: DISK: AddSearchPath: 'c:\users\jan\documents\my games\gas powered games\supreme commander forged alliance\maps\flooded argon.v0002', mounted as '/maps/flooded argon.v0002/'
info: DISK: AddSearchPath: 'c:\users\jan\documents\my games\gas powered games\supreme commander forged alliance\maps\forgotten_facilities_10x10.v0011', mounted as '/maps/forgotten_facilities_10x10.v0011/'
info: DISK: AddSearchPath: 'c:\users\jan\documents\my games\gas powered games\supreme commander forged alliance\maps\funkytown.v0007', mounted as '/maps/funkytown.v0007/'
info: DISK: AddSearchPath: 'c:\users\jan\documents\my games\gas powered games\supreme commander forged alliance\maps\gap of rohan.v0001', mounted as '/maps/gap of rohan.v0001/'
info: DISK: AddSearchPath: 'c:\users\jan\documents\my games\gas powered games\supreme commander forged alliance\maps\gap of rohan.v0003', mounted as '/maps/gap of rohan.v0003/'
info: DISK: AddSearchPath: 'c:\users\jan\documents\my games\gas powered games\supreme commander forged alliance\maps\gap_of_rohan_fixed_pathing.v0001', mounted as '/maps/gap_of_rohan_fixed_pathing.v0001/'
info: DISK: AddSearchPath: 'c:\users\jan\documents\my games\gas powered games\supreme commander forged alliance\maps\gap_of_rohan_v4_fixed_pathing.v0004', mounted as '/maps/gap_of_rohan_v4_fixed_pathing.v0004/'
info: DISK: AddSearchPath: 'c:\users\jan\documents\my games\gas powered games\supreme commander forged alliance\maps\gb_clanpro_6v6.v0001', mounted as '/maps/gb_clanpro_6v6.v0001/'
info: DISK: AddSearchPath: 'c:\users\jan\documents\my games\gas powered games\supreme commander forged alliance\maps\goodlands_8p.v0007', mounted as '/maps/goodlands_8p.v0007/'
info: DISK: AddSearchPath: 'c:\users\jan\documents\my games\gas powered games\supreme commander forged alliance\maps\hilly_plateau.v0001', mounted as '/maps/hilly_plateau.v0001/'
info: DISK: AddSearchPath: 'c:\users\jan\documents\my games\gas powered games\supreme commander forged alliance\maps\hrungdaks canyon 4v4.v0004', mounted as '/maps/hrungdaks canyon 4v4.v0004/'
info: DISK: AddSearchPath: 'c:\users\jan\documents\my games\gas powered games\supreme commander forged alliance\maps\hyperion_lite.v0001', mounted as '/maps/hyperion_lite.v0001/'
info: DISK: AddSearchPath: 'c:\users\jan\documents\my games\gas powered games\supreme commander forged alliance\maps\last oasis.v0002', mounted as '/maps/last oasis.v0002/'
info: DISK: AddSearchPath: 'c:\users\jan\documents\my games\gas powered games\supreme commander forged alliance\maps\loki 3v3.v0002', mounted as '/maps/loki 3v3.v0002/'
info: DISK: AddSearchPath: 'c:\users\jan\documents\my games\gas powered games\supreme commander forged alliance\maps\loki.v0002', mounted as '/maps/loki.v0002/'
info: DISK: AddSearchPath: 'c:\users\jan\documents\my games\gas powered games\supreme commander forged alliance\maps\loki.v0003', mounted as '/maps/loki.v0003/'
info: DISK: AddSearchPath: 'c:\users\jan\documents\my games\gas powered games\supreme commander forged alliance\maps\lunchbox_gap_5v5.v0001', mounted as '/maps/lunchbox_gap_5v5.v0001/'
info: DISK: AddSearchPath: 'c:\users\jan\documents\my games\gas powered games\supreme commander forged alliance\maps\mayhem_of_64_acus.v0001', mounted as '/maps/mayhem_of_64_acus.v0001/'
info: DISK: AddSearchPath: 'c:\users\jan\documents\my games\gas powered games\supreme commander forged alliance\maps\mayhem_of_64_acus_v2.v0001', mounted as '/maps/mayhem_of_64_acus_v2.v0001/'
info: DISK: AddSearchPath: 'c:\users\jan\documents\my games\gas powered games\supreme commander forged alliance\maps\mezmerizing paradise betav1.v0001', mounted as '/maps/mezmerizing paradise betav1.v0001/'
info: DISK: AddSearchPath: 'c:\users\jan\documents\my games\gas powered games\supreme commander forged alliance\maps\moonlight mesas.v0001', mounted as '/maps/moonlight mesas.v0001/'
info: DISK: AddSearchPath: 'c:\users\jan\documents\my games\gas powered games\supreme commander forged alliance\maps\neroxisgen_proto_07.v0001', mounted as '/maps/neroxisgen_proto_07.v0001/'
info: DISK: AddSearchPath: 'c:\users\jan\documents\my games\gas powered games\supreme commander forged alliance\maps\neroxisgen_proto_14.v0001', mounted as '/maps/neroxisgen_proto_14.v0001/'
info: DISK: AddSearchPath: 'c:\users\jan\documents\my games\gas powered games\supreme commander forged alliance\maps\niflheim_-_final_ii_v2.v0002', mounted as '/maps/niflheim_-_final_ii_v2.v0002/'
info: DISK: AddSearchPath: 'c:\users\jan\documents\my games\gas powered games\supreme commander forged alliance\maps\norfair.v0001', mounted as '/maps/norfair.v0001/'
info: DISK: AddSearchPath: 'c:\users\jan\documents\my games\gas powered games\supreme commander forged alliance\maps\novaxstationassault.v0006', mounted as '/maps/novaxstationassault.v0006/'
info: DISK: AddSearchPath: 'c:\users\jan\documents\my games\gas powered games\supreme commander forged alliance\maps\ocil_wetlands.v0004', mounted as '/maps/ocil_wetlands.v0004/'
info: DISK: AddSearchPath: 'c:\users\jan\documents\my games\gas powered games\supreme commander forged alliance\maps\on melancholy hillv3', mounted as '/maps/on melancholy hillv3/'
info: DISK: AddSearchPath: 'c:\users\jan\documents\my games\gas powered games\supreme commander forged alliance\maps\ordor_flat.v0007', mounted as '/maps/ordor_flat.v0007/'
info: DISK: AddSearchPath: 'c:\users\jan\documents\my games\gas powered games\supreme commander forged alliance\maps\osiris.v0003', mounted as '/maps/osiris.v0003/'
info: DISK: AddSearchPath: 'c:\users\jan\documents\my games\gas powered games\supreme commander forged alliance\maps\owly_cliffs.v0005', mounted as '/maps/owly_cliffs.v0005/'
info: DISK: AddSearchPath: 'c:\users\jan\documents\my games\gas powered games\supreme commander forged alliance\maps\ozone islands v3', mounted as '/maps/ozone islands v3/'
info: DISK: AddSearchPath: 'c:\users\jan\documents\my games\gas powered games\supreme commander forged alliance\maps\paradisebay.v0007', mounted as '/maps/paradisebay.v0007/'
info: DISK: AddSearchPath: 'c:\users\jan\documents\my games\gas powered games\supreme commander forged alliance\maps\phantom_bunny_roanoke_v12.v0002', mounted as '/maps/phantom_bunny_roanoke_v12.v0002/'
info: DISK: AddSearchPath: 'c:\users\jan\documents\my games\gas powered games\supreme commander forged alliance\maps\point of reach v4', mounted as '/maps/point of reach v4/'
info: DISK: AddSearchPath: 'c:\users\jan\documents\my games\gas powered games\supreme commander forged alliance\maps\quantumsea.v0003', mounted as '/maps/quantumsea.v0003/'
info: DISK: AddSearchPath: 'c:\users\jan\documents\my games\gas powered games\supreme commander forged alliance\maps\red rocks', mounted as '/maps/red rocks/'
info: DISK: AddSearchPath: 'c:\users\jan\documents\my games\gas powered games\supreme commander forged alliance\maps\regor_vi_highlands.v0006', mounted as '/maps/regor_vi_highlands.v0006/'
info: DISK: AddSearchPath: 'c:\users\jan\documents\my games\gas powered games\supreme commander forged alliance\maps\rush me more ep', mounted as '/maps/rush me more ep/'
info: DISK: AddSearchPath: 'c:\users\jan\documents\my games\gas powered games\supreme commander forged alliance\maps\rush me more.v0010', mounted as '/maps/rush me more.v0010/'
info: DISK: AddSearchPath: 'c:\users\jan\documents\my games\gas powered games\supreme commander forged alliance\maps\rush me more.v0030', mounted as '/maps/rush me more.v0030/'
info: DISK: AddSearchPath: 'c:\users\jan\documents\my games\gas powered games\supreme commander forged alliance\maps\sandy clutch teamplay_ai', mounted as '/maps/sandy clutch teamplay_ai/'
info: DISK: AddSearchPath: 'c:\users\jan\documents\my games\gas powered games\supreme commander forged alliance\maps\scca_coop_a01.v0012', mounted as '/maps/scca_coop_a01.v0012/'
info: DISK: AddSearchPath: 'c:\users\jan\documents\my games\gas powered games\supreme commander forged alliance\maps\scca_coop_a01.v0013', mounted as '/maps/scca_coop_a01.v0013/'
info: DISK: AddSearchPath: 'c:\users\jan\documents\my games\gas powered games\supreme commander forged alliance\maps\scca_coop_a03.v0017', mounted as '/maps/scca_coop_a03.v0017/'
info: DISK: AddSearchPath: 'c:\users\jan\documents\my games\gas powered games\supreme commander forged alliance\maps\scca_coop_a03.v0018', mounted as '/maps/scca_coop_a03.v0018/'
info: DISK: AddSearchPath: 'c:\users\jan\documents\my games\gas powered games\supreme commander forged alliance\maps\scca_coop_a04.v0017', mounted as '/maps/scca_coop_a04.v0017/'
info: DISK: AddSearchPath: 'c:\users\jan\documents\my games\gas powered games\supreme commander forged alliance\maps\scca_coop_a04.v0018', mounted as '/maps/scca_coop_a04.v0018/'
info: DISK: AddSearchPath: 'c:\users\jan\documents\my games\gas powered games\supreme commander forged alliance\maps\scca_coop_a05.v0020', mounted as '/maps/scca_coop_a05.v0020/'
info: DISK: AddSearchPath: 'c:\users\jan\documents\my games\gas powered games\supreme commander forged alliance\maps\scca_coop_a06.v0019', mounted as '/maps/scca_coop_a06.v0019/'
info: DISK: AddSearchPath: 'c:\users\jan\documents\my games\gas powered games\supreme commander forged alliance\maps\scca_coop_a06.v0020', mounted as '/maps/scca_coop_a06.v0020/'
info: DISK: AddSearchPath: 'c:\users\jan\documents\my games\gas powered games\supreme commander forged alliance\maps\scca_coop_a06.v0021', mounted as '/maps/scca_coop_a06.v0021/'
info: DISK: AddSearchPath: 'c:\users\jan\documents\my games\gas powered games\supreme commander forged alliance\maps\scca_coop_e01.v0016', mounted as '/maps/scca_coop_e01.v0016/'
info: DISK: AddSearchPath: 'c:\users\jan\documents\my games\gas powered games\supreme commander forged alliance\maps\scca_coop_e01.v0018', mounted as '/maps/scca_coop_e01.v0018/'
info: DISK: AddSearchPath: 'c:\users\jan\documents\my games\gas powered games\supreme commander forged alliance\maps\scca_coop_e01.v0019', mounted as '/maps/scca_coop_e01.v0019/'
info: DISK: AddSearchPath: 'c:\users\jan\documents\my games\gas powered games\supreme commander forged alliance\maps\scca_coop_e02.v0014', mounted as '/maps/scca_coop_e02.v0014/'
info: DISK: AddSearchPath: 'c:\users\jan\documents\my games\gas powered games\supreme commander forged alliance\maps\scca_coop_e02.v0015', mounted as '/maps/scca_coop_e02.v0015/'
info: DISK: AddSearchPath: 'c:\users\jan\documents\my games\gas powered games\supreme commander forged alliance\maps\scca_coop_e02.v0016', mounted as '/maps/scca_coop_e02.v0016/'
info: DISK: AddSearchPath: 'c:\users\jan\documents\my games\gas powered games\supreme commander forged alliance\maps\scca_coop_e03.v0016', mounted as '/maps/scca_coop_e03.v0016/'
info: DISK: AddSearchPath: 'c:\users\jan\documents\my games\gas powered games\supreme commander forged alliance\maps\scca_coop_e03.v0018', mounted as '/maps/scca_coop_e03.v0018/'
info: DISK: AddSearchPath: 'c:\users\jan\documents\my games\gas powered games\supreme commander forged alliance\maps\scca_coop_e04.v0015', mounted as '/maps/scca_coop_e04.v0015/'
info: DISK: AddSearchPath: 'c:\users\jan\documents\my games\gas powered games\supreme commander forged alliance\maps\scca_coop_e04.v0017', mounted as '/maps/scca_coop_e04.v0017/'
info: DISK: AddSearchPath: 'c:\users\jan\documents\my games\gas powered games\supreme commander forged alliance\maps\scca_coop_e05.v0013', mounted as '/maps/scca_coop_e05.v0013/'
info: DISK: AddSearchPath: 'c:\users\jan\documents\my games\gas powered games\supreme commander forged alliance\maps\scca_coop_e05.v0014', mounted as '/maps/scca_coop_e05.v0014/'
info: DISK: AddSearchPath: 'c:\users\jan\documents\my games\gas powered games\supreme commander forged alliance\maps\scca_coop_e05.v0016', mounted as '/maps/scca_coop_e05.v0016/'
info: DISK: AddSearchPath: 'c:\users\jan\documents\my games\gas powered games\supreme commander forged alliance\maps\scca_coop_e05_v01', mounted as '/maps/scca_coop_e05_v01/'
info: DISK: AddSearchPath: 'c:\users\jan\documents\my games\gas powered games\supreme commander forged alliance\maps\scca_coop_e06.v0017', mounted as '/maps/scca_coop_e06.v0017/'
info: DISK: AddSearchPath: 'c:\users\jan\documents\my games\gas powered games\supreme commander forged alliance\maps\scca_coop_r01.v0015', mounted as '/maps/scca_coop_r01.v0015/'
info: DISK: AddSearchPath: 'c:\users\jan\documents\my games\gas powered games\supreme commander forged alliance\maps\scca_coop_r02.v0015', mounted as '/maps/scca_coop_r02.v0015/'
info: DISK: AddSearchPath: 'c:\users\jan\documents\my games\gas powered games\supreme commander forged alliance\maps\scca_coop_r03.v0015', mounted as '/maps/scca_coop_r03.v0015/'
info: DISK: AddSearchPath: 'c:\users\jan\documents\my games\gas powered games\supreme commander forged alliance\maps\scca_coop_r04.v0017', mounted as '/maps/scca_coop_r04.v0017/'
info: DISK: AddSearchPath: 'c:\users\jan\documents\my games\gas powered games\supreme commander forged alliance\maps\scca_coop_r05.v0015', mounted as '/maps/scca_coop_r05.v0015/'
info: DISK: AddSearchPath: 'c:\users\jan\documents\my games\gas powered games\supreme commander forged alliance\maps\scca_coop_r05.v0016', mounted as '/maps/scca_coop_r05.v0016/'
info: DISK: AddSearchPath: 'c:\users\jan\documents\my games\gas powered games\supreme commander forged alliance\maps\scca_coop_r06.v0013', mounted as '/maps/scca_coop_r06.v0013/'
info: DISK: AddSearchPath: 'c:\users\jan\documents\my games\gas powered games\supreme commander forged alliance\maps\scca_coop_r06.v0014', mounted as '/maps/scca_coop_r06.v0014/'
info: DISK: AddSearchPath: 'c:\users\jan\documents\my games\gas powered games\supreme commander forged alliance\maps\scca_coop_r06.v0015', mounted as '/maps/scca_coop_r06.v0015/'
info: DISK: AddSearchPath: 'c:\users\jan\documents\my games\gas powered games\supreme commander forged alliance\maps\scmp_019_3v3.v0003', mounted as '/maps/scmp_019_3v3.v0003/'
info: DISK: AddSearchPath: 'c:\users\jan\documents\my games\gas powered games\supreme commander forged alliance\maps\scmp_031_ai.v0001', mounted as '/maps/scmp_031_ai.v0001/'
info: DISK: AddSearchPath: 'c:\users\jan\documents\my games\gas powered games\supreme commander forged alliance\maps\scmp_supcomfi_st_r1.v0001', mounted as '/maps/scmp_supcomfi_st_r1.v0001/'
info: DISK: AddSearchPath: 'c:\users\jan\documents\my games\gas powered games\supreme commander forged alliance\maps\sedongs.v0002', mounted as '/maps/sedongs.v0002/'
info: DISK: AddSearchPath: 'c:\users\jan\documents\my games\gas powered games\supreme commander forged alliance\maps\sentina iii.v0001', mounted as '/maps/sentina iii.v0001/'
info: DISK: AddSearchPath: 'c:\users\jan\documents\my games\gas powered games\supreme commander forged alliance\maps\setons lite.v0001', mounted as '/maps/setons lite.v0001/'
info: DISK: AddSearchPath: 'c:\users\jan\documents\my games\gas powered games\supreme commander forged alliance\maps\setons_clutch_ep.v0002', mounted as '/maps/setons_clutch_ep.v0002/'
info: DISK: AddSearchPath: 'c:\users\jan\documents\my games\gas powered games\supreme commander forged alliance\maps\shard.v0001', mounted as '/maps/shard.v0001/'
info: DISK: AddSearchPath: 'c:\users\jan\documents\my games\gas powered games\supreme commander forged alliance\maps\sheboygen_falls.v0016', mounted as '/maps/sheboygen_falls.v0016/'
info: DISK: AddSearchPath: 'c:\users\jan\documents\my games\gas powered games\supreme commander forged alliance\maps\slizeorot.v0003', mounted as '/maps/slizeorot.v0003/'
info: DISK: AddSearchPath: 'c:\users\jan\documents\my games\gas powered games\supreme commander forged alliance\maps\standing stones.v0002', mounted as '/maps/standing stones.v0002/'
info: DISK: AddSearchPath: 'c:\users\jan\documents\my games\gas powered games\supreme commander forged alliance\maps\stella_maris_wm_1v1.v0001', mounted as '/maps/stella_maris_wm_1v1.v0001/'
info: DISK: AddSearchPath: 'c:\users\jan\documents\my games\gas powered games\supreme commander forged alliance\maps\survival run v8.v0001', mounted as '/maps/survival run v8.v0001/'
info: DISK: AddSearchPath: 'c:\users\jan\documents\my games\gas powered games\supreme commander forged alliance\maps\survival_5thdimension v2', mounted as '/maps/survival_5thdimension v2/'
info: DISK: AddSearchPath: 'c:\users\jan\documents\my games\gas powered games\supreme commander forged alliance\maps\survival_5thdimension.v0001', mounted as '/maps/survival_5thdimension.v0001/'
info: DISK: AddSearchPath: 'c:\users\jan\documents\my games\gas powered games\supreme commander forged alliance\maps\survival_5thdimension_8_player.v0003', mounted as '/maps/survival_5thdimension_8_player.v0003/'
info: DISK: AddSearchPath: 'c:\users\jan\documents\my games\gas powered games\supreme commander forged alliance\maps\survival_5thdimension_8_player.v0004', mounted as '/maps/survival_5thdimension_8_player.v0004/'
info: DISK: AddSearchPath: 'c:\users\jan\documents\my games\gas powered games\supreme commander forged alliance\maps\survival_5thdimension_practice.v0003', mounted as '/maps/survival_5thdimension_practice.v0003/'
info: DISK: AddSearchPath: 'c:\users\jan\documents\my games\gas powered games\supreme commander forged alliance\maps\survival_5thdimension_v8.v0001', mounted as '/maps/survival_5thdimension_v8.v0001/'
info: DISK: AddSearchPath: 'c:\users\jan\documents\my games\gas powered games\supreme commander forged alliance\maps\survival_5thdim_center.v0006', mounted as '/maps/survival_5thdim_center.v0006/'
info: DISK: AddSearchPath: 'c:\users\jan\documents\my games\gas powered games\supreme commander forged alliance\maps\survival_beach_ramp_mayhem.v0001', mounted as '/maps/survival_beach_ramp_mayhem.v0001/'
info: DISK: AddSearchPath: 'c:\users\jan\documents\my games\gas powered games\supreme commander forged alliance\maps\survival_extremedesertsparks.v0001', mounted as '/maps/survival_extremedesertsparks.v0001/'
info: DISK: AddSearchPath: 'c:\users\jan\documents\my games\gas powered games\supreme commander forged alliance\maps\survival_horde.v0005', mounted as '/maps/survival_horde.v0005/'
info: DISK: AddSearchPath: 'c:\users\jan\documents\my games\gas powered games\supreme commander forged alliance\maps\survival_horde_ee.v0015', mounted as '/maps/survival_horde_ee.v0015/'
info: DISK: AddSearchPath: 'c:\users\jan\documents\my games\gas powered games\supreme commander forged alliance\maps\survival_horde_ee.v0016', mounted as '/maps/survival_horde_ee.v0016/'
info: DISK: AddSearchPath: 'c:\users\jan\documents\my games\gas powered games\supreme commander forged alliance\maps\survival_mayhem&bo_3d.v0002', mounted as '/maps/survival_mayhem&bo_3d.v0002/'
info: DISK: AddSearchPath: 'c:\users\jan\documents\my games\gas powered games\supreme commander forged alliance\maps\survival_mayhem&bo_3d_v1.v0016', mounted as '/maps/survival_mayhem&bo_3d_v1.v0016/'
info: DISK: AddSearchPath: 'c:\users\jan\documents\my games\gas powered games\supreme commander forged alliance\maps\survival_mayhem&bo_3d_v1.v0054', mounted as '/maps/survival_mayhem&bo_3d_v1.v0054/'
info: DISK: AddSearchPath: 'c:\users\jan\documents\my games\gas powered games\supreme commander forged alliance\maps\survival_mayhem&bo_3d_v1.v0057', mounted as '/maps/survival_mayhem&bo_3d_v1.v0057/'
info: DISK: AddSearchPath: 'c:\users\jan\documents\my games\gas powered games\supreme commander forged alliance\maps\survival_mayhem&bo_3d_v1.v0060', mounted as '/maps/survival_mayhem&bo_3d_v1.v0060/'
info: DISK: AddSearchPath: 'c:\users\jan\documents\my games\gas powered games\supreme commander forged alliance\maps\survival_mayhem&bo_3d_v1.v0072', mounted as '/maps/survival_mayhem&bo_3d_v1.v0072/'
info: DISK: AddSearchPath: 'c:\users\jan\documents\my games\gas powered games\supreme commander forged alliance\maps\survival_mayhem&bo_3d_v1.v0088', mounted as '/maps/survival_mayhem&bo_3d_v1.v0088/'
info: DISK: AddSearchPath: 'c:\users\jan\documents\my games\gas powered games\supreme commander forged alliance\maps\survival_mayhem_bo_3d_rpg.v0027', mounted as '/maps/survival_mayhem_bo_3d_rpg.v0027/'
info: DISK: AddSearchPath: 'c:\users\jan\documents\my games\gas powered games\supreme commander forged alliance\maps\survival_mayhem_bo_3d_rpg.v0035', mounted as '/maps/survival_mayhem_bo_3d_rpg.v0035/'
info: DISK: AddSearchPath: 'c:\users\jan\documents\my games\gas powered games\supreme commander forged alliance\maps\survival_party.v0003', mounted as '/maps/survival_party.v0003/'
info: DISK: AddSearchPath: 'c:\users\jan\documents\my games\gas powered games\supreme commander forged alliance\maps\survival_rngdimension.v0001', mounted as '/maps/survival_rngdimension.v0001/'
info: DISK: AddSearchPath: 'c:\users\jan\documents\my games\gas powered games\supreme commander forged alliance\maps\the pyramid 5v5', mounted as '/maps/the pyramid 5v5/'
info: DISK: AddSearchPath: 'c:\users\jan\documents\my games\gas powered games\supreme commander forged alliance\maps\thetacivilianrescue.v0008', mounted as '/maps/thetacivilianrescue.v0008/'
info: DISK: AddSearchPath: 'c:\users\jan\documents\my games\gas powered games\supreme commander forged alliance\maps\the_dark_heart_faf', mounted as '/maps/the_dark_heart_faf/'
info: DISK: AddSearchPath: 'c:\users\jan\documents\my games\gas powered games\supreme commander forged alliance\maps\the_land_wilderness_v3.v0001', mounted as '/maps/the_land_wilderness_v3.v0001/'
info: DISK: AddSearchPath: 'c:\users\jan\documents\my games\gas powered games\supreme commander forged alliance\maps\tripleshuriken.v0001', mounted as '/maps/tripleshuriken.v0001/'
info: DISK: AddSearchPath: 'c:\users\jan\documents\my games\gas powered games\supreme commander forged alliance\maps\twin rivers ep', mounted as '/maps/twin rivers ep/'
info: DISK: AddSearchPath: 'c:\users\jan\documents\my games\gas powered games\supreme commander forged alliance\maps\twin rivers.v0001', mounted as '/maps/twin rivers.v0001/'
info: DISK: AddSearchPath: 'c:\users\jan\documents\my games\gas powered games\supreme commander forged alliance\maps\twin_rivers_4x4.v0002', mounted as '/maps/twin_rivers_4x4.v0002/'
info: DISK: AddSearchPath: 'c:\users\jan\documents\my games\gas powered games\supreme commander forged alliance\maps\voi vittu', mounted as '/maps/voi vittu/'
info: DISK: AddSearchPath: 'c:\users\jan\documents\my games\gas powered games\supreme commander forged alliance\maps\volcanoduel.v0001', mounted as '/maps/volcanoduel.v0001/'
info: DISK: AddSearchPath: 'c:\users\jan\documents\my games\gas powered games\supreme commander forged alliance\maps\voodoo thermo v4', mounted as '/maps/voodoo thermo v4/'
info: DISK: AddSearchPath: 'c:\users\jan\documents\my games\gas powered games\supreme commander forged alliance\maps\voodoo tournament v18', mounted as '/maps/voodoo tournament v18/'
info: DISK: AddSearchPath: 'c:\users\jan\documents\my games\gas powered games\supreme commander forged alliance\maps\voodoo tournament v1c', mounted as '/maps/voodoo tournament v1c/'
info: DISK: AddSearchPath: 'c:\users\jan\documents\my games\gas powered games\supreme commander forged alliance\maps\voodoo_space_war_v1.v0001', mounted as '/maps/voodoo_space_war_v1.v0001/'
info: DISK: AddSearchPath: 'c:\users\jan\documents\my games\gas powered games\supreme commander forged alliance\maps\wartime2.v0001', mounted as '/maps/wartime2.v0001/'
info: DISK: AddSearchPath: 'c:\users\jan\documents\my games\gas powered games\supreme commander forged alliance\maps\wartime2_4v4.v0001', mounted as '/maps/wartime2_4v4.v0001/'
info: DISK: AddSearchPath: 'c:\users\jan\documents\my games\gas powered games\supreme commander forged alliance\maps\waters of isis 3v3', mounted as '/maps/waters of isis 3v3/'
info: DISK: AddSearchPath: 'c:\users\jan\documents\my games\gas powered games\supreme commander forged alliance\maps\white firev2', mounted as '/maps/white firev2/'
info: DISK: AddSearchPath: 'c:\users\jan\documents\my games\gas powered games\supreme commander forged alliance\maps\wonder 5v5 half open v3', mounted as '/maps/wonder 5v5 half open v3/'
info: DISK: AddSearchPath: 'c:\users\jan\documents\my games\gas powered games\supreme commander forged alliance\maps\wonder open 5v5', mounted as '/maps/wonder open 5v5/'
info: DISK: AddSearchPath: 'c:\users\jan\documents\my games\gas powered games\supreme commander forged alliance\maps\wonder open 5v5 v3b.v0002', mounted as '/maps/wonder open 5v5 v3b.v0002/'
info: DISK: AddSearchPath: 'c:\users\jan\documents\my games\gas powered games\supreme commander forged alliance\maps\wonder open 6v6 v2', mounted as '/maps/wonder open 6v6 v2/'
info: DISK: AddSearchPath: 'c:\users\jan\documents\my games\gas powered games\supreme commander forged alliance\maps\wonder_open_4v4_na.v0003', mounted as '/maps/wonder_open_4v4_na.v0003/'
info: DISK: AddSearchPath: 'c:\users\jan\documents\my games\gas powered games\supreme commander forged alliance\maps\x1ca_coop_001.v0019', mounted as '/maps/x1ca_coop_001.v0019/'
info: DISK: AddSearchPath: 'c:\users\jan\documents\my games\gas powered games\supreme commander forged alliance\maps\x1ca_coop_001.v0022', mounted as '/maps/x1ca_coop_001.v0022/'
info: DISK: AddSearchPath: 'c:\users\jan\documents\my games\gas powered games\supreme commander forged alliance\maps\x1ca_coop_001.v0023', mounted as '/maps/x1ca_coop_001.v0023/'
info: DISK: AddSearchPath: 'c:\users\jan\documents\my games\gas powered games\supreme commander forged alliance\maps\x1ca_coop_001.v0024', mounted as '/maps/x1ca_coop_001.v0024/'
info: DISK: AddSearchPath: 'c:\users\jan\documents\my games\gas powered games\supreme commander forged alliance\maps\x1ca_coop_002.v0016', mounted as '/maps/x1ca_coop_002.v0016/'
info: DISK: AddSearchPath: 'c:\users\jan\documents\my games\gas powered games\supreme commander forged alliance\maps\x1ca_coop_002.v0018', mounted as '/maps/x1ca_coop_002.v0018/'
info: DISK: AddSearchPath: 'c:\users\jan\documents\my games\gas powered games\supreme commander forged alliance\maps\x1ca_coop_002.v0019', mounted as '/maps/x1ca_coop_002.v0019/'
info: DISK: AddSearchPath: 'c:\users\jan\documents\my games\gas powered games\supreme commander forged alliance\maps\x1ca_coop_002.v0020', mounted as '/maps/x1ca_coop_002.v0020/'
info: DISK: AddSearchPath: 'c:\users\jan\documents\my games\gas powered games\supreme commander forged alliance\maps\x1ca_coop_003.v0017', mounted as '/maps/x1ca_coop_003.v0017/'
info: DISK: AddSearchPath: 'c:\users\jan\documents\my games\gas powered games\supreme commander forged alliance\maps\x1ca_coop_003.v0018', mounted as '/maps/x1ca_coop_003.v0018/'
info: DISK: AddSearchPath: 'c:\users\jan\documents\my games\gas powered games\supreme commander forged alliance\maps\x1ca_coop_004.v0017', mounted as '/maps/x1ca_coop_004.v0017/'
info: DISK: AddSearchPath: 'c:\users\jan\documents\my games\gas powered games\supreme commander forged alliance\maps\x1ca_coop_004.v0018', mounted as '/maps/x1ca_coop_004.v0018/'
info: DISK: AddSearchPath: 'c:\users\jan\documents\my games\gas powered games\supreme commander forged alliance\maps\x1ca_coop_005.v0015', mounted as '/maps/x1ca_coop_005.v0015/'
info: DISK: AddSearchPath: 'c:\users\jan\documents\my games\gas powered games\supreme commander forged alliance\maps\x1ca_coop_005.v0017', mounted as '/maps/x1ca_coop_005.v0017/'
info: DISK: AddSearchPath: 'c:\users\jan\documents\my games\gas powered games\supreme commander forged alliance\maps\x1ca_coop_005.v0018', mounted as '/maps/x1ca_coop_005.v0018/'
info: DISK: AddSearchPath: 'c:\users\jan\documents\my games\gas powered games\supreme commander forged alliance\maps\x1ca_coop_006.v0014', mounted as '/maps/x1ca_coop_006.v0014/'
info: DISK: AddSearchPath: 'c:\users\jan\documents\my games\gas powered games\supreme commander forged alliance\maps\x1ca_coop_006.v0015', mounted as '/maps/x1ca_coop_006.v0015/'
info: DISK: AddSearchPath: 'c:\users\jan\documents\my games\gas powered games\supreme commander forged alliance\maps\x1ca_coop_006.v0018', mounted as '/maps/x1ca_coop_006.v0018/'
info: DISK: AddSearchPath: 'c:\users\jan\documents\my games\gas powered games\supreme commander forged alliance\maps\z-d_rasty_lite.v0001', mounted as '/maps/z-d_rasty_lite.v0001/'
info: DISK: AddSearchPath: 'c:\users\jan\documents\my games\gas powered games\supreme commander forged alliance\maps\zepilot_dual_gap_v4.v0001', mounted as '/maps/zepilot_dual_gap_v4.v0001/'
info: DISK: AddSearchPath: 'c:\users\jan\documents\my games\gas powered games\supreme commander forged alliance\maps\zombi war v4', mounted as '/maps/zombi war v4/'
info: DISK: AddSearchPath: 'c:\users\jan\documents\my games\gas powered games\supreme commander forged alliance\maps\zombies_sands_of_ablicka.v0001', mounted as '/maps/zombies_sands_of_ablicka.v0001/'
info: DISK: AddSearchPath: 'c:\users\jan\documents\my games\gas powered games\supreme commander forged alliance\maps\zombies_zeta_wonder.v0001', mounted as '/maps/zombies_zeta_wonder.v0001/'
info: DISK: AddSearchPath: 'c:\users\jan\documents\my games\gas powered games\supreme commander forged alliance\maps\zone control for faf 8p', mounted as '/maps/zone control for faf 8p/'
info: DISK: AddSearchPath: 'c:\users\jan\documents\my games\gas powered games\supreme commander forged alliance\maps\zorg rampage.v0001', mounted as '/maps/zorg rampage.v0001/'
info: DISK: AddSearchPath: 'c:\users\jan\documents\my games\gas powered games\supreme commander forged alliance\maps\scca_coop_e05_v01\sounds', mounted as '/sounds/'
info: DISK: AddSearchPath: 'c:\users\jan\documents\my games\gas powered games\supreme commander forged alliance\mods\#1marlos mods compilation', mounted as '/mods/#1marlos mods compilation/'
info: DISK: AddSearchPath: 'c:\users\jan\documents\my games\gas powered games\supreme commander forged alliance\mods\#2x resources,storage,buildrate,buildrange', mounted as '/mods/#2x resources,storage,buildrate,buildrange/'
info: DISK: AddSearchPath: 'c:\users\jan\documents\my games\gas powered games\supreme commander forged alliance\mods\#build range x3', mounted as '/mods/#build range x3/'
info: DISK: AddSearchPath: 'c:\users\jan\documents\my games\gas powered games\supreme commander forged alliance\mods\#quality of life', mounted as '/mods/#quality of life/'
info: DISK: AddSearchPath: 'c:\users\jan\documents\my games\gas powered games\supreme commander forged alliance\mods\#quality of performance', mounted as '/mods/#quality of performance/'
info: DISK: AddSearchPath: 'c:\users\jan\documents\my games\gas powered games\supreme commander forged alliance\mods\30particlev3', mounted as '/mods/30particlev3/'
info: DISK: AddSearchPath: 'c:\users\jan\documents\my games\gas powered games\supreme commander forged alliance\mods\5x resources,storage,buildrate,2x buildrange', mounted as '/mods/5x resources,storage,buildrate,2x buildrange/'
info: DISK: AddSearchPath: 'c:\users\jan\documents\my games\gas powered games\supreme commander forged alliance\mods\additionalcamerastuff', mounted as '/mods/additionalcamerastuff/'
info: DISK: AddSearchPath: 'c:\users\jan\documents\my games\gas powered games\supreme commander forged alliance\mods\advanced shields', mounted as '/mods/advanced shields/'
info: DISK: AddSearchPath: 'c:\users\jan\documents\my games\gas powered games\supreme commander forged alliance\mods\advanced shields v4', mounted as '/mods/advanced shields v4/'
info: DISK: AddSearchPath: 'c:\users\jan\documents\my games\gas powered games\supreme commander forged alliance\mods\advanced shields v5', mounted as '/mods/advanced shields v5/'
info: DISK: AddSearchPath: 'c:\users\jan\documents\my games\gas powered games\supreme commander forged alliance\mods\all factions', mounted as '/mods/all factions/'
info: DISK: AddSearchPath: 'c:\users\jan\documents\my games\gas powered games\supreme commander forged alliance\mods\all factions t1', mounted as '/mods/all factions t1/'
info: DISK: AddSearchPath: 'c:\users\jan\documents\my games\gas powered games\supreme commander forged alliance\mods\allah akbar', mounted as '/mods/allah akbar/'
info: DISK: AddSearchPath: 'c:\users\jan\documents\my games\gas powered games\supreme commander forged alliance\mods\allfactions', mounted as '/mods/allfactions/'
info: DISK: AddSearchPath: 'c:\users\jan\documents\my games\gas powered games\supreme commander forged alliance\mods\allfactions_faf_bo_nomads', mounted as '/mods/allfactions_faf_bo_nomads/'
info: DISK: AddSearchPath: 'c:\users\jan\documents\my games\gas powered games\supreme commander forged alliance\mods\all_faction_quantum_gate', mounted as '/mods/all_faction_quantum_gate/'
info: DISK: AddSearchPath: 'c:\users\jan\documents\my games\gas powered games\supreme commander forged alliance\mods\antares unit pack', mounted as '/mods/antares unit pack/'
info: DISK: AddSearchPath: 'c:\users\jan\documents\my games\gas powered games\supreme commander forged alliance\mods\antaresunitpack', mounted as '/mods/antaresunitpack/'
info: DISK: AddSearchPath: 'c:\users\jan\documents\my games\gas powered games\supreme commander forged alliance\mods\bhedit', mounted as '/mods/bhedit/'
info: DISK: AddSearchPath: 'c:\users\jan\documents\my games\gas powered games\supreme commander forged alliance\mods\blackopsfaf-acus', mounted as '/mods/blackopsfaf-acus/'
info: DISK: AddSearchPath: 'c:\users\jan\documents\my games\gas powered games\supreme commander forged alliance\mods\blackopsfaf-exunits', mounted as '/mods/blackopsfaf-exunits/'
info: DISK: AddSearchPath: 'c:\users\jan\documents\my games\gas powered games\supreme commander forged alliance\mods\blackopsfaf-unleashed', mounted as '/mods/blackopsfaf-unleashed/'
info: DISK: AddSearchPath: 'c:\users\jan\documents\my games\gas powered games\supreme commander forged alliance\mods\brewlan', mounted as '/mods/brewlan/'
info: DISK: AddSearchPath: 'c:\users\jan\documents\my games\gas powered games\supreme commander forged alliance\mods\brewlan_units', mounted as '/mods/brewlan_units/'
info: DISK: AddSearchPath: 'c:\users\jan\documents\my games\gas powered games\supreme commander forged alliance\mods\build rate range x2', mounted as '/mods/build rate range x2/'
info: DISK: AddSearchPath: 'c:\users\jan\documents\my games\gas powered games\supreme commander forged alliance\mods\cheapantinukev3.1', mounted as '/mods/cheapantinukev3.1/'
info: DISK: AddSearchPath: 'c:\users\jan\documents\my games\gas powered games\supreme commander forged alliance\mods\common', mounted as '/mods/common/'
info: DISK: AddSearchPath: 'c:\users\jan\documents\my games\gas powered games\supreme commander forged alliance\mods\defencesexpand', mounted as '/mods/defencesexpand/'
info: DISK: AddSearchPath: 'c:\users\jan\documents\my games\gas powered games\supreme commander forged alliance\mods\em', mounted as '/mods/em/'
info: DISK: AddSearchPath: 'c:\users\jan\documents\my games\gas powered games\supreme commander forged alliance\mods\exengineeringstation', mounted as '/mods/exengineeringstation/'
info: DISK: AddSearchPath: 'c:\users\jan\documents\my games\gas powered games\supreme commander forged alliance\mods\exmex', mounted as '/mods/exmex/'
info: DISK: AddSearchPath: 'c:\users\jan\documents\my games\gas powered games\supreme commander forged alliance\mods\experimental point defence', mounted as '/mods/experimental point defence/'
info: DISK: AddSearchPath: 'c:\users\jan\documents\my games\gas powered games\supreme commander forged alliance\mods\expwars_1', mounted as '/mods/expwars_1/'
info: DISK: AddSearchPath: 'c:\users\jan\documents\my games\gas powered games\supreme commander forged alliance\mods\fast building and com upgrades', mounted as '/mods/fast building and com upgrades/'
info: DISK: AddSearchPath: 'c:\users\jan\documents\my games\gas powered games\supreme commander forged alliance\mods\fastbuild x2 range x5 power', mounted as '/mods/fastbuild x2 range x5 power/'
info: DISK: AddSearchPath: 'c:\users\jan\documents\my games\gas powered games\supreme commander forged alliance\mods\fastbuild2x', mounted as '/mods/fastbuild2x/'
info: DISK: AddSearchPath: 'c:\users\jan\documents\my games\gas powered games\supreme commander forged alliance\mods\hydro', mounted as '/mods/hydro/'
info: DISK: AddSearchPath: 'c:\users\jan\documents\my games\gas powered games\supreme commander forged alliance\mods\idleengineers', mounted as '/mods/idleengineers/'
info: DISK: AddSearchPath: 'c:\users\jan\documents\my games\gas powered games\supreme commander forged alliance\mods\low bo commander upgrades costs', mounted as '/mods/low bo commander upgrades costs/'
info: DISK: AddSearchPath: 'c:\users\jan\documents\my games\gas powered games\supreme commander forged alliance\mods\low commander upgrades costs', mounted as '/mods/low commander upgrades costs/'
info: DISK: AddSearchPath: 'c:\users\jan\documents\my games\gas powered games\supreme commander forged alliance\mods\no build restrictions in campaign', mounted as '/mods/no build restrictions in campaign/'
info: DISK: AddSearchPath: 'c:\users\jan\documents\my games\gas powered games\supreme commander forged alliance\mods\no collision with friendlies', mounted as '/mods/no collision with friendlies/'
info: DISK: AddSearchPath: 'c:\users\jan\documents\my games\gas powered games\supreme commander forged alliance\mods\no friendly fire', mounted as '/mods/no friendly fire/'
info: DISK: AddSearchPath: 'c:\users\jan\documents\my games\gas powered games\supreme commander forged alliance\mods\noaircrashdamage', mounted as '/mods/noaircrashdamage/'
info: DISK: AddSearchPath: 'c:\users\jan\documents\my games\gas powered games\supreme commander forged alliance\mods\notify', mounted as '/mods/notify/'
info: DISK: AddSearchPath: 'c:\users\jan\documents\my games\gas powered games\supreme commander forged alliance\mods\nuclearrepulsorshields', mounted as '/mods/nuclearrepulsorshields/'
info: DISK: AddSearchPath: 'c:\users\jan\documents\my games\gas powered games\supreme commander forged alliance\mods\oof', mounted as '/mods/oof/'
info: DISK: AddSearchPath: 'c:\users\jan\documents\my games\gas powered games\supreme commander forged alliance\mods\pathofveterancyv8', mounted as '/mods/pathofveterancyv8/'
info: DISK: AddSearchPath: 'c:\users\jan\documents\my games\gas powered games\supreme commander forged alliance\mods\pxmodalphav6', mounted as '/mods/pxmodalphav6/'
info: DISK: AddSearchPath: 'c:\users\jan\documents\my games\gas powered games\supreme commander forged alliance\mods\quantumgateteleport', mounted as '/mods/quantumgateteleport/'
info: DISK: AddSearchPath: 'c:\users\jan\documents\my games\gas powered games\supreme commander forged alliance\mods\quantumresourcegenerators', mounted as '/mods/quantumresourcegenerators/'
info: DISK: AddSearchPath: 'c:\users\jan\documents\my games\gas powered games\supreme commander forged alliance\mods\rescources x2', mounted as '/mods/rescources x2/'
info: DISK: AddSearchPath: 'c:\users\jan\documents\my games\gas powered games\supreme commander forged alliance\mods\resource rich', mounted as '/mods/resource rich/'
info: DISK: AddSearchPath: 'c:\users\jan\documents\my games\gas powered games\supreme commander forged alliance\mods\resource rich x3', mounted as '/mods/resource rich x3/'
info: DISK: AddSearchPath: 'c:\users\jan\documents\my games\gas powered games\supreme commander forged alliance\mods\reveal_positions', mounted as '/mods/reveal_positions/'
info: DISK: AddSearchPath: 'c:\users\jan\documents\my games\gas powered games\supreme commander forged alliance\mods\rks_explosions', mounted as '/mods/rks_explosions/'
info: DISK: AddSearchPath: 'c:\users\jan\documents\my games\gas powered games\supreme commander forged alliance\mods\sharedarmies', mounted as '/mods/sharedarmies/'
info: DISK: AddSearchPath: 'c:\users\jan\documents\my games\gas powered games\supreme commander forged alliance\mods\shields', mounted as '/mods/shields/'
info: DISK: AddSearchPath: 'c:\users\jan\documents\my games\gas powered games\supreme commander forged alliance\mods\siege shields', mounted as '/mods/siege shields/'
info: DISK: AddSearchPath: 'c:\users\jan\documents\my games\gas powered games\supreme commander forged alliance\mods\some mods fix', mounted as '/mods/some mods fix/'
info: DISK: AddSearchPath: 'c:\users\jan\documents\my games\gas powered games\supreme commander forged alliance\mods\some mods naval', mounted as '/mods/some mods naval/'
info: DISK: AddSearchPath: 'c:\users\jan\documents\my games\gas powered games\supreme commander forged alliance\mods\storagerich_x10', mounted as '/mods/storagerich_x10/'
info: DISK: AddSearchPath: 'c:\users\jan\documents\my games\gas powered games\supreme commander forged alliance\mods\storagerich_x10fixed', mounted as '/mods/storagerich_x10fixed/'
info: DISK: AddSearchPath: 'c:\users\jan\documents\my games\gas powered games\supreme commander forged alliance\mods\storagerich_x5', mounted as '/mods/storagerich_x5/'
info: DISK: AddSearchPath: 'c:\users\jan\documents\my games\gas powered games\supreme commander forged alliance\mods\survival mayhem&bo balance', mounted as '/mods/survival mayhem&bo balance/'
info: DISK: AddSearchPath: 'c:\users\jan\documents\my games\gas powered games\supreme commander forged alliance\mods\t2_t3_storage', mounted as '/mods/t2_t3_storage/'
info: DISK: AddSearchPath: 'c:\users\jan\documents\my games\gas powered games\supreme commander forged alliance\mods\t2_t3_storage_faf', mounted as '/mods/t2_t3_storage_faf/'
info: DISK: AddSearchPath: 'c:\users\jan\documents\my games\gas powered games\supreme commander forged alliance\mods\t3engstationsfaf', mounted as '/mods/t3engstationsfaf/'
info: DISK: AddSearchPath: 'c:\users\jan\documents\my games\gas powered games\supreme commander forged alliance\mods\totalmayhem', mounted as '/mods/totalmayhem/'
info: DISK: AddSearchPath: 'c:\users\jan\documents\my games\gas powered games\supreme commander forged alliance\mods\tvg_official_stormrideron13', mounted as '/mods/tvg_official_stormrideron13/'
info: DISK: AddSearchPath: 'c:\users\jan\documents\my games\gas powered games\supreme commander forged alliance\mods\uef to sera mod for coop', mounted as '/mods/uef to sera mod for coop/'
info: DISK: AddSearchPath: 'c:\users\jan\documents\my games\gas powered games\supreme commander forged alliance\mods\ultra shields', mounted as '/mods/ultra shields/'
info: DISK: AddSearchPath: 'c:\users\jan\documents\my games\gas powered games\supreme commander forged alliance\mods\unitcap x4', mounted as '/mods/unitcap x4/'
info: DISK: AddSearchPath: 'c:\users\jan\documents\my games\gas powered games\supreme commander forged alliance\mods\waterworld', mounted as '/mods/waterworld/'
info: DISK: AddSearchPath: 'c:\users\jan\documents\my games\gas powered games\supreme commander forged alliance\mods\x1.3 build range', mounted as '/mods/x1.3 build range/'
info: DISK: AddSearchPath: 'c:\users\jan\documents\my games\gas powered games\supreme commander forged alliance\mods\x1.5 build range', mounted as '/mods/x1.5 build range/'
info: DISK: AddSearchPath: 'c:\users\jan\documents\my games\gas powered games\supreme commander forged alliance\mods\x100', mounted as '/mods/x100/'
info: DISK: AddSearchPath: 'c:\users\jan\documents\my games\gas powered games\supreme commander forged alliance\mods\x2 build range', mounted as '/mods/x2 build range/'
info: DISK: AddSearchPath: 'c:\users\jan\documents\my games\gas powered games\supreme commander forged alliance\mods\x3 build range', mounted as '/mods/x3 build range/'
info: DISK: AddSearchPath: 'c:\users\jan\documents\my games\gas powered games\supreme commander forged alliance\mods\x5', mounted as '/mods/x5/'
info: DISK: AddSearchPath: 'c:\users\jan\documents\my games\gas powered games\supreme commander forged alliance\mods\xtremwars', mounted as '/mods/xtremwars/'
info: DISK: AddSearchPath: 'c:\users\jan\documents\my games\gas powered games\supreme commander forged alliance\mods\zombies', mounted as '/mods/zombies/'
info: DISK: AddSearchPath: 'c:\programdata\faforever\gamedata\lobby_coop.cop', mounted as '/'
info: DISK: AddSearchPath: 'c:\programdata\faforever\gamedata\advanced strategic icons.nxt', mounted as '/'
info: DISK: AddSearchPath: 'c:\programdata\faforever\gamedata\labwars.nxt', mounted as '/'
info: DISK: AddSearchPath: 'c:\programdata\faforever\gamedata\effects.nx2', mounted as '/'
info: DISK: AddSearchPath: 'c:\programdata\faforever\gamedata\env.nx2', mounted as '/'
info: DISK: AddSearchPath: 'c:\programdata\faforever\gamedata\etc.nx2', mounted as '/'
info: DISK: AddSearchPath: 'c:\programdata\faforever\gamedata\loc.nx2', mounted as '/'
info: DISK: AddSearchPath: 'c:\programdata\faforever\gamedata\lua.nx2', mounted as '/'
info: DISK: AddSearchPath: 'c:\programdata\faforever\gamedata\meshes.nx2', mounted as '/'
info: DISK: AddSearchPath: 'c:\programdata\faforever\gamedata\modules.nx2', mounted as '/'
info: DISK: AddSearchPath: 'c:\programdata\faforever\gamedata\projectiles.nx2', mounted as '/'
info: DISK: AddSearchPath: 'c:\programdata\faforever\gamedata\schook.nx2', mounted as '/'
info: DISK: AddSearchPath: 'c:\programdata\faforever\gamedata\textures.nx2', mounted as '/'
info: DISK: AddSearchPath: 'c:\programdata\faforever\gamedata\units.nx2', mounted as '/'
info: DISK: AddSearchPath: 'c:\program files (x86)\steam\steamapps\common\supreme commander forged alliance\gamedata\ambience.scd', mounted as '/'
info: DISK: AddSearchPath: 'c:\program files (x86)\steam\steamapps\common\supreme commander forged alliance\gamedata\editor.scd', mounted as '/'
info: DISK: AddSearchPath: 'c:\program files (x86)\steam\steamapps\common\supreme commander forged alliance\gamedata\effects.scd', mounted as '/'
info: DISK: AddSearchPath: 'c:\program files (x86)\steam\steamapps\common\supreme commander forged alliance\gamedata\env.scd', mounted as '/'
info: DISK: AddSearchPath: 'c:\program files (x86)\steam\steamapps\common\supreme commander forged alliance\gamedata\loc_us.scd', mounted as '/'
info: DISK: AddSearchPath: 'c:\program files (x86)\steam\steamapps\common\supreme commander forged alliance\gamedata\lua.scd', mounted as '/'
info: DISK: AddSearchPath: 'c:\program files (x86)\steam\steamapps\common\supreme commander forged alliance\gamedata\meshes.scd', mounted as '/'
info: DISK: AddSearchPath: 'c:\program files (x86)\steam\steamapps\common\supreme commander forged alliance\gamedata\mods.scd', mounted as '/'
info: DISK: AddSearchPath: 'c:\program files (x86)\steam\steamapps\common\supreme commander forged alliance\gamedata\mohodata.scd', mounted as '/'
info: DISK: AddSearchPath: 'c:\program files (x86)\steam\steamapps\common\supreme commander forged alliance\gamedata\moholua.scd', mounted as '/'
info: DISK: AddSearchPath: 'c:\program files (x86)\steam\steamapps\common\supreme commander forged alliance\gamedata\objects.scd', mounted as '/'
info: DISK: AddSearchPath: 'c:\program files (x86)\steam\steamapps\common\supreme commander forged alliance\gamedata\projectiles.scd', mounted as '/'
info: DISK: AddSearchPath: 'c:\program files (x86)\steam\steamapps\common\supreme commander forged alliance\gamedata\props.scd', mounted as '/'
info: DISK: AddSearchPath: 'c:\program files (x86)\steam\steamapps\common\supreme commander forged alliance\gamedata\schook.scd', mounted as '/'
info: DISK: AddSearchPath: 'c:\program files (x86)\steam\steamapps\common\supreme commander forged alliance\gamedata\skins.scd', mounted as '/'
info: DISK: AddSearchPath: 'c:\program files (x86)\steam\steamapps\common\supreme commander forged alliance\gamedata\textures.scd', mounted as '/'
info: DISK: AddSearchPath: 'c:\program files (x86)\steam\steamapps\common\supreme commander forged alliance\gamedata\units.scd', mounted as '/'
info: DISK: AddSearchPath: 'c:\program files (x86)\steam\steamapps\common\supreme commander forged alliance', mounted as '/'
info: DISK: AddSearchPath: 'c:\programdata\faforever\movies', mounted as '/movies/'
info: DISK: AddSearchPath: 'c:\programdata\faforever\gamedata\a01_vo.nx2', mounted as '/'
info: DISK: AddSearchPath: 'c:\programdata\faforever\gamedata\a02_vo.nx2', mounted as '/'
info: DISK: AddSearchPath: 'c:\programdata\faforever\gamedata\a03_vo.nx2', mounted as '/'
info: DISK: AddSearchPath: 'c:\programdata\faforever\gamedata\a04_vo.nx2', mounted as '/'
info: DISK: AddSearchPath: 'c:\programdata\faforever\gamedata\a05_vo.nx2', mounted as '/'
info: DISK: AddSearchPath: 'c:\programdata\faforever\gamedata\a06_vo.nx2', mounted as '/'
info: DISK: AddSearchPath: 'c:\programdata\faforever\gamedata\c01_vo.nx2', mounted as '/'
info: DISK: AddSearchPath: 'c:\programdata\faforever\gamedata\c02_vo.nx2', mounted as '/'
info: DISK: AddSearchPath: 'c:\programdata\faforever\gamedata\c03_vo.nx2', mounted as '/'
info: DISK: AddSearchPath: 'c:\programdata\faforever\gamedata\c04_vo.nx2', mounted as '/'
info: DISK: AddSearchPath: 'c:\programdata\faforever\gamedata\c05_vo.nx2', mounted as '/'
info: DISK: AddSearchPath: 'c:\programdata\faforever\gamedata\c06_vo.nx2', mounted as '/'
info: DISK: AddSearchPath: 'c:\programdata\faforever\gamedata\e01_vo.nx2', mounted as '/'
info: DISK: AddSearchPath: 'c:\programdata\faforever\gamedata\e02_vo.nx2', mounted as '/'
info: DISK: AddSearchPath: 'c:\programdata\faforever\gamedata\e03_vo.nx2', mounted as '/'
info: DISK: AddSearchPath: 'c:\programdata\faforever\gamedata\e04_vo.nx2', mounted as '/'
info: DISK: AddSearchPath: 'c:\programdata\faforever\gamedata\e05_vo.nx2', mounted as '/'
info: DISK: AddSearchPath: 'c:\programdata\faforever\gamedata\e06_vo.nx2', mounted as '/'
info: DISK: AddSearchPath: 'c:\programdata\faforever\gamedata\faf_tut_common_vo.nx2', mounted as '/'
info: DISK: AddSearchPath: 'c:\programdata\faforever\gamedata\faf_tut_fourleaf_bo_vo.nx2', mounted as '/'
info: DISK: AddSearchPath: 'c:\programdata\faforever\gamedata\faf_tut_loki_bo_vo.nx2', mounted as '/'
info: DISK: AddSearchPath: 'c:\programdata\faforever\gamedata\faf_tut_summerduel_bo_vo.nx2', mounted as '/'
info: DISK: AddSearchPath: 'c:\programdata\faforever\gamedata\prothyon16_vo.nx2', mounted as '/'
info: DISK: AddSearchPath: 'c:\programdata\faforever\gamedata\tcr_vo.nx2', mounted as '/'
info: Hooked /lua/userInit.lua with /schook/lua/userInit.lua
info: Hooked /lua/globalInit.lua with /schook/lua/globalInit.lua
info: Hooked /loc/us/strings_db.lua with /mods/coop/hook/loc/us/strings_db.lua
debug: Loading module '\000/lua/mods.lua\000'
debug: Loading module '\000/lua/system/setutils.lua\000'
info: MD5 of global settings: d2a23d6464d3fd77956e7648c43b5077
info: IsStreamingWaveBank("/sounds/aeonselect.xwb") => false
debug: Wavebank prepared: 548cb68
debug: SND: Loaded WaveBank 'aeonselect' at 548cb68
info: IsStreamingWaveBank("/sounds/ambienttest.xwb") => false
debug: Wavebank prepared: 548cc98
debug: SND: Loaded WaveBank 'ambienttest' at 548cc98
info: IsStreamingWaveBank("/sounds/cybranselect.xwb") => false
debug: Wavebank prepared: 548cdc8
debug: SND: Loaded WaveBank 'cybranselect' at 548cdc8
info: IsStreamingWaveBank("/sounds/explosions.xwb") => false
debug: Wavebank prepared: 548cef8
debug: SND: Loaded WaveBank 'explosions' at 548cef8
info: IsStreamingWaveBank("/sounds/explosionsstream.xwb") => true
debug: SND: Loaded WaveBank 'explosionsstream' at 548d028
info: IsStreamingWaveBank("/sounds/fmv_bg.xwb") => true
debug: SND: Loaded WaveBank 'fmv_bg' at 548e598
info: IsStreamingWaveBank("/sounds/impacts.xwb") => false
debug: Wavebank prepared: 548f700
debug: SND: Loaded WaveBank 'impacts' at 548f700
info: IsStreamingWaveBank("/sounds/interface.xwb") => false
debug: Wavebank prepared: 548f830
debug: SND: Loaded WaveBank 'interface' at 548f830
info: IsStreamingWaveBank("/sounds/music.xwb") => true
debug: SND: Loaded WaveBank 'music' at 548f960
info: IsStreamingWaveBank("/sounds/op_briefing.xwb") => true
debug: SND: Loaded WaveBank 'op_briefing' at 5490ac8
info: IsStreamingWaveBank("/sounds/seraphimselect.xwb") => false
debug: Wavebank prepared: 5491c30
debug: SND: Loaded WaveBank 'seraphimselect' at 5491c30
info: IsStreamingWaveBank("/sounds/uaa.xwb") => false
debug: Wavebank prepared: 5491d60
debug: SND: Loaded WaveBank 'uaa' at 5491d60
info: IsStreamingWaveBank("/sounds/uaadestroy.xwb") => false
debug: Wavebank prepared: 5491e90
debug: SND: Loaded WaveBank 'uaadestroy' at 5491e90
info: IsStreamingWaveBank("/sounds/uaaweapon.xwb") => false
debug: Wavebank prepared: 5491fc0
debug: SND: Loaded WaveBank 'uaaweapon' at 5491fc0
info: IsStreamingWaveBank("/sounds/uab.xwb") => false
debug: Wavebank prepared: 54920f0
debug: SND: Loaded WaveBank 'uab' at 54920f0
info: IsStreamingWaveBank("/sounds/ual.xwb") => false
debug: Wavebank prepared: 5492220
debug: SND: Loaded WaveBank 'ual' at 5492220
info: IsStreamingWaveBank("/sounds/ualdestroy.xwb") => false
debug: Wavebank prepared: 5492350
debug: SND: Loaded WaveBank 'ualdestroy' at 5492350
info: IsStreamingWaveBank("/sounds/ualweapon.xwb") => false
debug: Wavebank prepared: 5492480
debug: SND: Loaded WaveBank 'ualweapon' at 5492480
info: IsStreamingWaveBank("/sounds/uas.xwb") => false
debug: Wavebank prepared: 54925b0
debug: SND: Loaded WaveBank 'uas' at 54925b0
info: IsStreamingWaveBank("/sounds/uasdestroy.xwb") => true
debug: SND: Loaded WaveBank 'uasdestroy' at 54926e0
info: IsStreamingWaveBank("/sounds/uasweapon.xwb") => false
debug: Wavebank prepared: 5493848
debug: SND: Loaded WaveBank 'uasweapon' at 5493848
info: IsStreamingWaveBank("/sounds/uea.xwb") => false
debug: Wavebank prepared: 5493978
debug: SND: Loaded WaveBank 'uea' at 5493978
info: IsStreamingWaveBank("/sounds/ueadestroy.xwb") => false
debug: Wavebank prepared: 5494838
debug: SND: Loaded WaveBank 'ueadestroy' at 5494838
info: IsStreamingWaveBank("/sounds/ueaweapon.xwb") => false
debug: Wavebank prepared: 54945c8
debug: SND: Loaded WaveBank 'ueaweapon' at 54945c8
info: IsStreamingWaveBank("/sounds/ueb.xwb") => false
debug: Wavebank prepared: 5494700
debug: SND: Loaded WaveBank 'ueb' at 5494700
info: IsStreamingWaveBank("/sounds/uefselect.xwb") => false
debug: Wavebank prepared: 5493d40
debug: SND: Loaded WaveBank 'uefselect' at 5493d40
info: IsStreamingWaveBank("/sounds/uel.xwb") => false
debug: Wavebank prepared: 54940e8
debug: SND: Loaded WaveBank 'uel' at 54940e8
info: IsStreamingWaveBank("/sounds/ueldestroy.xwb") => false
debug: Wavebank prepared: 5493e78
debug: SND: Loaded WaveBank 'ueldestroy' at 5493e78
info: IsStreamingWaveBank("/sounds/uelweapon.xwb") => false
debug: Wavebank prepared: 5493fb0
debug: SND: Loaded WaveBank 'uelweapon' at 5493fb0
info: IsStreamingWaveBank("/sounds/ues.xwb") => false
debug: Wavebank prepared: 5494970
debug: SND: Loaded WaveBank 'ues' at 5494970
info: IsStreamingWaveBank("/sounds/uesdestroy.xwb") => true
debug: SND: Loaded WaveBank 'uesdestroy' at 5494ab0
info: IsStreamingWaveBank("/sounds/uesweapon.xwb") => false
debug: Wavebank prepared: 5493ad0
debug: SND: Loaded WaveBank 'uesweapon' at 5493ad0
info: IsStreamingWaveBank("/sounds/unitrumble.xwb") => false
debug: Wavebank prepared: 5494220
debug: SND: Loaded WaveBank 'unitrumble' at 5494220
info: IsStreamingWaveBank("/sounds/unitsglobal.xwb") => false
debug: Wavebank prepared: 5493c08
debug: SND: Loaded WaveBank 'unitsglobal' at 5493c08
info: IsStreamingWaveBank("/sounds/ura.xwb") => false
debug: Wavebank prepared: 5494358
debug: SND: Loaded WaveBank 'ura' at 5494358
info: IsStreamingWaveBank("/sounds/uradestroy.xwb") => false
debug: Wavebank prepared: 5494490
debug: SND: Loaded WaveBank 'uradestroy' at 5494490
info: IsStreamingWaveBank("/sounds/uraweapon.xwb") => false
debug: Wavebank prepared: 5495eb0
debug: SND: Loaded WaveBank 'uraweapon' at 5495eb0
info: IsStreamingWaveBank("/sounds/urb.xwb") => false
debug: Wavebank prepared: 54970f8
debug: SND: Loaded WaveBank 'urb' at 54970f8
info: IsStreamingWaveBank("/sounds/url.xwb") => false
debug: Wavebank prepared: 5496fc0
debug: SND: Loaded WaveBank 'url' at 5496fc0
info: IsStreamingWaveBank("/sounds/urldestroy.xwb") => false
debug: Wavebank prepared: 5495fe8
debug: SND: Loaded WaveBank 'urldestroy' at 5495fe8
info: IsStreamingWaveBank("/sounds/urlweapon.xwb") => false
debug: Wavebank prepared: 5497980
debug: SND: Loaded WaveBank 'urlweapon' at 5497980
info: IsStreamingWaveBank("/sounds/urs.xwb") => false
debug: Wavebank prepared: 54969a8
debug: SND: Loaded WaveBank 'urs' at 54969a8
info: IsStreamingWaveBank("/sounds/ursdestroy.xwb") => true
debug: SND: Loaded WaveBank 'ursdestroy' at 5497c20
info: IsStreamingWaveBank("/sounds/ursstream.xwb") => true
debug: SND: Loaded WaveBank 'ursstream' at 5498d88
info: IsStreamingWaveBank("/sounds/ursweapon.xwb") => false
debug: Wavebank prepared: 5496870
debug: SND: Loaded WaveBank 'ursweapon' at 5496870
info: IsStreamingWaveBank("/sounds/xaa_weapon.xwb") => false
debug: Wavebank prepared: 5497710
debug: SND: Loaded WaveBank 'xaa_weapon' at 5497710
info: IsStreamingWaveBank("/sounds/xab.xwb") => false
debug: Wavebank prepared: 5496600
debug: SND: Loaded WaveBank 'xab' at 5496600
info: IsStreamingWaveBank("/sounds/xal.xwb") => false
debug: Wavebank prepared: 5495d78
debug: SND: Loaded WaveBank 'xal' at 5495d78
info: IsStreamingWaveBank("/sounds/xal_weapon.xwb") => false
debug: Wavebank prepared: 5497230
debug: SND: Loaded WaveBank 'xal_weapon' at 5497230
info: IsStreamingWaveBank("/sounds/xas.xwb") => false
debug: Wavebank prepared: 5496d50
debug: SND: Loaded WaveBank 'xas' at 5496d50
info: IsStreamingWaveBank("/sounds/xas_weapons.xwb") => false
debug: Wavebank prepared: 5497848
debug: SND: Loaded WaveBank 'xas_weapons' at 5497848
info: IsStreamingWaveBank("/sounds/xea.xwb") => false
debug: Wavebank prepared: 5496120
debug: SND: Loaded WaveBank 'xea' at 5496120
info: IsStreamingWaveBank("/sounds/xea_weapons.xwb") => false
debug: Wavebank prepared: 5495c40
debug: SND: Loaded WaveBank 'xea_weapons' at 5495c40
info: IsStreamingWaveBank("/sounds/xeb.xwb") => false
debug: Wavebank prepared: 5496ae0
debug: SND: Loaded WaveBank 'xeb' at 5496ae0
info: IsStreamingWaveBank("/sounds/xel.xwb") => false
debug: Wavebank prepared: 5497368
debug: SND: Loaded WaveBank 'xel' at 5497368
info: IsStreamingWaveBank("/sounds/xel_weapons.xwb") => false
debug: Wavebank prepared: 54975d8
debug: SND: Loaded WaveBank 'xel_weapons' at 54975d8
info: IsStreamingWaveBank("/sounds/xes.xwb") => false
debug: Wavebank prepared: 5496258
debug: SND: Loaded WaveBank 'xes' at 5496258
info: IsStreamingWaveBank("/sounds/xes_destroy.xwb") => true
debug: SND: Loaded WaveBank 'xes_destroy' at 5499ef0
info: IsStreamingWaveBank("/sounds/xes_weapons.xwb") => false
debug: Wavebank prepared: 54974a0
debug: SND: Loaded WaveBank 'xes_weapons' at 54974a0
info: IsStreamingWaveBank("/sounds/xra.xwb") => false
debug: Wavebank prepared: 5497ab8
debug: SND: Loaded WaveBank 'xra' at 5497ab8
info: IsStreamingWaveBank("/sounds/xra_weapon.xwb") => false
debug: Wavebank prepared: 5496390
debug: SND: Loaded WaveBank 'xra_weapon' at 5496390
info: IsStreamingWaveBank("/sounds/xrb.xwb") => false
debug: Wavebank prepared: 54964c8
debug: SND: Loaded WaveBank 'xrb' at 54964c8
info: IsStreamingWaveBank("/sounds/xrl.xwb") => false
debug: Wavebank prepared: 5496738
debug: SND: Loaded WaveBank 'xrl' at 5496738
info: IsStreamingWaveBank("/sounds/xrl_stream.xwb") => true
debug: SND: Loaded WaveBank 'xrl_stream' at 549b058
info: IsStreamingWaveBank("/sounds/xrl_weapon.xwb") => false
debug: Wavebank prepared: 5496e88
debug: SND: Loaded WaveBank 'xrl_weapon' at 5496e88
info: IsStreamingWaveBank("/sounds/xrs.xwb") => false
debug: Wavebank prepared: 5496c18
debug: SND: Loaded WaveBank 'xrs' at 5496c18
info: IsStreamingWaveBank("/sounds/xrs_weapon.xwb") => false
debug: Wavebank prepared: 549cf50
debug: SND: Loaded WaveBank 'xrs_weapon' at 549cf50
info: IsStreamingWaveBank("/sounds/xsa.xwb") => false
debug: Wavebank prepared: 549d1c0
debug: SND: Loaded WaveBank 'xsa' at 549d1c0
info: IsStreamingWaveBank("/sounds/xsa_destroy.xwb") => false
debug: Wavebank prepared: 549d7d8
debug: SND: Loaded WaveBank 'xsa_destroy' at 549d7d8
info: IsStreamingWaveBank("/sounds/xsa_weapon.xwb") => false
debug: Wavebank prepared: 549d910
debug: SND: Loaded WaveBank 'xsa_weapon' at 549d910
info: IsStreamingWaveBank("/sounds/xsb.xwb") => false
debug: Wavebank prepared: 549d2f8
debug: SND: Loaded WaveBank 'xsb' at 549d2f8
info: IsStreamingWaveBank("/sounds/xsb_weapon.xwb") => false
debug: Wavebank prepared: 549cba8
debug: SND: Loaded WaveBank 'xsb_weapon' at 549cba8
info: IsStreamingWaveBank("/sounds/xsl.xwb") => false
debug: Wavebank prepared: 549da48
debug: SND: Loaded WaveBank 'xsl' at 549da48
info: IsStreamingWaveBank("/sounds/xsl_destroy.xwb") => false
debug: Wavebank prepared: 549e060
debug: SND: Loaded WaveBank 'xsl_destroy' at 549e060
info: IsStreamingWaveBank("/sounds/xsl_weapon.xwb") => false
debug: Wavebank prepared: 549d430
debug: SND: Loaded WaveBank 'xsl_weapon' at 549d430
info: IsStreamingWaveBank("/sounds/xss.xwb") => false
debug: Wavebank prepared: 549c590
debug: SND: Loaded WaveBank 'xss' at 549c590
info: IsStreamingWaveBank("/sounds/xss_destroy.xwb") => true
debug: SND: Loaded WaveBank 'xss_destroy' at 549e1c8
info: IsStreamingWaveBank("/sounds/xss_weapon.xwb") => false
debug: Wavebank prepared: 549c800
debug: SND: Loaded WaveBank 'xss_weapon' at 549c800
debug: SND: Loaded SoundBank 'ambienttest'
debug: SND: Loaded SoundBank 'explosions'
debug: SND: Loaded SoundBank 'fmv_bg'
debug: SND: Loaded SoundBank 'impacts'
debug: SND: Loaded SoundBank 'interface'
debug: SND: Loaded SoundBank 'music'
debug: SND: Loaded SoundBank 'op_briefing'
debug: SND: Loaded SoundBank 'seraphimselect'
debug: SND: Loaded SoundBank 'uaa'
debug: SND: Loaded SoundBank 'uaadestroy'
debug: SND: Loaded SoundBank 'uaaweapon'
debug: SND: Loaded SoundBank 'uab'
debug: SND: Loaded SoundBank 'ual'
debug: SND: Loaded SoundBank 'ualdestroy'
debug: SND: Loaded SoundBank 'ualweapon'
debug: SND: Loaded SoundBank 'uas'
debug: SND: Loaded SoundBank 'uasdestroy'
debug: SND: Loaded SoundBank 'uasweapon'
debug: SND: Loaded SoundBank 'uea'
debug: SND: Loaded SoundBank 'ueadestroy'
debug: SND: Loaded SoundBank 'ueaweapon'
debug: SND: Loaded SoundBank 'ueb'
debug: SND: Loaded SoundBank 'uel'
debug: SND: Loaded SoundBank 'ueldestroy'
debug: SND: Loaded SoundBank 'uelweapon'
debug: SND: Loaded SoundBank 'ues'
debug: SND: Loaded SoundBank 'uesdestroy'
debug: SND: Loaded SoundBank 'uesweapon'
debug: SND: Loaded SoundBank 'unitrumble'
debug: SND: Loaded SoundBank 'unitsglobal'
debug: SND: Loaded SoundBank 'ura'
debug: SND: Loaded SoundBank 'uradestroy'
debug: SND: Loaded SoundBank 'uraweapon'
debug: SND: Loaded SoundBank 'urb'
debug: SND: Loaded SoundBank 'url'
debug: SND: Loaded SoundBank 'urldestroy'
debug: SND: Loaded SoundBank 'urlweapon'
debug: SND: Loaded SoundBank 'urs'
debug: SND: Loaded SoundBank 'ursdestroy'
debug: SND: Loaded SoundBank 'ursstream'
debug: SND: Loaded SoundBank 'ursweapon'
debug: SND: Loaded SoundBank 'xaa'
debug: SND: Loaded SoundBank 'xaa_weapon'
debug: SND: Loaded SoundBank 'xab'
debug: SND: Loaded SoundBank 'xal'
debug: SND: Loaded SoundBank 'xal_weapon'
debug: SND: Loaded SoundBank 'xas'
debug: SND: Loaded SoundBank 'xas_weapon'
debug: SND: Loaded SoundBank 'xca'
debug: SND: Loaded SoundBank 'xcb'
debug: SND: Loaded SoundBank 'xcl'
debug: SND: Loaded SoundBank 'xcs'
debug: SND: Loaded SoundBank 'xea'
debug: SND: Loaded SoundBank 'xea_weapon'
debug: SND: Loaded SoundBank 'xeb'
debug: SND: Loaded SoundBank 'xel'
debug: SND: Loaded SoundBank 'xel_weapons'
debug: SND: Loaded SoundBank 'xes'
debug: SND: Loaded SoundBank 'xes_destroy'
debug: SND: Loaded SoundBank 'xes_weapons'
debug: SND: Loaded SoundBank 'xra'
debug: SND: Loaded SoundBank 'xra_weapon'
debug: SND: Loaded SoundBank 'xrb'
debug: SND: Loaded SoundBank 'xrl'
debug: SND: Loaded SoundBank 'xrl_destroy'
debug: SND: Loaded SoundBank 'xrl_stream'
debug: SND: Loaded SoundBank 'xrl_weapon'
debug: SND: Loaded SoundBank 'xrs'
debug: SND: Loaded SoundBank 'xrs_weapon'
debug: SND: Loaded SoundBank 'xsa'
debug: SND: Loaded SoundBank 'xsa_destroy'
debug: SND: Loaded SoundBank 'xsa_weapon'
debug: SND: Loaded SoundBank 'xsb'
debug: SND: Loaded SoundBank 'xsb_weapon'
debug: SND: Loaded SoundBank 'xsl'
debug: SND: Loaded SoundBank 'xsl_destroy'
debug: SND: Loaded SoundBank 'xsl_weapon'
debug: SND: Loaded SoundBank 'xss'
debug: SND: Loaded SoundBank 'xss_destroy'
debug: SND: Loaded SoundBank 'xss_weapon'
debug: MEM: -1712486624 bytes SND
info: MD5 of global settings: d2a23d6464d3fd77956e7648c43b5077
info: IsStreamingWaveBank("/sounds/voice/us/a01_vo.xwb") => false
debug: Wavebank prepared: 549c1e8
debug: SND: Loaded WaveBank 'a01_vo' at 549c1e8
info: IsStreamingWaveBank("/sounds/voice/us/a02_vo.xwb") => false
debug: Wavebank prepared: 549d568
debug: SND: Loaded WaveBank 'a02_vo' at 549d568
info: IsStreamingWaveBank("/sounds/voice/us/a03_vo.xwb") => false
debug: Wavebank prepared: 549dcb8
debug: SND: Loaded WaveBank 'a03_vo' at 549dcb8
info: IsStreamingWaveBank("/sounds/voice/us/a04_vo.xwb") => false
debug: Wavebank prepared: 549c6c8
debug: SND: Loaded WaveBank 'a04_vo' at 549c6c8
info: IsStreamingWaveBank("/sounds/voice/us/a05_vo.xwb") => false
debug: Wavebank prepared: 549d6a0
debug: SND: Loaded WaveBank 'a05_vo' at 549d6a0
info: IsStreamingWaveBank("/sounds/voice/us/a06_vo.xwb") => false
debug: Wavebank prepared: 549c320
debug: SND: Loaded WaveBank 'a06_vo' at 549c320
info: IsStreamingWaveBank("/sounds/voice/us/briefings.xwb") => true
debug: SND: Loaded WaveBank 'briefings' at 54c8e50
info: IsStreamingWaveBank("/sounds/voice/us/c01_vo.xwb") => false
debug: Wavebank prepared: 549c458
debug: SND: Loaded WaveBank 'c01_vo' at 549c458
info: IsStreamingWaveBank("/sounds/voice/us/c02_vo.xwb") => false
debug: Wavebank prepared: 549ddf0
debug: SND: Loaded WaveBank 'c02_vo' at 549ddf0
info: IsStreamingWaveBank("/sounds/voice/us/c03_vo.xwb") => false
debug: Wavebank prepared: 549c938
debug: SND: Loaded WaveBank 'c03_vo' at 549c938
info: IsStreamingWaveBank("/sounds/voice/us/c04_vo.xwb") => false
debug: Wavebank prepared: 549db80
debug: SND: Loaded WaveBank 'c04_vo' at 549db80
info: IsStreamingWaveBank("/sounds/voice/us/c05_vo.xwb") => false
debug: Wavebank prepared: 549df28
debug: SND: Loaded WaveBank 'c05_vo' at 549df28
info: IsStreamingWaveBank("/sounds/voice/us/c06_vo.xwb") => false
debug: Wavebank prepared: 549d088
debug: SND: Loaded WaveBank 'c06_vo' at 549d088
info: IsStreamingWaveBank("/sounds/voice/us/e01_vo.xwb") => false
debug: Wavebank prepared: 549ca70
debug: SND: Loaded WaveBank 'e01_vo' at 549ca70
info: IsStreamingWaveBank("/sounds/voice/us/e02_vo.xwb") => false
debug: Wavebank prepared: 549cce0
debug: SND: Loaded WaveBank 'e02_vo' at 549cce0
info: IsStreamingWaveBank("/sounds/voice/us/e03_vo.xwb") => false
debug: Wavebank prepared: 549ce18
debug: SND: Loaded WaveBank 'e03_vo' at 549ce18
info: IsStreamingWaveBank("/sounds/voice/us/e04_vo.xwb") => false
debug: Wavebank prepared: 54cb0f0
debug: SND: Loaded WaveBank 'e04_vo' at 54cb0f0
info: IsStreamingWaveBank("/sounds/voice/us/e05_vo.xwb") => false
debug: Wavebank prepared: 54cb228
debug: SND: Loaded WaveBank 'e05_vo' at 54cb228
info: IsStreamingWaveBank("/sounds/voice/us/e06_vo.xwb") => false
debug: Wavebank prepared: 54cbbe8
debug: SND: Loaded WaveBank 'e06_vo' at 54cbbe8
info: IsStreamingWaveBank("/sounds/voice/us/faf_tut_common_vo.xwb") => false
debug: Wavebank prepared: 54ca9a0
debug: SND: Loaded WaveBank 'faf_tut_common_vo' at 54ca9a0
info: IsStreamingWaveBank("/sounds/voice/us/faf_tut_fourleaf_bo_vo.xwb") => false
debug: Wavebank prepared: 54ca250
debug: SND: Loaded WaveBank 'faf_tut_fourleaf_bo_vo' at 54ca250
info: IsStreamingWaveBank("/sounds/voice/us/faf_tut_loki_bo_vo.xwb") => false
debug: Wavebank prepared: 54ca868
debug: SND: Loaded WaveBank 'faf_tut_loki_bo_vo' at 54ca868
info: IsStreamingWaveBank("/sounds/voice/us/faf_tut_summerduel_bo_vo.xwb") => false
debug: Wavebank prepared: 54cb360
debug: SND: Loaded WaveBank 'faf_tut_summerduel_bo_vo' at 54cb360
info: IsStreamingWaveBank("/sounds/voice/us/prothyon16_vo.xwb") => false
debug: Wavebank prepared: 54caad8
debug: SND: Loaded WaveBank 'prothyon16_vo' at 54caad8
info: IsStreamingWaveBank("/sounds/voice/us/seraphim_language.xwb") => true
debug: SND: Loaded WaveBank 'seraphim_language' at 54cbfc0
info: IsStreamingWaveBank("/sounds/voice/us/tcr_vo.xwb") => false
debug: Wavebank prepared: 54cac10
debug: SND: Loaded WaveBank 'tcr_vo' at 54cac10
info: IsStreamingWaveBank("/sounds/voice/us/x01_vo.xwb") => true
debug: SND: Loaded WaveBank 'x01_vo' at 54cd9c0
info: IsStreamingWaveBank("/sounds/voice/us/x02_vo.xwb") => true
debug: SND: Loaded WaveBank 'x02_vo' at 54cd858
info: IsStreamingWaveBank("/sounds/voice/us/x03_vo.xwb") => true
debug: SND: Loaded WaveBank 'x03_vo' at 54cdb28
info: IsStreamingWaveBank("/sounds/voice/us/x04_vo.xwb") => true
debug: SND: Loaded WaveBank 'x04_vo' at 54cd588
info: IsStreamingWaveBank("/sounds/voice/us/x05_vo.xwb") => true
debug: SND: Loaded WaveBank 'x05_vo' at 54cd150
info: IsStreamingWaveBank("/sounds/voice/us/x06_vo.xwb") => true
debug: SND: Loaded WaveBank 'x06_vo' at 54cddf8
info: IsStreamingWaveBank("/sounds/voice/us/x1t_vo.xwb") => true
debug: SND: Loaded WaveBank 'x1t_vo' at 54cd6f0
info: IsStreamingWaveBank("/sounds/voice/us/x_fmv.xwb") => true
debug: SND: Loaded WaveBank 'x_fmv' at 54cdf60
info: IsStreamingWaveBank("/sounds/voice/us/xgg.xwb") => true
debug: SND: Loaded WaveBank 'xgg' at 54cdc90
debug: SND: Loaded SoundBank 'a01_vo'
debug: SND: Loaded SoundBank 'a02_vo'
debug: SND: Loaded SoundBank 'a03_vo'
debug: SND: Loaded SoundBank 'a04_vo'
debug: SND: Loaded SoundBank 'a05_vo'
debug: SND: Loaded SoundBank 'a06_vo'
debug: SND: Loaded SoundBank 'briefings'
debug: SND: Loaded SoundBank 'c01_vo'
debug: SND: Loaded SoundBank 'c02_vo'
debug: SND: Loaded SoundBank 'c03_vo'
debug: SND: Loaded SoundBank 'c04_vo'
debug: SND: Loaded SoundBank 'c05_vo'
debug: SND: Loaded SoundBank 'c06_vo'
debug: SND: Loaded SoundBank 'e01_vo'
debug: SND: Loaded SoundBank 'e02_vo'
debug: SND: Loaded SoundBank 'e03_vo'
debug: SND: Loaded SoundBank 'e04_vo'
debug: SND: Loaded SoundBank 'e05_vo'
debug: SND: Loaded SoundBank 'e06_vo'
debug: SND: Loaded SoundBank 'faf_tut_common_vo'
debug: SND: Loaded SoundBank 'faf_tut_fourleaf_bo_vo'
debug: SND: Loaded SoundBank 'faf_tut_loki_bo_vo'
debug: SND: Loaded SoundBank 'faf_tut_summerduel_bo_vo'
debug: SND: Loaded SoundBank 'prothyon16_vo'
debug: SND: Loaded SoundBank 'tcr_vo'
debug: SND: Loaded SoundBank 'x01_vo'
debug: SND: Loaded SoundBank 'x02_vo'
debug: SND: Loaded SoundBank 'x03_vo'
debug: SND: Loaded SoundBank 'x04_vo'
debug: SND: Loaded SoundBank 'x05_vo'
debug: SND: Loaded SoundBank 'x06_vo'
debug: SND: Loaded SoundBank 'x1t_vo'
debug: SND: Loaded SoundBank 'x_fmv'
debug: SND: Loaded SoundBank 'xgg'
debug: MEM: -796091502 bytes SND
info: MD5 of global settings: d2a23d6464d3fd77956e7648c43b5077
debug: MEM: -796091502 bytes SND
debug: Loading module '\000/lua/sim/buffdefinitions.lua\000'
debug: Loading module '\000/lua/sim/adjacencybuffs.lua\000'
debug: Loading module '\000/lua/sim/adjacencybufffunctions.lua\000'
info: Hooked /lua/sim/adjacencybufffunctions.lua with /schook/lua/sim/adjacencybufffunctions.lua
debug: Loading module '\000/lua/sim/cheatbuffs.lua\000'
debug: Loading module '\000/lua/user/prefs.lua\000'
debug: Loading module '\000/lua/options/optionslogic.lua\000'
info: Hooked /loc/us/strings_db.lua with /mods/coop/hook/loc/us/strings_db.lua
debug: Loading module '\000/lua/ui/uiutil.lua\000'
info: Hooked /lua/ui/uiutil.lua with /mods/coop/hook/lua/ui/uiutil.lua
debug: Loading module '\000/lua/lazyvar.lua\000'
debug: Loading module '\000/lua/maui/layouthelpers.lua\000'
debug: Loading module '\000/lua/maui/group.lua\000'
debug: Loading module '\000/lua/maui/control.lua\000'
debug: Loading module '\000/lua/maui/text.lua\000'
debug: Loading module '\000/lua/maui/multilinetext.lua\000'
debug: Loading module '\000/lua/maui/button.lua\000'
debug: Loading module '\000/lua/maui/bitmap.lua\000'
debug: Loading module '\000/lua/maui/dragger.lua\000'
debug: Loading module '\000/lua/maui/edit.lua\000'
debug: Loading module '\000/lua/utf.lua\000'
debug: Loading module '\000/lua/ui/controls/checkbox.lua\000'
debug: Loading module '\000/lua/maui/radiobuttons.lua\000'
debug: Loading module '\000/lua/maui/checkbox.lua\000'
debug: Loading module '\000/lua/maui/border.lua\000'
debug: Loading module '\000/lua/maui/scrollbar.lua\000'
debug: Loading module '\000/lua/maui/cursor.lua\000'
debug: Loading module '\000/lua/ui/controls/border.lua\000'
debug: Loading module '\000/lua/ui/controls/ninepatch.lua\000'
debug: Loading module '\000/lua/maui/itemlist.lua\000'
debug: Loading module '\000/lua/skins/layouts.lua\000'
debug: Loading module '\000/lua/ui/controls/popups/popup.lua\000'
debug: Loading module '\000/lua/ui/dialogs/eschandler.lua\000'
debug: Loading module '\000/lua/system/utils.lua\000'
debug: Loading module '\000/lua/ui/controls/popups/inputdialog.lua\000'
debug: Loading module '\000/lua/skins/skins.lua\000'
info: /savereplay
info: REPLAY ID: 57396
info: adding font file /fonts/arial.ttf
info: adding font file /fonts/arialbd.ttf
info: adding font file /fonts/arialbi.ttf
info: adding font file /fonts/ariali.ttf
info: adding font file /fonts/arialn.ttf
info: adding font file /fonts/arialnb.ttf
info: adding font file /fonts/arialnbi.ttf
info: adding font file /fonts/arialni.ttf
info: adding font file /fonts/ariblk.ttf
info: adding font file /fonts/arlrdbd.ttf
info: adding font file /fonts/butterbe.ttf
info: adding font file /fonts/vdub.ttf
info: adding font file /fonts/wintermu.ttf
info: adding font file /fonts/zeroes_3.ttf
debug: Loading module '\000/lua/keymap/keynames.lua\000'
debug: Loading module '\000/lua/keymap/keymapper.lua\000'
debug: Loading module '\000/lua/keymap/keydescriptions.lua\000'
debug: Loading module '\000/lua/keymap/keyactions.lua\000'
debug: Loading module '\000/lua/keymap/debugkeyactions.lua\000'
info: Compiled shader: /effects/cartographic.fx
info: Compiled shader: /effects/frame.fx
info: Compiled shader: /effects/mesh.fx
info: Compiled shader: /effects/particle.fx
info: Compiled shader: /effects/primbatcher.fx
info: Compiled shader: /effects/range.fx
info: Compiled shader: /effects/sky.fx
info: Compiled shader: /effects/terrain.fx
info: Compiled shader: /effects/ui.fx
info: Compiled shader: /effects/vision.fx
info: Compiled shader: /effects/water2.fx
info: SHADERS COMPILED
debug: Loading module '\000/lua/options/options.lua\000'
debug: Loading module '\000/lua/usermusic.lua\000'
debug: Loading module '\000/lua/ui/game/reclaim.lua\000'
debug: Wavebank prepared: 548d028
debug: Wavebank prepared: 548e598
debug: Wavebank prepared: 548f960
debug: Wavebank prepared: 5490ac8
debug: Wavebank prepared: 54926e0
debug: Wavebank prepared: 5494ab0
debug: Wavebank prepared: 5497c20
debug: Wavebank prepared: 5498d88
debug: Wavebank prepared: 5499ef0
debug: Wavebank prepared: 549b058
debug: Wavebank prepared: 549e1c8
debug: Wavebank prepared: 54c8e50
debug: Wavebank prepared: 54cbfc0
debug: Wavebank prepared: 54cd858
debug: Wavebank prepared: 54cdb28
debug: Wavebank prepared: 54cd588
debug: Wavebank prepared: 54cd150
debug: Wavebank prepared: 54cddf8
debug: Wavebank prepared: 54cd6f0
debug: Wavebank prepared: 54cdf60
debug: Loading module '\000/lua/maui/frame.lua\000'
debug: Loading module '\000/lua/ui/uimain.lua\000'
debug: Loading module '\000/lua/multiplayer/onlineprovider.lua\000'
debug: Loading module '\000/lua/ui/campaign/campaignmanager.lua\000'
debug: Loading module '\000/lua/multiplayer/gpgnet.lua\000'
info: GPGNET: entering idle state.
debug: Wavebank prepared: 54cd9c0
debug: Wavebank prepared: 54cdc90
debug: Loading module '\000/lua/ui/lobby/lobby.lua\000'
info: Hooked /lua/ui/lobby/lobby.lua with /mods/coop/hook/lua/ui/lobby/lobby.lua
debug: Loading module '\000/lua/version.lua\000'
debug: Loading module '\000/lua/ui/menus/menucommon.lua\000'
debug: Loading module '\000/lua/ui/game/tooltip.lua\000'
debug: Loading module '\000/lua/ui/help/tooltips.lua\000'
debug: Loading module '\000/lua/keymap/defaultkeymap.lua\000'
debug: Loading module '\000/lua/ui/maputil.lua\000'
info: Hooked /lua/ui/maputil.lua with /mods/coop/hook/lua/ui/maputil.lua
debug: Loading module '\000/etc/faf/mapblacklist.lua\000'
debug: Loading module '\000/lua/ui/controls/radiobutton.lua\000'
debug: Loading module '\000/lua/ui/controls/mappreview.lua\000'
debug: Loading module '\000/lua/ui/controls/resmappreview.lua\000'
debug: Loading module '\000/lua/ui/texturepool.lua\000'
debug: Loading module '\000/lua/ui/controls/acubutton.lua\000'
debug: Loading module '\000/lua/gamecolors.lua\000'
debug: Loading module '\000/lua/maui/slider.lua\000'
debug: Loading module '\000/lua/ui/lobby/data/playerdata.lua\000'
debug: Loading module '\000/lua/ui/lobby/data/watchedvalue/watchedvaluetable.lua\000'
debug: Loading module '\000/lua/ui/lobby/data/watchedvalue/watchedvalue.lua\000'
debug: Loading module '\000/lua/factions.lua\000'
debug: Loading module '\000/lua/ui/lobby/data/gamedata.lua\000'
debug: Loading module '\000/lua/ui/lobby/data/watchedvalue/watchedvaluearray.lua\000'
debug: Loading module '\000/lua/ui/controls/togglebutton.lua\000'
debug: Loading module '\000/lua/ui/lobby/lobbycomm.lua\000'
info: Hooked /lua/ui/lobby/lobbycomm.lua with /mods/coop/hook/lua/ui/lobby/lobbycomm.lua
debug: Loading module '\000/lua/ui/controls/textarea.lua\000'
debug: Loading module '\000/lua/ui/lobby/trueskill.lua\000'
debug: Loading module '\000/etc/faf/blacklist.lua\000'
debug: Loading module '\000/lua/ui/help/tooltips-country.lua\000'
debug: Loading module '\000/lua/system/dkson.lua\000'
debug: Loading module '\000/lua/ui/lobby/unitsanalyzer.lua\000'
debug: Loading module '\000/lua/ui/lobby/changelog.lua\000'
debug: Loading module '\000/lua/ui/controls/combo.lua\000'
debug: Loading module '\000/lua/ui/lobby/changelogdata.lua\000'
debug: Loading module '\000/lua/ui/lobby/aitypes.lua\000'
debug: Loading module '\000/lua/ai/customais_v2/sorianai.lua\000'
debug: Loading module '\000/lua/ui/lobby/lobbyoptions.lua\000'
info: Hooked /lua/ui/lobby/lobbyoptions.lua with /mods/coop/hook/lua/ui/lobby/lobbyoptions.lua
debug: Loading module '\000/mods/zombies/lua/ai/lobbyoptions/lobbyoptions.lua\000'
info: /country
info: /init
info: /numgames
info: /mean
info: /clan
info: /deviation
info: GPGNET: setting nat handler to 0x155a4004
info: LOBBY: Game port 56340[UDP] opened.
info: LOBBY: starting with local uid of 112345 [Katharsas]
info: GPGNET: entering lobby state.
info: NET: using deflate compression for sends to JansNB:64703.
info: LOBBY: Connecting to host "cyophy" [JansNB:64703, uid=340471]
info: Can't add chat text -- no chat display
info: text="Connecting to game host..."
info: NET: using deflate compression for receives from JansNB:64703
info: LOBBY: connection to "cyophy" [JansNB:64703, uid=340471] made, status=Connecting.
info: CONNECTED TO HOST
debug: Loading module '\000/lua/maui/effecthelpers.lua\000'
info: Supreme Commander: Forged Alliance version 3709
debug: Loading module '\000/lua/ui/lobby/chatarea.lua\000'
debug: Loading module '\000/lua/maui/statusbar.lua\000'
debug: Loading module '\000/lua/ui/controls/columnlayout.lua\000'
info: LOBBY: "cyophy" [JansNB:64703, uid=340471] has established connections to: 112345
info:  { }
info:  {
info:     zcbf6277-24e3-437a-b968-Common-v1 = true
info:     b0d9ac94-c5e6-11e5-9912-ba0be0483c18 = true
info:     ecbf6277-24e3-597a-b968-EcoManager-v11 = true
info:     95bf3388-b52a-11e5-9f22-ba0be0483c18 = true
info:  }
info:  { }
info:  {
info:     zcbf6277-24e3-437a-b968-Common-v1 = true
info:     b0d9ac94-c5e6-11e5-9912-ba0be0483c18 = true
info:     ecbf6277-24e3-597a-b968-EcoManager-v11 = true
info:     95bf3388-b52a-11e5-9f22-ba0be0483c18 = true
info:  }
info: MOD LIST SET TO:
info:         EcoManager  (ecbf6277-24e3-597a-b968-EcoManager-v11)
info:         Reveal Positions        (b0d9ac94-c5e6-11e5-9912-ba0be0483c18)
info:         Additional Camera Stuff v3.2    (95bf3388-b52a-11e5-9f22-ba0be0483c18)
info:         Common Mod Tools        (zcbf6277-24e3-437a-b968-Common-v1)
info:  {
info:     ad271f12-c9e9-4222-870b-fe68b842f52b = true
info:     6aa65d2a-5926-11dc-8314-0800200c9a08 = true
info:  }
info:  {
info:     zcbf6277-24e3-437a-b968-Common-v1 = true
info:     b0d9ac94-c5e6-11e5-9912-ba0be0483c18 = true
info:     ecbf6277-24e3-597a-b968-EcoManager-v11 = true
info:     95bf3388-b52a-11e5-9f22-ba0be0483c18 = true
info:  }
info:  {
info:     ad271f12-c9e9-4222-870b-fe68b842f52b = true
info:     6aa65d2a-5926-11dc-8314-0800200c9a08 = true
info:  }
info:  {
info:     zcbf6277-24e3-437a-b968-Common-v1 = true
info:     b0d9ac94-c5e6-11e5-9912-ba0be0483c18 = true
info:     ecbf6277-24e3-597a-b968-EcoManager-v11 = true
info:     95bf3388-b52a-11e5-9f22-ba0be0483c18 = true
info:  }
info: MOD LIST SET TO:
info:         Common Mod Tools        (zcbf6277-24e3-437a-b968-Common-v1)
info:         Additional Camera Stuff v3.2    (95bf3388-b52a-11e5-9f22-ba0be0483c18)
info:         1.5x Build Range        (ad271f12-c9e9-4222-870b-fe68b842f52b)
info:         Reveal Positions        (b0d9ac94-c5e6-11e5-9912-ba0be0483c18)
info:         Antares Unit Pack (6aa65d2a-5926-11dc-8314-0800200c9a08)
info:         EcoManager  (ecbf6277-24e3-597a-b968-EcoManager-v11)
debug: Loading module '\000/lua/ui/lobby/modsmanager.lua\000'
debug: Loading module '\000/lua/ui/lobby/unitsrestrictions.lua\000'
info: ModsManager activated: GAME mod - 1.5x Build Range ---- (v1.0) - /mods/x1.5 build range
info: ModsManager activated: GAME mod - Antares Unit Pack ---- (v2.0) - /mods/antares unit pack
info: ModsManager activated: UI mod - EcoManager ---- (v11.0) - /mods/em
info: ModsManager activated: UI mod - Reveal Positions ---- (v1.0) - /mods/reveal_positions
info: ModsManager activated: UI mod - Common Mod Tools ---- (v1.0) - /mods/common
info: ModsManager activated: UI mod - Additional Camera Stuff ---- (v3.2) - /mods/additionalcamerastuff
info: mods.sim.active {
info: mods.sim.active    ad271f12-c9e9-4222-870b-fe68b842f52b = true
info: mods.sim.active    6aa65d2a-5926-11dc-8314-0800200c9a08 = true
info: mods.sim.active }
info: mods.ui.active {
info: mods.ui.active    zcbf6277-24e3-437a-b968-Common-v1 = true
info: mods.ui.active    b0d9ac94-c5e6-11e5-9912-ba0be0483c18 = true
info: mods.ui.active    95bf3388-b52a-11e5-9f22-ba0be0483c18 = true
info: mods.ui.active    ecbf6277-24e3-597a-b968-EcoManager-v11 = true
info: mods.ui.active }
info:  {
info:     ad271f12-c9e9-4222-870b-fe68b842f52b = true
info:     6aa65d2a-5926-11dc-8314-0800200c9a08 = true
info:  }
info:  {
info:     zcbf6277-24e3-437a-b968-Common-v1 = true
info:     b0d9ac94-c5e6-11e5-9912-ba0be0483c18 = true
info:     95bf3388-b52a-11e5-9f22-ba0be0483c18 = true
info:     ecbf6277-24e3-597a-b968-EcoManager-v11 = true
info:  }
info: MOD LIST SET TO:
info:         Common Mod Tools        (zcbf6277-24e3-437a-b968-Common-v1)
info:         EcoManager  (ecbf6277-24e3-597a-b968-EcoManager-v11)
info:         1.5x Build Range        (ad271f12-c9e9-4222-870b-fe68b842f52b)
info:         Reveal Positions        (b0d9ac94-c5e6-11e5-9912-ba0be0483c18)
info:         Antares Unit Pack (6aa65d2a-5926-11dc-8314-0800200c9a08)
info:         Additional Camera Stuff v3.2    (95bf3388-b52a-11e5-9f22-ba0be0483c18)
info:  { }
info:  {
info:     zcbf6277-24e3-437a-b968-Common-v1 = true
info:     b0d9ac94-c5e6-11e5-9912-ba0be0483c18 = true
info:     ecbf6277-24e3-597a-b968-EcoManager-v11 = true
info:     95bf3388-b52a-11e5-9f22-ba0be0483c18 = true
info:  }
info:  { }
info:  {
info:     zcbf6277-24e3-437a-b968-Common-v1 = true
info:     b0d9ac94-c5e6-11e5-9912-ba0be0483c18 = true
info:     ecbf6277-24e3-597a-b968-EcoManager-v11 = true
info:     95bf3388-b52a-11e5-9f22-ba0be0483c18 = true
info:  }
info: MOD LIST SET TO:
info:         EcoManager  (ecbf6277-24e3-597a-b968-EcoManager-v11)
info:         Reveal Positions        (b0d9ac94-c5e6-11e5-9912-ba0be0483c18)
info:         Additional Camera Stuff v3.2    (95bf3388-b52a-11e5-9f22-ba0be0483c18)
info:         Common Mod Tools        (zcbf6277-24e3-437a-b968-Common-v1)
debug: Loading module '\000/lua/ui/game/gamemain.lua\000'
debug: Loading module '\000/lua/ui/game/wlduiprovider.lua\000'
debug: Loading module '\000/lua/ui/game/gamecommon.lua\000'
debug: Loading module '\000/lua/maui/movie.lua\000'
debug: Loading module '\000/lua/ui/controls.lua\000'
debug: Loading module '\000/lua/ui/game/chat.lua\000'
debug: Loading module '\000/lua/uiutilssorian.lua\000'
debug: Loading module '\000/lua/maui/window.lua\000'
info: Hooked /lua/maui/window.lua with /schook/lua/maui/window.lua
debug: Loading module '\000/lua/ui/notify/commands.lua\000'
debug: OpenMovie /movies/seraphim_load.sfd: 1
debug: Preparing movie /movies/seraphim_load.sfd: 1
debug: Preparing movie /movies/seraphim_load.sfd: 1
debug: Preparing movie /movies/seraphim_load.sfd: 1
debug: Preparing movie /movies/seraphim_load.sfd: 1
debug: Preparing movie /movies/seraphim_load.sfd: 1
debug: Preparing movie /movies/seraphim_load.sfd: 1
debug: Playing movie c:\program files (x86)\steam\steamapps\common\supreme commander forged alliance\movies\seraphim_load.sfd: 1
debug: Loading module '\000/lua/ui/help/loadingtips.lua\000'
info: Starting background task "Map loader /maps/x1ca_001/x1ca_001.scmap"
info: Background task "Map loader /maps/x1ca_001/x1ca_001.scmap" running.
info: Active game mods for blueprint loading: \000{ }
info: Blueprints Loading... '*.bp' files
info: Blueprints Loading: original files from /effects directory
info: Blueprints Loading: original files from /env directory
info: Blueprints Loading: original files from /meshes directory
info: Blueprints Loading: original files from /projectiles directory
info: Blueprints Loading: original files from /props directory
info: Blueprints Loading: original files from /units directory
info: Blueprints Extracting mesh...
info: Blueprints Modding...
info: Blueprints Loading... completed: 599 original, 0 modded, and 25 preset units
info: Blueprints Loading... completed: 379 original and 0 modded projectiles
info: Blueprints Registering...
debug: MEM: -31 bytes RULE
info: Hooked /lua/SessionInit.lua with /schook/lua/SessionInit.lua
info: Hooked /lua/userInit.lua with /schook/lua/userInit.lua
info: Hooked /lua/globalInit.lua with /schook/lua/globalInit.lua
info: Hooked /loc/us/strings_db.lua with /mods/coop/hook/loc/us/strings_db.lua
debug: Loading module '\000/lua/mods.lua\000'
debug: Loading module '\000/lua/system/setutils.lua\000'
debug: Loading module '\000/lua/sim/buffdefinitions.lua\000'
debug: Loading module '\000/lua/sim/adjacencybuffs.lua\000'
debug: Loading module '\000/lua/sim/adjacencybufffunctions.lua\000'
info: Hooked /lua/sim/adjacencybufffunctions.lua with /schook/lua/sim/adjacencybufffunctions.lua
debug: Loading module '\000/lua/sim/cheatbuffs.lua\000'
debug: Loading module '\000/lua/user/prefs.lua\000'
debug: Loading module '\000/lua/options/optionslogic.lua\000'
info: Hooked /loc/us/strings_db.lua with /mods/coop/hook/loc/us/strings_db.lua
debug: Loading module '\000/lua/ui/uiutil.lua\000'
info: Hooked /lua/ui/uiutil.lua with /mods/coop/hook/lua/ui/uiutil.lua
debug: Loading module '\000/lua/lazyvar.lua\000'
debug: Loading module '\000/lua/maui/layouthelpers.lua\000'
debug: Loading module '\000/lua/maui/group.lua\000'
debug: Loading module '\000/lua/maui/control.lua\000'
debug: Loading module '\000/lua/maui/text.lua\000'
debug: Loading module '\000/lua/maui/multilinetext.lua\000'
debug: Loading module '\000/lua/maui/button.lua\000'
debug: Loading module '\000/lua/maui/bitmap.lua\000'
debug: Loading module '\000/lua/maui/dragger.lua\000'
debug: Loading module '\000/lua/maui/edit.lua\000'
debug: Loading module '\000/lua/utf.lua\000'
debug: Loading module '\000/lua/ui/controls/checkbox.lua\000'
debug: Loading module '\000/lua/maui/radiobuttons.lua\000'
debug: Loading module '\000/lua/maui/checkbox.lua\000'
debug: Loading module '\000/lua/maui/border.lua\000'
debug: Loading module '\000/lua/maui/scrollbar.lua\000'
debug: Loading module '\000/lua/maui/cursor.lua\000'
debug: Loading module '\000/lua/ui/controls/border.lua\000'
debug: Loading module '\000/lua/ui/controls/ninepatch.lua\000'
debug: Loading module '\000/lua/maui/itemlist.lua\000'
debug: Loading module '\000/lua/skins/layouts.lua\000'
debug: Loading module '\000/lua/ui/controls/popups/popup.lua\000'
debug: Loading module '\000/lua/ui/dialogs/eschandler.lua\000'
debug: Loading module '\000/lua/system/utils.lua\000'
debug: Loading module '\000/lua/ui/controls/popups/inputdialog.lua\000'
debug: Loading module '\000/lua/skins/skins.lua\000'
info: /savereplay
info: REPLAY ID: 57396
info: Active mods in session: \000{
info:   {
info:     after={ },
info:     author="Myxir, Anihilnine",
info:     before={ },
info:     conflicts={ },
info:     copyright="Do whatever you want with it, feel free to add stuff, copy, edit, delete code or publish own versions",
info:     description="Multiple things regarding worldview, minimap and camera actions.",
info:     enabled=true,
info:     exclusive=false,
info:     hookdir="/hook",
info:     icon="/mods/additionalCameraStuff/icon.png",
info:     location="/mods/additionalcamerastuff",
info:     name="Additional Camera Stuff v3.2",
info:     requires={ },
info:     requiresNames={ },
info:     selectable=true,
info:     shadowdir="/shadow",
info:     ui_only=true,
info:     uid="95bf3388-b52a-11e5-9f22-ba0be0483c18",
info:     version=3.2000000476837
info:   },
info:   {
info:     author="Myxir",
info:     conflicts={ },
info:     copyright="Myxir",
info:     description="Reveals starting locations of players",
info:     exclusive=false,
info:     hookdir="/hook",
info:     icon="/textures/ui/common/dialogs/mod-manager/generic-icon_bmp.dds",
info:     location="/mods/reveal_positions",
info:     name="Reveal Positions",
info:     selectable=true,
info:     shadowdir="/shadow",
info:     ui_only=true,
info:     uid="b0d9ac94-c5e6-11e5-9912-ba0be0483c18",
info:     url="",
info:     version=1
info:   },
info:   {
info:     after={ },
info:     author="Crotalus",
info:     before={ "zcbf6277-24e3-437a-b968-Common-v1" },
info:     conflicts={
info:       "ecbf6277-24e3-437a-b968-EcoManager-v10",
info:       "ecbf6277-24e3-437a-b968-EcoManager-v9",
info:       "ecbf6277-24e3-437a-b968-EcoManager-v8",
info:       "ecbf6277-24e3-437a-b968-EcoManager-v7",
info:       "ecbf6277-24e3-437a-b968-EcoManager-v6",
info:       "ecbf6277-24e3-437a-b968-EcoManager-v5",
info:       "ecbf6277-24e3-437a-b968-EcoManager-v4",
info:       "ecbf6277-24e3-437a-b968-75e7e7c67db9",
info:       "21188cdf-ec69-43bd-b756-6140a84c0197",
info:       "5c1ac506-03d3-4734-b6c1-0746592849c3",
info:       "5f56b6fd-de36-44f1-ba2b-e7d012025f2a"
info:     },
info:     copyright="Crotalus",
info:     description="EcoManager, helps with micromanaging the economy, 3686 compatible",
info:     enabled=true,
info:     exclusive=false,
info:     hookdir="/hook",
info:     icon="/textures/ui/common/dialogs/mod-manager/generic-icon_bmp.dds",
info:     location="/mods/em",
info:     name="EcoManager",
info:     requires={ "zcbf6277-24e3-437a-b968-Common-v1" },
info:     requiresNames={ },
info:     selectable=true,
info:     shadowdir="/shadow",
info:     ui_only=true,
info:     uid="ecbf6277-24e3-597a-b968-EcoManager-v11",
info:     url="",
info:     version=11
info:   },
info:   {
info:     after={ },
info:     author="Crotalus",
info:     before={ },
info:     conflicts={
info:       "ecbf6277-24e3-437a-b968-EcoManager-v4",
info:       "ecbf6277-24e3-437a-b968-75e7e7c67db9",
info:       "21188cdf-ec69-43bd-b756-6140a84c0197",
info:       "5c1ac506-03d3-4734-b6c1-0746592849c3",
info:       "5f56b6fd-de36-44f1-ba2b-e7d012025f2a"
info:     },
info:     copyright="Crotalus",
info:     description="Common ModTools v1, toolbox for other mods",
info:     enabled=true,
info:     exclusive=false,
info:     hookdir="/hook",
info:     icon="/textures/ui/common/dialogs/mod-manager/generic-icon_bmp.dds",
info:     location="/mods/common",
info:     name="Common Mod Tools",
info:     requires={ },
info:     requiresNames={ },
info:     selectable=true,
info:     shadowdir="/shadow",
info:     ui_only=true,
info:     uid="zcbf6277-24e3-437a-b968-Common-v1",
info:     url="",
info:     version=1
info:   }
info: }
info: Hooked /lua/UserSync.lua with /schook/lua/UserSync.lua
info: Hooked /lua/UserSync.lua with /mods/coop/hook/lua/UserSync.lua
debug: Loading module '\000/lua/ui/game/reclaim.lua\000'
debug: Loading module '\000/lua/ui/notify/notify.lua\000'
debug: Loading module '\000/lua/ui/game/chat.lua\000'
info: Hooked /lua/ui/game/chat.lua with /mods/em/hook/lua/ui/game/chat.lua
debug: Loading module '\000/lua/uiutilssorian.lua\000'
debug: Loading module '\000/lua/maui/effecthelpers.lua\000'
debug: Loading module '\000/lua/maui/window.lua\000'
info: Hooked /lua/maui/window.lua with /schook/lua/maui/window.lua
debug: Loading module '\000/lua/ui/controls/combo.lua\000'
debug: Loading module '\000/lua/ui/uimain.lua\000'
debug: Loading module '\000/lua/multiplayer/onlineprovider.lua\000'
debug: Loading module '\000/lua/ui/campaign/campaignmanager.lua\000'
debug: Loading module '\000/lua/maui/slider.lua\000'
debug: Loading module '\000/lua/ui/game/tooltip.lua\000'
debug: Loading module '\000/lua/ui/help/tooltips.lua\000'
debug: Loading module '\000/lua/keymap/defaultkeymap.lua\000'
debug: Loading module '\000/lua/ui/controls.lua\000'
debug: Loading module '\000/lua/factions.lua\000'
debug: Loading module '\000/lua/ui/notify/commands.lua\000'
debug: Loading module '\000/mods/em/modules/commands.lua\000'
debug: Loading module '\000/lua/ui/notify/defaultmessages.lua\000'
debug: Loading module '\000/lua/ui/notify/notifyoverlay.lua\000'
info: Hooked /lua/UserSync.lua with /schook/lua/UserSync.lua
info: Hooked /lua/UserSync.lua with /mods/coop/hook/lua/UserSync.lua
debug: MEM: -5247026 bytes STIMap
debug: MEM: -5247026 bytes LoadTexturing
debug: MEM: -5247026 bytes WaterMask
debug: MEM: -12252683 bytes TERRAIN
info: Background task "Map loader /maps/x1ca_001/x1ca_001.scmap" finished.
info: Saving replay to "gpgnet://127.0.0.1:57396/10893152/Katharsas.SCFAreplay"
debug: MEM: -32 bytes LUABP
info: Hooked /lua/simInit.lua with /schook/lua/simInit.lua
info: Hooked /lua/simInit.lua with /mods/coop/hook/lua/simInit.lua
info: Hooked /lua/globalInit.lua with /schook/lua/globalInit.lua
info: Hooked /loc/us/strings_db.lua with /mods/coop/hook/loc/us/strings_db.lua
debug: Loading module '\000/lua/mods.lua\000'
debug: Loading module '\000/lua/system/setutils.lua\000'
debug: Loading module '\000/lua/sim/buffdefinitions.lua\000'
debug: Loading module '\000/lua/sim/adjacencybuffs.lua\000'
debug: Loading module '\000/lua/sim/adjacencybufffunctions.lua\000'
info: Hooked /lua/sim/adjacencybufffunctions.lua with /schook/lua/sim/adjacencybufffunctions.lua
debug: Loading module '\000/lua/sim/cheatbuffs.lua\000'
info: Hooked /lua/SimSync.lua with /schook/lua/SimSync.lua
info: Hooked /lua/SimSync.lua with /schook/lua/SimSync.lua
debug: Loading module '\000/lua/sim/scenarioutilities.lua\000'
info: Hooked /lua/sim/scenarioutilities.lua with /mods/coop/hook/lua/sim/scenarioutilities.lua
debug: Loading module '\000/lua/sim/entity.lua\000'
debug: Loading module '\000/lua/scenarioframework.lua\000'
info: Hooked /lua/scenarioframework.lua with /mods/coop/hook/lua/scenarioframework.lua
debug: Loading module '\000/lua/scenariotriggers.lua\000'
info: Hooked /lua/scenariotriggers.lua with /mods/coop/hook/lua/scenariotriggers.lua
debug: Loading module '\000/lua/upgradetemplates.lua\000'
debug: Loading module '\000/lua/scenarioplatoonai.lua\000'
debug: Loading module '\000/lua/utilities.lua\000'
debug: Loading module '\000/lua/ai/aibuildstructures.lua\000'
debug: Loading module '\000/lua/basetemplates.lua\000'
debug: Loading module '\000/lua/buildingtemplates.lua\000'
debug: Loading module '\000/lua/ai/aiutilities.lua\000'
debug: Loading module '\000/lua/unittemplates.lua\000'
debug: Loading module '\000/lua/ai/aiattackutilities.lua\000'
debug: Loading module '\000/lua/ai/sorianutilities.lua\000'
debug: Loading module '\000/lua/ai/sorianlang.lua\000'
debug: Loading module '\000/lua/sim/buff.lua\000'
debug: Loading module '\000/lua/ai/aibehaviors.lua\000'
debug: Loading module '\000/lua/editor/unitcountbuildconditions.lua\000'
debug: Loading module '\000/lua/editor/sorianbuildconditions.lua\000'
debug: Loading module '\000/lua/editor/markerbuildconditions.lua\000'
debug: Loading module '\000/lua/sim/vizmarker.lua\000'
debug: Loading module '\000/lua/simcamera.lua\000'
debug: Loading module '\000/lua/system/singleevent.lua\000'
debug: Loading module '\000/lua/cinematics.lua\000'
debug: Loading module '\000/lua/sim/simuistate.lua\000'
debug: Loading module '\000/lua/simpinggroup.lua\000'
debug: Loading module '\000/lua/simobjectives.lua\000'
debug: Loading module '\000/lua/sim/categoryutils.lua\000'
debug: Loading module '\000/lua/game.lua\000'
debug: Loading module '\000/lua/sim/bufffield.lua\000'
debug: Loading module '\000/lua/ui/lobby/unitsanalyzer.lua\000'
debug: Loading module '\000/lua/factions.lua\000'
debug: Loading module '\000/lua/ai/platoontemplates/airplatoontemplates.lua\000'
debug: Loading module '\000/lua/ai/platoontemplates/airplatoontemplatessorian.lua\000'
debug: Loading module '\000/lua/ai/platoontemplates/engineerplatoontemplates.lua\000'
debug: Loading module '\000/lua/ai/platoontemplates/engineerplatoontemplatessorian.lua\000'
debug: Loading module '\000/lua/ai/platoontemplates/landplatoontemplates.lua\000'
debug: Loading module '\000/lua/ai/platoontemplates/landplatoontemplatessorian.lua\000'
debug: Loading module '\000/lua/ai/platoontemplates/seaplatoontemplates.lua\000'
debug: Loading module '\000/lua/ai/platoontemplates/seaplatoontemplatessorian.lua\000'
debug: Loading module '\000/lua/ai/platoontemplates/structureplatoontemplates.lua\000'
debug: Loading module '\000/lua/ai/platoontemplates/structureplatoontemplatessorian.lua\000'
debug: Loading module '\000/lua/ai/aibuilders/aiairattackbuilders.lua\000'
debug: Loading module '\000/lua/ai/aibuilders/aiartillerybuilders.lua\000'
debug: Loading module '\000/lua/ai/aibuilders/aidefensebuilders.lua\000'
debug: Loading module '\000/lua/ai/aiaddbuildertable.lua\000'
debug: Loading module '\000/lua/ai/aibuilders/aieconomicbuilders.lua\000'
debug: Loading module '\000/lua/ai/aibuilders/aieconomyupgradebuilders.lua\000'
debug: Loading module '\000/lua/ai/aibuilders/aiexpansionbuilders.lua\000'
debug: Loading module '\000/lua/ai/aibuilders/aiexperimentalbuilders.lua\000'
debug: Loading module '\000/lua/ai/aibuilders/aifactoryconstructionbuilders.lua\000'
debug: Loading module '\000/lua/ai/aibuilders/aiintelbuilders.lua\000'
debug: Loading module '\000/lua/ai/aibuilders/ailandattackbuilders.lua\000'
debug: Loading module '\000/lua/ai/aibuilders/ainavalbuilders.lua\000'
debug: Loading module '\000/lua/ai/aibuilders/aiseaattackbuilders.lua\000'
debug: Loading module '\000/lua/ai/aibuilders/sorianairattackbuilders.lua\000'
debug: Loading module '\000/lua/ai/aibuilders/sorianartillerybuilders.lua\000'
debug: Loading module '\000/lua/ai/aibuilders/soriandefensebuilders.lua\000'
debug: Loading module '\000/lua/ai/aibuilders/sorianeconomicbuilders.lua\000'
debug: Loading module '\000/lua/ai/aibuilders/sorianeconomyupgradebuilders.lua\000'
debug: Loading module '\000/lua/ai/aibuilders/sorianexpansionbuilders.lua\000'
debug: Loading module '\000/lua/ai/aibuilders/sorianexperimentalbuilders.lua\000'
debug: Loading module '\000/lua/ai/aibuilders/sorianfactoryconstructionbuilders.lua\000'
debug: Loading module '\000/lua/ai/aibuilders/sorianintelbuilders.lua\000'
debug: Loading module '\000/lua/ai/aibuilders/sorianlandattackbuilders.lua\000'
debug: Loading module '\000/lua/ai/aibuilders/soriannavalbuilders.lua\000'
debug: Loading module '\000/lua/ai/aibuilders/sorianseaattackbuilders.lua\000'
debug: Loading module '\000/lua/ai/aibuilders/sorianstrategybuilders.lua\000'
debug: Loading module '\000/lua/ai/aibuilders/sorianstrategyplatoonbuilders.lua\000'
debug: Loading module '\000/lua/ai/aibasetemplates/challengeexpansion.lua\000'
debug: Loading module '\000/lua/ai/aibasetemplates/challengemain.lua\000'
debug: Loading module '\000/lua/ai/aibasetemplates/challengenaval.lua\000'
debug: Loading module '\000/lua/ai/aibasetemplates/navalexpansionlarge.lua\000'
debug: Loading module '\000/lua/ai/aibasetemplates/navalexpansionsmall.lua\000'
debug: Loading module '\000/lua/ai/aibasetemplates/normalmain.lua\000'
debug: Loading module '\000/lua/ai/aibasetemplates/normalnaval.lua\000'
debug: Loading module '\000/lua/ai/aibasetemplates/rushexpansionairfull.lua\000'
debug: Loading module '\000/lua/ai/aibasetemplates/rushexpansionairsmall.lua\000'
debug: Loading module '\000/lua/ai/aibasetemplates/rushexpansionbalancedfull.lua\000'
debug: Loading module '\000/lua/ai/aibasetemplates/rushexpansionbalancedsmall.lua\000'
debug: Loading module '\000/lua/ai/aibasetemplates/rushexpansionlandfull.lua\000'
debug: Loading module '\000/lua/ai/aibasetemplates/rushexpansionlandsmall.lua\000'
debug: Loading module '\000/lua/ai/aibasetemplates/rushexpansionnaval.lua\000'
debug: Loading module '\000/lua/ai/aibasetemplates/rushmainair.lua\000'
debug: Loading module '\000/lua/ai/aibasetemplates/rushmainbalanced.lua\000'
debug: Loading module '\000/lua/ai/aibasetemplates/rushmainland.lua\000'
debug: Loading module '\000/lua/ai/aibasetemplates/rushmainnaval.lua\000'
debug: Loading module '\000/lua/ai/aibasetemplates/rushsetons.lua\000'
debug: Loading module '\000/lua/ai/aibasetemplates/sorianexpansionairfull.lua\000'
debug: Loading module '\000/lua/ai/aibasetemplates/sorianexpansionbalancedfull.lua\000'
debug: Loading module '\000/lua/ai/aibasetemplates/sorianexpansionbalancedsmall.lua\000'
debug: Loading module '\000/lua/ai/aibasetemplates/sorianexpansionturtlefull.lua\000'
debug: Loading module '\000/lua/ai/aibasetemplates/sorianexpansionwaterfull.lua\000'
debug: Loading module '\000/lua/ai/aibasetemplates/sorianmainair.lua\000'
debug: Loading module '\000/lua/ai/aibasetemplates/sorianmainbalanced.lua\000'
debug: Loading module '\000/lua/ai/aibasetemplates/sorianmainrush.lua\000'
debug: Loading module '\000/lua/ai/aibasetemplates/sorianmainturtle.lua\000'
debug: Loading module '\000/lua/ai/aibasetemplates/sorianmainwater.lua\000'
debug: Loading module '\000/lua/ai/aibasetemplates/soriannavalexpansionlarge.lua\000'
debug: Loading module '\000/lua/ai/aibasetemplates/soriannavalexpansionsmall.lua\000'
debug: Loading module '\000/lua/ai/aibasetemplates/techexpansion.lua\000'
debug: Loading module '\000/lua/ai/aibasetemplates/techexpansionsmall.lua\000'
debug: Loading module '\000/lua/ai/aibasetemplates/techmain.lua\000'
debug: Loading module '\000/lua/ai/aibasetemplates/techsmall.lua\000'
debug: Loading module '\000/lua/ai/aibasetemplates/turtleexpansion.lua\000'
debug: Loading module '\000/lua/ai/aibasetemplates/turtlemain.lua\000'
debug: MEM: -32 bytes OGRID
debug: Loading module '\000/lua/triggermanager.lua\000'
debug: Loading module '\000/lua/scenarioenvironment.lua\000'
debug: Loading module '\000/lua/ui/lobby/lobbyoptions.lua\000'
info: Hooked /lua/ui/lobby/lobbyoptions.lua with /mods/coop/hook/lua/ui/lobby/lobbyoptions.lua
info: Loading save file: \000/maps/x1ca_coop_001.v0024/X1CA_Coop_001_save.lua
info: Loading script file: \000/maps/x1ca_coop_001.v0024/X1CA_Coop_001_script.lua
debug: Loading module '\000/lua/ai/opai/basemanager.lua\000'
debug: Loading module '\000/lua/ai/opai/baseopai.lua\000'
debug: Loading module '\000/lua/ai/opai/reactiveai.lua\000'
debug: Loading module '\000/lua/ai/opai/navalopai.lua\000'
debug: Loading module '\000/lua/ai/opai/generatenaval.lua\000'
debug: Loading module '\000/maps/x1ca_coop_001.v0024/x1ca_coop_001_m1orderai.lua\000'
debug: Loading module '\000/maps/x1ca_coop_001.v0024/x1ca_coop_001_m2orderai.lua\000'
debug: Loading module '\000/maps/x1ca_coop_001.v0024/x1ca_coop_001_m2uefai.lua\000'
debug: Loading module '\000/maps/x1ca_coop_001.v0024/x1ca_coop_001_m3orderai.lua\000'
debug: Loading module '\000/maps/x1ca_coop_001.v0024/x1ca_coop_001_m4uefai.lua\000'
debug: Loading module '\000/maps/x1ca_coop_001.v0024/x1ca_coop_001_m4seraphimai.lua\000'
debug: Loading module '\000/maps/x1ca_coop_001.v0024/x1ca_coop_001_strings.lua\000'
debug: Loading module '\000/lua/tauntmanager.lua\000'
debug: Loading module '\000/lua/aibrain.lua\000'
info: Hooked /lua/aibrain.lua with /mods/coop/hook/lua/aibrain.lua
debug: Loading module '\000/lua/aibrainplans.lua\000'
debug: Loading module '\000/lua/editor/platooncountbuildconditions.lua\000'
debug: Loading module '\000/lua/ai/aibuildunits.lua\000'
debug: Loading module '\000/lua/sim/factorybuildermanager.lua\000'
debug: Loading module '\000/lua/sim/buildermanager.lua\000'
debug: Loading module '\000/lua/sim/builder.lua\000'
debug: Loading module '\000/lua/sim/platoonformmanager.lua\000'
debug: Loading module '\000/lua/sim/brainconditionsmonitor.lua\000'
debug: Loading module '\000/lua/sim/engineermanager.lua\000'
debug: Loading module '\000/lua/sim/strategymanager.lua\000'
debug: Loading module '\000/lua/sim/strategybuilder.lua\000'
debug: Loading module '\000/lua/simutils.lua\000'
info: Hooked /lua/simutils.lua with /mods/coop/hook/lua/simutils.lua
debug: Loading module '\000/lua/simplayerquery.lua\000'
debug: Loading module '\000/lua/sim/score.lua\000'
debug: Loading module '\000/lua/aipersonality.lua\000'
debug: Loading module '\000/lua/platoon.lua\000'
info: Hooked /lua/platoon.lua with /mods/coop/hook/lua/platoon.lua
debug: Loading module '\000/lua/ai/opai/defaultblankplanlist.lua\000'
info: * OnCreateAI: AIPersonality: ()
info: * OnCreateAI: AIPersonality: ()
info: * OnCreateAI: AIPersonality: ()
info: * OnCreateAI: AIPersonality: ()
debug: Loading module '\000/lua/sim/prop.lua\000'
debug: Loading module '\000/lua/effectutilities.lua\000'
debug: Loading module '\000/lua/effecttemplates.lua\000'
debug: Loading module '\000/lua/proptree.lua\000'
debug: Loading module '\000/lua/defaultexplosions.lua\000'
warning:  NUM PROPS = 4157
info: BeginSession...
debug: Active mods in sim: \000{ }
info: *DEBUG: InitializeScenarioArmies, army = \000Player1
info: *DEBUG: InitializeScenarioArmies, army = \000Seraphim
info: *DEBUG: InitializeScenarioArmies, army = \000Order
info: *DEBUG: InitializeScenarioArmies, army = \000UEF
info: *DEBUG: InitializeScenarioArmies, army = \000Civilians
debug: Loading module '\000/units/ueb5101/ueb5101_script.lua\000'
debug: Loading module '\000/lua/terranunits.lua\000'
debug: Loading module '\000/lua/defaultunits.lua\000'
debug: Loading module '\000/lua/sim/unit.lua\000'
info: Hooked /lua/sim/unit.lua with /mods/coop/hook/lua/sim/unit.lua
debug: Loading module '\000/lua/shield.lua\000'
debug: Loading module '\000/lua/overspill.lua\000'
debug: Loading module '\000/lua/wreckage.lua\000'
debug: Loading module '\000/lua/armordefinition.lua\000'
debug: Loading module '\000/units/xec8009/xec8009_script.lua\000'
debug: Loading module '\000/units/ueb0101/ueb0101_script.lua\000'
debug: Loading module '\000/lua/tarmacs.lua\000'
debug: Loading module '\000/units/ueb2304/ueb2304_script.lua\000'
debug: Loading module '\000/lua/terranweapons.lua\000'
info: Hooked /lua/terranweapons.lua with /schook/lua/terranweapons.lua
debug: Loading module '\000/lua/sim/defaultweapons.lua\000'
debug: Loading module '\000/lua/sim/weapon.lua\000'
info: Hooked /lua/sim/weapon.lua with /schook/lua/sim/weapon.lua
debug: Loading module '\000/lua/sim/nukedamage.lua\000'
debug: Loading module '\000/lua/sim/collisionbeam.lua\000'
debug: Loading module '\000/lua/sim/defaultdamage.lua\000'
debug: Loading module '\000/lua/sim/calcballisticacceleration.lua\000'
debug: Loading module '\000/lua/defaultcollisionbeams.lua\000'
debug: Loading module '\000/units/xec8004/xec8004_script.lua\000'
debug: Loading module '\000/units/ueb1101/ueb1101_script.lua\000'
debug: Loading module '\000/units/xec8001/xec8001_script.lua\000'
debug: Loading module '\000/units/uaa0203/uaa0203_script.lua\000'
debug: Loading module '\000/lua/aeonunits.lua\000'
debug: Loading module '\000/lua/aeonweapons.lua\000'
info: Hooked /lua/aeonweapons.lua with /schook/lua/aeonweapons.lua
debug: Loading module '\000/lua/sim/navigator.lua\000'
debug: Loading module '\000/units/uel0205/uel0205_script.lua\000'
debug: Loading module '\000/units/zeb9501/zeb9501_script.lua\000'
debug: Loading module '\000/units/ueb1105/ueb1105_script.lua\000'
debug: Loading module '\000/units/uaa0303/uaa0303_script.lua\000'
debug: Loading module '\000/units/zeb9502/zeb9502_script.lua\000'
debug: Loading module '\000/units/ueb5202/ueb5202_script.lua\000'
debug: Loading module '\000/units/uel0303/uel0303_script.lua\000'
debug: Loading module '\000/units/uaa0102/uaa0102_script.lua\000'
debug: Loading module '\000/units/uea0203/uea0203_script.lua\000'
debug: Loading module '\000/units/ueb2109/ueb2109_script.lua\000'
debug: Loading module '\000/units/ueb0102/ueb0102_script.lua\000'
debug: Loading module '\000/units/ueb1106/ueb1106_script.lua\000'
debug: Loading module '\000/units/xel0305/xel0305_script.lua\000'
debug: Loading module '\000/units/zeb9601/zeb9601_script.lua\000'
debug: Loading module '\000/units/zeb9602/zeb9602_script.lua\000'
debug: Loading module '\000/units/uea0102/uea0102_script.lua\000'
debug: Loading module '\000/units/zeb9603/zeb9603_script.lua\000'
debug: Loading module '\000/units/xec8012/xec8012_script.lua\000'
debug: Loading module '\000/units/ueb1303/ueb1303_script.lua\000'
debug: Loading module '\000/units/xec8003/xec8003_script.lua\000'
debug: Loading module '\000/units/ueb3202/ueb3202_script.lua\000'
info: *DEBUG: InitializeScenarioArmies, army = \000Player2
debug: Loading module '\000/units/xec8011/xec8011_script.lua\000'
debug: Loading module '\000/units/xec8002/xec8002_script.lua\000'
debug: Loading module '\000/units/xec8010/xec8010_script.lua\000'
debug: Loading module '\000/units/ueb1302/ueb1302_script.lua\000'
debug: Loading module '\000/units/ueb1301/ueb1301_script.lua\000'
debug: Loading module '\000/units/ueb4301/ueb4301_script.lua\000'
debug: Loading module '\000/units/ueb0304/ueb0304_script.lua\000'
debug: Loading module '\000/units/ueb3201/ueb3201_script.lua\000'
debug: Loading module '\000/units/ueb2104/ueb2104_script.lua\000'
debug: Loading module '\000/units/ueb2204/ueb2204_script.lua\000'
debug: Loading module '\000/lua/formations.lua\000'
debug: Loading module '\000/units/ues0203/ues0203_script.lua\000'
debug: Loading module '\000/units/uab2101/uab2101_script.lua\000'
debug: Loading module '\000/units/ual0309/ual0309_script.lua\000'
debug: Loading module '\000/units/ual0301/ual0301_script.lua\000'
debug: Loading module '\000/units/uab1106/uab1106_script.lua\000'
debug: Loading module '\000/units/uab1104/uab1104_script.lua\000'
debug: Loading module '\000/units/uab1302/uab1302_script.lua\000'
debug: Loading module '\000/units/uab1101/uab1101_script.lua\000'
debug: Loading module '\000/units/uab1301/uab1301_script.lua\000'
debug: Loading module '\000/units/uab1105/uab1105_script.lua\000'
debug: Loading module '\000/units/uab1102/uab1102_script.lua\000'
debug: Loading module '\000/units/uab1201/uab1201_script.lua\000'
debug: Loading module '\000/units/uab0302/uab0302_script.lua\000'
debug: Loading module '\000/units/zab9602/zab9602_script.lua\000'
debug: Loading module '\000/units/zab9502/zab9502_script.lua\000'
debug: Loading module '\000/units/uab1303/uab1303_script.lua\000'
debug: Loading module '\000/lua/ai/opai/airattacks_save.lua\000'
debug: Loading module '\000/lua/editor/miscbuildconditions.lua\000'
debug: Loading module '\000/lua/ai/attackmanager.lua\000'
debug: Loading module '\000/units/zab9501/zab9501_script.lua\000'
debug: Loading module '\000/units/uab0301/uab0301_script.lua\000'
debug: Loading module '\000/lua/ai/opai/basiclandattack_save.lua\000'
debug: Loading module '\000/lua/enhancementcommon.lua\000'
debug: Loading module '\000/units/uas0203/uas0203_script.lua\000'
debug: Loading module '\000/units/xas0204/xas0204_script.lua\000'
debug: Loading module '\000/units/ual0202/ual0202_script.lua\000'
debug: Loading module '\000/units/ual0201/ual0201_script.lua\000'
debug: Loading module '\000/units/ual0104/ual0104_script.lua\000'
debug: Loading module '\000/units/ual0205/ual0205_script.lua\000'
debug: Loading module '\000/units/ual0101/ual0101_script.lua\000'
debug: Loading module '\000/units/uab2204/uab2204_script.lua\000'
debug: Loading module '\000/units/uab5101/uab5101_script.lua\000'
debug: Loading module '\000/units/uab2104/uab2104_script.lua\000'
debug: Loading module '\000/units/uab3201/uab3201_script.lua\000'
debug: Loading module '\000/units/uab2303/uab2303_script.lua\000'
debug: Loading module '\000/units/uab2304/uab2304_script.lua\000'
debug: Loading module '\000/units/uab2301/uab2301_script.lua\000'
info: Debug: SetPlayableArea before round : 12.5, 560.5 435.5, 1010.5
info: Debug: SetPlayableArea after round : 12, 560 432, 1008
debug: Loading module '\000/lua/simsync.lua\000'
info: Hooked /lua/simsync.lua with /schook/lua/simsync.lua
info: Camera:SyncPlayableRect \000{ x0=12, x1=432, y0=560, y1=1008 }
info: Request: \000{
info:   Name="WorldCamera",
info:   Region={ x0=12, x1=432, y0=560, y1=1008 },
info:   Type="CAMERA_SYNC_PLAYABLE_RECT"
info: }
debug: Loading module '\000/lua/victory.lua\000'
debug: Loading module '\000/lua/maui/frame.lua\000'
debug: Loading module '\000/lua/ui/game/gamemain.lua\000'
info: Hooked /lua/ui/game/gamemain.lua with /mods/additionalcamerastuff/hook/lua/ui/game/gamemain.lua
info: Hooked /lua/ui/game/gamemain.lua with /mods/reveal_positions/hook/lua/ui/game/gamemain.lua
info: Hooked /lua/ui/game/gamemain.lua with /mods/em/hook/lua/ui/game/gamemain.lua
info: Hooked /lua/ui/game/gamemain.lua with /mods/common/hook/lua/ui/game/gamemain.lua
debug: Loading module '\000/lua/ui/game/wlduiprovider.lua\000'
debug: Loading module '\000/lua/ui/game/gamecommon.lua\000'
debug: Loading module '\000/lua/maui/movie.lua\000'
debug: Loading module '\000/lua/keymap/keymapper.lua\000'
debug: Loading module '\000/lua/keymap/keydescriptions.lua\000'
debug: Loading module '\000/lua/keymap/keyactions.lua\000'
debug: Loading module '\000/lua/keymap/debugkeyactions.lua\000'
debug: Loading module '\000/mods/additionalcamerastuff/modules/acsui.lua\000'
debug: Loading module '\000/mods/additionalcamerastuff/modules/acscamera.lua\000'
debug: Loading module '\000/mods/additionalcamerastuff/modules/acsprefsui.lua\000'
debug: Loading module '\000/mods/additionalcamerastuff/modules/acsprefs.lua\000'
debug: Loading module '\000/mods/additionalcamerastuff/modules/acsutils.lua\000'
debug: Loading module '\000/lua/ui/game/selection.lua\000'
info: Hooked /lua/ui/game/selection.lua with /schook/lua/ui/game/selection.lua
debug: Loading module '\000/mods/common/units.lua\000'
debug: Loading module '\000/mods/common/select.lua\000'
debug: Loading module '\000/mods/common/score.lua\000'
debug: Loading module '\000/lua/usercamera.lua\000'
debug: Loading module '\000/lua/enhancementcommon.lua\000'
debug: Loading module '\000/lua/ui/game/missiontext.lua\000'
debug: Loading module '\000/lua/ui/game/economy.lua\000'
info: Hooked /lua/ui/game/economy.lua with /mods/em/hook/lua/ui/game/economy.lua
debug: Loading module '\000/lua/maui/statusbar.lua\000'
debug: Loading module '\000/mods/em/modules/throttle.lua\000'
debug: Loading module '\000/mods/em/modules/utils.lua\000'
debug: Loading module '\000/mods/em/modules/economy.lua\000'
debug: Loading module '\000/mods/em/modules/units.lua\000'
debug: Loading module '\000/mods/em/modules/init.lua\000'
debug: Loading module '\000/mods/em/modules/pause.lua\000'
debug: Loading module '\000/mods/em/modules/autoshare.lua\000'
debug: Loading module '\000/mods/em/modules/prefs.lua\000'
debug: Loading module '\000/mods/em/modules/score.lua\000'
debug: Loading module '\000/lua/game.lua\000'
debug: Loading module '\000/lua/sim/bufffield.lua\000'
debug: Loading module '\000/lua/sim/buff.lua\000'
debug: Loading module '\000/lua/sim/entity.lua\000'
debug: Loading module '\000/lua/sim/categoryutils.lua\000'
debug: Loading module '\000/lua/ui/lobby/unitsanalyzer.lua\000'
debug: Loading module '\000/lua/userplayerquery.lua\000'
debug: Loading module '\000/lua/ui/game/prefetchtextures.lua\000'
debug: [uiutil.lua, function UIFile()] - Unable to find file:/textures/ui/uef/icons/units/zxa0001_icon.dds
debug: Loading module '\000/lua/ui/game/borders.lua\000'
debug: Loading module '\000/lua/ui/game/layouts/borders_mini.lua\000'
debug: Loading module '\000/lua/ui/game/worldview.lua\000'
info: Hooked /lua/ui/game/worldview.lua with /mods/additionalcamerastuff/hook/lua/ui/game/worldview.lua
debug: Loading module '\000/lua/ui/controls/worldview.lua\000'
info: Hooked /lua/ui/controls/worldview.lua with /mods/additionalcamerastuff/hook/lua/ui/controls/worldview.lua
debug: Loading module '\000/lua/ui/game/ping.lua\000'
debug: Loading module '\000/lua/user/userdecal.lua\000'
debug: Loading module '\000/lua/ui/game/unitview.lua\000'
debug: Loading module '\000/lua/keymap/selectedinfo.lua\000'
debug: Loading module '\000/lua/ui/game/construction.lua\000'
info: Hooked /lua/ui/game/construction.lua with /mods/em/hook/lua/ui/game/construction.lua
debug: Loading module '\000/lua/ui/controls/specialgrid.lua\000'
debug: Loading module '\000/lua/maui/mauiutil.lua\000'
debug: Loading module '\000/lua/ui/game/build_templates.lua\000'
debug: Loading module '\000/lua/ui/game/buildmode.lua\000'
debug: Loading module '\000/lua/ui/game/tabs.lua\000'
info: Hooked /lua/ui/game/tabs.lua with /mods/coop/hook/lua/ui/game/tabs.lua
debug: Loading module '\000/lua/ui/game/unitviewdetail.lua\000'
debug: Loading module '\000/lua/ui/help/unitdescription.lua\000'
debug: Loading module '\000/lua/ui/templates_factory.lua\000'
debug: Loading module '\000/lua/ui/game/straticons.lua\000'
debug: Loading module '\000/lua/ui/notify/enhancementqueue.lua\000'
debug: Loading module '\000/lua/keymap/hotkeylabelsui.lua\000'
debug: Loading module '\000/lua/ui/game/selectionsort.lua\000'
debug: Loading module '\000/mods/em/modules/events.lua\000'
debug: Loading module '\000/lua/ui/game/commandmode.lua\000'
info: Hooked /lua/ui/game/commandmode.lua with /mods/em/hook/lua/ui/game/commandmode.lua
debug: Loading module '\000/lua/ui/game/orders.lua\000'
debug: Loading module '\000/lua/maui/grid.lua\000'
debug: Loading module '\000/lua/keymap/misckeyactions.lua\000'
debug: Loading module '\000/lua/utilities.lua\000'
debug: Loading module '\000/lua/ui/game/commandmeshes.lua\000'
info: creating medium fidelity terrain
info: creating low fidelity water
debug: Loading module '\000/lua/ui/game/multifunction.lua\000'
debug: Loading module '\000/lua/ui/game/minimap.lua\000'
info: Hooked /lua/ui/game/minimap.lua with /schook/lua/ui/game/minimap.lua
info: Hooked /lua/ui/game/minimap.lua with /mods/additionalcamerastuff/hook/lua/ui/game/minimap.lua
debug: Loading module '\000/lua/ui/game/rangeoverlayparams.lua\000'
debug: Loading module '\000/lua/ui/game/layouts/economy_mini.lua\000'
info: Hooked /lua/ui/game/layouts/economy_mini.lua with /mods/em/hook/lua/ui/game/layouts/economy_mini.lua
debug: Loading module '\000/lua/ui/game/layouts/tabs_mini.lua\000'
debug: Loading module '\000/lua/ui/game/layouts/multifunction_mini.lua\000'
debug: Loading module '\000/lua/ui/game/layouts/orders_mini.lua\000'
debug: Loading module '\000/lua/ui/game/avatars.lua\000'
debug: Loading module '\000/lua/ui/game/layouts/avatars_mini.lua\000'
debug: Loading module '\000/lua/ui/game/layouts/construction_mini.lua\000'
debug: Loading module '\000/lua/ui/game/layouts/unitview_mini.lua\000'
debug: Loading module '\000/lua/ui/game/layouts/unitviewdetail_mini.lua\000'
debug: Loading module '\000/lua/ui/game/controlgroups.lua\000'
debug: Loading module '\000/lua/ui/game/announcement.lua\000'
debug: Loading module '\000/lua/ui/game/layouts/controlgroups_mini.lua\000'
debug: Loading module '\000/lua/ui/game/transmissionlog.lua\000'
debug: Loading module '\000/lua/ui/game/windowmanager.lua\000'
debug: Loading module '\000/lua/ui/game/helptext.lua\000'
debug: Loading module '\000/lua/ui/game/timer.lua\000'
debug: Loading module '\000/lua/ui/game/consoleecho.lua\000'
debug: Loading module '\000/lua/ui/game/taunt.lua\000'
debug: Loading module '\000/lua/aichatsorian.lua\000'
info: creating medium fidelity terrain
info: creating low fidelity water
debug: Loading module '\000/lua/ui/game/layouts/minimap_mini.lua\000'
debug: Loading module '\000/lua/ui/game/objectives2.lua\000'
debug: Loading module '\000/lua/ui/game/layouts/objectives2_mini.lua\000'
debug: Loading module '\000/lua/ui/game/launchconsolecommands.lua\000'
debug: Loading module '\000/lua/keymap/hotkeylabels.lua\000'
debug: Loading module '\000/lua/keymap/unitkeygroups.lua\000'
warning: Not showing label for keybind LeftBracket due to length
debug: Loading module '\000/lua/ui/notify/customiser.lua\000'
debug: Loading module '\000/mods/additionalcamerastuff/modules/acsmain.lua\000'
debug: Loading module '\000/mods/em/modules/factories.lua\000'
debug: Loading module '\000/mods/em/modules/options.lua\000'
debug: Loading module '\000/mods/em/modules/shields.lua\000'
debug: Loading module '\000/mods/em/modules/mexes.lua\000'
debug: Loading module '\000/mods/em/modules/buildoverlay.lua\000'
debug: Loading module '\000/mods/em/modules/throttlemass.lua\000'
debug: Loading module '\000/lua/keymap/hotbuild.lua\000'
debug: Loading module '\000/lua/keymap/upgradetab.lua\000'
debug: Loading module '\000/lua/usermusic.lua\000'
debug: Loading module '\000/lua/ui/game/layouts/missiontext_mini.lua\000'
debug: Loading module '\000/lua/ui/game/score.lua\000'
info: Hooked /lua/ui/game/score.lua with /mods/em/hook/lua/ui/game/score.lua
debug: Loading module '\000/lua/ui/game/layouts/chat_layout.lua\000'
warning: GetResource: Invalid name ""
info: Can't find texture "" -- trying fallback.
warning: GetResource: Invalid name ""
info: Can't find texture "" -- trying fallback.
warning: GetResource: Invalid name ""
info: Can't find texture "" -- trying fallback.
debug: Loading module '\000/lua/ui/game/strategicicons.lua\000'
debug: Loading module '\000/lua/ui/dialogs/disconnect.lua\000'
info: Exe Version: 1.0 
debug: Loading module '\000/lua/ai/opai/defaultblankplan.lua\000'
debug: Current gametime: 00:00:00
info: playable area coordinates are { 12, 560, 432, 1008 }
info: Offmapareas are {
info:   { x0=-88, x1=532, y0=460, y1=560 },
info:   { x0=-88, x1=532, y0=1008, y1=1108 },
info:   { x0=-88, x1=12, y0=560, y1=1008 },
info:   { x0=432, x1=532, y0=560, y1=1008 }
info: }
debug: Loading module '\000/lua/sim/blip.lua\000'
info: Exe Version: 1.0 
info: Exe Version: 1.0 
info: Exe Version: 1.0 
info: Exe Version: 1.0 
info: Exe Version: 1.0 
debug: Loading module '\000/lua/ui/dialogs/saveload.lua\000'
debug: Loading module '\000/lua/ui/menus/menucommon.lua\000'
debug: Loading module '\000/lua/ui/controls/filepicker.lua\000'
info: Exe Version: 1.0 
debug: Loading module '\000/lua/ui/dialogs/options.lua\000'
info: Exe Version: 1.0 
info: Exe Version: 1.0 
info: playable area coordinates are { 12, 560, 432, 1008 }
info: Offmapareas are {
info:   { x0=-88, x1=532, y0=460, y1=560 },
info:   { x0=-88, x1=532, y0=1008, y1=1108 },
info:   { x0=-88, x1=12, y0=560, y1=1008 },
info:   { x0=432, x1=532, y0=560, y1=1008 }
info: }
debug: Loading module '\000/lua/ui/game/scoreaccum.lua\000'
info: Hooked /lua/ui/game/scoreaccum.lua with /mods/em/hook/lua/ui/game/scoreaccum.lua
info: Hooked /lua/ui/game/scoreaccum.lua with /mods/common/hook/lua/ui/game/scoreaccum.lua
debug: Loading module '\000/lua/editor/basemanagerbuildconditions.lua\000'
debug: Loading module '\000/lua/ai/opai/basemanagerplatoonthreads.lua\000'
debug: Loading module '\000/lua/editor/amplatoonhelperfunctions.lua\000'
debug: Loading module '\000/effects/entities/aeonbuildeffect/aeonbuildeffect01_script.lua\000'
debug: Loading module '\000/lua/sim/defaultprojectiles.lua\000'
debug: Loading module '\000/lua/sim/projectile.lua\000'
debug: Loading module '\000/lua/defaultantiprojectile.lua\000'
info: Hooked /lua/defaultantiprojectile.lua with /schook/lua/defaultantiprojectile.lua
debug: OpenMovie /movies/X01_HQ_M01_04229.sfd: 901
debug: Preparing movie /movies/X01_HQ_M01_04229.sfd: 901
debug: Preparing movie /movies/X01_HQ_M01_04229.sfd: 901
debug: Preparing movie /movies/X01_HQ_M01_04229.sfd: 901
debug: Preparing movie /movies/X01_HQ_M01_04229.sfd: 901
debug: Preparing movie /movies/X01_HQ_M01_04229.sfd: 901
debug: Preparing movie /movies/X01_HQ_M01_04229.sfd: 901
debug: Loading module '\000/lua/ui/game/layouts/missiontext_nis.lua\000'
debug: Playing movie c:\program files (x86)\steam\steamapps\common\supreme commander forged alliance\movies\x01_hq_m01_04229.sfd: 947
debug: Loading module '\000/lua/simcallbacks.lua\000'
debug: Loading module '\000/lua/simping.lua\000'
debug: Loading module '\000/lua/selfdestruct.lua\000'
debug: Loading module '\000/lua/simcameramarkers.lua\000'
debug: Loading module '\000/lua/simdialogue.lua\000'
debug: Loading module '\000/lua/simdiplomacy.lua\000'
debug: Loading module '\000/lua/spreadattack.lua\000'
debug: Loading module '\000/lua/weaponpriorities.lua\000'
debug: OpenMovie /movies/X01_HQ_M01_04847.sfd: 1370
debug: Preparing movie /movies/X01_HQ_M01_04847.sfd: 1370
debug: Preparing movie /movies/X01_HQ_M01_04847.sfd: 1370
debug: Preparing movie /movies/X01_HQ_M01_04847.sfd: 1370
debug: Preparing movie /movies/X01_HQ_M01_04847.sfd: 1370
debug: Preparing movie /movies/X01_HQ_M01_04847.sfd: 1370
debug: Preparing movie /movies/X01_HQ_M01_04847.sfd: 1370
debug: Playing movie c:\program files (x86)\steam\steamapps\common\supreme commander forged alliance\movies\x01_hq_m01_04847.sfd: 1417
debug: Loading module '\000/lua/ai/opai/airattacks_editorfunctions.lua\000'
debug: Loading module '\000/lua/ai/opai/basiclandattack_editorfunctions.lua\000'
debug: OpenMovie /movies/X01_HQ_M01_04848.sfd: 1975
debug: Preparing movie /movies/X01_HQ_M01_04848.sfd: 1975
debug: Preparing movie /movies/X01_HQ_M01_04848.sfd: 1975
debug: Preparing movie /movies/X01_HQ_M01_04848.sfd: 1975
debug: Preparing movie /movies/X01_HQ_M01_04848.sfd: 1975
debug: Preparing movie /movies/X01_HQ_M01_04848.sfd: 1975
debug: Preparing movie /movies/X01_HQ_M01_04848.sfd: 1975
debug: Playing movie c:\program files (x86)\steam\steamapps\common\supreme commander forged alliance\movies\x01_hq_m01_04848.sfd: 2022
debug: Loading module '\000/lua/ui/game/tracking.lua\000'
debug: Loading module '\000/projectiles/taarailgun01/taarailgun01_script.lua\000'
debug: Loading module '\000/lua/terranprojectiles.lua\000'
debug: Loading module '\000/projectiles/taalightfragmentationshell01/taalightfragmentationshell01_script.lua\000'
debug: Loading module '\000/projectiles/taamissileflayer01/taamissileflayer01_script.lua\000'
debug: Loading module '\000/projectiles/shieldcollider/shieldcollider_script.lua\000'
debug: Loading module '\000/lua/editor/otherarmyunitcountbuildconditions.lua\000'
info: Hooked /lua/editor/otherarmyunitcountbuildconditions.lua with /mods/coop/hook/lua/editor/otherarmyunitcountbuildconditions.lua
debug: Loading module '\000/units/uaa0103/uaa0103_script.lua\000'
debug: Current gametime: 00:00:30
debug: Loading module '\000/projectiles/adflaserlight01/adflaserlight01_script.lua\000'
debug: Loading module '\000/lua/aeonprojectiles.lua\000'
debug: Loading module '\000/effects/entities/debrismisc04/debrismisc04_script.lua\000'
debug: Loading module '\000/lua/genericdebris.lua\000'
debug: OpenMovie /movies/X01_HQ_M01_04849.sfd: 2729
debug: Preparing movie /movies/X01_HQ_M01_04849.sfd: 2729
debug: Preparing movie /movies/X01_HQ_M01_04849.sfd: 2729
debug: Preparing movie /movies/X01_HQ_M01_04849.sfd: 2729
debug: Preparing movie /movies/X01_HQ_M01_04849.sfd: 2729
debug: Preparing movie /movies/X01_HQ_M01_04849.sfd: 2729
debug: Preparing movie /movies/X01_HQ_M01_04849.sfd: 2729
debug: Playing movie c:\program files (x86)\steam\steamapps\common\supreme commander forged alliance\movies\x01_hq_m01_04849.sfd: 2772
debug: Loading module '\000/units/uel0001/uel0001_script.lua\000'
debug: Loading module '\000/effects/entities/unitteleport03/unitteleport03_script.lua\000'
debug: Loading module '\000/effects/entities/debrismisc09/debrismisc09_script.lua\000'
debug: Loading module '\000/lua/objectivearrow.lua\000'
debug: OpenMovie /movies/X01_HQ_M01_04850.sfd: 3588
debug: Preparing movie /movies/X01_HQ_M01_04850.sfd: 3588
debug: Preparing movie /movies/X01_HQ_M01_04850.sfd: 3588
debug: Preparing movie /movies/X01_HQ_M01_04850.sfd: 3588
debug: Preparing movie /movies/X01_HQ_M01_04850.sfd: 3588
debug: Preparing movie /movies/X01_HQ_M01_04850.sfd: 3588
debug: Preparing movie /movies/X01_HQ_M01_04850.sfd: 3588
debug: Loading module '\000/lua/ui/dialogs/score.lua\000'
debug: Loading module '\000/lua/ui/dialogs/hotstats.lua\000'
debug: Loading module '\000/lua/ui/dialogs/myeffecthelpers.lua\000'
debug: Loading module '\000/effects/entities/debrismisc010/debrismisc010_script.lua\000'
debug: Loading module '\000/lua/renderselectparams.lua\000'
debug: Playing movie c:\program files (x86)\steam\steamapps\common\supreme commander forged alliance\movies\x01_hq_m01_04850.sfd: 3623
debug: Loading module '\000/lua/ui/game/rallypoint.lua\000'
debug: Loading module '\000/lua/ui/controls/worldmesh.lua\000'
debug: Loading module '\000/lua/formations.lua\000'
debug: Loading module '\000/lua/spreadattack.lua\000'
debug: OpenMovie /movies/X01_Fletcher_M01_03419.sfd: 3865
debug: Preparing movie /movies/X01_Fletcher_M01_03419.sfd: 3865
debug: Preparing movie /movies/X01_Fletcher_M01_03419.sfd: 3865
debug: Preparing movie /movies/X01_Fletcher_M01_03419.sfd: 3865
debug: Preparing movie /movies/X01_Fletcher_M01_03419.sfd: 3865
debug: Preparing movie /movies/X01_Fletcher_M01_03419.sfd: 3865
debug: Preparing movie /movies/X01_Fletcher_M01_03419.sfd: 3865
debug: Playing movie c:\program files (x86)\steam\steamapps\common\supreme commander forged alliance\movies\x01_fletcher_m01_03419.sfd: 3910
debug: Loading module '\000/effects/entities/uefbuildeffect/uefbuildeffect02_script.lua\000'
debug: Loading module '\000/effects/entities/uefbuild/uefbuild01_script.lua\000'
debug: Loading module '\000/units/uaa0302/uaa0302_script.lua\000'
debug: Loading module '\000/effects/entities/uefbuildeffect/uefbuildeffect03_script.lua\000'
debug: Loading module '\000/lua/ui/game/commandgraphparams.lua\000'
debug: Loading module '\000/lua/ui/game/commandwaypoint.lua\000'
debug: Loading module '\000/lua/ui/game/commandgraph.lua\000'
info: Hooked /lua/ui/game/commandgraph.lua with /schook/lua/ui/game/commandgraph.lua
debug: Current gametime: 00:01:00
debug: OpenMovie /movies/X01_HQ_M01_05102.sfd: 5420
debug: Preparing movie /movies/X01_HQ_M01_05102.sfd: 5420
debug: Preparing movie /movies/X01_HQ_M01_05102.sfd: 5420
debug: Preparing movie /movies/X01_HQ_M01_05102.sfd: 5420
debug: Preparing movie /movies/X01_HQ_M01_05102.sfd: 5420
debug: Preparing movie /movies/X01_HQ_M01_05102.sfd: 5420
debug: Preparing movie /movies/X01_HQ_M01_05102.sfd: 5420
debug: Playing movie c:\program files (x86)\steam\steamapps\common\supreme commander forged alliance\movies\x01_hq_m01_05102.sfd: 5463
debug: Loading module '\000/units/uel0105/uel0105_script.lua\000'
debug: Loading module '\000/projectiles/aifbombgraviton01/aifbombgraviton01_script.lua\000'
debug: Current gametime: 00:01:30
debug: Loading module '\000/projectiles/sinker/sinker_script.lua\000'
debug: OpenMovie /movies/X01_HQ_M01_04230.sfd: 6951
debug: Preparing movie /movies/X01_HQ_M01_04230.sfd: 6951
debug: Preparing movie /movies/X01_HQ_M01_04230.sfd: 6951
debug: Preparing movie /movies/X01_HQ_M01_04230.sfd: 6951
debug: Preparing movie /movies/X01_HQ_M01_04230.sfd: 6951
debug: Preparing movie /movies/X01_HQ_M01_04230.sfd: 6951
debug: Preparing movie /movies/X01_HQ_M01_04230.sfd: 6951
debug: Playing movie c:\program files (x86)\steam\steamapps\common\supreme commander forged alliance\movies\x01_hq_m01_04230.sfd: 6990
debug: Current gametime: 00:02:00
debug: Loading module '\000/units/ueb0201/ueb0201_script.lua\000'
debug: Current gametime: 00:02:30
debug: Current gametime: 00:03:00
debug: Loading module '\000/units/uel0208/uel0208_script.lua\000'
warning: Error running OnRelease script in <deleted object>: ...mdata\faforever\gamedata\lua.nx2\lua\maui\button.lua(84): Game object has been destroyed
         stack traceback:
         	[C]: in function `Play'
         	...mdata\faforever\gamedata\lua.nx2\lua\maui\button.lua(84): in function <...mdata\faforever\gamedata\lua.nx2\lua\maui\button.lua:78>
debug: Loading module '\000/units/xal0203/xal0203_script.lua\000'
debug: Current gametime: 00:03:30
debug: Current gametime: 00:04:00
debug: Loading module '\000/units/ueb0301/ueb0301_script.lua\000'
debug: Current gametime: 00:04:30
info: CWldSession::DoBeat() unknown entity id (0x2ff00bd7) supplied in a pose update.
debug: Loading module '\000/units/ueb0202/ueb0202_script.lua\000'
debug: OpenMovie /movies/X01_Hall_M01_03618.sfd: 18694
debug: Preparing movie /movies/X01_Hall_M01_03618.sfd: 18694
debug: Preparing movie /movies/X01_Hall_M01_03618.sfd: 18694
debug: Preparing movie /movies/X01_Hall_M01_03618.sfd: 18694
debug: Preparing movie /movies/X01_Hall_M01_03618.sfd: 18694
debug: Preparing movie /movies/X01_Hall_M01_03618.sfd: 18694
debug: Preparing movie /movies/X01_Hall_M01_03618.sfd: 18694
debug: Playing movie c:\program files (x86)\steam\steamapps\common\supreme commander forged alliance\movies\x01_hall_m01_03618.sfd: 18737
debug: Current gametime: 00:05:00
debug: Loading module '\000/units/uel0309/uel0309_script.lua\000'
debug: Current gametime: 00:05:30
debug: Current gametime: 00:06:00
debug: Loading module '\000/lua/sim/tasks/enhancetask.lua\000'
debug: Loading module '\000/lua/sim/scripttask.lua\000'
debug: Loading module '\000/units/ueb1201/ueb1201_script.lua\000'
debug: Loading module '\000/units/ueb0302/ueb0302_script.lua\000'
debug: Loading module '\000/units/ueb4202/ueb4202_script.lua\000'
debug: Current gametime: 00:06:30
debug: Current gametime: 00:07:00
debug: Loading module '\000/units/xaa0202/xaa0202_script.lua\000'
debug: Current gametime: 00:07:30
debug: Loading module '\000/lua/ui/game/confirmunitdestroy.lua\000'
debug: OpenMovie /movies/X01_HQ_M01_05103.sfd: 29792
debug: Preparing movie /movies/X01_HQ_M01_05103.sfd: 29792
debug: Preparing movie /movies/X01_HQ_M01_05103.sfd: 29792
debug: Preparing movie /movies/X01_HQ_M01_05103.sfd: 29792
debug: Preparing movie /movies/X01_HQ_M01_05103.sfd: 29792
debug: Preparing movie /movies/X01_HQ_M01_05103.sfd: 29792
debug: Preparing movie /movies/X01_HQ_M01_05103.sfd: 29792
debug: Playing movie c:\program files (x86)\steam\steamapps\common\supreme commander forged alliance\movies\x01_hq_m01_05103.sfd: 29833
debug: Loading module '\000/lua/ui/lobby/restrictedunitsdata.lua\000'
debug: Current gametime: 00:08:00
debug: OpenMovie /movies/X01_HQ_M01_05100.sfd: 31739
debug: Preparing movie /movies/X01_HQ_M01_05100.sfd: 31739
debug: Preparing movie /movies/X01_HQ_M01_05100.sfd: 31739
debug: Preparing movie /movies/X01_HQ_M01_05100.sfd: 31739
debug: Preparing movie /movies/X01_HQ_M01_05100.sfd: 31739
debug: Preparing movie /movies/X01_HQ_M01_05100.sfd: 31739
debug: Preparing movie /movies/X01_HQ_M01_05100.sfd: 31739
debug: Playing movie c:\program files (x86)\steam\steamapps\common\supreme commander forged alliance\movies\x01_hq_m01_05100.sfd: 31782
debug: Loading module '\000/projectiles/adfdisruptor01/adfdisruptor01_script.lua\000'
debug: Current gametime: 00:08:30
debug: Loading module '\000/lua/ui/dialogs/keybindings.lua\000'
debug: Loading module '\000/lua/keymap/properkeynames.lua\000'
debug: Loading module '\000/lua/keymap/keynames.lua\000'
debug: Loading module '\000/lua/keymap/keycategories.lua\000'
debug: Loading module '\000/units/del0204/del0204_script.lua\000'
debug: Current gametime: 00:09:00
debug: Loading module '\000/projectiles/tdffragmentationgrenade01/tdffragmentationgrenade01_script.lua\000'
debug: Loading module '\000/projectiles/tdfplasma02/tdfplasma02_script.lua\000'
debug: Current gametime: 00:09:30
debug: Loading module '\000/projectiles/tdfionizedplasmagatlingcannon01/tdfionizedplasmagatlingcannon01_script.lua\000'
debug: Current gametime: 00:10:00
debug: Loading module '\000/units/delk002/delk002_script.lua\000'
debug: Loading module '\000/lua/kirvesweapons.lua\000'
debug: Loading module '\000/lua/kirveseffects.lua\000'
debug: Loading module '\000/lua/kirvesbeams.lua\000'
debug: Loading module '\000/units/uel0301/uel0301_script.lua\000'
debug: Current gametime: 00:10:30
debug: Current gametime: 00:11:00
debug: Loading module '\000/projectiles/aaphalanx01/aaphalanx01_script.lua\000'
debug: Loading module '\000/lua/kirvesprojectiles.lua\000'
debug: Current gametime: 00:11:30
debug: Current gametime: 00:12:00
debug: Current gametime: 00:12:30
debug: Current gametime: 00:13:00
debug: Loading module '\000/units/uea0304/uea0304_script.lua\000'
debug: Current gametime: 00:13:30
debug: Loading module '\000/units/uea0003/uea0003_script.lua\000'
debug: Loading module '\000/units/ueb3104/ueb3104_script.lua\000'
debug: Loading module '\000/units/ueb2301/ueb2301_script.lua\000'
debug: Current gametime: 00:14:00
debug: Current gametime: 00:14:30
debug: Current gametime: 00:15:00
debug: Loading module '\000/projectiles/tdfgauss02/tdfgauss02_script.lua\000'
debug: Current gametime: 00:15:30
debug: OpenMovie /movies/X01_Fletcher_M01_03621.sfd: 60909
debug: Preparing movie /movies/X01_Fletcher_M01_03621.sfd: 60909
debug: Preparing movie /movies/X01_Fletcher_M01_03621.sfd: 60909
debug: Preparing movie /movies/X01_Fletcher_M01_03621.sfd: 60909
debug: Preparing movie /movies/X01_Fletcher_M01_03621.sfd: 60909
debug: Preparing movie /movies/X01_Fletcher_M01_03621.sfd: 60909
debug: Preparing movie /movies/X01_Fletcher_M01_03621.sfd: 60909
debug: Playing movie c:\program files (x86)\steam\steamapps\common\supreme commander forged alliance\movies\x01_fletcher_m01_03621.sfd: 60947
debug: Loading module '\000/projectiles/aaalightdisplacementautocannonmissile01/aaalightdisplacementautocannonmissile01_script.lua\000'
debug: Current gametime: 00:16:00
debug: Current gametime: 00:16:30
debug: Current gametime: 00:17:00
debug: Loading module '\000/projectiles/tifsmallyieldnuclearbomb01/tifsmallyieldnuclearbomb01_script.lua\000'
debug: OpenMovie /movies/X01_HQ_M01_03632.sfd: 66931
debug: Preparing movie /movies/X01_HQ_M01_03632.sfd: 66931
debug: Preparing movie /movies/X01_HQ_M01_03632.sfd: 66931
debug: Preparing movie /movies/X01_HQ_M01_03632.sfd: 66931
debug: Preparing movie /movies/X01_HQ_M01_03632.sfd: 66931
debug: Preparing movie /movies/X01_HQ_M01_03632.sfd: 66931
debug: Preparing movie /movies/X01_HQ_M01_03632.sfd: 66931
debug: Playing movie c:\program files (x86)\steam\steamapps\common\supreme commander forged alliance\movies\x01_hq_m01_03632.sfd: 66978
debug: Current gametime: 00:17:30
debug: Loading module '\000/projectiles/aaafizz01/aaafizz01_script.lua\000'
debug: Current gametime: 00:18:00
debug: Loading module '\000/projectiles/aaazealotmissile01/aaazealotmissile01_script.lua\000'
debug: Current gametime: 00:18:30
debug: Loading module '\000/units/uea0104/uea0104_script.lua\000'
debug: Current gametime: 00:19:00
debug: Loading module '\000/units/uea0303/uea0303_script.lua\000'
debug: Loading module '\000/units/uea0302/uea0302_script.lua\000'
debug: Current gametime: 00:19:30
debug: Loading module '\000/units/uea0305/uea0305_script.lua\000'
debug: Current gametime: 00:20:00
debug: Loading module '\000/projectiles/aaasonicpulse01/aaasonicpulse01_script.lua\000'
debug: Current gametime: 00:20:30
debug: [uiutil.lua, function UIFile()] - Unable to find file:/textures/ui/uef/icons/units/unknown_icon.dds
debug: Current gametime: 00:21:00
debug: Current gametime: 00:21:30
debug: Loading module '\000/projectiles/tdfplasmaheavy02/tdfplasmaheavy02_script.lua\000'
debug: OpenMovie /movies/X01_HQ_M01_03627.sfd: 83388
debug: Preparing movie /movies/X01_HQ_M01_03627.sfd: 83388
debug: Preparing movie /movies/X01_HQ_M01_03627.sfd: 83388
debug: Preparing movie /movies/X01_HQ_M01_03627.sfd: 83388
debug: Preparing movie /movies/X01_HQ_M01_03627.sfd: 83388
debug: Preparing movie /movies/X01_HQ_M01_03627.sfd: 83388
debug: Preparing movie /movies/X01_HQ_M01_03627.sfd: 83388
debug: Playing movie c:\program files (x86)\steam\steamapps\common\supreme commander forged alliance\movies\x01_hq_m01_03627.sfd: 83435
debug: Loading module '\000/projectiles/tdfginsu01/tdfginsu01_script.lua\000'
debug: Current gametime: 00:22:00
debug: Current gametime: 00:22:30
debug: OpenMovie /movies/X01_HQ_M01_03628.sfd: 87278
debug: Preparing movie /movies/X01_HQ_M01_03628.sfd: 87278
debug: Preparing movie /movies/X01_HQ_M01_03628.sfd: 87278
debug: Preparing movie /movies/X01_HQ_M01_03628.sfd: 87278
debug: Preparing movie /movies/X01_HQ_M01_03628.sfd: 87278
debug: Preparing movie /movies/X01_HQ_M01_03628.sfd: 87278
debug: Preparing movie /movies/X01_HQ_M01_03628.sfd: 87278
debug: Playing movie c:\program files (x86)\steam\steamapps\common\supreme commander forged alliance\movies\x01_hq_m01_03628.sfd: 87321
debug: Current gametime: 00:23:00
debug: Current gametime: 00:23:30
debug: Current gametime: 00:24:00
debug: Current gametime: 00:24:30
debug: Current gametime: 00:25:00
debug: Loading module '\000/projectiles/tdfplasmaheavy03/tdfplasmaheavy03_script.lua\000'
debug: Loading module '\000/projectiles/adfquantumcannon02/adfquantumcannon02_script.lua\000'
debug: Current gametime: 00:25:30
debug: Current gametime: 00:26:00
debug: Current gametime: 00:26:30
debug: OpenMovie /movies/X01_HQ_M01_03629.sfd: 101374
debug: Preparing movie /movies/X01_HQ_M01_03629.sfd: 101374
debug: Preparing movie /movies/X01_HQ_M01_03629.sfd: 101374
debug: Preparing movie /movies/X01_HQ_M01_03629.sfd: 101374
debug: Preparing movie /movies/X01_HQ_M01_03629.sfd: 101374
debug: Preparing movie /movies/X01_HQ_M01_03629.sfd: 101374
debug: Preparing movie /movies/X01_HQ_M01_03629.sfd: 101374
debug: Playing movie c:\program files (x86)\steam\steamapps\common\supreme commander forged alliance\movies\x01_hq_m01_03629.sfd: 101421
debug: Current gametime: 00:27:00
debug: Current gametime: 00:27:30
debug: Current gametime: 00:28:00
debug: Current gametime: 00:28:30
info: CWldSession::DoBeat() unknown entity id (0x2ff00ad1) supplied in a pose update.
debug: Loading module '\000/units/uel0401/uel0401_script.lua\000'
debug: Loading module '\000/units/uel0307/uel0307_script.lua\000'
debug: Current gametime: 00:29:00
debug: Current gametime: 00:29:30
debug: Current gametime: 00:30:00
debug: Loading module '\000/units/ueb0103/ueb0103_script.lua\000'
debug: Loading module '\000/projectiles/adfreactoncannon01/adfreactoncannon01_script.lua\000'
debug: Loading module '\000/effects/entities/scudeath01/scudeath01_script.lua\000'
debug: Loading module '\000/effects/entities/scudeathshockwave01/scudeathshockwave01_script.lua\000'
debug: Current gametime: 00:30:30
debug: Loading module '\000/projectiles/tdfgauss04/tdfgauss04_script.lua\000'
debug: Current gametime: 00:31:00
debug: Loading module '\000/projectiles/adfoblivioncannon03/adfoblivioncannon03_script.lua\000'
debug: Current gametime: 00:31:30
debug: Loading module '\000/units/uaa0101/uaa0101_script.lua\000'
debug: OpenMovie /movies/X01_HQ_M01_03624.sfd: 120263
debug: Preparing movie /movies/X01_HQ_M01_03624.sfd: 120263
debug: Preparing movie /movies/X01_HQ_M01_03624.sfd: 120263
debug: Preparing movie /movies/X01_HQ_M01_03624.sfd: 120263
debug: Preparing movie /movies/X01_HQ_M01_03624.sfd: 120263
debug: Preparing movie /movies/X01_HQ_M01_03624.sfd: 120263
debug: Preparing movie /movies/X01_HQ_M01_03624.sfd: 120263
debug: Playing movie c:\program files (x86)\steam\steamapps\common\supreme commander forged alliance\movies\x01_hq_m01_03624.sfd: 120310
debug: Loading module '\000/projectiles/adfgraviton01/adfgraviton01_script.lua\000'
debug: Current gametime: 00:32:00
info: CWldSession::DoBeat() unknown entity id (0x2ff00ae6) supplied in a pose update.
debug: OpenMovie /movies/X01_HQ_M01_03631.sfd: 122638
debug: Preparing movie /movies/X01_HQ_M01_03631.sfd: 122638
debug: Preparing movie /movies/X01_HQ_M01_03631.sfd: 122638
debug: Preparing movie /movies/X01_HQ_M01_03631.sfd: 122638
debug: Preparing movie /movies/X01_HQ_M01_03631.sfd: 122638
debug: Preparing movie /movies/X01_HQ_M01_03631.sfd: 122638
debug: Preparing movie /movies/X01_HQ_M01_03631.sfd: 122638
debug: Playing movie c:\program files (x86)\steam\steamapps\common\supreme commander forged alliance\movies\x01_hq_m01_03631.sfd: 122677
debug: Current gametime: 00:32:30
debug: Loading module '\000/units/ueb0203/ueb0203_script.lua\000'
debug: Current gametime: 00:33:00
debug: Loading module '\000/units/ueb0303/ueb0303_script.lua\000'
debug: Current gametime: 00:33:30
debug: OpenMovie /movies/X01_HQ_M01_03625.sfd: 127555
debug: Preparing movie /movies/X01_HQ_M01_03625.sfd: 127555
debug: Preparing movie /movies/X01_HQ_M01_03625.sfd: 127555
debug: Preparing movie /movies/X01_HQ_M01_03625.sfd: 127555
debug: Preparing movie /movies/X01_HQ_M01_03625.sfd: 127555
debug: Preparing movie /movies/X01_HQ_M01_03625.sfd: 127555
debug: Preparing movie /movies/X01_HQ_M01_03625.sfd: 127555
debug: Playing movie c:\program files (x86)\steam\steamapps\common\supreme commander forged alliance\movies\x01_hq_m01_03625.sfd: 127596
debug: Loading module '\000/units/ues0302/ues0302_script.lua\000'
debug: OpenMovie /movies/X01_HQ_M02_02893.sfd: 127818
debug: Preparing movie /movies/X01_HQ_M02_02893.sfd: 127818
debug: Preparing movie /movies/X01_HQ_M02_02893.sfd: 127818
debug: Preparing movie /movies/X01_HQ_M02_02893.sfd: 127818
debug: Preparing movie /movies/X01_HQ_M02_02893.sfd: 127818
debug: Preparing movie /movies/X01_HQ_M02_02893.sfd: 127818
debug: Preparing movie /movies/X01_HQ_M02_02893.sfd: 127818
debug: Playing movie c:\program files (x86)\steam\steamapps\common\supreme commander forged alliance\movies\x01_hq_m02_02893.sfd: 127861
debug: Loading module '\000/units/uec1401/uec1401_script.lua\000'
debug: Loading module '\000/units/uec1101/uec1101_script.lua\000'
debug: Loading module '\000/units/uec1501/uec1501_script.lua\000'
debug: Loading module '\000/units/uec1201/uec1201_script.lua\000'
debug: Loading module '\000/units/uec1301/uec1301_script.lua\000'
debug: Loading module '\000/units/uel0202/uel0202_script.lua\000'
debug: Loading module '\000/units/ueb2101/ueb2101_script.lua\000'
debug: Loading module '\000/units/uel0111/uel0111_script.lua\000'
debug: Loading module '\000/units/uel0103/uel0103_script.lua\000'
debug: Loading module '\000/units/ueb2303/ueb2303_script.lua\000'
debug: Loading module '\000/units/uel0201/uel0201_script.lua\000'
debug: Loading module '\000/units/uel0106/uel0106_script.lua\000'
debug: Loading module '\000/units/uab5202/uab5202_script.lua\000'
debug: Loading module '\000/units/uab3101/uab3101_script.lua\000'
debug: Loading module '\000/units/zab9601/zab9601_script.lua\000'
debug: Loading module '\000/units/uab4202/uab4202_script.lua\000'
debug: Loading module '\000/units/uab4301/uab4301_script.lua\000'
debug: Loading module '\000/units/uab4201/uab4201_script.lua\000'
debug: Loading module '\000/units/uab0202/uab0202_script.lua\000'
debug: Loading module '\000/units/xaa0305/xaa0305_script.lua\000'
debug: Loading module '\000/units/ual0111/ual0111_script.lua\000'
debug: Loading module '\000/units/ual0303/ual0303_script.lua\000'
debug: Loading module '\000/units/ual0106/ual0106_script.lua\000'
info: Debug: SetPlayableArea before round : 12.5, 280.5 435.5, 1010.5
info: Debug: SetPlayableArea after round : 12, 280 432, 1008
info: Camera:SyncPlayableRect \000{ x0=12, x1=432, y0=280, y1=1008 }
info: Request: \000{
info:   Name="WorldCamera",
info:   Region={ x0=12, x1=432, y0=280, y1=1008 },
info:   Type="CAMERA_SYNC_PLAYABLE_RECT"
info: }
info: playable area coordinates are { 12, 280, 432, 1008 }
info: Offmapareas are {
info:   { x0=-88, x1=532, y0=180, y1=280 },
info:   { x0=-88, x1=532, y0=1008, y1=1108 },
info:   { x0=-88, x1=12, y0=280, y1=1008 },
info:   { x0=432, x1=532, y0=280, y1=1008 }
info: }
debug: Loading module '\000/projectiles/tdfplasma01/tdfplasma01_script.lua\000'
debug: Loading module '\000/projectiles/aaazealotmissile02/aaazealotmissile02_script.lua\000'
debug: Loading module '\000/projectiles/tdfgauss01/tdfgauss01_script.lua\000'
debug: OpenMovie /movies/X01_Graham_M02_04003.sfd: 128118
debug: Preparing movie /movies/X01_Graham_M02_04003.sfd: 128118
debug: Loading module '\000/projectiles/tdfmachinegun01/tdfmachinegun01_script.lua\000'
debug: Preparing movie /movies/X01_Graham_M02_04003.sfd: 128118
debug: Preparing movie /movies/X01_Graham_M02_04003.sfd: 128118
debug: Preparing movie /movies/X01_Graham_M02_04003.sfd: 128118
debug: Preparing movie /movies/X01_Graham_M02_04003.sfd: 128118
debug: Preparing movie /movies/X01_Graham_M02_04003.sfd: 128118
debug: Playing movie c:\program files (x86)\steam\steamapps\common\supreme commander forged alliance\movies\x01_graham_m02_04003.sfd: 128120
info: CWldSession::DoBeat() unknown entity id (0x2ff00bb4) supplied in a pose update.
debug: Loading module '\000/projectiles/aaaautocannonquantum01/aaaautocannonquantum01_script.lua\000'
debug: Loading module '\000/projectiles/adflaserlight02/adflaserlight02_script.lua\000'
debug: Loading module '\000/projectiles/aifmissileserpentine01/aifmissileserpentine01_script.lua\000'
debug: Loading module '\000/projectiles/tiffragmentationsensorshell01/tiffragmentationsensorshell01_script.lua\000'
debug: Loading module '\000/projectiles/tiffragmentationsensorshell02/tiffragmentationsensorshell02_script.lua\000'
debug: Current gametime: 00:34:00
debug: OpenMovie /movies/X01_Hall_M02_04004.sfd: 128998
debug: Preparing movie /movies/X01_Hall_M02_04004.sfd: 128998
debug: Preparing movie /movies/X01_Hall_M02_04004.sfd: 128998
debug: Preparing movie /movies/X01_Hall_M02_04004.sfd: 128998
debug: Preparing movie /movies/X01_Hall_M02_04004.sfd: 128998
debug: Preparing movie /movies/X01_Hall_M02_04004.sfd: 128998
debug: Preparing movie /movies/X01_Hall_M02_04004.sfd: 128998
debug: Playing movie c:\program files (x86)\steam\steamapps\common\supreme commander forged alliance\movies\x01_hall_m02_04004.sfd: 129042
debug: Loading module '\000/projectiles/tifartillery01/tifartillery01_script.lua\000'
debug: Loading module '\000/projectiles/adfsonicpulsar01/adfsonicpulsar01_script.lua\000'
debug: Loading module '\000/units/ual0103/ual0103_script.lua\000'
debug: OpenMovie /movies/X01_Gari_M02_02896.sfd: 129522
debug: Preparing movie /movies/X01_Gari_M02_02896.sfd: 129522
debug: Preparing movie /movies/X01_Gari_M02_02896.sfd: 129522
debug: Preparing movie /movies/X01_Gari_M02_02896.sfd: 129522
debug: Preparing movie /movies/X01_Gari_M02_02896.sfd: 129522
debug: Preparing movie /movies/X01_Gari_M02_02896.sfd: 129522
debug: Preparing movie /movies/X01_Gari_M02_02896.sfd: 129522
debug: Playing movie c:\program files (x86)\steam\steamapps\common\supreme commander forged alliance\movies\x01_gari_m02_02896.sfd: 129561
info: CWldSession::DoBeat() unknown entity id (0x2ff01158) supplied in a pose update.
debug: Loading module '\000/projectiles/tdfriot01/tdfriot01_script.lua\000'
debug: Current gametime: 00:34:30
debug: Current gametime: 00:35:00
debug: Current gametime: 00:35:30
debug: Loading module '\000/units/ual0304/ual0304_script.lua\000'
debug: Loading module '\000/projectiles/adfquadlaserlight01/adfquadlaserlight01_script.lua\000'
debug: Loading module '\000/units/ues0201/ues0201_script.lua\000'
debug: Current gametime: 00:36:00
debug: Loading module '\000/projectiles/aifsonanceshell01/aifsonanceshell01_script.lua\000'
debug: Loading module '\000/projectiles/adflaserhighintensity01/adflaserhighintensity01_script.lua\000'
debug: Current gametime: 00:36:30
debug: Loading module '\000/projectiles/aifmortar01/aifmortar01_script.lua\000'
debug: Loading module '\000/units/ual0208/ual0208_script.lua\000'
debug: Current gametime: 00:37:00
debug: Loading module '\000/units/ues0202/ues0202_script.lua\000'
debug: Loading module '\000/projectiles/tifmissilecruise04/tifmissilecruise04_script.lua\000'
debug: Loading module '\000/projectiles/tdfgauss03/tdfgauss03_script.lua\000'
debug: Current gametime: 00:37:30
debug: Current gametime: 00:38:00
debug: Loading module '\000/projectiles/tdfriot02/tdfriot02_script.lua\000'
debug: Current gametime: 00:38:30
debug: Current gametime: 00:39:00
debug: OpenMovie /movies/X01_Graham_M02_04236.sfd: 147561
debug: Preparing movie /movies/X01_Graham_M02_04236.sfd: 147561
debug: Preparing movie /movies/X01_Graham_M02_04236.sfd: 147561
debug: Preparing movie /movies/X01_Graham_M02_04236.sfd: 147561
debug: Preparing movie /movies/X01_Graham_M02_04236.sfd: 147561
debug: Preparing movie /movies/X01_Graham_M02_04236.sfd: 147561
debug: Preparing movie /movies/X01_Graham_M02_04236.sfd: 147561
debug: Playing movie c:\program files (x86)\steam\steamapps\common\supreme commander forged alliance\movies\x01_graham_m02_04236.sfd: 147598
debug: Loading module '\000/projectiles/tdfplasmaheavy04/tdfplasmaheavy04_script.lua\000'
debug: Loading module '\000/units/uec0001/uec0001_script.lua\000'
debug: Loading module '\000/units/ueb3101/ueb3101_script.lua\000'
debug: Loading module '\000/units/ueb1202/ueb1202_script.lua\000'
debug: Loading module '\000/units/uab4302/uab4302_script.lua\000'
debug: Loading module '\000/units/uab3104/uab3104_script.lua\000'
debug: Loading module '\000/units/uab0201/uab0201_script.lua\000'
debug: Loading module '\000/units/uab1202/uab1202_script.lua\000'
debug: Loading module '\000/lua/ai/opai/engineerattack_save.lua\000'
debug: Loading module '\000/units/uab3102/uab3102_script.lua\000'
debug: Loading module '\000/units/zab9603/zab9603_script.lua\000'
debug: Loading module '\000/units/uab0303/uab0303_script.lua\000'
debug: Loading module '\000/units/uab2205/uab2205_script.lua\000'
debug: Loading module '\000/units/uab2109/uab2109_script.lua\000'
debug: Loading module '\000/lua/ai/opai/navalattacks_save.lua\000'
debug: Loading module '\000/units/uab2302/uab2302_script.lua\000'
debug: Loading module '\000/units/ual0001/ual0001_script.lua\000'
debug: Loading module '\000/units/ual0401/ual0401_script.lua\000'
debug: Loading module '\000/units/uas0102/uas0102_script.lua\000'
debug: Loading module '\000/units/uas0201/uas0201_script.lua\000'
debug: Loading module '\000/lua/aeon_naval_weapons.lua\000'
debug: Loading module '\000/units/uas0202/uas0202_script.lua\000'
debug: Loading module '\000/units/uas0302/uas0302_script.lua\000'
debug: Loading module '\000/units/uaa0104/uaa0104_script.lua\000'
debug: Loading module '\000/units/ual0307/ual0307_script.lua\000'
debug: Loading module '\000/units/uas0103/uas0103_script.lua\000'
debug: Loading module '\000/units/uaa0304/uaa0304_script.lua\000'
debug: Loading module '\000/units/xal0305/xal0305_script.lua\000'
debug: Loading module '\000/units/xaa0306/xaa0306_script.lua\000'
debug: Loading module '\000/units/dalk003/dalk003_script.lua\000'
info: Debug: SetPlayableArea before round : 12.5, 280.5 860.5, 1010.5
info: Debug: SetPlayableArea after round : 12, 280 860, 1008
info: Camera:SyncPlayableRect \000{ x0=12, x1=860, y0=280, y1=1008 }
info: Request: \000{
info:   Name="WorldCamera",
info:   Region={ x0=12, x1=860, y0=280, y1=1008 },
info:   Type="CAMERA_SYNC_PLAYABLE_RECT"
info: }
info: playable area coordinates are { 12, 280, 860, 1008 }
info: Offmapareas are {
info:   { x0=-88, x1=960, y0=180, y1=280 },
info:   { x0=-88, x1=960, y0=1008, y1=1108 },
info:   { x0=-88, x1=12, y0=280, y1=1008 },
info:   { x0=860, x1=960, y0=280, y1=1008 }
info: }
debug: OpenMovie /movies/X01_HQ_M02_03662.sfd: 147931
debug: Preparing movie /movies/X01_HQ_M02_03662.sfd: 147931
debug: Preparing movie /movies/X01_HQ_M02_03662.sfd: 147931
debug: Preparing movie /movies/X01_HQ_M02_03662.sfd: 147931
debug: Preparing movie /movies/X01_HQ_M02_03662.sfd: 147931
debug: Preparing movie /movies/X01_HQ_M02_03662.sfd: 147931
debug: Preparing movie /movies/X01_HQ_M02_03662.sfd: 147931
debug: Playing movie c:\program files (x86)\steam\steamapps\common\supreme commander forged alliance\movies\x01_hq_m02_03662.sfd: 147961
debug: Loading module '\000/projectiles/adfheavydisruptorcannon01/adfheavydisruptorcannon01_script.lua\000'
debug: Loading module '\000/lua/ai/opai/navalattacks_editorfunctions.lua\000'
info: *DEBUG: Taunt played number 1
debug: Loading module '\000/projectiles/aantorpedo01/aantorpedo01_script.lua\000'
info: AIGetMarkerLocationsEx 0 markers for Land Path Node
info: AIGetMarkerLocationsEx 0 markers for Water Path Node
info: AIGetMarkerLocationsEx 0 markers for Air Path Node
info: AIGetMarkerLocationsEx 0 markers for Amphibious Path Node
info: AIGetMarkerLocationsEx 0 markers for Amphibious Path Node (generated from Land/Water markers).
debug: Loading module '\000/projectiles/tananglertorpedo01/tananglertorpedo01_script.lua\000'
debug: Loading module '\000/projectiles/timantitorpedo01/timantitorpedo01_script.lua\000'
debug: Loading module '\000/projectiles/aimantitorpedo02/aimantitorpedo02_script.lua\000'
debug: OpenMovie /movies/X01_HQ_M02_04851.sfd: 148377
debug: Preparing movie /movies/X01_HQ_M02_04851.sfd: 148377
debug: Preparing movie /movies/X01_HQ_M02_04851.sfd: 148377
debug: Preparing movie /movies/X01_HQ_M02_04851.sfd: 148377
debug: Preparing movie /movies/X01_HQ_M02_04851.sfd: 148377
debug: Preparing movie /movies/X01_HQ_M02_04851.sfd: 148377
debug: Preparing movie /movies/X01_HQ_M02_04851.sfd: 148377
debug: Playing movie c:\program files (x86)\steam\steamapps\common\supreme commander forged alliance\movies\x01_hq_m02_04851.sfd: 148416
info: *DEBUG: Taunt played number 2
debug: OpenMovie /movies/X01_HQ_M02_04852.sfd: 148626
debug: Preparing movie /movies/X01_HQ_M02_04852.sfd: 148626
debug: Preparing movie /movies/X01_HQ_M02_04852.sfd: 148626
debug: Preparing movie /movies/X01_HQ_M02_04852.sfd: 148626
debug: Preparing movie /movies/X01_HQ_M02_04852.sfd: 148626
debug: Preparing movie /movies/X01_HQ_M02_04852.sfd: 148626
debug: Preparing movie /movies/X01_HQ_M02_04852.sfd: 148626
debug: Playing movie c:\program files (x86)\steam\steamapps\common\supreme commander forged alliance\movies\x01_hq_m02_04852.sfd: 148670
debug: Loading module '\000/projectiles/aaasonicpulse02/aaasonicpulse02_script.lua\000'
debug: Loading module '\000/units/uab0102/uab0102_script.lua\000'
debug: Loading module '\000/units/uab1103/uab1103_script.lua\000'
debug: Loading module '\000/units/uas0401/uas0401_script.lua\000'
debug: Current gametime: 00:39:30
debug: OpenMovie /movies/X01_Gari_M02_03664.sfd: 149146
debug: Preparing movie /movies/X01_Gari_M02_03664.sfd: 149146
debug: Preparing movie /movies/X01_Gari_M02_03664.sfd: 149146
debug: Preparing movie /movies/X01_Gari_M02_03664.sfd: 149146
debug: Preparing movie /movies/X01_Gari_M02_03664.sfd: 149146
debug: Preparing movie /movies/X01_Gari_M02_03664.sfd: 149146
debug: Preparing movie /movies/X01_Gari_M02_03664.sfd: 149146
debug: Playing movie c:\program files (x86)\steam\steamapps\common\supreme commander forged alliance\movies\x01_gari_m02_03664.sfd: 149176
debug: Loading module '\000/projectiles/aifbombquark01/aifbombquark01_script.lua\000'
debug: Loading module '\000/projectiles/adfoblivioncannon02/adfoblivioncannon02_script.lua\000'
info: *DEBUG: Taunt played number 6
debug: OpenMovie /movies/X01_Hall_M02_03665.sfd: 149555
debug: Preparing movie /movies/X01_Hall_M02_03665.sfd: 149555
debug: Preparing movie /movies/X01_Hall_M02_03665.sfd: 149555
debug: Preparing movie /movies/X01_Hall_M02_03665.sfd: 149555
debug: Preparing movie /movies/X01_Hall_M02_03665.sfd: 149555
debug: Preparing movie /movies/X01_Hall_M02_03665.sfd: 149555
debug: Preparing movie /movies/X01_Hall_M02_03665.sfd: 149555
debug: Playing movie c:\program files (x86)\steam\steamapps\common\supreme commander forged alliance\movies\x01_hall_m02_03665.sfd: 149597
debug: OpenMovie /movies/X01_Gari_T01_04518.sfd: 149773
debug: Preparing movie /movies/X01_Gari_T01_04518.sfd: 149773
debug: Preparing movie /movies/X01_Gari_T01_04518.sfd: 149773
debug: Preparing movie /movies/X01_Gari_T01_04518.sfd: 149773
debug: Preparing movie /movies/X01_Gari_T01_04518.sfd: 149773
debug: Preparing movie /movies/X01_Gari_T01_04518.sfd: 149773
debug: Preparing movie /movies/X01_Gari_T01_04518.sfd: 149773
debug: Playing movie c:\program files (x86)\steam\steamapps\common\supreme commander forged alliance\movies\x01_gari_t01_04518.sfd: 149811
debug: Loading module '\000/projectiles/taamissileflayer02/taamissileflayer02_script.lua\000'
debug: Loading module '\000/projectiles/taarailgun02/taarailgun02_script.lua\000'
debug: OpenMovie /movies/X01_HQ_M02_04889.sfd: 150352
debug: Preparing movie /movies/X01_HQ_M02_04889.sfd: 150352
debug: Preparing movie /movies/X01_HQ_M02_04889.sfd: 150352
debug: Preparing movie /movies/X01_HQ_M02_04889.sfd: 150352
debug: Preparing movie /movies/X01_HQ_M02_04889.sfd: 150352
debug: Preparing movie /movies/X01_HQ_M02_04889.sfd: 150352
debug: Preparing movie /movies/X01_HQ_M02_04889.sfd: 150352
debug: Playing movie c:\program files (x86)\steam\steamapps\common\supreme commander forged alliance\movies\x01_hq_m02_04889.sfd: 150398
debug: Current gametime: 00:40:00
debug: Loading module '\000/projectiles/aantorpedocluster01/aantorpedocluster01_script.lua\000'
debug: Loading module '\000/projectiles/aantorpedoclustersplit01/aantorpedoclustersplit01_script.lua\000'
debug: Loading module '\000/units/uaa0310/uaa0310_script.lua\000'
debug: Loading module '\000/projectiles/aaserpentine/aaserpentine_script.lua\000'
debug: Loading module '\000/projectiles/adfquatumautogun01/adfquatumautogun01_script.lua\000'
debug: Loading module '\000/projectiles/aifsonanceshell02/aifsonanceshell02_script.lua\000'
debug: Current gametime: 00:40:30
debug: Loading module '\000/projectiles/adfoblivioncannon01/adfoblivioncannon01_script.lua\000'
debug: OpenMovie /movies/X01_Graham_M02_03638.sfd: 153182
debug: Preparing movie /movies/X01_Graham_M02_03638.sfd: 153182
debug: Preparing movie /movies/X01_Graham_M02_03638.sfd: 153182
debug: Preparing movie /movies/X01_Graham_M02_03638.sfd: 153182
debug: Preparing movie /movies/X01_Graham_M02_03638.sfd: 153182
debug: Preparing movie /movies/X01_Graham_M02_03638.sfd: 153182
debug: Preparing movie /movies/X01_Graham_M02_03638.sfd: 153182
debug: Playing movie c:\program files (x86)\steam\steamapps\common\supreme commander forged alliance\movies\x01_graham_m02_03638.sfd: 153229
debug: Loading module '\000/projectiles/aifmiasmashell01/aifmiasmashell01_script.lua\000'
debug: Loading module '\000/projectiles/aimantitorpedo01/aimantitorpedo01_script.lua\000'
debug: Loading module '\000/projectiles/adfquantumcannon01/adfquantumcannon01_script.lua\000'
debug: OpenMovie /movies/X01_HQ_M02_04246.sfd: 153738
debug: Preparing movie /movies/X01_HQ_M02_04246.sfd: 153738
debug: Preparing movie /movies/X01_HQ_M02_04246.sfd: 153738
debug: Preparing movie /movies/X01_HQ_M02_04246.sfd: 153738
debug: Preparing movie /movies/X01_HQ_M02_04246.sfd: 153738
debug: Preparing movie /movies/X01_HQ_M02_04246.sfd: 153738
debug: Preparing movie /movies/X01_HQ_M02_04246.sfd: 153738
debug: Playing movie c:\program files (x86)\steam\steamapps\common\supreme commander forged alliance\movies\x01_hq_m02_04246.sfd: 153776
debug: Loading module '\000/projectiles/aifmiasmashell02/aifmiasmashell02_script.lua\000'
debug: Loading module '\000/projectiles/aimantimissile01/aimantimissile01_script.lua\000'
debug: Current gametime: 00:41:00
debug: Current gametime: 00:41:30
debug: Loading module '\000/units/ues0304/ues0304_script.lua\000'
info: *DEBUG: Taunt played number 7
debug: OpenMovie /movies/X01_Gari_T01_04515.sfd: 157247
debug: Preparing movie /movies/X01_Gari_T01_04515.sfd: 157247
debug: Preparing movie /movies/X01_Gari_T01_04515.sfd: 157247
debug: Preparing movie /movies/X01_Gari_T01_04515.sfd: 157247
debug: Preparing movie /movies/X01_Gari_T01_04515.sfd: 157247
debug: Preparing movie /movies/X01_Gari_T01_04515.sfd: 157247
debug: Preparing movie /movies/X01_Gari_T01_04515.sfd: 157247
debug: Playing movie c:\program files (x86)\steam\steamapps\common\supreme commander forged alliance\movies\x01_gari_t01_04515.sfd: 157277
info: CWldSession::DoBeat() unknown entity id (0x2ff0054c) supplied in a pose update.
info: *DEBUG: Taunt played number 2
debug: Current gametime: 00:42:00
info: *DEBUG: Taunt played number 3
debug: OpenMovie /movies/X01_HQ_M02_04238.sfd: 159887
debug: Preparing movie /movies/X01_HQ_M02_04238.sfd: 159887
debug: Preparing movie /movies/X01_HQ_M02_04238.sfd: 159887
debug: Preparing movie /movies/X01_HQ_M02_04238.sfd: 159887
debug: Preparing movie /movies/X01_HQ_M02_04238.sfd: 159887
debug: Preparing movie /movies/X01_HQ_M02_04238.sfd: 159887
debug: Preparing movie /movies/X01_HQ_M02_04238.sfd: 159887
debug: Playing movie c:\program files (x86)\steam\steamapps\common\supreme commander forged alliance\movies\x01_hq_m02_04238.sfd: 159937
debug: Current gametime: 00:42:30
debug: Current gametime: 00:43:00
debug: Current gametime: 00:43:30
debug: Current gametime: 00:44:00
debug: Current gametime: 00:44:30
debug: Current gametime: 00:45:00
info: *DEBUG: Taunt played number 1
info: CWldSession::DoBeat() unknown entity id (0x2ff00263) supplied in a pose update.
info: CWldSession::DoBeat() unknown entity id (0x2ff002c6) supplied in a pose update.
debug: OpenMovie /movies/X01_Gari_T01_04511.sfd: 170168
debug: Preparing movie /movies/X01_Gari_T01_04511.sfd: 170168
debug: Preparing movie /movies/X01_Gari_T01_04511.sfd: 170168
debug: Preparing movie /movies/X01_Gari_T01_04511.sfd: 170168
debug: Preparing movie /movies/X01_Gari_T01_04511.sfd: 170168
debug: Preparing movie /movies/X01_Gari_T01_04511.sfd: 170168
debug: Preparing movie /movies/X01_Gari_T01_04511.sfd: 170168
debug: Playing movie c:\program files (x86)\steam\steamapps\common\supreme commander forged alliance\movies\x01_gari_t01_04511.sfd: 170219
debug: Current gametime: 00:45:30
info: *DEBUG: Taunt played number 4
debug: OpenMovie /movies/X01_Gari_T01_04516.sfd: 173003
debug: Preparing movie /movies/X01_Gari_T01_04516.sfd: 173003
debug: Preparing movie /movies/X01_Gari_T01_04516.sfd: 173003
debug: Preparing movie /movies/X01_Gari_T01_04516.sfd: 173003
debug: Preparing movie /movies/X01_Gari_T01_04516.sfd: 173003
debug: Preparing movie /movies/X01_Gari_T01_04516.sfd: 173003
debug: Preparing movie /movies/X01_Gari_T01_04516.sfd: 173003
debug: Playing movie c:\program files (x86)\steam\steamapps\common\supreme commander forged alliance\movies\x01_gari_t01_04516.sfd: 173044
debug: Current gametime: 00:46:00
debug: OpenMovie /movies/X01_Graham_M02_03653.sfd: 174075
debug: Preparing movie /movies/X01_Graham_M02_03653.sfd: 174075
debug: Preparing movie /movies/X01_Graham_M02_03653.sfd: 174075
debug: Preparing movie /movies/X01_Graham_M02_03653.sfd: 174075
debug: Preparing movie /movies/X01_Graham_M02_03653.sfd: 174075
debug: Preparing movie /movies/X01_Graham_M02_03653.sfd: 174075
debug: Preparing movie /movies/X01_Graham_M02_03653.sfd: 174075
debug: Playing movie c:\program files (x86)\steam\steamapps\common\supreme commander forged alliance\movies\x01_graham_m02_03653.sfd: 174115
debug: OpenMovie /movies/X01_Gari_M02_04245.sfd: 174308
debug: Preparing movie /movies/X01_Gari_M02_04245.sfd: 174308
debug: Preparing movie /movies/X01_Gari_M02_04245.sfd: 174308
debug: Preparing movie /movies/X01_Gari_M02_04245.sfd: 174308
debug: Preparing movie /movies/X01_Gari_M02_04245.sfd: 174308
debug: Preparing movie /movies/X01_Gari_M02_04245.sfd: 174308
debug: Preparing movie /movies/X01_Gari_M02_04245.sfd: 174308
debug: Playing movie c:\program files (x86)\steam\steamapps\common\supreme commander forged alliance\movies\x01_gari_m02_04245.sfd: 174354
info: *DEBUG: Taunt played number 9
debug: Current gametime: 00:46:30
debug: Loading module '\000/projectiles/aifquantumwarhead02/aifquantumwarhead02_script.lua\000'
debug: Loading module '\000/lua/sim/damagearea.lua\000'
warning: ACU kill detected. Rating for ranked games is now enforced.
debug: Loading module '\000/effects/quantumwarhead/quantumwarheadeffect01_script.lua\000'
debug: OpenMovie /movies/X01_Gari_T01_04530.sfd: 175053
debug: Preparing movie /movies/X01_Gari_T01_04530.sfd: 175053
debug: Preparing movie /movies/X01_Gari_T01_04530.sfd: 175053
debug: Preparing movie /movies/X01_Gari_T01_04530.sfd: 175053
debug: Preparing movie /movies/X01_Gari_T01_04530.sfd: 175053
debug: Preparing movie /movies/X01_Gari_T01_04530.sfd: 175053
debug: Preparing movie /movies/X01_Gari_T01_04530.sfd: 175053
info: Sending game result: 6 score 1
debug: Loading module '\000/lua/ui/game/gameresult.lua\000'
info: GAMERESULT : \000score 1
debug: Playing movie c:\program files (x86)\steam\steamapps\common\supreme commander forged alliance\movies\x01_gari_t01_04530.sfd: 175088
debug: OpenMovie /movies/X01_HQ_M02_03675.sfd: 175278
debug: Preparing movie /movies/X01_HQ_M02_03675.sfd: 175278
debug: Preparing movie /movies/X01_HQ_M02_03675.sfd: 175278
debug: Preparing movie /movies/X01_HQ_M02_03675.sfd: 175278
debug: Preparing movie /movies/X01_HQ_M02_03675.sfd: 175278
debug: Preparing movie /movies/X01_HQ_M02_03675.sfd: 175278
debug: Preparing movie /movies/X01_HQ_M02_03675.sfd: 175278
debug: Playing movie c:\program files (x86)\steam\steamapps\common\supreme commander forged alliance\movies\x01_hq_m02_03675.sfd: 175320
info: CWldSession::DoBeat() unknown entity id (0x2ff007ba) supplied in a pose update.
info: CWldSession::DoBeat() unknown entity id (0x2ff007bd) supplied in a pose update.
debug: Loading module '\000/units/xsa0203/xsa0203_script.lua\000'
debug: Loading module '\000/lua/seraphimunits.lua\000'
debug: Loading module '\000/lua/seraphimweapons.lua\000'
debug: Loading module '\000/lua/defaultbufffield.lua\000'
debug: Loading module '\000/units/xsa0103/xsa0103_script.lua\000'
debug: Loading module '\000/units/uel0104/uel0104_script.lua\000'
debug: Loading module '\000/units/xsl0201/xsl0201_script.lua\000'
debug: Loading module '\000/units/ueb1104/ueb1104_script.lua\000'
debug: Loading module '\000/units/xsl0202/xsl0202_script.lua\000'
debug: Loading module '\000/units/xsl0111/xsl0111_script.lua\000'
debug: Loading module '\000/units/xsl0303/xsl0303_script.lua\000'
debug: Loading module '\000/units/ueb1102/ueb1102_script.lua\000'
debug: Loading module '\000/units/ueb4302/ueb4302_script.lua\000'
debug: Loading module '\000/units/xec1301/xec1301_script.lua\000'
debug: Loading module '\000/units/xsl0309/xsl0309_script.lua\000'
debug: Loading module '\000/units/xsb2204/xsb2204_script.lua\000'
debug: Loading module '\000/units/xsb2304/xsb2304_script.lua\000'
debug: Loading module '\000/units/xsb4301/xsb4301_script.lua\000'
debug: Loading module '\000/units/xsb2301/xsb2301_script.lua\000'
debug: Loading module '\000/units/xsb2303/xsb2303_script.lua\000'
debug: Loading module '\000/units/xsb4201/xsb4201_script.lua\000'
debug: Loading module '\000/units/zsb9601/zsb9601_script.lua\000'
debug: Loading module '\000/units/zsb9501/zsb9501_script.lua\000'
debug: Loading module '\000/units/xsb0301/xsb0301_script.lua\000'
debug: Loading module '\000/units/xsb5101/xsb5101_script.lua\000'
debug: Loading module '\000/units/xsb3104/xsb3104_script.lua\000'
debug: Loading module '\000/units/xsb5202/xsb5202_script.lua\000'
debug: Loading module '\000/units/xsb3101/xsb3101_script.lua\000'
debug: Loading module '\000/units/xsb2305/xsb2305_script.lua\000'
debug: Loading module '\000/units/xsb1106/xsb1106_script.lua\000'
debug: Loading module '\000/units/xsb1302/xsb1302_script.lua\000'
debug: Loading module '\000/units/xsb1303/xsb1303_script.lua\000'
debug: Loading module '\000/units/xsb1201/xsb1201_script.lua\000'
debug: Loading module '\000/units/xsb1301/xsb1301_script.lua\000'
debug: Loading module '\000/units/xsb4302/xsb4302_script.lua\000'
debug: Loading module '\000/units/xsb3201/xsb3201_script.lua\000'
debug: Loading module '\000/units/xsb1105/xsb1105_script.lua\000'
debug: Loading module '\000/units/xsb2302/xsb2302_script.lua\000'
debug: Loading module '\000/units/zsb9502/zsb9502_script.lua\000'
debug: Loading module '\000/units/zsb9602/zsb9602_script.lua\000'
debug: Loading module '\000/units/xsb0302/xsb0302_script.lua\000'
debug: Loading module '\000/units/zsb9603/zsb9603_script.lua\000'
debug: Loading module '\000/units/xsb3202/xsb3202_script.lua\000'
debug: Loading module '\000/units/xsb0303/xsb0303_script.lua\000'
debug: Loading module '\000/units/xsb2205/xsb2205_script.lua\000'
debug: Loading module '\000/units/xsb4203/xsb4203_script.lua\000'
debug: Loading module '\000/units/xsb4202/xsb4202_script.lua\000'
debug: Loading module '\000/units/xsa0303/xsa0303_script.lua\000'
debug: Loading module '\000/units/xsa0202/xsa0202_script.lua\000'
debug: Loading module '\000/units/xss0201/xss0201_script.lua\000'
info: Hooked /units/xss0201/xss0201_script.lua with /mods/coop/hook/units/xss0201/xss0201_script.lua
debug: Loading module '\000/units/xss0302/xss0302_script.lua\000'
debug: Loading module '\000/units/xss0202/xss0202_script.lua\000'
debug: Loading module '\000/units/xss0203/xss0203_script.lua\000'
debug: Loading module '\000/units/xss0304/xss0304_script.lua\000'
debug: Loading module '\000/units/xsl0103/xsl0103_script.lua\000'
debug: Loading module '\000/units/xsl0205/xsl0205_script.lua\000'
debug: Loading module '\000/units/xsl0305/xsl0305_script.lua\000'
debug: Loading module '\000/units/xsl0401/xsl0401_script.lua\000'
debug: Loading module '\000/units/xsa0304/xsa0304_script.lua\000'
debug: Loading module '\000/units/xss0303/xss0303_script.lua\000'
debug: Loading module '\000/units/xsl0001/xsl0001_script.lua\000'
info: Debug: SetPlayableArea before round : 12.5, 12.5 1010.5, 1010.5
info: Debug: SetPlayableArea after round : 12, 12 1008, 1008
info: Camera:SyncPlayableRect \000{ x0=12, x1=1008, y0=12, y1=1008 }
info: Request: \000{
info:   Name="WorldCamera",
info:   Region={ x0=12, x1=1008, y0=12, y1=1008 },
info:   Type="CAMERA_SYNC_PLAYABLE_RECT"
info: }
info: playable area coordinates are { 12, 12, 1008, 1008 }
info: Offmapareas are {
info:   { x0=-88, x1=1108, y0=-88, y1=12 },
info:   { x0=-88, x1=1108, y0=1008, y1=1108 },
info:   { x0=-88, x1=12, y0=12, y1=1008 },
info:   { x0=1008, x1=1108, y0=12, y1=1008 }
info: }
debug: OpenMovie /movies/X01_HQ_M03_03683.sfd: 175869
debug: Preparing movie /movies/X01_HQ_M03_03683.sfd: 175869
debug: Preparing movie /movies/X01_HQ_M03_03683.sfd: 175869
debug: Preparing movie /movies/X01_HQ_M03_03683.sfd: 175869
debug: Preparing movie /movies/X01_HQ_M03_03683.sfd: 175869
debug: Preparing movie /movies/X01_HQ_M03_03683.sfd: 175869
debug: Preparing movie /movies/X01_HQ_M03_03683.sfd: 175869
debug: Loading module '\000/projectiles/sdfaireaubolter02/sdfaireaubolter02_script.lua\000'
debug: Loading module '\000/lua/seraphimprojectiles.lua\000'
debug: Loading module '\000/projectiles/sdftaucannon01/sdftaucannon01_script.lua\000'
debug: Loading module '\000/projectiles/sdfaireaubolter01/sdfaireaubolter01_script.lua\000'
debug: Playing movie c:\program files (x86)\steam\steamapps\common\supreme commander forged alliance\movies\x01_hq_m03_03683.sfd: 175879
debug: Loading module '\000/projectiles/sifthunthoartilleryshell01/sifthunthoartilleryshell01_script.lua\000'
debug: Loading module '\000/projectiles/sdfheavyphasicautogun02/sdfheavyphasicautogun02_script.lua\000'
debug: Loading module '\000/projectiles/sifthunthoartilleryshell02/sifthunthoartilleryshell02_script.lua\000'
debug: Loading module '\000/projectiles/sboothetacticalbomb01/sboothetacticalbomb01_script.lua\000'
debug: Loading module '\000/projectiles/sifsuthanusartilleryshell02/sifsuthanusartilleryshell02_script.lua\000'
debug: Loading module '\000/units/xsa0302/xsa0302_script.lua\000'
debug: Loading module '\000/effects/entities/seraphimbuildeffect01/seraphimbuildeffect01_script.lua\000'
debug: Loading module '\000/projectiles/saalosaareautocannon01/saalosaareautocannon01_script.lua\000'
debug: Current gametime: 00:47:00
debug: OpenMovie /movies/X01_Fletcher_M03_04694.sfd: 176963
debug: Preparing movie /movies/X01_Fletcher_M03_04694.sfd: 176963
debug: Preparing movie /movies/X01_Fletcher_M03_04694.sfd: 176963
debug: Loading module '\000/projectiles/sdfsnipershot01/sdfsnipershot01_script.lua\000'
debug: Preparing movie /movies/X01_Fletcher_M03_04694.sfd: 176963
debug: Preparing movie /movies/X01_Fletcher_M03_04694.sfd: 176963
debug: Preparing movie /movies/X01_Fletcher_M03_04694.sfd: 176963
debug: Preparing movie /movies/X01_Fletcher_M03_04694.sfd: 176963
debug: Playing movie c:\program files (x86)\steam\steamapps\common\supreme commander forged alliance\movies\x01_fletcher_m03_04694.sfd: 177007
debug: Loading module '\000/projectiles/sbozhanaseebomb01/sbozhanaseebomb01_script.lua\000'
debug: Loading module '\000/projectiles/saaolarisaaartillery02/saaolarisaaartillery02_script.lua\000'
debug: Loading module '\000/effects/entities/sbozhanaseebombeffect01/sbozhanaseebombeffect01_script.lua\000'
debug: Loading module '\000/effects/entities/sbozhanaseebombeffect02/sbozhanaseebombeffect02_script.lua\000'
debug: Loading module '\000/projectiles/saashleoaagatlinggun03/saashleoaagatlinggun03_script.lua\000'
debug: Loading module '\000/projectiles/sifinainostrategicmissile01/sifinainostrategicmissile01_script.lua\000'
debug: Loading module '\000/lua/ui/game/nukelaunchping.lua\000'
debug: OpenMovie /movies/X01_Graham_M02_04891.sfd: 178179
debug: Preparing movie /movies/X01_Graham_M02_04891.sfd: 178179
debug: Preparing movie /movies/X01_Graham_M02_04891.sfd: 178179
debug: Preparing movie /movies/X01_Graham_M02_04891.sfd: 178179
debug: Preparing movie /movies/X01_Graham_M02_04891.sfd: 178179
debug: Preparing movie /movies/X01_Graham_M02_04891.sfd: 178179
debug: Preparing movie /movies/X01_Graham_M02_04891.sfd: 178179
debug: Playing movie c:\program files (x86)\steam\steamapps\common\supreme commander forged alliance\movies\x01_graham_m02_04891.sfd: 178216
debug: Current gametime: 00:47:30
info: *DEBUG: Taunt played number 4
debug: OpenMovie /movies/X01_Fletcher_M03_03690.sfd: 178735
debug: Preparing movie /movies/X01_Fletcher_M03_03690.sfd: 178735
debug: Preparing movie /movies/X01_Fletcher_M03_03690.sfd: 178735
debug: Preparing movie /movies/X01_Fletcher_M03_03690.sfd: 178735
debug: Preparing movie /movies/X01_Fletcher_M03_03690.sfd: 178735
debug: Preparing movie /movies/X01_Fletcher_M03_03690.sfd: 178735
debug: Preparing movie /movies/X01_Fletcher_M03_03690.sfd: 178735
debug: Playing movie c:\program files (x86)\steam\steamapps\common\supreme commander forged alliance\movies\x01_fletcher_m03_03690.sfd: 178778
info: *DEBUG: Taunt played number 10
debug: Current gametime: 00:48:00
debug: Loading module '\000/effects/entities/inainoeffectcontroller01/inainoeffectcontroller01_script.lua\000'
info: *DEBUG: Taunt played number 5
debug: Loading module '\000/effects/entities/sifinainostrategicmissileeffect02/sifinainostrategicmissileeffect02_script.lua\000'
debug: Loading module '\000/effects/entities/sifinainostrategicmissileeffect01/sifinainostrategicmissileeffect01_script.lua\000'
debug: Loading module '\000/effects/entities/sifinainostrategicmissileeffect04/sifinainostrategicmissileeffect04_script.lua\000'
debug: Loading module '\000/effects/entities/sifinainostrategicmissileeffect03/sifinainostrategicmissileeffect03_script.lua\000'
debug: Loading module '\000/units/ues0401/ues0401_script.lua\000'
debug: Current gametime: 00:48:30
debug: Loading module '\000/projectiles/siflaansetacticalmissile02/siflaansetacticalmissile02_script.lua\000'
debug: Loading module '\000/projectiles/tdphalanx01/tdphalanx01_script.lua\000'
debug: Loading module '\000/projectiles/simantimissile02/simantimissile02_script.lua\000'
debug: Current gametime: 00:49:00
debug: Loading module '\000/projectiles/sanuallcavitationtorpedo04/sanuallcavitationtorpedo04_script.lua\000'
debug: Loading module '\000/projectiles/sananaittorpedo01/sananaittorpedo01_script.lua\000'
debug: Loading module '\000/projectiles/sanajelluantitorpedo01/sanajelluantitorpedo01_script.lua\000'
debug: Current gametime: 00:49:30
debug: Loading module '\000/projectiles/sdfheavyquarnoncannon01/sdfheavyquarnoncannon01_script.lua\000'
debug: Loading module '\000/projectiles/siflaansetacticalmissile03/siflaansetacticalmissile03_script.lua\000'
debug: Current gametime: 00:50:00
debug: Loading module '\000/units/uea0103/uea0103_script.lua\000'
debug: Current gametime: 00:50:30
debug: Loading module '\000/projectiles/saaolarisaaartillery06/saaolarisaaartillery06_script.lua\000'
debug: Loading module '\000/projectiles/sanuallcavitationtorpedo02/sanuallcavitationtorpedo02_script.lua\000'
debug: Current gametime: 00:51:00
debug: Loading module '\000/projectiles/saalosaareautocannon04/saalosaareautocannon04_script.lua\000'
debug: Loading module '\000/projectiles/tifnapalmcarpetbomb01/tifnapalmcarpetbomb01_script.lua\000'
debug: Loading module '\000/projectiles/siflaansetacticalmissile01/siflaansetacticalmissile01_script.lua\000'
debug: Current gametime: 00:51:30
debug: Loading module '\000/units/xsa0204/xsa0204_script.lua\000'
debug: Current gametime: 00:52:00
debug: OpenMovie /movies/X01_Hall_M03_03717.sfd: 195590
debug: Preparing movie /movies/X01_Hall_M03_03717.sfd: 195590
debug: Preparing movie /movies/X01_Hall_M03_03717.sfd: 195590
debug: Preparing movie /movies/X01_Hall_M03_03717.sfd: 195590
debug: Preparing movie /movies/X01_Hall_M03_03717.sfd: 195590
debug: Preparing movie /movies/X01_Hall_M03_03717.sfd: 195590
debug: Preparing movie /movies/X01_Hall_M03_03717.sfd: 195590
debug: Playing movie c:\program files (x86)\steam\steamapps\common\supreme commander forged alliance\movies\x01_hall_m03_03717.sfd: 195629
info: *DEBUG: Taunt played number 3
debug: OpenMovie /movies/X01_HQ_M03_03715.sfd: 195885
debug: Preparing movie /movies/X01_HQ_M03_03715.sfd: 195885
debug: Preparing movie /movies/X01_HQ_M03_03715.sfd: 195885
debug: Preparing movie /movies/X01_HQ_M03_03715.sfd: 195885
debug: Preparing movie /movies/X01_HQ_M03_03715.sfd: 195885
debug: Preparing movie /movies/X01_HQ_M03_03715.sfd: 195885
debug: Preparing movie /movies/X01_HQ_M03_03715.sfd: 195885
debug: Playing movie c:\program files (x86)\steam\steamapps\common\supreme commander forged alliance\movies\x01_hq_m03_03715.sfd: 195929
info: *DEBUG: Taunt played number 1
debug: OpenMovie /movies/X01_Fletcher_M03_04256.sfd: 196287
debug: Preparing movie /movies/X01_Fletcher_M03_04256.sfd: 196287
debug: Preparing movie /movies/X01_Fletcher_M03_04256.sfd: 196287
debug: Preparing movie /movies/X01_Fletcher_M03_04256.sfd: 196287
debug: Preparing movie /movies/X01_Fletcher_M03_04256.sfd: 196287
debug: Preparing movie /movies/X01_Fletcher_M03_04256.sfd: 196287
debug: Preparing movie /movies/X01_Fletcher_M03_04256.sfd: 196287
debug: Playing movie c:\program files (x86)\steam\steamapps\common\supreme commander forged alliance\movies\x01_fletcher_m03_04256.sfd: 196329
debug: OpenMovie /movies/X01_Shun-Ullevash_T01_04334.sfd: 196578
debug: Preparing movie /movies/X01_Shun-Ullevash_T01_04334.sfd: 196578
debug: Preparing movie /movies/X01_Shun-Ullevash_T01_04334.sfd: 196578
debug: Preparing movie /movies/X01_Shun-Ullevash_T01_04334.sfd: 196578
debug: Preparing movie /movies/X01_Shun-Ullevash_T01_04334.sfd: 196578
debug: Preparing movie /movies/X01_Shun-Ullevash_T01_04334.sfd: 196578
debug: Preparing movie /movies/X01_Shun-Ullevash_T01_04334.sfd: 196578
debug: Playing movie c:\program files (x86)\steam\steamapps\common\supreme commander forged alliance\movies\x01_shun-ullevash_t01_04334.sfd: 196622
debug: Loading module '\000/projectiles/saaolarisaaartillery03/saaolarisaaartillery03_script.lua\000'
debug: Current gametime: 00:52:30
debug: Current gametime: 00:53:00
debug: Loading module '\000/units/xss0103/xss0103_script.lua\000'
debug: Loading module '\000/projectiles/tananglertorpedo02/tananglertorpedo02_script.lua\000'
debug: Current gametime: 00:53:30
debug: Current gametime: 00:54:00
debug: Loading module '\000/projectiles/sdfaireauweapon01/sdfaireauweapon01_script.lua\000'
debug: Loading module '\000/projectiles/sdfexperimentalphasonproj01/sdfexperimentalphasonproj01_script.lua\000'
debug: Loading module '\000/projectiles/sdfsinnuntheweapon01/sdfsinnuntheweapon01_script.lua\000'
debug: Loading module '\000/projectiles/timmissileintercerptor01/timmissileintercerptor01_script.lua\000'
debug: Current gametime: 00:54:30
debug: Loading module '\000/projectiles/tifmissilecruise03/tifmissilecruise03_script.lua\000'
debug: OpenMovie /movies/X01_HQ_M03_04255.sfd: 205613
debug: Preparing movie /movies/X01_HQ_M03_04255.sfd: 205613
debug: Preparing movie /movies/X01_HQ_M03_04255.sfd: 205613
debug: Preparing movie /movies/X01_HQ_M03_04255.sfd: 205613
debug: Preparing movie /movies/X01_HQ_M03_04255.sfd: 205613
debug: Preparing movie /movies/X01_HQ_M03_04255.sfd: 205613
debug: Preparing movie /movies/X01_HQ_M03_04255.sfd: 205613
debug: Playing movie c:\program files (x86)\steam\steamapps\common\supreme commander forged alliance\movies\x01_hq_m03_04255.sfd: 205654
debug: Loading module '\000/units/xsl0402/xsl0402_script.lua\000'
debug: Loading module '\000/projectiles/sdfohcannon01/sdfohcannon01_script.lua\000'
info: *DEBUG: Taunt played number 2
debug: OpenMovie /movies/X01_Shun-Ullevash_T01_04338.sfd: 205944
debug: Preparing movie /movies/X01_Shun-Ullevash_T01_04338.sfd: 205944
debug: Preparing movie /movies/X01_Shun-Ullevash_T01_04338.sfd: 205944
debug: Preparing movie /movies/X01_Shun-Ullevash_T01_04338.sfd: 205944
debug: Preparing movie /movies/X01_Shun-Ullevash_T01_04338.sfd: 205944
debug: Preparing movie /movies/X01_Shun-Ullevash_T01_04338.sfd: 205944
debug: Preparing movie /movies/X01_Shun-Ullevash_T01_04338.sfd: 205944
debug: Playing movie c:\program files (x86)\steam\steamapps\common\supreme commander forged alliance\movies\x01_shun-ullevash_t01_04338.sfd: 205988
debug: Current gametime: 00:55:00
debug: Current gametime: 00:55:30
debug: Current gametime: 00:56:00
debug: Loading module '\000/units/xel0306/xel0306_script.lua\000'
debug: Current gametime: 00:56:30
debug: Current gametime: 00:57:00
debug: Current gametime: 00:57:30
debug: Loading module '\000/projectiles/tifmissilecruise02/tifmissilecruise02_script.lua\000'
debug: Current gametime: 00:58:00
debug: Current gametime: 00:58:30
debug: Current gametime: 00:59:00
debug: Loading module '\000/projectiles/tifmissilecruise05/tifmissilecruise05_script.lua\000'
debug: Current gametime: 00:59:30
debug: Current gametime: 01:00:00
debug: Current gametime: 01:00:30
debug: Loading module '\000/projectiles/sdfshieeihautocannon01/sdfshieeihautocannon01_script.lua\000'
debug: Current gametime: 01:01:00
debug: Current gametime: 01:01:30
debug: Current gametime: 01:02:00
info: *DEBUG: Taunt played number 11
debug: OpenMovie /movies/X01_Fletcher_M03_03712.sfd: 234067
debug: Preparing movie /movies/X01_Fletcher_M03_03712.sfd: 234067
debug: Preparing movie /movies/X01_Fletcher_M03_03712.sfd: 234067
debug: Preparing movie /movies/X01_Fletcher_M03_03712.sfd: 234067
debug: Preparing movie /movies/X01_Fletcher_M03_03712.sfd: 234067
debug: Preparing movie /movies/X01_Fletcher_M03_03712.sfd: 234067
debug: Preparing movie /movies/X01_Fletcher_M03_03712.sfd: 234067
debug: Playing movie c:\program files (x86)\steam\steamapps\common\supreme commander forged alliance\movies\x01_fletcher_m03_03712.sfd: 234113
warning: Error running OnRelease script in <deleted object>: ...mdata\faforever\gamedata\lua.nx2\lua\maui\button.lua(84): Game object has been destroyed
         stack traceback:
         	[C]: in function `Play'
         	...mdata\faforever\gamedata\lua.nx2\lua\maui\button.lua(84): in function <...mdata\faforever\gamedata\lua.nx2\lua\maui\button.lua:78>
debug: OpenMovie /movies/X01_Fletcher_M03_03706.sfd: 234858
debug: Preparing movie /movies/X01_Fletcher_M03_03706.sfd: 234858
debug: Preparing movie /movies/X01_Fletcher_M03_03706.sfd: 234858
debug: Preparing movie /movies/X01_Fletcher_M03_03706.sfd: 234858
debug: Preparing movie /movies/X01_Fletcher_M03_03706.sfd: 234858
debug: Preparing movie /movies/X01_Fletcher_M03_03706.sfd: 234858
debug: Preparing movie /movies/X01_Fletcher_M03_03706.sfd: 234858
debug: Playing movie c:\program files (x86)\steam\steamapps\common\supreme commander forged alliance\movies\x01_fletcher_m03_03706.sfd: 234891
debug: Loading module '\000/projectiles/simantimissile01/simantimissile01_script.lua\000'
debug: Current gametime: 01:02:30
debug: Current gametime: 01:03:00
debug: Loading module '\000/projectiles/tifmissilenuke02/tifmissilenuke02_script.lua\000'
debug: Current gametime: 01:03:30
debug: Loading module '\000/effects/entities/uefnukeeffectcontroller01/uefnukeeffectcontroller01_script.lua\000'
info: *DEBUG: Taunt played number 6
debug: Loading module '\000/effects/entities/uefnukeeffect01/uefnukeeffect01_script.lua\000'
debug: Loading module '\000/effects/entities/uefnukeeffect02/uefnukeeffect02_script.lua\000'
debug: Loading module '\000/effects/entities/uefnukeshockwave01/uefnukeshockwave01_script.lua\000'
debug: Loading module '\000/effects/entities/uefnukeshockwave02/uefnukeshockwave02_script.lua\000'
debug: Loading module '\000/effects/entities/uefnukeeffect03/uefnukeeffect03_script.lua\000'
debug: Loading module '\000/effects/entities/uefnukeflavorplume01/uefnukeflavorplume01_script.lua\000'
debug: OpenMovie /movies/X01_Fletcher_M03_03713.sfd: 240779
debug: Preparing movie /movies/X01_Fletcher_M03_03713.sfd: 240779
debug: Preparing movie /movies/X01_Fletcher_M03_03713.sfd: 240779
debug: Preparing movie /movies/X01_Fletcher_M03_03713.sfd: 240779
debug: Preparing movie /movies/X01_Fletcher_M03_03713.sfd: 240779
debug: Preparing movie /movies/X01_Fletcher_M03_03713.sfd: 240779
debug: Preparing movie /movies/X01_Fletcher_M03_03713.sfd: 240779
debug: Playing movie c:\program files (x86)\steam\steamapps\common\supreme commander forged alliance\movies\x01_fletcher_m03_03713.sfd: 240821
debug: Loading module '\000/effects/entities/uefnukeeffect05/uefnukeeffect05_script.lua\000'
debug: Current gametime: 01:04:00
debug: Current gametime: 01:04:30
debug: Current gametime: 01:05:00
info: *DEBUG: Taunt played number 7
debug: OpenMovie /movies/X01_Fletcher_M03_03714.sfd: 245872
debug: Preparing movie /movies/X01_Fletcher_M03_03714.sfd: 245872
debug: Preparing movie /movies/X01_Fletcher_M03_03714.sfd: 245872
debug: Preparing movie /movies/X01_Fletcher_M03_03714.sfd: 245872
debug: Preparing movie /movies/X01_Fletcher_M03_03714.sfd: 245872
debug: Preparing movie /movies/X01_Fletcher_M03_03714.sfd: 245872
debug: Preparing movie /movies/X01_Fletcher_M03_03714.sfd: 245872
debug: Playing movie c:\program files (x86)\steam\steamapps\common\supreme commander forged alliance\movies\x01_fletcher_m03_03714.sfd: 245916
debug: Current gametime: 01:05:30
debug: Loading module '\000/projectiles/sanheavycavitationtorpedo02/sanheavycavitationtorpedo02_script.lua\000'
debug: Loading module '\000/projectiles/sanheavycavitationtorpedo03/sanheavycavitationtorpedo03_script.lua\000'
debug: Current gametime: 01:06:00
debug: Loading module '\000/projectiles/sifzthuthaamartilleryshell02/sifzthuthaamartilleryshell02_script.lua\000'
debug: Current gametime: 01:06:30
debug: Loading module '\000/units/xea0306/xea0306_script.lua\000'
debug: Current gametime: 01:07:00
debug: Current gametime: 01:07:30
info: CWldSession::DoBeat() unknown entity id (0x2ff00776) supplied in a pose update.
debug: Current gametime: 01:08:00
info: *DEBUG: Taunt played number 8
debug: OpenMovie /movies/X01_Fletcher_T01_04532.sfd: 258852
debug: Preparing movie /movies/X01_Fletcher_T01_04532.sfd: 258852
debug: Preparing movie /movies/X01_Fletcher_T01_04532.sfd: 258852
debug: Preparing movie /movies/X01_Fletcher_T01_04532.sfd: 258852
debug: Preparing movie /movies/X01_Fletcher_T01_04532.sfd: 258852
debug: Preparing movie /movies/X01_Fletcher_T01_04532.sfd: 258852
debug: Preparing movie /movies/X01_Fletcher_T01_04532.sfd: 258852
debug: Playing movie c:\program files (x86)\steam\steamapps\common\supreme commander forged alliance\movies\x01_fletcher_t01_04532.sfd: 258888
debug: Current gametime: 01:08:30
info: *DEBUG: Taunt played number 3
info: *DEBUG: Taunt played number 4
debug: OpenMovie /movies/X01_Shun-Ullevash_T01_04342.sfd: 260545
debug: Preparing movie /movies/X01_Shun-Ullevash_T01_04342.sfd: 260545
debug: Preparing movie /movies/X01_Shun-Ullevash_T01_04342.sfd: 260545
debug: Preparing movie /movies/X01_Shun-Ullevash_T01_04342.sfd: 260545
debug: Preparing movie /movies/X01_Shun-Ullevash_T01_04342.sfd: 260545
debug: Preparing movie /movies/X01_Shun-Ullevash_T01_04342.sfd: 260545
debug: Preparing movie /movies/X01_Shun-Ullevash_T01_04342.sfd: 260545
debug: Playing movie c:\program files (x86)\steam\steamapps\common\supreme commander forged alliance\movies\x01_shun-ullevash_t01_04342.sfd: 260587
debug: Current gametime: 01:09:00
info: CWldSession::DoBeat() unknown entity id (0x2ff014c6) supplied in a pose update.
info: CWldSession::DoBeat() unknown entity id (0x2ff014f8) supplied in a pose update.
warning: ACU kill detected. Rating for ranked games is now enforced.
debug: Current gametime: 01:09:30
debug: OpenMovie /movies/X01_Shun-Ullevash_M03_04257.sfd: 262981
debug: Preparing movie /movies/X01_Shun-Ullevash_M03_04257.sfd: 262981
debug: Preparing movie /movies/X01_Shun-Ullevash_M03_04257.sfd: 262981
debug: Preparing movie /movies/X01_Shun-Ullevash_M03_04257.sfd: 262981
debug: Preparing movie /movies/X01_Shun-Ullevash_M03_04257.sfd: 262981
debug: Preparing movie /movies/X01_Shun-Ullevash_M03_04257.sfd: 262981
debug: Preparing movie /movies/X01_Shun-Ullevash_M03_04257.sfd: 262981
info: Sending game result: 1 score 1
info: GAMERESULT : \000score 1
debug: Playing movie c:\program files (x86)\steam\steamapps\common\supreme commander forged alliance\movies\x01_shun-ullevash_m03_04257.sfd: 263021
debug: OpenMovie /movies/X01_Hall_M03_04258.sfd: 263191
debug: Preparing movie /movies/X01_Hall_M03_04258.sfd: 263191
debug: Preparing movie /movies/X01_Hall_M03_04258.sfd: 263191
debug: Preparing movie /movies/X01_Hall_M03_04258.sfd: 263191
debug: Preparing movie /movies/X01_Hall_M03_04258.sfd: 263191
debug: Preparing movie /movies/X01_Hall_M03_04258.sfd: 263191
debug: Preparing movie /movies/X01_Hall_M03_04258.sfd: 263191
debug: Playing movie c:\program files (x86)\steam\steamapps\common\supreme commander forged alliance\movies\x01_hall_m03_04258.sfd: 263230
debug: Loading module '\000/maps/x1ca_coop_001.v0024/x1ca_coop_001_operation.lua\000'
debug: Loading module '\000/lua/system/dkson.lua\000'
info: Sending stats: {"stats":[{"blueprints":{"xaa0202":{"kills":232},"uaa0302":{"kills":20},"uea0302":{"built":12},"xsb2303":{"kills":8},"ueb3201":{"lost":1,"built":1},"ueb2204":{"built":5},"xsb1301":{"kills":26},"uab0302":{"kills":3},"ueb4302":{"built":1},"xel0305":{"lost":1,"built":5},"xsl0201":{"kills":24},"uab2204":{"kills":5},"ueb2304":{"lost":1,"built":16},"uab2101":{"kills":6},"uab2104":{"kills":2},"ueb5202":{"lost":1,"built":1},"xsb1303":{"kills":6},"uab5202":{"kills":1},"uab2304":{"kills":3},"uel0301_Engineer":{"built":1},"ueb0202":{"built":1},"xsb1302":{"kills":14},"uel0301_Combat":{"built":1},"ueb1105":{"lost":4,"built":5},"uab1105":{"kills":1},"ueb0201":{"built":2},"xsb4301":{"kills":7},"uel0309":{"lost":3,"built":59},"xsl0401":{"kills":1},"uaa0304":{"kills":3},"ueb0301":{"built":2},"uab0301":{"kills":1},"uel0301":{"built":1},"zab9602":{"kills":9},"uel0105":{"lost":2,"built":8},"ueb1106":{"lost":4,"built":14},"ual0101":{"kills":3},"xsb2204":{"kills":1},"uel0301_RAS":{"built":1},"ual0309":{"kills":12},"xsl0111":{"kills":1},"xss0304":{"kills":1},"xss0203":{"kills":2},"zab9601":{"kills":6},"xsb5202":{"kills":7},"xsl0001":{"kills":19},"ueb1101":{"built":4},"ual0201":{"kills":107},"xsa0304":{"kills":1},"ueb0102":{"built":1},"xsb4201":{"kills":12},"ues0203":{"built":6},"zsb9601":{"kills":24},"xsa0204":{"kills":4},"xsl0303":{"kills":88},"xsb2301":{"kills":26},"xsb2304":{"kills":9},"zsb9501":{"kills":36},"uab1301":{"kills":10},"xsb4202":{"kills":4},"xss0201":{"kills":9},"ueb1303":{"lost":4,"built":24},"uel0208":{"lost":4,"built":7},"xss0302":{"kills":5},"ual0304":{"kills":1},"uel0001":{"built":1,"lowest_health":12000},"uab4202":{"kills":3},"xss0103":{"kills":1},"xsl0202":{"kills":32},"xsl0205":{"kills":15},"ueb3202":{"lost":2,"built":2},"xsa0302":{"kills":19},"xsa0203":{"kills":281},"xsb4203":{"kills":1},"ueb2104":{"lost":1,"built":2},"ueb0302":{"built":1},"uab1106":{"kills":11},"zeb9602":{"built":4},"ual0202":{"kills":6},"ueb1301":{"built":13},"xaa0305":{"kills":66},"ueb4301":{"lost":2,"built":9},"uea0305":{"lost":15,"built":51},"zeb9601":{"built":2},"uab4201":{"kills":1},"uab5101":{"kills":24},"uaa0303":{"kills":8},"zeb9502":{"built":2},"uab1104":{"kills":1},"xal0203":{"kills":36},"uel0401":{"built":1},"ual0303":{"kills":6},"xsl0309":{"kills":28},"ueb0304":{"lost":1,"built":2},"ueb1201":{"built":1},"ueb0101":{"built":2},"uaa0203":{"kills":923},"ual0205":{"kills":28},"uab2303":{"kills":3},"uab3201":{"kills":1},"ues0401":{"built":3},"uaa0103":{"kills":136},"ueb1302":{"built":6},"uab1101":{"kills":4},"xsb1106":{"kills":11},"uea0303":{"lost":9,"built":16},"uea0003":{"lost":2,"built":3},"uaa0102":{"kills":60},"xsb1105":{"kills":1},"uab2301":{"kills":2},"uab1302":{"kills":7},"del0204":{"lost":6,"built":9},"ueb2301":{"built":6},"uea0304":{"lost":7,"built":69},"xsa0303":{"kills":163}},"type":"Human","general":{"score":1604789,"currentcap":{"count":500},"lastReclaimedMass":14205.840820313,"mass":821037.5625,"built":{"mass":532114,"count":380,"energy":19431270},"kills":{"mass":380793.3125,"count":1138,"energy":11916642},"lost":{"mass":217778.09375,"count":159,"energy":12583175},"currentunits":{"count":221},"energy":75769472,"lastReclaimedEnergy":45},"faction":1,"resources":{"massin":{"total":821037.5625,"rate":25.900003433228},"energyout":{"total":53089104,"rate":3096.1748046875},"energyin":{"total":75769472,"rate":1914},"energyover":22219088,"massover":84990.1875,"massout":{"total":545123.9375,"rate":18.589782714844}},"name":"cyophy","units":{"air":{"lost":122,"kills":733,"built":157},"tech3":{"lost":132,"kills":120,"built":296},"cdr":{"lost":0,"kills":1,"built":1},"tech2":{"lost":13,"kills":634,"built":36},"tech1":{"lost":14,"kills":382,"built":43},"transportation":{"lost":0,"kills":0,"built":0},"land":{"lost":16,"kills":282,"built":102},"sacu":{"lost":0,"kills":0,"built":4},"structures":{"lost":21,"kills":129,"built":129},"engineer":{"lost":11,"kills":24,"built":79},"naval":{"lost":0,"kills":5,"built":9},"experimental":{"lost":0,"kills":1,"built":4}}},{"blueprints":{"xsb4202":{"lost":1,"built":1},"xsb2303":{"lost":10,"built":11},"uel0303":{"kills":222},"xsb2302":{"lost":1,"built":1},"ueb3201":{"kills":5},"ueb2204":{"kills":29},"xsb1301":{"lost":16,"built":19},"zsb9602":{"lost":2,"built":3},"uea0203":{"kills":271},"xsl0202":{"lost":111,"built":111},"ueb2104":{"kills":2},"ueb1101":{"kills":3},"xsb1303":{"lost":8,"built":8},"xss0202":{"lost":5,"built":5},"xss0203":{"lost":4,"built":7},"xsb3201":{"lost":1,"built":1},"ues0201":{"kills":74},"xsb1201":{"lost":1,"built":1},"xsl0402":{"built":5},"xsb1302":{"lost":14,"built":16},"xsl0205":{"lost":91,"built":91},"xsa0202":{"built":1},"uea0304":{"kills":24},"xss0201":{"lost":24,"built":24},"xsa0103":{"built":2},"xsb3104":{"lost":1,"built":1},"uec1401":{"kills":4},"xsa0204":{"lost":20,"built":20},"xec8002":{"kills":8},"xsl0111":{"lost":101,"built":101},"xsa0303":{"built":85},"xsb5101":{"lost":6,"built":66},"xsb3101":{"lost":3,"built":3},"xsb4301":{"lost":12,"built":12},"uec1201":{"kills":1},"xsb2205":{"lost":2,"built":2},"xsl0401":{"lost":5,"built":5},"ueb2101":{"kills":5},"uel0103":{"kills":46},"xsb4201":{"lost":12,"built":12},"xsb0302":{"lost":1,"built":1},"ueb1201":{"kills":23},"xsl0201":{"lost":110,"built":110},"uec1301":{"kills":3},"xsb2301":{"lost":15,"built":15},"xsb2304":{"lost":7,"built":7},"zsb9501":{"lost":5,"built":5},"ues0302":{"kills":13},"delk002":{"kills":12},"uea0102":{"kills":154},"uel0104":{"kills":21},"uel0208":{"kills":6},"uel0307":{"kills":43},"xsb0303":{"lost":1,"built":1},"xsb2305":{"lost":1,"built":1},"xss0302":{"lost":10,"built":8},"xsa0203":{"lost":6,"built":172},"xec8010":{"kills":1},"uel0106":{"kills":19},"uea0103":{"kills":140},"xsa0302":{"lost":1,"built":11},"zeb9501":{"kills":23},"xsb4203":{"lost":2,"built":2},"xec8003":{"kills":9},"xsb4302":{"lost":3,"built":3},"uec1101":{"kills":11},"xsl0305":{"lost":2,"built":2},"xss0303":{"lost":1,"built":1},"ueb2304":{"kills":2},"ueb3101":{"kills":1},"ueb4202":{"kills":2},"zeb9601":{"kills":35},"uel0111":{"kills":74},"ueb5101":{"kills":36},"xsb0301":{"lost":1,"built":2},"ues0202":{"kills":25},"uec1501":{"kills":2},"zeb9602":{"kills":10},"uea0305":{"kills":462},"uel0401":{"kills":2},"uel0202":{"kills":214},"xsl0309":{"lost":65,"built":57},"xsb3202":{"lost":27,"built":27},"xsl0103":{"lost":78,"built":78},"zsb9601":{"lost":21,"built":19},"xec8004":{"kills":3},"xss0103":{"lost":15,"built":15},"xsb1106":{"lost":42,"built":49},"ueb4301":{"kills":3},"xsb2204":{"lost":13,"built":13},"xsl0303":{"lost":352,"built":348},"xel0305":{"kills":201},"xsa0304":{"built":32},"zsb9502":{"lost":4,"built":6},"uea0303":{"kills":493},"xsl0001":{"lost":1,"built":1,"lowest_health":0},"ueb5202":{"kills":1},"xsb1105":{"lost":11,"built":11},"zsb9603":{"lost":2,"built":2},"uel0309":{"kills":52},"xss0304":{"lost":3,"built":3},"ueb2301":{"kills":41},"xsb5202":{"lost":6,"built":6},"uel0205":{"kills":232}},"type":"AI","general":{"score":1303065,"currentcap":{"count":1000},"lastReclaimedMass":677.67834472656,"mass":696948.6875,"built":{"mass":604701,"count":1617,"energy":7246160},"kills":{"mass":617190.3125,"count":1072,"energy":15738093},"lost":{"mass":1277372.75,"count":1553,"energy":26485212},"currentunits":{"count":39.999977111816},"energy":65637776,"lastReclaimedEnergy":0},"faction":4,"resources":{"massin":{"total":696948.6875,"rate":4.7250003814697},"energyout":{"total":38209488,"rate":49.799999237061},"energyin":{"total":65637776,"rate":750},"energyover":27422722,"massover":0,"massout":{"total":695656.6875,"rate":5.1000003814697}},"name":"Seraphim","units":{"air":{"lost":330,"kills":445,"built":333},"tech3":{"lost":648,"kills":392,"built":643},"cdr":{"lost":1,"kills":0,"built":1},"tech2":{"lost":622,"kills":407,"built":621},"tech1":{"lost":277,"kills":272,"built":347},"transportation":{"lost":0,"kills":81,"built":0},"land":{"lost":943,"kills":472,"built":930},"sacu":{"lost":0,"kills":0,"built":0},"structures":{"lost":225,"kills":121,"built":300},"engineer":{"lost":66,"kills":29,"built":58},"naval":{"lost":65,"kills":47,"built":66},"experimental":{"lost":5,"kills":1,"built":5}}},{"blueprints":{"uab3201":{"lost":3,"built":3},"uaa0302":{"built":26},"uea0302":{"kills":60},"ueb3202":{"kills":6},"uel0303":{"kills":128},"ueb3201":{"kills":1},"ueb2204":{"kills":10},"xal0305":{"lost":36,"built":36},"uab0302":{"lost":6,"built":6},"ual0201":{"lost":179,"built":179},"uea0203":{"kills":6},"uab2204":{"lost":26,"built":26},"ueb2304":{"kills":44},"uab2101":{"lost":22,"built":22},"uab3101":{"lost":3,"built":3},"uab2109":{"lost":6,"built":6},"ueb1101":{"kills":14},"uab0303":{"lost":1,"built":1},"uab2304":{"lost":24,"built":24},"zab9603":{"lost":2,"built":2},"ues0201":{"kills":30},"uel0201":{"kills":6},"uaa0101":{"built":3},"ual0303":{"lost":15,"built":11},"uec1401":{"kills":17},"uec1301":{"kills":5},"ueb1105":{"kills":6},"zab9502":{"lost":6,"built":6},"ueb2301":{"kills":12},"ual0103":{"lost":24,"built":24},"uab0202":{"lost":2,"built":2},"ueb1106":{"kills":5},"uab0301":{"lost":4,"built":4},"uea0304":{"kills":414},"uaa0304":{"built":10},"uec1101":{"kills":79},"ueb1202":{"kills":3},"uab0201":{"lost":2,"built":2},"uab5202":{"lost":11,"built":10},"uel0105":{"kills":5},"zab9601":{"lost":6,"built":6},"ual0101":{"lost":16,"built":16},"uea0003":{"kills":6},"uab0102":{"built":1},"ual0309":{"lost":123,"built":103},"uaa0104":{"built":19},"uea0102":{"built":4},"uab1102":{"lost":2,"built":2},"uab4302":{"lost":2,"built":2},"uas0401":{"lost":2},"uec1201":{"kills":16},"ueb1201":{"kills":4},"ueb0304":{"kills":10},"ueb4202":{"kills":5},"uel0103":{"kills":3},"uas0103":{"lost":14,"built":14},"xaa0202":{"lost":2,"built":186},"uab1302":{"lost":25,"built":24},"ual0401":{"lost":4,"built":4},"uab2104":{"lost":18,"built":18},"xal0203":{"lost":81,"built":80},"ueb2101":{"kills":16},"uab1201":{"lost":13,"built":12},"uab1301":{"lost":23,"built":18},"ual0208":{"lost":13,"built":8},"ual0001":{"lost":1,"built":1,"lowest_health":0},"ueb1303":{"kills":1},"uel0208":{"kills":53},"uel0307":{"kills":22},"ual0104":{"lost":11,"built":11},"uab2303":{"lost":13,"built":13},"uab2205":{"lost":2,"built":2},"zab9501":{"lost":5,"built":5},"uaa0310":{"lost":1},"uab4301":{"lost":7,"built":7},"xaa0305":{"lost":9,"built":57},"uab2302":{"lost":1,"built":1},"xaa0306":{"built":6},"ual0301":{"lost":1,"built":1},"ual0304":{"lost":6,"built":6},"xas0204":{"lost":5,"built":5},"uab1106":{"lost":83,"built":83},"uab1103":{"lost":1,"built":1},"ual0106":{"lost":24,"built":24},"uab5101":{"lost":34,"built":145},"uab1202":{"lost":1,"built":1},"ues0202":{"kills":7},"uea0305":{"kills":377},"uas0202":{"lost":7,"built":7},"dalk003":{"lost":8,"built":8},"uas0302":{"lost":7,"built":7},"uaa0303":{"built":82},"ual0111":{"lost":16,"built":16},"uab1104":{"lost":31,"built":29},"ueb4301":{"kills":2},"uab4201":{"lost":3,"built":3},"uab3102":{"lost":3,"built":3},"uab3104":{"lost":1,"built":1},"ual0202":{"lost":108,"built":104},"ueb3101":{"kills":1},"uel0106":{"kills":8},"uab4202":{"lost":7,"built":7},"ual0205":{"lost":77,"built":77},"uab1303":{"lost":7,"built":7},"uas0203":{"lost":17,"built":17},"uaa0203":{"lost":12,"built":856},"uaa0103":{"built":238},"xel0305":{"kills":82},"uab1101":{"lost":76,"built":74},"uas0102":{"lost":3,"built":3},"uea0303":{"kills":263},"ual0307":{"lost":11,"built":10},"uaa0102":{"built":67},"uas0201":{"lost":14,"built":11},"uab2301":{"lost":24,"built":24},"uab1105":{"lost":50,"built":50},"del0204":{"kills":19},"zab9602":{"lost":15,"built":15},"uec1501":{"kills":4},"uel0205":{"kills":50}},"type":"AI","general":{"score":729910,"currentcap":{"count":1000},"lastReclaimedMass":15707.990234375,"mass":797232.125,"built":{"mass":394349,"count":3008,"energy":7533160},"kills":{"mass":355339.125,"count":482,"energy":15683269},"lost":{"mass":1429284.625,"count":2960,"energy":31714592},"currentunits":{"count":11.100006103516},"energy":42746408,"lastReclaimedEnergy":0},"faction":2,"resources":{"massin":{"total":797232.125,"rate":0},"energyout":{"total":19725160,"rate":0},"energyin":{"total":42746408,"rate":0},"energyover":23025938,"massover":323671.8125,"massout":{"total":473563.4375,"rate":0}},"name":"Order","units":{"air":{"lost":1595,"kills":205,"built":1584},"tech3":{"lost":510,"kills":249,"built":471},"cdr":{"lost":1,"kills":0,"built":1},"tech2":{"lost":1533,"kills":121,"built":1514},"tech1":{"lost":909,"kills":58,"built":1018},"transportation":{"lost":19,"kills":4,"built":19},"land":{"lost":771,"kills":201,"built":736},"sacu":{"lost":1,"kills":0,"built":1},"structures":{"lost":571,"kills":119,"built":671},"engineer":{"lost":138,"kills":23,"built":113},"naval":{"lost":72,"kills":11,"built":67},"experimental":{"lost":7,"kills":0,"built":4}}},{"blueprints":{"xaa0202":{"kills":24},"uaa0302":{"kills":7},"uea0302":{"built":3},"ueb3202":{"built":2},"uel0303":{"lost":77,"built":125},"ueb3201":{"lost":5,"built":10},"ueb2204":{"lost":16,"built":41},"uaa0203":{"kills":76},"ueb4302":{"built":1},"xel0305":{"lost":8,"built":25},"xsl0201":{"kills":111},"ueb2304":{"lost":7,"built":10},"ueb2104":{"lost":2,"built":6},"uab2104":{"kills":2},"ueb1101":{"lost":5,"built":10},"ueb2101":{"lost":11,"built":17},"uel0201":{"lost":4,"built":36},"uaa0101":{"kills":2},"ual0303":{"kills":6},"xsb1302":{"kills":1},"xsl0205":{"kills":197},"ual0103":{"kills":13},"xsl0401":{"kills":28},"uaa0304":{"kills":42},"ueb0301":{"built":2},"xsa0103":{"kills":2},"ual0101":{"kills":8},"xsl0111":{"kills":163},"xsa0303":{"kills":122},"uel0103":{"lost":43,"built":86},"uel0309":{"lost":27,"built":75},"ues0203":{"built":6},"ueb1201":{"lost":14,"built":27},"xsb2204":{"kills":1},"ueb0304":{"built":1},"xsb2301":{"kills":3},"uab1105":{"kills":2},"ueb1302":{"built":18},"uab1301":{"kills":4},"uec1501":{"kills":2},"zsb9601":{"kills":29},"ueb1303":{"built":8},"ueb2303":{"built":2},"uel0307":{"lost":6,"built":8},"ueb5202":{"built":5},"ual0202":{"kills":67},"ueb1301":{"built":15},"xea0306":{"built":3},"uea0303":{"built":108},"uab4301":{"kills":1},"uea0102":{"built":108},"xsa0302":{"kills":13},"zeb9501":{"lost":6,"built":11},"xsa0304":{"kills":8},"uea0203":{"built":102},"uel0202":{"lost":91,"built":168},"xsl0303":{"kills":1139},"zeb9602":{"lost":1,"built":9},"ual0106":{"kills":20},"ueb3104":{"built":1},"xsa0204":{"kills":3},"uec1101":{"kills":2},"ueb4301":{"lost":3,"built":12},"uea0305":{"built":67},"ueb5101":{"lost":48,"built":494},"xsl0202":{"kills":197},"uaa0303":{"kills":29},"ual0111":{"kills":26},"xsa0202":{"kills":4},"uel0104":{"lost":15,"built":46},"ueb3101":{"lost":1,"built":3},"uel0111":{"lost":25,"built":92},"xsl0309":{"kills":46},"xsa0203":{"kills":203},"xsl0103":{"kills":71},"ual0201":{"kills":30},"ueb0302":{"built":2},"ueb4202":{"lost":6,"built":11},"uel0208":{"lost":2,"built":3},"xsb1106":{"kills":2},"zeb9601":{"lost":6,"built":16},"uaa0103":{"kills":1},"uel0106":{"lost":20,"built":26},"xec1301":{"built":1},"uea0103":{"built":80},"uaa0104":{"kills":8},"uec1301":{"kills":1},"uaa0102":{"kills":6},"xel0306":{"lost":1,"built":8},"xsl0305":{"kills":1},"ueb1105":{"built":30},"ueb1106":{"built":34},"ueb2301":{"lost":18,"built":55},"xsb4201":{"kills":5},"uel0205":{"lost":49,"built":104}},"type":"AI","general":{"score":1055134,"currentcap":{"count":1500},"lastReclaimedMass":3099.4792480469,"mass":610631.25,"built":{"mass":407748,"count":2133,"energy":11537612},"kills":{"mass":316659.03125,"count":693,"energy":5319621},"lost":{"mass":293377.1875,"count":894,"energy":8778801},"currentunits":{"count":803.80206298828},"energy":61423772,"lastReclaimedEnergy":592.5},"faction":1,"resources":{"massin":{"total":610631.25,"rate":36.350002288818},"energyout":{"total":33768212,"rate":2080.0119628906},"energyin":{"total":61423772,"rate":3936.8959960938},"energyover":27538914,"massover":163467.015625,"massout":{"total":421858.0625,"rate":18.088394165039}},"name":"UEF","units":{"air":{"lost":378,"kills":114,"built":482},"tech3":{"lost":263,"kills":245,"built":509},"cdr":{"lost":0,"kills":0,"built":0},"tech2":{"lost":327,"kills":260,"built":636},"tech1":{"lost":304,"kills":186,"built":987},"transportation":{"lost":89,"kills":4,"built":105},"land":{"lost":380,"kills":571,"built":832},"sacu":{"lost":0,"kills":0,"built":0},"structures":{"lost":149,"kills":17,"built":854},"engineer":{"lost":29,"kills":21,"built":78},"naval":{"lost":0,"kills":0,"built":6},"experimental":{"lost":0,"kills":2,"built":0}}},{"blueprints":{"ueb3202":{"built":2},"uel0303":{"built":4},"xec8010":{"lost":1,"built":5},"xsa0203":{"built":10},"uaa0203":{"kills":3,"built":12},"ual0201":{"kills":27},"uea0203":{"built":8},"ueb2304":{"built":11},"ueb2104":{"built":1},"ueb1101":{"lost":6,"built":43},"xec8012":{"built":8},"ueb2101":{"lost":4,"built":7},"uel0201":{"built":5},"uec1101":{"lost":48,"built":82},"ueb1105":{"built":13},"zeb9502":{"built":2},"uec1501":{"lost":5,"built":16},"ueb1202":{"lost":1,"built":1},"xsa0103":{"built":9},"ual0101":{"kills":1},"ueb2109":{"built":8},"xec8002":{"lost":8,"built":21},"uec1201":{"lost":7,"built":13},"ueb0102":{"built":2},"ueb1201":{"built":7},"xec8001":{"built":42},"ueb0101":{"built":8},"ueb4202":{"built":3},"uel0208":{"built":3},"zeb9501":{"built":8},"uel0202":{"built":14},"zeb9602":{"built":1},"ual0106":{"kills":2},"ueb3104":{"built":2},"ueb4301":{"built":4},"uec1401":{"lost":9,"built":24},"ueb5101":{"lost":12,"built":172},"ueb1104":{"built":6},"uaa0303":{"built":3},"uel0103":{"built":3},"ueb1102":{"built":1},"ueb1106":{"lost":3,"built":14},"xec8003":{"lost":9,"built":117},"uaa0103":{"kills":10,"built":6},"uel0111":{"built":7},"uec0001":{"built":16},"ueb3101":{"lost":1,"built":3},"ueb3201":{"built":1},"xec8004":{"lost":4,"built":133},"ueb2204":{"lost":2,"built":13},"uel0104":{"built":14},"xel0305":{"built":4},"xec8009":{"built":9},"xsl0303":{"built":3},"xsl0201":{"built":10},"ueb1303":{"built":1},"uea0102":{"built":5},"xsl0202":{"built":5},"uec1301":{"lost":7,"built":12},"uaa0102":{"kills":1,"built":2},"xsl0111":{"built":5},"ueb5202":{"built":1},"zeb9601":{"built":1},"zeb9603":{"built":3},"ueb2301":{"lost":4,"built":30},"xec8011":{"built":6},"uel0205":{"built":11}},"type":"AI","general":{"score":8,"currentcap":{"count":500},"lastReclaimedMass":0,"mass":569.59777832031,"built":{"mass":0,"count":1016,"energy":0},"kills":{"mass":2262,"count":31,"energy":33880},"lost":{"mass":12639,"count":131,"energy":47690},"currentunits":{"count":305},"energy":2331.0834960938,"lastReclaimedEnergy":0},"faction":1,"resources":{"massin":{"total":569.59777832031,"rate":0},"energyout":{"total":323.99890136719,"rate":0},"energyin":{"total":2331.0834960938,"rate":0},"energyover":2007.0792236328,"massover":569.60070800781,"massout":{"total":0,"rate":0}},"name":"Civilians","units":{"air":{"lost":0,"kills":10,"built":60},"tech3":{"lost":0,"kills":0,"built":37},"cdr":{"lost":0,"kills":0,"built":0},"tech2":{"lost":7,"kills":2,"built":148},"tech1":{"lost":26,"kills":29,"built":343},"transportation":{"lost":0,"kills":0,"built":8},"land":{"lost":98,"kills":21,"built":609},"sacu":{"lost":0,"kills":0,"built":0},"structures":{"lost":131,"kills":0,"built":857},"engineer":{"lost":0,"kills":0,"built":3},"naval":{"lost":0,"kills":0,"built":3},"experimental":{"lost":0,"kills":0,"built":0}}},{"blueprints":{"ueb0304":{"built":1},"uaa0302":{"kills":88},"uel0303":{"lost":3,"built":3},"xsb2302":{"kills":3},"ueb0203":{"built":1},"ueb2204":{"built":2},"ueb0302":{"built":1},"ueb4302":{"built":1},"xsb1106":{"kills":63},"ueb2304":{"lost":2,"built":13},"ueb5202":{"lost":1,"built":5},"xsb1303":{"kills":7},"xss0202":{"kills":12},"xss0203":{"kills":3},"xsb2205":{"kills":3},"ueb0202":{"built":1},"xsl0205":{"kills":27},"uab1105":{"kills":40},"uab0301":{"kills":18},"uab0201":{"kills":12},"xsl0111":{"kills":41},"xss0304":{"kills":8},"xsb4301":{"kills":6},"ueb0303":{"built":1},"xsb4201":{"kills":4},"xsb2204":{"kills":58},"ual0401":{"kills":24},"xsb2301":{"kills":17},"zsb9501":{"kills":2},"uab1303":{"kills":12},"ueb4202":{"built":7},"uel0208":{"lost":12,"built":33},"uel0307":{"lost":44,"built":56},"ual0104":{"kills":8},"uel0001":{"built":1,"lowest_health":12000},"uaa0310":{"kills":9},"uab4301":{"kills":2},"xsa0302":{"kills":41},"zeb9501":{"lost":2,"built":3},"ual0202":{"kills":262},"uea0305":{"lost":11,"built":113},"xas0204":{"kills":15},"xsb0301":{"kills":1},"ues0202":{"lost":13,"built":20},"dalk003":{"kills":16},"xsl0309":{"kills":25},"xsl0103":{"kills":33},"ual0205":{"kills":141},"uab1101":{"kills":75},"uea0102":{"kills":21},"uea0303":{"built":133},"uea0003":{"lost":6,"built":20},"zab9601":{"kills":19},"uas0201":{"kills":25},"uab2301":{"kills":166},"ueb1106":{"built":8},"uea0104":{"built":2},"uab3201":{"kills":1},"uea0302":{"built":3},"xsb2303":{"kills":19},"uel0301_BubbleShield":{"built":1},"xsa0203":{"kills":325},"xsb1301":{"kills":22},"uab0302":{"kills":16},"ual0201":{"kills":37},"xsl0201":{"kills":21},"uab2204":{"kills":87},"xaa0306":{"kills":55},"uab2101":{"kills":80},"uab3101":{"kills":2},"ueb1101":{"lost":4,"built":4},"uab5202":{"kills":5},"uab2304":{"kills":100},"ues0201":{"lost":41,"built":56},"ual0303":{"kills":9},"xsb1302":{"kills":32},"uel0301_RAS":{"built":14},"zab9502":{"kills":11},"ual0103":{"kills":26},"ueb0201":{"built":1},"xsl0401":{"kills":60},"uaa0304":{"kills":78},"ueb0301":{"built":1},"xss0201":{"kills":114},"uel0105":{"lost":3,"built":11},"xsb3104":{"kills":1},"ual0101":{"kills":3},"ual0309":{"kills":116},"xsb2305":{"kills":1},"xsa0303":{"kills":322},"uas0302":{"kills":16},"xsb3101":{"kills":2},"zsb9502":{"kills":16},"xsb1105":{"kills":11},"xaa0202":{"kills":407},"ueb0103":{"built":1},"uab1302":{"kills":70},"ueb0102":{"built":1},"uas0103":{"kills":17},"uel0309":{"built":15},"uab1301":{"kills":40},"ueb0101":{"built":4},"uab1102":{"kills":1},"xss0103":{"kills":44},"xsb2304":{"kills":18},"ueb1302":{"built":2},"ues0302":{"lost":5,"built":6},"ual0208":{"kills":5},"ual0001":{"kills":13},"ueb1303":{"built":2},"ual0301":{"kills":7},"xss0302":{"kills":58},"xsb0303":{"kills":1},"uab2303":{"kills":56},"uab4202":{"kills":4},"zab9501":{"kills":33},"uas0401":{"kills":1},"zsb9603":{"kills":11},"xel0305":{"lost":94,"built":129},"uab2302":{"kills":1},"xal0305":{"kills":33},"xsb4203":{"kills":2},"xss0303":{"kills":5},"xsb4302":{"kills":26},"uab1106":{"kills":35},"uab1103":{"kills":1},"ual0106":{"kills":1},"ueb3104":{"lost":1,"built":1},"xaa0305":{"kills":407},"ueb4301":{"lost":2,"built":10},"zeb9601":{"built":6},"uas0202":{"kills":15},"uab2104":{"kills":17},"uaa0203":{"kills":1399},"uaa0303":{"kills":399},"ual0111":{"kills":28},"uab1104":{"kills":13},"xsl0303":{"kills":531},"uel0401":{"lost":1,"built":2},"xsl0202":{"kills":131},"zab9602":{"kills":26},"xsa0304":{"kills":310},"uab0202":{"kills":8},"uab1202":{"kills":2},"ues0304":{"built":7},"xsl0305":{"kills":7},"ueb1301":{"built":4},"zeb9603":{"built":1},"xsb5202":{"kills":1},"uaa0103":{"kills":125},"xsb3202":{"kills":27},"uab4302":{"kills":1},"ual0304":{"kills":9},"uaa0104":{"kills":101},"ual0307":{"kills":10},"uaa0102":{"kills":36},"zsb9601":{"kills":9},"uas0203":{"kills":25},"uab1201":{"kills":20},"xal0203":{"kills":31},"ueb2301":{"built":5},"delk002":{"lost":8,"built":8},"uel0205":{"lost":87,"built":111}},"type":"Human","general":{"score":2831887,"currentcap":{"count":500},"lastReclaimedMass":165148.015625,"mass":1186150.25,"built":{"mass":999722,"count":811,"energy":21451610},"kills":{"mass":1343946.5,"count":2065,"energy":31410596},"lost":{"mass":536806,"count":515,"energy":12936780},"currentunits":{"count":286},"energy":91181512,"lastReclaimedEnergy":677.29998779297},"faction":1,"resources":{"massin":{"total":1186150.25,"rate":23.400003433228},"energyout":{"total":60690756,"rate":1276.9666748047},"energyin":{"total":91181512,"rate":2782},"energyover":29622952,"massover":23019.23046875,"massout":{"total":1140405.5,"rate":6.0416665077209}},"name":"Katharsas","units":{"air":{"lost":192,"kills":969,"built":254},"tech3":{"lost":301,"kills":598,"built":476},"cdr":{"lost":0,"kills":1,"built":1},"tech2":{"lost":199,"kills":1072,"built":298},"tech1":{"lost":14,"kills":389,"built":34},"transportation":{"lost":0,"kills":12,"built":2},"land":{"lost":254,"kills":670,"built":399},"sacu":{"lost":0,"kills":1,"built":15},"structures":{"lost":12,"kills":347,"built":87},"engineer":{"lost":21,"kills":111,"built":75},"naval":{"lost":59,"kills":95,"built":93},"experimental":{"lost":1,"kills":5,"built":2}}}]}
info: syncing max ping markers: \00015
info: Block is too late ! 
info: terminated 
debug: OpenMovie /movies/menu_background.sfd: 264425
debug: Preparing movie /movies/menu_background.sfd: 264425
debug: Preparing movie /movies/menu_background.sfd: 264425
debug: Preparing movie /movies/menu_background.sfd: 264425
debug: Preparing movie /movies/menu_background.sfd: 264425
debug: Preparing movie /movies/menu_background.sfd: 264425
debug: Preparing movie /movies/menu_background.sfd: 264425
debug: OpenMovie /movies/X01_Hall_DB01_04018.sfd: 264425
debug: Preparing movie /movies/X01_Hall_DB01_04018.sfd: 264425
debug: Preparing movie /movies/X01_Hall_DB01_04018.sfd: 264425
debug: Preparing movie /movies/X01_Hall_DB01_04018.sfd: 264425
debug: Preparing movie /movies/X01_Hall_DB01_04018.sfd: 264425
debug: Preparing movie /movies/X01_Hall_DB01_04018.sfd: 264425
debug: Preparing movie /movies/X01_Hall_DB01_04018.sfd: 264425
debug: Playing movie c:\program files (x86)\steam\steamapps\common\supreme commander forged alliance\movies\menu_background.sfd: 264425
debug: Playing movie c:\program files (x86)\steam\steamapps\common\supreme commander forged alliance\movies\x01_hall_db01_04018.sfd: 264433
info: GPGNET: setting nat handler to 0x00000000
info: CNetTCPBuf::Read(): recv() failed: WSAEINTR
info: Run time: 1h27m53s
```
</details>

**OS**
Windows

### PR DESCRIPTION
**Pull request by andreasley**
Fixes #1560 and probably also #1246.

Previously, only skirmish maps were added to the list of installed maps. This led to replays of coop missions not showing up.
This patch fixes this while retaining the filter for skirmish maps when creating a new game.

### CODE REVIEW

File: src/main/java/com/faforever/client/map/MapService.java [hunk 1]
```diff
@@ -303,25 +303,20 @@ public Image loadPreview(String mapName, PreviewSize previewSize) {
...
-          logger.debug("Found map {} locally", mapFolderName);
-          return Optional.of(mapBean);
-        }
-      }
+    String mapFolderKey = mapFolderName.toLowerCase();
+    if (!mapsByFolderName.containsKey(mapFolderKey)) {
+      return Optional.empty();
+    } else {
+      MapBean mapBean = mapsByFolderName.get(mapFolderKey);
+      return Optional.of(mapBean);
```
Comment (Geosearchef) [inline src/main/java/com/faforever/client/map/MapService.java]: I'd either remove the else, therefore having it as an abort condition or swap if and else around.

**Review by Geosearchef — DISMISSED** [review]
Looks good to me, are you sure installedMaps and mapsByName are kept im sync correctly?

**Comment by bukajsytlos** [comment]
or return Optional.ofNullable(map. getValue(key))

**Comment by andreasley** [comment]
> Looks good to me, are you sure installedMaps and mapsByName are kept im sync correctly?

Reasonably sure, as there's a change listener on `installedMaps` that updates `mapsByName`.

**Review by 1-alex98 — CHANGES_REQUESTED** [review]
What about the maps shon in the create game dialog do they now contain coop maps!!???

**Comment by andreasley** [comment]
> What about the maps shon in the create game dialog do they now contain coop maps!!???

No, of course not. :)

**Comment by 1-alex98** [comment]
True found the code for that

**Review by 1-alex98 — APPROVED** [review]

**Comment by 1-alex98** [comment]
tested it look good
