### PR TITLE
fix copy map name on create game window

### LINKED ISSUE #2687: Map name in Game Creation dialog map thumbnail is no longer right-clickable since the introduction of map zoom
Before we had [map zoom](https://github.com/FAForever/downlords-faf-client/pull/2641) in the Game creation dialog, one could right click the map name displayed on top of the thumbnail to copy it to clipboard, when that map was a generated one. This was useful in case i had to restart faf because my lobby broke (since restarting faf clears generated maps, i have to get that map name into the clipboard to be able to set the lobby back up fast). With the addition of map zoom, the right click functionality is gone, and instead the right click now behaves exactly like the left click, zooming in the map. This leaves no option for copying the map name of a generated map that's not associated with a replay except for hosting a game on that map and alt-tabbing to the faf client, then highlighting the lobby and right-clicking the map name in the lobby details on the right. Since sometimes broken lobbies disappear from the custom game list, even this option might not be available precisely when it's needed.

### PR DESCRIPTION
**Pull request by Marc-Spector**
Closes #2687

### CODE REVIEW

File: src/main/java/com/faforever/client/game/CreateGameController.java [hunk 1]
```diff
@@ -522,10 +525,20 @@ public void onMapFilterButtonClicked() {
...
+          .map(MapVersionBean::getFolderName)
+          .ifPresent(mapName -> PopupUtil.showImagePopup(mapService.loadPreview(mapName, PreviewSize.LARGE)));
+
+      // No other way to make same design without using StackPane class therefore we use this dirty hack
+    } else if (button == MouseButton.SECONDARY && mapNameLabel.getBoundsInParent().contains(mouseEvent.getX(), mouseEvent.getY())) {
+      contextMenuBuilder.newBuilder()
+          .addItem(CopyLabelMenuItem.class, mapNameLabel)
+          .build()
+          .show(mapNameLabel, mouseEvent.getScreenX(), mouseEvent.getScreenY());
+    }
```
Comment (Sheikah45) [inline src/main/java/com/faforever/client/game/CreateGameController.java]: Rather than complicating the onMapPreviewImageClicked, add a new function and assign it to onContextMenuRequested of the stackPane perhaps

**Review by Sheikah45 — APPROVED** [review]
