### PR TITLE
Fix chat user player status state updates

### LINKED ISSUE #2065: Chat user list is not updated correctly in many situations
**Describe the bug**
I'm noticing these issues on the TMM version of the client, but I think they may be issues with the base branch.

1. A player who left the game early shows up as still playing. This game had 4 players, and the other 3 do not show up as playing anymore.
image
The map is permanently stuck and persists when the player joins other games:
image

2. Players sometimes show up as chat only even though they are logged in. This issue goes away upon restarting the client, which indicates a problem with synchronizing state. You can see some players have flags which means they must be logged in to the lobby server:
image

3. Adding friends doesn't add them to the friends section, but does change the context menu entry to "remove friend". (I did not search for the player's name, I just found them in the list)

Related #2061

**OS**
Windows

**Wanna have the bug fixed quickly?**
Visit Issue hunt...
[Issue hunt](https://issuehunt.io/r/FAForever/downlords-faf-client)

### LINKED ISSUE #2066: Players sometimes show up as chat only even when logged in
Players sometimes show up as chat only even though they are logged in. This issue goes away upon restarting the client, which indicates a problem with synchronizing state. You can see some players have flags which means they must be logged in to the lobby server:
image

Related #2065

**To Reproduce**
Log in to the client, scroll down to the chat only section. Sometimes you will see people with flags down there.

**OS**
Windows

**Wanna have the bug fixed quickly?**
Visit Issue hunt...
[Issue hunt](https://issuehunt.io/r/FAForever/downlords-faf-client)

### LINKED ISSUE #2067: Player who leaves a game early still shows up as playing
A player who left the game early shows up as still playing. This game had 4 players, and the other 3 do not show up as playing anymore.
image
The map is permanently stuck and persists when the player joins other games:
image

Related #2065

**To Reproduce**
Start a game with a bunch of players. One person leaves early, and the game continues on. After the remaining players finish the game, the person who left early is still shown as playing.

**Log or error message**
This is my log file:

**Expected behavior**

**Screenshots**

**OS**
Linux or Windows

**Wanna have the bug fixed quickly?**
Visit Issue hunt...
[Issue hunt](https://issuehunt.io/r/FAForever/downlords-faf-client)

### PR DESCRIPTION
**Pull request by Sheikah45**
Fixes #2067 
Fixes #2066 
Fixes #2065
Fixes user color initialization

### CODE REVIEW

File: src/main/java/com/faforever/client/chat/ChatUserService.java [hunk 1]
```diff
@@ -38,114 +38,121 @@ public void afterPropertiesSet() {
...
+                      }
+                    })
+                );
+          } else {
+            chatChannelUser.setClan(null);
+          }
+        });
+      }
+    } else {
+      chatChannelUser.setClan(null);
```
Comment (1-alex98) [inline src/main/java/com/faforever/client/chat/ChatUserService.java]: Maybe we can refactor this since it is hardly readable anymore. Should be extracted into methods. Too many nesting

File: src/main/java/com/faforever/client/chat/ChatUserService.java [hunk 2]
```diff
@@ -38,114 +38,121 @@ public void afterPropertiesSet() {
...
-                    }
-                  })
-              );
-        } else {
-          chatChannelUser.setClan(null);
-          chatChannelUser.setClanTag(null);
-        }
-      });
+    if (chatChannelUser.isDisplayed()) {
+      if (chatChannelUser.getClan().isEmpty()) {
```
Comment (1-alex98) [inline src/main/java/com/faforever/client/chat/ChatUserService.java]:
```suggestion
      if (!chatChannelUser.getClan().isEmpty()) {
           return;
      }
```

Comment (1-alex98) [reply src/main/java/com/faforever/client/chat/ChatUserService.java]: Early return avoids another level of nesting

File: src/main/java/com/faforever/client/chat/ChatUserService.java [hunk 3]
```diff
@@ -38,114 +38,121 @@ public void afterPropertiesSet() {
...
-            Image avatar;
-            if (!Strings.isNullOrEmpty(player.getAvatarUrl())) {
-              avatar = avatarService.loadAvatar(player.getAvatarUrl());
-            } else {
-              avatar = null;
-            }
-            Platform.runLater(() -> {
-              chatChannelUser.setAvatar(avatar);
+    if (chatChannelUser.isDisplayed()) {
+      if (chatChannelUser.getAvatar().isEmpty()) {
```
Comment (1-alex98) [inline src/main/java/com/faforever/client/chat/ChatUserService.java]:
```suggestion
      if (!chatChannelUser.getAvatar().isEmpty()) {
          return;
      }
```

File: src/main/java/com/faforever/client/chat/ChatUserService.java [hunk 4]
```diff
@@ -38,114 +38,121 @@ public void afterPropertiesSet() {
...
   public void populateCountry(ChatChannelUser chatChannelUser) {
-    if (chatChannelUser.getCountryFlag().isEmpty()) {
-      chatChannelUser.getPlayer()
-          .ifPresent(player -> {
-            Optional<Image> countryFlag = countryFlagService.loadCountryFlag(player.getCountry());
-            Platform.runLater(() -> {
-              chatChannelUser.setCountryFlag(countryFlag.orElse(null));
-              chatChannelUser.setCountryName(i18n.getCountryNameLocalized(player.getCountry()));
+    if (chatChannelUser.isDisplayed()) {
+      if (chatChannelUser.getCountryFlag().isEmpty()) {
```
Comment (1-alex98) [inline src/main/java/com/faforever/client/chat/ChatUserService.java]: early return -> less nesting

File: src/main/java/com/faforever/client/chat/ChatUserService.java [hunk 5]
```diff
@@ -38,114 +38,121 @@ public void afterPropertiesSet() {
...
+            if (status != PlayerStatus.IDLE) {
+              mapImage = mapService.loadPreview(player.getGame().getMapFolderName(), PreviewSize.SMALL);
+            } else {
+              mapImage = null;
+            }
+            Platform.runLater(() -> {
+              chatChannelUser.setStatusTooltipText(i18n.get(status.getI18nKey()));
+              chatChannelUser.setGameStatusImage(playerStatusImage);
+              chatChannelUser.setMapImage(mapImage);
+            });
```
Comment (1-alex98) [inline src/main/java/com/faforever/client/chat/ChatUserService.java]:
```suggestion
            setImages()
```

File: src/main/java/com/faforever/client/chat/ChatUserService.java [hunk 6]
```diff
@@ -38,114 +38,121 @@ public void afterPropertiesSet() {
...
             });
-          });
+      }
+    } else {
+      chatChannelUser.setCountryFlag(null);
+      chatChannelUser.setCountryName(null);
     }
   }
 
   public void populateGameStatus(ChatChannelUser chatChannelUser) {
```
Comment (1-alex98) [inline src/main/java/com/faforever/client/chat/ChatUserService.java]: Miss leading name also does other things

**Review by 1-alex98 — CHANGES_REQUESTED** [review]
Looks nice
