### PR TITLE
Fix for #294 (PlayerTooltip missing)

### LINKED ISSUE #294: Player tooltip is broken in chat user list
It's just empty

### PR DESCRIPTION
**Pull request by Brutus5000**
Uses the existing PlayerCardTooltip, even though it doesn't add much information.

Note: clan tags still show an empty popup!

(Connects to #294 - waffle.io)

### CODE REVIEW

File: src/main/java/com/faforever/client/chat/ChatUserItemController.java [hunk 1]
```diff
@@ -311,6 +312,20 @@ void onMouseEnterGameStatus() {
   }
 
   @FXML
+  void onMouseEnterUsername() {
+    if (playerInfoBean.getChatOnly()) {
+      return;
+    } else {
```
Comment (micheljung) [inline src/main/java/com/faforever/client/chat/ChatUserItemController.java]: Bei einem `return;` ist das `} else {` überflüssig

File: src/main/java/com/faforever/client/chat/ChatUserItemController.java [hunk 2]
```diff
@@ -311,6 +312,20 @@ void onMouseEnterGameStatus() {
...
+      PlayerCardTooltipController playerCardTooltipController = applicationContext.getBean(PlayerCardTooltipController.class);
+      playerCardTooltipController.setPlayer(playerInfoBean);
+
+      Tooltip statusTooltip = new Tooltip();
+      statusTooltip.setGraphic(playerCardTooltipController.getRoot());
+      Tooltip.install(usernameLabel, statusTooltip);
+    }
```
Comment (micheljung) [inline src/main/java/com/faforever/client/chat/ChatUserItemController.java]: This installs a tooltip on every mouse-over, even if it has already been installed.

Also, there already is a tooltip installed. See `configureTooltip()`
