### PR TITLE
Tooltip memory leak fix

### LINKED ISSUE #1462: Potential Tooltip memory problem
Current speculation:

If a tooltip is installed on a certain game row/tile (because that game was the last game the user hovered over to show a tooltip), then:
Whenever a lobby game changes (any change, inlcuding team composition / position, ...), additional nodes are evicted from scene graph but cannot be garbage collected until user hovers over another game to show another tooltip. If the game gets closed, the "leaked" nodes will not increase but also not get collected until user hovers over different game.

This means:
- Long lobby sim potentially creates lots of node garbage that is not collected by GC

Data:
single player in lobby, 100 slot/observer changes => 400 direct Labels nodes: 6 in scenegraph, 396 dead and not collectable by GC (were in scenegraph at some point of time, will become collectable once new row is hovered)

### PR DESCRIPTION
**Pull request by Katharsas**
Fixes #1462

### CODE REVIEW

File: src/main/java/com/faforever/client/fx/JavaFxUtil.java [hunk 1]
```diff
@@ -129,7 +129,7 @@ public static void fixTooltipDuration() {
    */
   public static Tooltip createCustomTooltip(Node content) {
     Tooltip tooltip = new Tooltip();
-    PopupWindowHelper.getContent(tooltip).setAll(content);
+    PopupWindowHelper.getContent(tooltip).setAll(content);// effectively calls tooltip.getContent.setAll()
```
Comment (1-alex98) [inline src/main/java/com/faforever/client/fx/JavaFxUtil.java]: remove

**Review by 1-alex98 — CHANGES_REQUESTED** [review]

**Review by 1-alex98 — APPROVED** [review]

**Review by Brutus5000 — APPROVED** [review]

**Review by 1-alex98 — APPROVED** [review]
