### PR TITLE
Rework/Fix game tiles

### LINKED ISSUE #945: "Play" Tab -> Table/Tile issues
Actual Issue:
In Tile view, checking/unchecking "Show password protected" / "show game with mods" does not work. I have to switch to Table view and then back to Tile view to apply the checkbox changes.

Annoying but not an issue:
In Table view, when there are many mods in a lobby, i cannot see all mods - it only shows e.g. "mod1, mod2 and 3 more...". i have to switch to Tile view and then hover over the lobby - very unintuitive.

### PR DESCRIPTION
**Pull request by 1-alex98**
Fixes #945

### CODE REVIEW

File: src/main/java/com/faforever/client/game/GameService.java [hunk 1]
```diff
@@ -625,4 +612,11 @@ private void removeGame(GameInfoMessage gameInfoMessage) {
       uidToGameInfoBean.remove(gameInfoMessage.getUid());
     }
   }
+
+  /**
+   * Can be used as a lock/monitor , so that the game service pauses the adding of new games
+   */
+  public ObservableMap<Integer, Game> getUidToInfoGameBean() {
+    return uidToGameInfoBean;
+  }
```
Comment (micheljung) [inline src/main/java/com/faforever/client/game/GameService.java]: Actually, any access on `uidToGameInfoBean` *must* be synchronized. Otherwise, you run into race conditions. Therefore, exposing this is dangerous and should be avoided.

Also, there are no spaces in front of commas but periods at the end of JavaDoc ;-)

If you need to expose it, you could return an immutable copy. If it's needed to e.g. add listeners to it, a method can be provided that adds listeners.

File: src/main/java/com/faforever/client/game/GamesTableController.java [hunk 2]
```diff
@@ -71,6 +75,9 @@ public GamesTableController(MapService mapService, JoinGameHelper joinGameHelper
     this.preferencesService = preferencesService;
 
     this.selectedGame = new SimpleObjectProperty<>();
+
+    modChangedListener = (observable, oldValue, newValue) -> modsColumn.setVisible(newValue);
+    passwordChangeListener = (observable, oldValue, newValue) -> passwordProtectionColumn.setVisible(newValue);
```
Comment (micheljung) [inline src/main/java/com/faforever/client/game/GamesTableController.java]: `modChangedListener` sounds like a mod has been changed. Better: `showModdedGamesChangedListener`.
And `showPasswordProtectedGamesChangedListener`

**Review by micheljung — CHANGES_REQUESTED** [review]

File: src/main/java/com/faforever/client/game/GameService.java (hunk 1 above)
Comment (1-alex98) [reply src/main/java/com/faforever/client/game/GameService.java]: I exposed it to use it as a monitor

**Comment by 1-alex98** [comment]
@Geosearchef would you review

File: src/main/java/com/faforever/client/game/GameService.java (hunk 1 above)
Comment (micheljung) [reply src/main/java/com/faforever/client/game/GameService.java]: Please check if there's a better way, this violates the Law of Demeter

File: src/main/java/com/faforever/client/game/GamesTilesContainerController.java [hunk 3]
```diff
@@ -60,15 +64,20 @@ public GamesTilesContainerController(UiService uiService, PreferencesService pre
...
-    gameListChangeListener = change -> Platform.runLater(() -> {
-      synchronized (change) {
+    gameListChangeListener = change -> {
+      Platform.runLater(() -> {
         while (change.next()) {
-          change.getRemoved().forEach(gameInfoBean -> tiledFlowPane.getChildren().remove(uidToGameCard.remove(gameInfoBean.getId())));
+          change.getRemoved().forEach(gameInfoBean -> {
+            boolean remove = tiledFlowPane.getChildren().remove(uidToGameCard.remove(gameInfoBean.getId()));
+            if (!remove) {
+              log.error("Tried to remove game tile that did not exist.");
```
Comment (micheljung) [inline src/main/java/com/faforever/client/game/GamesTilesContainerController.java:73]: Warn, not error

**Review by micheljung — CHANGES_REQUESTED** [review]
