### PR TITLE
Properly handle futures when the local replay directory has changed

### LINKED ISSUE #1541: Local replays sometimes fail to appear
The list of local replays should be reloaded automatically, starting with version 1.1.
For some reason, this doesn't always work, e.g. sometimes, new replays don't appear in the list.

### PR DESCRIPTION
**Pull request by andreasley**
Fixes #1541.

Previously, the code failed to properly wait on completion of futures that load replays. Depending on the timing, the new local replays may have been added correctly or not. This PR fixes that.

### CODE REVIEW

**Comment by axel1200** [comment]
unit tests?

File: src/main/java/com/faforever/client/replay/ReplayService.java [hunk 1]
```diff
@@ -201,8 +200,21 @@ private void onLocalReplaysWatchEvent(WatchKey key) {
       }
     }
 
-    localReplays.addAll(newReplays);
-    publisher.publishEvent(new LocalReplaysChangedEvent(this, newReplays, deletedReplays));
+    CompletableFuture[] replayFuturesArray = newReplaysFutures.toArray(new CompletableFuture[newReplaysFutures.size()]);
+    CompletableFuture<List<Replay>> newReplaysFuture = CompletableFuture.allOf(replayFuturesArray)
+        .thenApply(ignoredVoid ->
```
Comment (1-alex98) [inline src/main/java/com/faforever/client/replay/ReplayService.java:205]: thenRun

File: src/main/java/com/faforever/client/replay/ReplayService.java [hunk 2]
```diff
@@ -201,8 +200,21 @@ private void onLocalReplaysWatchEvent(WatchKey key) {
...
+            newReplaysFutures.stream()
+                .map(future -> future.join())
```
Comment (1-alex98) [inline src/main/java/com/faforever/client/replay/ReplayService.java]: CompletableFuture
        .allOf

**Review by 1-alex98 — CHANGES_REQUESTED** [review]

**Comment by 1-alex98** [comment]
Think about whether u could maybe add unit tests

File: src/main/java/com/faforever/client/replay/ReplayService.java (hunk 1 above)
Comment (andreasley) [reply src/main/java/com/faforever/client/replay/ReplayService.java:205]: Why?

File: src/main/java/com/faforever/client/replay/ReplayService.java (hunk 2 above)
Comment (andreasley) [reply src/main/java/com/faforever/client/replay/ReplayService.java]: What?

Comment (1-alex98) [reply src/main/java/com/faforever/client/replay/ReplayService.java]: To join CompletedFutures use CompletableFuture.allOf()

File: src/main/java/com/faforever/client/replay/ReplayService.java (hunk 1 above)
Comment (1-alex98) [reply src/main/java/com/faforever/client/replay/ReplayService.java:205]: Sorry i am wrong... but there is a method that takes a lambda without the parameter ignoredVoid. Use this method instead not totally sure whats it called thenCombine maybe

Comment (1-alex98) [reply src/main/java/com/faforever/client/replay/ReplayService.java:205]: ok whatever ignore me

File: src/main/java/com/faforever/client/replay/ReplayService.java (hunk 2 above)
Comment (andreasley) [reply src/main/java/com/faforever/client/replay/ReplayService.java]: Which is exactly what I'm doing. Hence my confusion. :)

Comment (1-alex98) [reply src/main/java/com/faforever/client/replay/ReplayService.java]: Should read the code closer sorry lemme check again

**Comment by 1-alex98** [comment]
I made a lot of shitty comments but somehting is wrong here what u are doing seems to be overly complecated

**Comment by andreasley** [comment]
> 
> 
> I made a lot of shitty comments but somehting is wrong here what u are doing seems to be overly complecated

It seems overly complicated to me, too, but that may just be because it's Java. ;)
Seriously though, wherever `CompletableFuture.allOf` is used in the codebase, it's exactly like this.
But if there's a better way, I'd love to learn.

File: src/main/java/com/faforever/client/replay/ReplayService.java [hunk 3]
```diff
@@ -201,8 +201,21 @@ private void onLocalReplaysWatchEvent(WatchKey key) {
...
```
Comment (1-alex98) [inline src/main/java/com/faforever/client/replay/ReplayService.java]: use method reference
```suggestion
                CompletableFuture::join
```

**Review by 1-alex98 — CHANGES_REQUESTED** [review]

**Comment by 1-alex98** [comment]
Apart from this it is totally fine what u do it seems.
One more thing is that The @Async annotaion in line 291 needs to be removed it is just bullshit there. It only works if it is called via a Spring proxy Object which is obviously not the case here (not your fault) just noticed when I looked at the code. I did the two things for u and gonna make a quick commit. Thank you for your work 👍

File: src/main/java/com/faforever/client/replay/ReplayService.java [hunk 4]
```diff
@@ -205,7 +202,8 @@ protected void onLocalReplaysWatchEvent(WatchKey key) {
     CompletableFuture<List<Replay>> newReplaysFuture = CompletableFuture.allOf(replayFuturesArray)
         .thenApply(ignoredVoid ->
             newReplaysFutures.stream()
-                .map(future -> future.join())
+                .map(CompletableFuture::join)
+                .filter(Objects::nonNull)
```
Comment (1-alex98) [inline src/main/java/com/faforever/client/replay/ReplayService.java:208]: Well we wanna avoid having null objects in list because it crashes UI

File: src/main/java/com/faforever/client/replay/ReplayService.java [hunk 5]
```diff
@@ -275,21 +273,21 @@ static String guessModByFileName(String fileName) {
       List<CompletableFuture<Replay>> replayFutures = StreamSupport.stream(directoryStream.spliterator(), false)
           .sorted(Comparator.comparing(path -> noCatch(() -> Files.getLastModifiedTime((Path) path))).reversed())
           .limit(MAX_REPLAYS)
-          .map( replayFile -> tryLoadingLocalReplay(replayFile))
+          .map(this::tryLoadingLocalReplay)
```
Comment (1-alex98) [inline src/main/java/com/faforever/client/replay/ReplayService.java:278]: Just a quick way of writting it

File: src/main/java/com/faforever/client/replay/ReplayService.java [hunk 6]
```diff
@@ -275,21 +273,21 @@ static String guessModByFileName(String fileName) {
...
           .filter(e -> !e.isCompletedExceptionally())
           .collect(Collectors.toList());
 
       CompletableFuture[] replayFuturesArray = replayFutures.toArray(new CompletableFuture[replayFutures.size()]);
       return CompletableFuture.allOf(replayFuturesArray)
           .thenApply(ignoredVoid ->
               replayFutures.stream()
-                  .map(future -> future.join())
+                  .map(CompletableFuture::join)
+                  .filter(Objects::nonNull)
```
Comment (1-alex98) [inline src/main/java/com/faforever/client/replay/ReplayService.java:287]: again see top

File: src/main/java/com/faforever/client/replay/ReplayService.java [hunk 7]
```diff
@@ -300,14 +298,14 @@ static String guessModByFileName(String fileName) {
       return CompletableFuture.allOf(featuredModFuture, mapBeanFuture).thenApply(ignoredVoid  -> {
         Optional<MapBean> mapBean = mapBeanFuture.join();
         if (!mapBean.isPresent()) {
-          throw new CompletionException(new FileNotFoundException());
+          logger.warn("Could not find map for replay file '{}'", replayFile);
```
Comment (1-alex98) [inline src/main/java/com/faforever/client/replay/ReplayService.java:303]: We certainly dont wanna throw here if we do then the whole loacl replay vault breaks, also there are legimit cases where a replay has no map. One is coop the maps are part of the game mod and hence are not found locally nor on the server

File: src/main/java/com/faforever/client/replay/ReplayService.java [hunk 8]
```diff
@@ -300,14 +298,14 @@ static String guessModByFileName(String fileName) {
...
         }
-        return new Replay(replayInfo, replayFile, featuredModFuture.join(), mapBean.get());
+        return new Replay(replayInfo, replayFile, featuredModFuture.join(), mapBean.orElse(null));
```
Comment (1-alex98) [inline src/main/java/com/faforever/client/replay/ReplayService.java:305]: Let's just say the map is null

File: src/main/java/com/faforever/client/replay/ReplayService.java [hunk 9]
```diff
@@ -300,14 +298,14 @@ static String guessModByFileName(String fileName) {
...
       });
     } catch (Exception e) {
       logger.warn("Could not read replay file '{}'", replayFile, e);
       moveCorruptedReplayFile(replayFile);
-      return CompletableFuture.failedFuture(e);
+      return CompletableFuture.completedFuture(null);
```
Comment (1-alex98) [inline src/main/java/com/faforever/client/replay/ReplayService.java:310]: Don't throw others wise replay vault stays empty, return null which is gonna be filtered out

File: src/main/java/com/faforever/client/vault/replay/ReplayVaultController.java [hunk 10]
```diff
@@ -183,9 +177,12 @@ public OffsetDateTime fromString(String string) {
       protected void updateItem(MapBean map, boolean empty) {
         super.updateItem(map, empty);
 
-        if (empty || map == null) {
+        if (empty) {
           setText(null);
           setGraphic(null);
+        } else if (map == null) {
+          setGraphic(null);
+          setText(i18n.get("map.unknown"));
```
Comment (1-alex98) [inline src/main/java/com/faforever/client/vault/replay/ReplayVaultController.java:185]: Let's tell te user we don't have this map

**Review by 1-alex98 — DISMISSED** [review]

**Comment by 1-alex98** [comment]
So the local replay vault had quite some issues esspecially with coop replays those made the whole local replay vault to not display

**Comment by 1-alex98** [comment]
@andreasley maybe read and complain if you don't like something

**Review by 1-alex98 — DISMISSED** [review]

**Comment by andreasley** [comment]
> @andreasley maybe read and complain if you don't like something

@axel1200 Looks good to me.
Your comments looked like statements, not questions, so I didn't feel compelled to respond. :)

**Comment by 1-alex98** [comment]
No they are not questions, but still donot hesitate to ask if anything is unclear or u disagree.

**Comment by 1-alex98** [comment]
btw we are on discord if u wanna have a chatter :D
