### PR TITLE
Fix client freezing

### LINKED ISSUE #1036: Client freezes on startup
```
Stacks at 2018-11-13 07:22:47 PM. Uptime is 19m 23s 900ms.

JavaFX-Launcher State: WAITING CPU usage on sample: 0ms
jdk.internal.misc.Unsafe.park(boolean, long)
java.util.concurrent.locks.LockSupport.park(Object)
java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt()
java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedInterruptibly(int)
java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(int)
java.util.concurrent.CountDownLatch.await()
com.faforever.client.FafClientApplication$$Lambda$263.run()
com.github.nocatch.NoCatch.noCatch(NoCatch$NoCatchRunnable, Class) NoCatch.java:49
com.github.nocatch.NoCatch.noCatch(NoCatch$NoCatchRunnable) NoCatch.java:34
com.faforever.client.FafClientApplication.init() FafClientApplication.java:81
com.sun.javafx.application.LauncherImpl.launchApplication1(Class, Class, String[])
com.sun.javafx.application.LauncherImpl.lambda$launchApplication$2(Class, Class, String[], CountDownLatch)
com.sun.javafx.application.LauncherImpl$$Lambda$184.run()
java.lang.Thread.run()
``` 
The launcher thread is waiting forever. The fix from issue https://github.com/FAForever/downlords-faf-client/issues/1021 is not working as intended.

### PR DESCRIPTION
**Pull request by 1-alex98**
Fixes #1036

### CODE REVIEW

File: src/main/java/com/faforever/client/FafClientApplication.java [hunk 1]
```diff
@@ -70,13 +70,20 @@ public void init() {
...
       runAndWaitLatch.countDown();
-    });
+    };
+
+    if (!Platform.isFxApplicationThread()) {
+      //Dangerous if we are on Application Thread, because initRunnable will wait on runAndWaitLatch::await
+      Platform.runLater(initRunnable);
+    } else {
+      initRunnable.run();
+    }
```
Comment (micheljung) [inline src/main/java/com/faforever/client/FafClientApplication.java]: check JavaFxUtil.runLater()

**Review by micheljung — CHANGES_REQUESTED** [review]
