### PR TITLE
Fixes #468 toast position

### LINKED ISSUE #468: Notifications shown on wrong monitor
When using a multiple monitor setup, notifications are not always shown on the monitor, where the client is located. When the client is maximized on the primary monitor, all notifications show up in the bottom left of the second monitor (which is located right of the primary one in my case).

Maybe show them all on primary monitor/the monitor the client is located.

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/40865979-notifications-shown-on-wrong-monitor?utm_campaign=plugin&utm_content=tracker%2F14200913&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F14200913&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by axel1200**
Remodels Anchor Points

### CODE REVIEW

File: src/main/java/com/faforever/client/main/MainController.java [hunk 1]
```diff
@@ -476,4 +456,52 @@ public void onRevealLogFolder() {
...
+    private final TransientNotificationsController transientNotificationsController;
+
+    public PopupDisplayer(TransientNotificationsController transientNotificationsController) {
+      this.transientNotificationsController = transientNotificationsController;
+    }
+
+    @Override
+    public void invalidated(Observable observable) {
+      boolean enabled = preferencesService.getPreferences().getNotification().isTransientNotificationsEnabled();
+      if (!transientNotificationsController.getRoot().getChildren().isEmpty() && enabled) {
```
Comment (micheljung) [inline src/main/java/com/faforever/client/main/MainController.java]: Avoid nesting and long blocks; Invert condition, use early return

File: src/main/java/com/faforever/client/main/MainController.java [hunk 2]
```diff
@@ -476,4 +456,52 @@ public void onRevealLogFolder() {
...
+        Rectangle2D visualBounds = getTransientNotificationAreaBounds();
+        double anchorX = visualBounds.getMaxX() - 1, anchorY = visualBounds.getMaxY() - 1;
+        switch (preferencesService.getPreferences().getNotification().toastPositionProperty().get()) {
+          case BOTTOM_RIGHT: {
+            transientNotificationsPopup.setAnchorLocation(AnchorLocation.CONTENT_BOTTOM_RIGHT);
+          }
```
Comment (micheljung) [inline src/main/java/com/faforever/client/main/MainController.java]: We don't use blocks `{ }` in cases, but an empty line after `break;`

File: src/main/java/com/faforever/client/main/MainController.java [hunk 3]
```diff
@@ -476,4 +456,52 @@ public void onRevealLogFolder() {
...
+          case TOP_LEFT: {
+            transientNotificationsPopup.setAnchorLocation(AnchorLocation.CONTENT_TOP_LEFT);
+            anchorX = visualBounds.getMinX();
+            anchorY = visualBounds.getMinY();
+          }
+          break;
+          default: {
+            transientNotificationsPopup.setAnchorLocation(AnchorLocation.CONTENT_BOTTOM_RIGHT);
+          }
+          break;
```
Comment (micheljung) [inline src/main/java/com/faforever/client/main/MainController.java]: No need for `break;` in last condition

File: src/main/java/com/faforever/client/main/MainController.java [hunk 4]
```diff
@@ -481,6 +461,47 @@ public void onRevealLogFolder() {
     this.platformService.reveal(logPath);
   }
 
+  public class PopupDisplayer implements InvalidationListener {
```
Comment (micheljung) [inline src/main/java/com/faforever/client/main/MainController.java]: Move to file and rename to `ToastNotificator` or `TransientNotificator` as you like :)
