### PR TITLE
Catch runtime exception in generated map folder deletion

### LINKED ISSUE #1991: Client crashes if unable to delete map generator maps
**Describe the bug**
Catch the exception issue a warning. Sometimes AV keeps program from deleting maps. Should not keep us from starting.

**OS**
Windows

**Wanna have the bug fixed quickly?**
Visit Issue hunt...
[Issue hunt](https://issuehunt.io/r/FAForever/downlords-faf-client)

### PR DESCRIPTION
**Pull request by Sheikah45**
Fixes #1991

### CODE REVIEW

File: src/main/java/com/faforever/client/map/generator/MapGeneratorService.java [hunk 1]
```diff
@@ -113,6 +113,8 @@ private void deleteGeneratedMaps() {
             .forEach(p -> noCatch(() -> FileUtils.deleteRecursively(p)));
       } catch (IOException e) {
         log.error("Could not list custom maps directory for deleting leftover generated maps.", e);
+      } catch (RuntimeException e) {
+        log.error("Could not delete generated map folder");
```
Comment (1-alex98) [inline src/main/java/com/faforever/client/map/generator/MapGeneratorService.java:117]: Should we inform the user 🤔

**Review by 1-alex98 — APPROVED** [review]

File: src/main/java/com/faforever/client/map/generator/MapGeneratorService.java (hunk 1 above)
Comment (Sheikah45) [reply src/main/java/com/faforever/client/map/generator/MapGeneratorService.java:117]: We could I just followed how it handled not being able to list the custom maps directory. 
The only real reason to inform I think would be so that they could delete it themselves if they wanted to but not sure if necessary or depending on how often it happens might just be annoying.
