### PR TITLE
Fixed PlayerEvent hashmap collection for statistics graph plotting.

### LINKED ISSUE #3375: [Bug]: User Profile statistics graphs are empty
### Describe the Bug

Win/Loss per faction, Units built and Techs build graphs are empty on all viewed user profiles.

### Log file or Error Message

No error message or log file.

### Reproduce the bug

Click any user and select "Show user info" from the context menu (or view your own user profile by clicking your name in the client on the top right corner and selecting "Show profile") and click the Statistics tab.

### Expected Behavior

Graphs should be showing the statistics.

### Screenshots

Image

### Additional context

_No response_

### Which Operating System are you using?

Windows

### PR DESCRIPTION
**Pull request by Rogerstalker**
Fixes #3375 

Stats fixed

### CODE REVIEW

File: src/main/java/com/faforever/client/player/PlayerInfoWindowController.java [hunk 1]
```diff
@@ -235,7 +235,7 @@ public void setOnlinePlayer(PlayerInfo player) {
     onRatingTypeChange();
 
     loadAchievements();
-    eventService.getPlayerEvents(player.getId()).collectMap(PlayerEvent::getId).subscribe(events -> {
+    eventService.getPlayerEvents(player.getId()).collectMap(playerEvent->playerEvent.getEvent().getId()).subscribe(events -> {
```
Comment (Sheikah45) [inline src/main/java/com/faforever/client/player/PlayerInfoWindowController.java]:
```suggestion
    eventService.getPlayerEvents(player.getId()).collectMap(playerEvent -> playerEvent.getEvent().getId()).subscribe(events -> {
```

**Review by Sheikah45 — CHANGES_REQUESTED** [review]

**Review by Sheikah45 — APPROVED** [review]
