### PR TITLE
Fix mod more number on tiles

### LINKED ISSUE #1054: Don't display all mods in tile view
image

When there are more than 3 mods, it should say "MOD1, MOD2, and N more"

### PR DESCRIPTION
**Pull request by Sheikah45**
Fixes #1054

### CODE REVIEW

File: src/main/java/com/faforever/client/game/GameTileController.java [hunk 1]
```diff
@@ -119,7 +119,7 @@ private String getSimModsLabelContent(ObservableMap<String, String> simMods) {
         .collect(Collectors.toList());
 
     if (simMods.size() > 2) {
-      return i18n.get("game.mods.twoAndMore", modNames.get(0), modNames.size());
+      return i18n.get("game.mods.twoAndMore", modNames.get(0), simMods.size() - 1);
```
Comment (Brutus5000) [inline src/main/java/com/faforever/client/game/GameTileController.java]: Looking at the ticket I would have expected size-2

**Review by Brutus5000 — CHANGES_REQUESTED** [review]

File: src/main/java/com/faforever/client/game/GameTileController.java (hunk 1 above)
Comment (Sheikah45) [reply src/main/java/com/faforever/client/game/GameTileController.java]: Yeah me too but it was implemented to just show the first mod and then the number if there are more than two mods. I would guess because some mods have long names

Comment (Brutus5000) [reply src/main/java/com/faforever/client/game/GameTileController.java]: But then the if-statement makes no sense? Shouldn't that be > 1 then? And the i18n string is also misleading...

Comment (Sheikah45) [reply src/main/java/com/faforever/client/game/GameTileController.java]: Yeah I can change the string title. And if there are 2 then it shows both names if there are more than two it shows name and n more

**Review by Brutus5000 — APPROVED** [review]
