### PR TITLE
Fix the event handler for FriendJoinedGameEvent

### LINKED ISSUE #701: Implement "friend joined game" notification
Log says **2018-01-16 14:49:55.574  WARN 235776 --- [lication Thread] com.faforever.client.config.BaseConfig   : No event handler registered for event of type 'FriendJoinedGameEvent**

Implemt a FriendJoinedGameNotifier, like the FriendOnlineNotifier.

### PR DESCRIPTION
**Pull request by 20seven**
Removed an uninitialized sound and made sure that the user isn't notified several times for same event.
Fixes #701

### CODE REVIEW

File: src/main/java/com/faforever/client/audio/AudioServiceImpl.java [hunk 1]
```diff
@@ -142,7 +142,8 @@ public void playFriendJoinsGameSound() {
     if (!notificationsPrefs.isFriendJoinsGameSoundEnabled()) {
       return;
     }
-    playSound(friendJoinsGameSound);
+    // FIXME implement
```
Comment (1-alex98) [inline src/main/java/com/faforever/client/audio/AudioServiceImpl.java:145]: Why exactly did you delete it?

Comment (20seven) [reply src/main/java/com/faforever/client/audio/AudioServiceImpl.java:145]:
```
//    friendJoinsGameSound = loadSound(FRIEND_JOINS_GAME_SOUND);
```

That sound doesn't exist. I figured - since friendOffline, friendOnline, and friendPlaysGame are also sounds not implemented yet - it was either a work in progress or someone decided not to use the same sound as the others that are already implemented.

Comment (1-alex98) [reply src/main/java/com/faforever/client/audio/AudioServiceImpl.java:145]: Hmm ok

Comment (1-alex98) [reply src/main/java/com/faforever/client/audio/AudioServiceImpl.java:145]: Would you make an issue on that, if there is no one yet ;)

Comment (20seven) [reply src/main/java/com/faforever/client/audio/AudioServiceImpl.java:145]: issue made: #746

File: src/main/java/com/faforever/client/player/FriendJoinedGameNotifier.java [hunk 2]
```diff
@@ -30,15 +30,19 @@
   private final JoinGameHelper joinGameHelper;
   private final PreferencesService preferencesService;
   private final AudioService audioService;
+  private List<FriendJoinedGameEvent> eventList;
```
Comment (micheljung) [inline src/main/java/com/faforever/client/player/FriendJoinedGameNotifier.java]: Since it's initialized in the constructor and not meant to be changed, this should be `final`.

File: src/main/java/com/faforever/client/player/FriendJoinedGameNotifier.java [hunk 3]
```diff
@@ -49,11 +53,13 @@ void postConstruct() {
...
     Player player = event.getPlayer();
-    Game game = player.getGame();
+    Game game = event.getGame();
 
     audioService.playFriendJoinsGameSound();
 
-    if (preferencesService.getPreferences().getNotification().isFriendJoinsGameToastEnabled()) {
+    if (preferencesService.getPreferences().getNotification().isFriendJoinsGameToastEnabled()
+        && !eventList.contains(event)) {
+      eventList.add(event);
```
Comment (micheljung) [inline src/main/java/com/faforever/client/player/FriendJoinedGameNotifier.java]: Since the events are never removed from the list, this creates a memory leak. The notifier keeps a reference to all events, the events have a reference to the players and games, those have further references, preventing all these objects from being garbage collected.

I'm not sure why this was added; since each event is only fired exactly once, the `contains()` check should always return false. What happens if we just remove `eventList`?

File: src/main/java/com/faforever/client/player/FriendJoinedGameNotifier.java [hunk 4]
```diff
@@ -49,11 +53,13 @@ void postConstruct() {
   @Subscribe
   public void onFriendJoinedGame(FriendJoinedGameEvent event) {
     Player player = event.getPlayer();
-    Game game = player.getGame();
+    Game game = event.getGame();
```
Comment (micheljung) [inline src/main/java/com/faforever/client/player/FriendJoinedGameNotifier.java:52]: Not saying it's wrong, but why did you decide to add the game to the event, instead of reading it from the user?

I do see one reason why this is better, but I'd like to know what yours is :)

**Review by micheljung — CHANGES_REQUESTED** [review]

File: src/main/java/com/faforever/client/player/FriendJoinedGameNotifier.java (hunk 3 above)
Comment (20seven) [reply src/main/java/com/faforever/client/player/FriendJoinedGameNotifier.java]: You're right, should've thought further than that easy fix. 

I put it in because, no, it doesn't fire exactly once. In fact, it fires every time someone joins or leaves a game where you have a friend. It also fired each time any change was made to the game (gametitle change, swapped teams, added mods, etc.). If youre unlucky, you have two or more friends in there and it goes completely haywire.

This is how it looks when i befriended someone hosting a popular Gap-game:
sanchopanda joined game


But I've looked over the code in PlayerServiceImpl and worked out a fix (which makes eventList unnecessary)

File: src/main/java/com/faforever/client/player/FriendJoinedGameNotifier.java (hunk 4 above)
Comment (20seven) [reply src/main/java/com/faforever/client/player/FriendJoinedGameNotifier.java:52]: Well, I had some issues with how games were set to the player. After fixing that, I still think it's more reasonable and logical that the message about a player joining a game should contain exactly that information; the player and the game.

**Review by micheljung — APPROVED** [review]
