### PR TITLE
Correctly play coop replays

### LINKED ISSUE #1164: Coop replays are broken
Example replay: 9576247

Seems like it can't read the map properly.
It can be launched via python client without any issues.
```
java.util.concurrent.CompletionException: java.io.IOException: Server returned HTTP response code: 403 for URL: http://content.faforever.com/faf/vault/maps/.zip
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(Unknown Source)
	at com.faforever.client.task.CompletableTask.lambda$new$1(CompletableTask.java:17)
	at javafx.base/com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(Unknown Source)
	at javafx.base/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(Unknown Source)
	at javafx.base/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(Unknown Source)
	at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at javafx.base/com.sun.javafx.event.EventUtil.fireEventImpl(Unknown Source)
	at javafx.base/com.sun.javafx.event.EventUtil.fireEvent(Unknown Source)
	at javafx.base/javafx.event.Event.fireEvent(Unknown Source)
	at javafx.graphics/javafx.concurrent.EventHelper.fireEvent(Unknown Source)
	at javafx.graphics/javafx.concurrent.Task.fireEvent(Unknown Source)
	at javafx.graphics/javafx.concurrent.Task.setState(Unknown Source)
	at javafx.graphics/javafx.concurrent.Task$TaskCallable.lambda$call$2(Unknown Source)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$9(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$10(Unknown Source)
	at javafx.graphics/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(Unknown Source)
	at javafx.graphics/com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at javafx.graphics/com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.io.IOException: Server returned HTTP response code: 403 for URL: http://content.faforever.com/faf/vault/maps/.zip
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.base/java.lang.reflect.Constructor.newInstance(Unknown Source)
	at java.base/sun.net.www.protocol.http.HttpURLConnection$10.run(Unknown Source)
	at java.base/sun.net.www.protocol.http.HttpURLConnection$10.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getChainedException(Unknown Source)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
	at com.faforever.client.map.DownloadMapTask.call(DownloadMapTask.java:55)
	at com.faforever.client.map.DownloadMapTask.call(DownloadMapTask.java:22)
	at javafx.graphics/javafx.concurrent.Task$TaskCallable.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	... 1 more
Caused by: java.io.IOException: Server returned HTTP response code: 403 for URL: http://content.faforever.com/faf/vault/maps/.zip
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getHeaderField(Unknown Source)
	at java.base/java.net.URLConnection.getHeaderFieldLong(Unknown Source)
	at java.base/java.net.URLConnection.getContentLengthLong(Unknown Source)
	at java.base/java.net.URLConnection.getContentLength(Unknown Source)
	at com.faforever.client.map.DownloadMapTask.call(DownloadMapTask.java:51)
	... 6 more
```

### PR DESCRIPTION
**Pull request by CyrilPaulus**
Fixes #1164

### CODE REVIEW

**Comment by 1-alex98** [comment]
@micheljung you need  to review that i got no idea how replay files are structured

**Review by Brutus5000 — COMMENTED** [review]
The replay file should contain binary lua data. Shouldn't we be able to parse the lua instead of shifting around magic bytes?

**Comment by 1-alex98** [comment]
@Brutus5000 @micheljung does exactly the same to determine map names in replays (this magic byte thing I mean)

He needs to review this and judge if it is ok I guess

File: src/main/java/com/faforever/client/replay/ReplayService.java [hunk 1]
```diff
@@ -143,6 +143,24 @@ static String parseMapName(byte[] rawReplayBytes) {
...
+  static String parseCoopMapName(byte[] rawReplayBytes) {
+    // "ScenarioFile" in hex
+    byte[] startPattern = new byte[] {0x53, 0x63, 0x65, 0x6E, 0x61, 0x72, 0x69, 0x6F, 0x46, 0x69, 0x6C, 0x65, 0x00, 0x01};
+    int mapStartIndex = Bytes.indexOf(rawReplayBytes, startPattern) + startPattern.length;
+    int mapEndIndex = 0;
+
+    for (int i = mapStartIndex; i < rawReplayBytes.length - 1; i++) {
+      //0x00 0x01 is the field delimiter
+      if (rawReplayBytes[i] == 0x00 && rawReplayBytes[i+1] == 0x01)
+        break;
```
Comment (Geosearchef) [inline src/main/java/com/faforever/client/replay/ReplayService.java:160]: brackets

File: src/main/java/com/faforever/client/replay/ReplayService.java [hunk 2]
```diff
@@ -143,6 +143,24 @@ static String parseMapName(byte[] rawReplayBytes) {
...
+      mapEndIndex = i;
```
Comment (Geosearchef) [inline src/main/java/com/faforever/client/replay/ReplayService.java]: could be moved into the for block (`mapEndIndex = i++`)

File: src/main/java/com/faforever/client/replay/ReplayService.java [hunk 3]
```diff
@@ -374,6 +392,11 @@ private void runFafReplayFile(Path path) throws IOException {
     Map<String, Integer> modVersions = replayInfo.getFeaturedModVersions();
     String mapName = replayInfo.getMapname();
 
+    // For some reason in the coop replay the map name is null in the metadata
+    // So we just take it directly from the replay data.
+    if (gameType.equals("coop"))
+      mapName = parseCoopMapName(rawReplayBytes);
```
Comment (Geosearchef) [inline src/main/java/com/faforever/client/replay/ReplayService.java]: THAT IS AWESOME. Can we do that for generated maps pls? There the map is null aswell due to having no ID in the db.

File: src/main/java/com/faforever/client/replay/ReplayService.java [hunk 4]
```diff
@@ -143,6 +143,24 @@ static String parseMapName(byte[] rawReplayBytes) {
     return mapPath.split("/")[2];
   }
 
+  @VisibleForTesting
+  static String parseCoopMapName(byte[] rawReplayBytes) {
+    // "ScenarioFile" in hex
+    byte[] startPattern = new byte[] {0x53, 0x63, 0x65, 0x6E, 0x61, 0x72, 0x69, 0x6F, 0x46, 0x69, 0x6C, 0x65, 0x00, 0x01};
```
Comment (Geosearchef) [inline src/main/java/com/faforever/client/replay/ReplayService.java]: maybe move into class constant

**Review by Geosearchef — CHANGES_REQUESTED** [review]

File: src/main/java/com/faforever/client/replay/ReplayService.java [hunk 5]
```diff
@@ -143,6 +143,24 @@ static String parseMapName(byte[] rawReplayBytes) {
...
+
+    for (int i = mapStartIndex; i < rawReplayBytes.length - 1; i++) {
+      //0x00 0x01 is the field delimiter
+      if (rawReplayBytes[i] == 0x00 && rawReplayBytes[i+1] == 0x01)
+        break;
+      mapEndIndex = i;
+    }
+
+    String mapPath = new String(rawReplayBytes, mapStartIndex, mapEndIndex + 1 - mapStartIndex, US_ASCII);
+    return mapPath.split("/")[2];
```
Comment (johnhce) [inline src/main/java/com/faforever/client/replay/ReplayService.java:166]: Is the map name always after the second slash?  A comment showing the format would make it more readable.

**Comment by micheljung** [comment]
I know nothing about Lua in the binary. Whatever works best and is easier to understand.

**Comment by 1-alex98** [comment]
Well then maybe try to make some further java docs and if it works reliably it is fine

File: src/main/java/com/faforever/client/replay/ReplayService.java (hunk 3 above)
Comment (CyrilPaulus) [reply src/main/java/com/faforever/client/replay/ReplayService.java]: I'll need some sample of generated map to check that it can correctly parse the map name.

File: src/main/java/com/faforever/client/replay/ReplayService.java (hunk 5 above)
Comment (CyrilPaulus) [reply src/main/java/com/faforever/client/replay/ReplayService.java:166]: In reality it's not the map name but the map folder name. The path that I take from the binary data is the path to the script file.

So it looks like this :
/maps/my_awesome_map.v008/my_awesome_map.lua

File: src/main/java/com/faforever/client/replay/ReplayService.java (hunk 1 above)
Comment (CyrilPaulus) [reply src/main/java/com/faforever/client/replay/ReplayService.java:160]: Around the if ? You use brackets for one instruction ?

**Review by johnhce — DISMISSED** [review]

File: src/main/java/com/faforever/client/replay/ReplayService.java (hunk 1 above)
Comment (1-alex98) [reply src/main/java/com/faforever/client/replay/ReplayService.java:160]: Our convention we always use brackets

File: src/main/java/com/faforever/client/replay/ReplayService.java (hunk 3 above)
Comment (1-alex98) [reply src/main/java/com/faforever/client/replay/ReplayService.java]: Rebase onto develop and you will be able to generate maps in the create game dialog

Comment (CyrilPaulus) [reply src/main/java/com/faforever/client/replay/ReplayService.java]: It's seems to be able to extract the map name (folder name in reality).
But are those uploaded to the vault ?

Here a link from a test that I did, but it doesn't exists.

http://content.faforever.com/faf/vault/maps/neroxismapgenerator_0.1.1_6524124518669183714.zip

**Comment by 1-alex98** [comment]
Did you test it also with the map gen replays
?

**Comment by CyrilPaulus** [comment]
As I said earlier :

It's seems to be able to extract the map name (folder name in reality) for a generated map.
But are those maps uploaded to the vault ?

Here a link from a test that I did, but it doesn't exists.

http://content.faforever.com/faf/vault/maps/neroxismapgenerator_0.1.1_6524124518669183714.zip

So the replay won't play because it can't download the map, but the name seems correct ?

**Comment by 1-alex98** [comment]
I noticed today the implementation has faults there. It should actually detect that it is a generated map and then not try to download it but generate it but in some cases it still trys to download. But it is ok we will address this in a separate issue/pull request

**Review by 1-alex98 — APPROVED** [review]

**Comment by 1-alex98** [comment]
Lets not do this now but next release

File: src/main/java/com/faforever/client/replay/ReplayService.java [hunk 6]
```diff
@@ -376,6 +396,11 @@ private void runFafReplayFile(Path path) throws IOException {
     Map<String, Integer> modVersions = replayInfo.getFeaturedModVersions();
     String mapName = replayInfo.getMapname();
 
+    // For some reason in the coop replay the map name is null in the metadata
+    // So we just take it directly from the replay data.
+    if (mapName == null || mapName.equals(""))
```
Comment (1-alex98) [inline src/main/java/com/faforever/client/replay/ReplayService.java]: use bracets

**Review by 1-alex98 — CHANGES_REQUESTED** [review]

**Comment by 1-alex98** [comment]
@CyrilPaulus Would u be so nice to add the brackets so i can merge it

**Comment by 1-alex98** [comment]
Really only the bracets

**Review by 1-alex98 — DISMISSED** [review]

**Comment by 1-alex98** [comment]
Will merge this soon, if anybody wants to say something concerning that do so no

File: src/main/java/com/faforever/client/replay/ReplayService.java [hunk 7]
```diff
@@ -376,6 +396,13 @@ private void runFafReplayFile(Path path) throws IOException {
     Map<String, Integer> modVersions = replayInfo.getFeaturedModVersions();
     String mapName = replayInfo.getMapname();
 
+    // For some reason in the coop replay the map name is null in the metadata
+    // So we just take it directly from the replay data.
+    if (mapName == null || mapName.equals("")) {
```
Comment (Brutus5000) [inline src/main/java/com/faforever/client/replay/ReplayService.java]: Use StringUtils.isEmpty

**Review by Brutus5000 — CHANGES_REQUESTED** [review]
