### PR TITLE
Delete folder of old mod

### LINKED ISSUE #1182: Overwriting old mods does not work correctly
While overwriting the old data might not be completely overwritten if the new file is shorter... This causes desyncs

### PR DESCRIPTION
**Pull request by 1-alex98**
Fixes #1182

### CODE REVIEW

File: src/test/java/com/faforever/client/mod/InstallModTaskTest.java [hunk 1]
```diff
@@ -4,23 +4,22 @@
...
 import java.nio.file.Files;
+import java.nio.file.Path;
 
 import static org.hamcrest.CoreMatchers.is;
 import static org.junit.Assert.assertThat;
 import static org.mockito.Mockito.when;
 
-@RunWith(MockitoJUnitRunner.class)
-public class InstallModTaskTest {
+public class InstallModTaskTest extends AbstractPlainJavaFxTest {
```
Comment (1-alex98) [inline src/test/java/com/faforever/client/mod/InstallModTaskTest.java:22]: Because setting the title of the task is related to java fx
