### PR TITLE
Show warning when vault base path contains non ascii characters

### LINKED ISSUE #2613: Non ascii characters in vault path
**Describe the bug**

The game can not load in maps / mods when there are unknown characters in the path of the map / mod. The client can detect that and choose a different location, but in this instance that didn't work.

**To Reproduce**

image

Any user profile with this type of character, it is polish according to the user.

**Expected behavior**

According to Zlo the client can already detect non-ascii characters in some situations. This would need to be extended.

**OS**

Windows

### PR DESCRIPTION
**Pull request by Marc-Spector**
Closes #2613

### CODE REVIEW

File: src/main/java/com/faforever/client/game/GameService.java [hunk 1]
```diff
@@ -283,12 +292,30 @@ public CompletableFuture<Void> hostGame(NewGameInfo newGameInfo) {
...
+          i18n.get("vaultBasePath.warning.description"),
+          WARN,
+          List.of(new CancelAction(i18n), new Action(i18n.get("vaultBasePath.warning.hostGame"), (event) -> createGame(newGameInfo))),
+          checkBox
+      ));
+      return completedFuture(null);
+    }
+
+    return createGame(newGameInfo);
+  }
```
Comment (Sheikah45) [inline src/main/java/com/faforever/client/game/GameService.java]: We shouldn't be creating ui elements in a service.

File: src/main/java/com/faforever/client/game/GameService.java [hunk 2]
```diff
@@ -310,6 +337,23 @@ public CompletableFuture<Void> joinGame(GameBean game, String password) {
...
+      JavaFxUtil.bindBidirectional(checkBox.selectedProperty(), forgedAlliancePrefs.dontShowNonAsciiVaultBasePathWarning());
+      notificationService.addNotification(new ImmediateNotification(
+          i18n.get("vaultBasePath.warning.title"),
+          i18n.get("vaultBasePath.warning.description"),
+          WARN,
+          List.of(new CancelAction(i18n), new Action(i18n.get("vaultBasePath.warning.joinGame"), (event) -> joinGame_(game, password))),
+          checkBox
+      ));
+      return completedFuture(null);
+    }
```
Comment (Sheikah45) [inline src/main/java/com/faforever/client/game/GameService.java]: Same as above about UI elements

File: src/main/java/com/faforever/client/game/GameService.java [hunk 3]
```diff
@@ -310,6 +337,23 @@ public CompletableFuture<Void> joinGame(GameBean game, String password) {
...
+
+    return joinGame_(game, password);
+  }
+
+  private CompletableFuture<Void> joinGame_(GameBean game, String password) {
```
Comment (Sheikah45) [inline src/main/java/com/faforever/client/game/GameService.java]: The underscore isn't a convention in this repo if used like this it should be more descriptive

File: src/main/java/com/faforever/client/game/GameService.java [hunk 4]
```diff
@@ -854,6 +898,10 @@ public CompletableFuture<Boolean> isGamePrefsPatchedToAllowMultiInstances() thro
     return completedFuture(GAME_PREFS_ALLOW_MULTI_LAUNCH_PATTERN.matcher(gamePrefsContent).find());
   }
 
+  public boolean checkVaultBasePathIsValidForAcsii() {
+    return US_ASCII.newEncoder().canEncode(preferencesService.getPreferences().getForgedAlliance().getVaultBaseDirectory().toString());
+  }
```
Comment (Sheikah45) [inline src/main/java/com/faforever/client/game/GameService.java]: Don't think we want this in the game service, or called before every game launch since it is pretty static, better to be in the preferencesService

File: src/main/java/com/faforever/client/preferences/ForgedAlliancePrefs.java [hunk 5]
```diff
@@ -40,6 +40,7 @@ public class ForgedAlliancePrefs {
   ObjectProperty<Path> installationPath = new SimpleObjectProperty<>(STEAM_FA_PATH);
   ObjectProperty<Path> preferencesFile = new SimpleObjectProperty<>(LOCAL_FA_DATA_PATH.resolve("Game.prefs"));
   ObjectProperty<Path> vaultBaseDirectory = new SimpleObjectProperty<>(DEFAULT_VAULT_DIRECTORY);
+  BooleanProperty dontShowNonAsciiVaultBasePathWarning = new SimpleBooleanProperty(false);
```
Comment (Sheikah45) [inline src/main/java/com/faforever/client/preferences/ForgedAlliancePrefs.java]: Rename to warnNonAsciiBasePath

**Review by Sheikah45 — CHANGES_REQUESTED** [review]
I recognize this is WIP but saw a few things I wanted to comment on. Generally I don't think we want the check to be in the GameService or performed before every game launch. It would probably be better to treat it similarly to the gamePathValid check and maybe only do it on start up and have a separate class/event which creates and handles the UI.

**Comment by Marc-Spector** [comment]
Thanks for comments. Should we also add this check before running a replay and a live replay? Or is this an unnecessary action?

**Comment by Sheikah45** [comment]
I think just once during client startup is fine

**Comment by Marc-Spector** [comment]
Done. I will add tests soon.

File: src/main/java/com/faforever/client/game/GameService.java [hunk 6]
```diff
@@ -227,6 +228,18 @@ public void afterPropertiesSet() {
...
+    if (preferencesService.isVaultBasePathInvalidForAscii()) {
+      log.warn("Vault base path contains non ASCII characters: {}", forgedAlliancePrefs.getVaultBaseDirectory());
+      if (forgedAlliancePrefs.getWarnNonAsciiVaultPath()) {
+        notificationService.addPersistentWarnNotification("vaultBasePath.nonAscii.warning.title",
+            List.of(new Action(i18n.get("vaultBasePath.nonAscii.warning.ignore"), event -> {
+              forgedAlliancePrefs.setWarnNonAsciiVaultPath(false);
+              preferencesService.storeInBackground();
+            })));
+      }
+    }
```
Comment (Sheikah45) [inline src/main/java/com/faforever/client/game/GameService.java]: I would move this to an event listener in the PreferencesService that is triggered on a log in event.

Also probably would be better to have a modal dialog like an immediate notification and option to change the path like we do with the game path. As persistent notifications are pretty minor and can be overlooked.

**Review by Sheikah45 — CHANGES_REQUESTED** [review]
The check shouldn't really be in the afterProperties set as that is during the initialization of the spring beans so there might be some weird interactions. I would make it listen for the login event and check after that. We should also make it more prevalent than a persistent notification so that users know it can cause more issues as persistent notifications can be ignored easily.

Similar to the game path dialog also would be nice to provide a way to change it there.

File: src/main/java/com/faforever/client/game/GameService.java (hunk 6 above)
Comment (Marc-Spector) [reply src/main/java/com/faforever/client/game/GameService.java]: Are you sure? A newbie running the client for the first time after logging in will see this dialog instead of getting to know the client?

Comment (Sheikah45) [reply src/main/java/com/faforever/client/game/GameService.java]: Yes. I think it is most important for people new to the client just like how we ask them to specify the installed game path first thing.

Since it can be a hard bug to track down that can cause launches to fail.

**Review by Sheikah45 — COMMENTED** [review]
Looks good to me is this done from your perspective?

**Comment by Marc-Spector** [comment]
I did as you asked (requested). Either I misunderstood your thoughts. :(

**Comment by Sheikah45** [comment]
No this is good you just didn't request a review so wasn't sure if it was done from your perspective

**Comment by Sheikah45** [comment]
Just wanted to make sure I didn't merge before you were finished

**Comment by Marc-Spector** [comment]
I need time to make sure that the pull request is working perfectly. I need to test all things because we don't have integration tests. I always request a review only when I consider it finished)

**Comment by Sheikah45** [comment]
Sounds good then I shall wait but the structure is good.

File: src/main/java/com/faforever/client/preferences/ui/SettingsController.java [hunk 7]
```diff
@@ -184,43 +186,10 @@ public class SettingsController implements Controller<Node> {
...
-            controller.setLocale(locale);
-            controller.setOnSelectedListener(this::onLanguageSelected);
-            controller.setSelected(locale.equals(currentLocale));
-            return controller.getRoot();
-          })
-          .collect(Collectors.toList());
-      languagesContainer.getChildren().setAll(nodes);
-    };
-  }
+  private InvalidationListener availableLanguagesListener;
```
Comment (Sheikah45) [inline src/main/java/com/faforever/client/preferences/ui/SettingsController.java:189]: Small nit is just that even though it doesn't allow for a nice lombok constructor this should probably still be final but not gonna hold up this PR because of that

**Review by Sheikah45 — APPROVED** [review]
