### PR TITLE
Only set value on free text fields

### LINKED ISSUE #2616: Cannot select any item for some criteria
Known broken criteria
From Maps vault: `Ranked`
From Replays vault: `Player Faction`, `Map is ranked`, `Validity`, `Victory Condition`

Sent by Eternal from discord:
test

### PR DESCRIPTION
**Pull request by 1-alex98**
I can not see a way to reproduce this thing in the tests.
We would need a way to test components in integration for this.
Two controllers get in each other's way here.
Fixes #2616

### CODE REVIEW

**Comment by 1-alex98** [comment]
To explain... this lambda did deselects everything the user types if the value list is filled with none string elements...

File: src/main/java/com/faforever/client/vault/search/SearchController.java [hunk 1]
```diff
@@ -177,18 +177,24 @@ private void addInvalidationListener(LogicalNodeController logicalNodeController
...
-    });
+    selectValueBeforeLoosingFocusOnValueField(logicalNodeController);
     logicalNodeController.specificationController.valueField.setOnKeyReleased(event -> {
       if (event.getCode() == KeyCode.ENTER) {
         searchButton.fire();
       }
     });
   }
 
+  private void selectValueBeforeLoosingFocusOnValueField(LogicalNodeController logicalNodeController) {
```
Comment (1-alex98) [inline src/main/java/com/faforever/client/vault/search/SearchController.java]: Why we need this?
Well if you start typing something in a free text field, then you want to see it life in the search query string. Default behaviour would be only to take effect if the combo box looses focus.
What's the issue?
This hack only works on free text fields or if the items list contains raw strings as items. In case the list is say booleans, it calls setValue("false") instead of setValue(false). This will cause the combo box to deselect. This will also trigger whenever the user tries to select something and overwrite him. Anyways if there is something in the list to select this feature is not that interesting. It's only needed for free text fields anyways so I now avoid it triggering on none free text fields.

**Review by Marc-Spector — DISMISSED** [review]

File: src/main/java/com/faforever/client/vault/search/SearchController.java (hunk 1 above)
Comment (Sheikah45) [inline src/main/java/com/faforever/client/vault/search/SearchController.java]: Losing not loosing

**Review by Sheikah45 — CHANGES_REQUESTED** [review]

**Review by Sheikah45 — APPROVED** [review]
