### PR TITLE
Fix tooltips in chat refactoring

### LINKED ISSUE #978: Improve tooltip behavior
In chat all tooltips are missing. When i hover over a name in chat no info is shown any longer

### PR DESCRIPTION
**Pull request by 1-alex98**
Fixes #978

### CODE REVIEW

File: src/main/java/com/faforever/client/chat/ChatUserItemController.java [hunk 1]
```diff
@@ -274,15 +277,14 @@ private void setAvatarUrl(@Nullable String avatarUrl) {
     }
   }
 
-  private void setClanTag(String newValue) {
-    if (StringUtils.isEmpty(newValue)) {
+  private void setClanTag(String clanTag) {
+    if (!chatUser.getPlayer().isPresent() || clanTag == null || clanTag.isEmpty()) {
```
Comment (micheljung) [inline src/main/java/com/faforever/client/chat/ChatUserItemController.java]: `com.google.common.base.Strings#isNullOrEmpty`

File: src/main/java/com/faforever/client/chat/ChatUserItemController.java [hunk 2]
```diff
@@ -429,27 +448,18 @@ private void onUserActivity() {
...
+      updateNameLabelText(chatUser.getPlayer().get());
+    }
   }
 
   private void updateClanMenu(Player player) {
-    clanService.getClanByTag(player.getClan()).thenAccept(optionalClan -> JavaFxUtil.runLater(() -> updateClanMenu(optionalClan)));
+    clanService.getClanByTag(player.getClan())
+        .thenAccept(optionalClan -> JavaFxUtil.runLater(() -> updateClanMenu(optionalClan)))
+        .exceptionally(throwable -> {
+          log.error("Clan was not updated", throwable);
```
Comment (micheljung) [inline src/main/java/com/faforever/client/chat/ChatUserItemController.java]: warn

File: src/test/java/com/faforever/client/chat/ChatChannelUserItemControllerTest.java [hunk 3]
```diff
@@ -92,25 +106,33 @@ public void testGetRoot() throws Exception {
 
   @Test
   public void testSetChatUser() throws Exception {
-    Player player = PlayerBuilder.create("junit").defaultValues().clan("e").get();
+    Player player = PlayerBuilder.create("junit")
+        .defaultValues()
+        .clan("e")
+        .avatar(new AvatarBean(new URL("http://www.zooroyal.de/magazin/wp-content/uploads/2017/06/hund-im-sommer-760x560.jpg"), "dog"))
```
Comment (micheljung) [inline src/test/java/com/faforever/client/chat/ChatChannelUserItemControllerTest.java]: Let's stay neutral and go with `http://example.com/avatar.png`

**Review by micheljung — CHANGES_REQUESTED** [review]
