### PR TITLE
Fix mod download

### LINKED ISSUE #717: Missing mods aren't installed correctly before starting game
image
Should it not have installed that mods for me?

### PR DESCRIPTION
**Pull request by 1-alex98**
Make some adjustmennts to get mod downloading work.
Fixes #717

### CODE REVIEW

File: src/main/java/com/faforever/client/legacy/UnixUidService.java [hunk 1]
```diff
@@ -17,6 +21,7 @@
   @Override
   public String generate(String sessionId, Path logFile) throws IOException {
     String uidDir = System.getProperty("nativeDir", "lib");
+    Files.setPosixFilePermissions(Paths.get(uidDir, "/faf-uid"), Sets.immutableEnumSet(PosixFilePermission.OTHERS_READ));
```
Comment (micheljung) [inline src/main/java/com/faforever/client/legacy/UnixUidService.java]: No path separator required/desired in `"/faf-uid"`

File: src/main/java/com/faforever/client/mod/ModServiceImpl.java [hunk 2]
```diff
@@ -163,14 +163,15 @@ private Thread startDirectoryWatcher(Path modsDirectory) throws IOException, Int
...
-  public void loadInstalledMods() {
+  public CompletableFuture<Void> loadInstalledMods() {
     try (DirectoryStream<Path> directoryStream = Files.newDirectoryStream(modsDirectory, entry -> Files.isDirectory(entry))) {
       for (Path path : directoryStream) {
         addMod(path);
       }
     } catch (IOException e) {
       logger.warn("Mods could not be read from: " + modsDirectory, e);
     }
+    return completedFuture(null);
```
Comment (micheljung) [inline src/main/java/com/faforever/client/mod/ModServiceImpl.java]: There is no need/benefit in returning a future here since it doesn't execute any asynchronous task

File: src/main/java/com/faforever/client/mod/ModServiceImpl.java [hunk 3]
```diff
@@ -201,14 +207,19 @@ public void loadInstalledMods() {
     }
 
     return taskService.submitTask(task).getFuture()
-        .thenAccept(aVoid -> loadInstalledMods());
+        .thenCompose(aVoid -> loadInstalledMods());
```
Comment (micheljung) [inline src/main/java/com/faforever/client/mod/ModServiceImpl.java]: Changing this from `thenAccept` to `thenCompose` makes no difference. The proper call would have been `thenRun` anyway, since the result of the previous future is not of interest and the called method also doesn't return anything.

File: src/main/java/com/faforever/client/mod/ModServiceImpl.java [hunk 4]
```diff
@@ -181,7 +182,12 @@ public void loadInstalledMods() {
   @SneakyThrows
   @Override
   public CompletableFuture<Void> downloadAndInstallMod(String uid) {
-    return fafService.getMod(uid).thenAccept(mod -> downloadAndInstallMod(mod, null, null));
+    return fafService.getModVersion(uid)
+        .thenCompose(mod -> downloadAndInstallMod(mod, null, null))
+        .exceptionally(throwable -> {
+          logger.warn("Sim mod was not installed", throwable);
```
Comment (micheljung) [inline src/main/java/com/faforever/client/mod/ModServiceImpl.java]: `Sim mod could not be installed` (otherwise, it sounds like "it wasn't but now it is")

File: src/main/java/com/faforever/client/mod/ModVersion.java [hunk 5]
```diff
@@ -0,0 +1,234 @@
...
+import javafx.beans.property.SimpleBooleanProperty;
+import javafx.beans.property.SimpleObjectProperty;
+import javafx.beans.property.SimpleStringProperty;
+import javafx.beans.property.StringProperty;
+import org.apache.maven.artifact.versioning.ComparableVersion;
+
+import java.net.URL;
+import java.time.OffsetDateTime;
+
+public class ModVersion {
```
Comment (micheljung) [inline src/main/java/com/faforever/client/mod/ModVersion.java]: As discussed, rename `Mod` instead.

**Review by micheljung — CHANGES_REQUESTED** [review]

**Review by micheljung — APPROVED** [review]
