### PR TITLE
Return empty String to avoid NullPointerException

### LINKED ISSUE #794: NullPointer on player having no games
image

### PR DESCRIPTION
**Pull request by 1-alex98**
Fixes #794

### CODE REVIEW

File: src/main/java/com/faforever/client/chat/UserInfoWindowController.java [hunk 1]
```diff
@@ -443,7 +443,7 @@ public String toString(Number object) {
         int number = object.intValue();
         int numberOfDataPoints = dataPoints.size();
         int dataPointIndex = number >= numberOfDataPoints ? numberOfDataPoints - 1 : number;
-        return DATE_FORMATTER.format(dataPoints.get(dataPointIndex).getInstant());
+        return dataPoints.get(dataPointIndex) == null ? "" : DATE_FORMATTER.format(dataPoints.get(dataPointIndex).getInstant());
```
Comment (micheljung) [inline src/main/java/com/faforever/client/chat/UserInfoWindowController.java]: Actually, the issue #794 is about getting an `ArrayIndexOutOfBoundsException` rather than `NullPointerException` which is caused when `dataPoints` does not contain an index `dataPointIndex` - so the exact same thing still happens with the code above.

The proper fix would be:
```
if(dataPointIndex >= dataPoints.size()) {
  return "";
}
return dataPoints.get(dataPointIndex);
```

Please adjust the issue title and commit message as well.

**Review by micheljung — CHANGES_REQUESTED** [review]

**Review by micheljung — APPROVED** [review]
