### PR TITLE
Fix not corrupted replays being marked as corrupt

### LINKED ISSUE #763: Replays marked as corrupt
All my replays from 2018 were moved to a folder marked corrupt, plus a few more. They are not corrupt.

### PR DESCRIPTION
**Pull request by 1-alex98**
Fixes #763

### CODE REVIEW

File: src/main/java/com/faforever/client/api/FafApiAccessorImpl.java [hunk 1]
```diff
@@ -326,9 +327,9 @@ public Mod getMod(String uid) {
 
   @Override
   public Optional<MapVersion> findMapByFolderName(String folderName) {
-    List<MapVersion> maps = getMany(MAP_ENDPOINT, 1, ImmutableMap.of(
-        "include", "latestVersion,author",
-        "sort", "-updateTime"));
+    List<MapVersion> maps = getMany("/data/mapVersion", 1, ImmutableMap.of(
+        "filter", MessageFormat.format("filename==\"*{0}*\"", folderName),
```
Comment (micheljung) [inline src/main/java/com/faforever/client/api/FafApiAccessorImpl.java]: `MessageFormat` is for human-readable strings and it adds locale-specific things like separators in `1'000'000` vs `1,000,000` and such. It's, therefore, not suitable for technical string building; use the "dumb" `String.format()` instead.

File: src/main/java/com/faforever/client/replay/ReplayServiceImpl.java [hunk 2]
```diff
@@ -176,7 +177,7 @@ static String guessModByFileName(String fileName) {
                 replayInfos.add(new Replay(replayInfo, replayFile, featuredMod, mapBean.get()));
               });
         } catch (Exception e) {
-          logger.warn("Could not read replay file {} ({})", replayFile, e.getMessage());
+          logger.warn(MessageFormat.format("Could not read replay file {0}", replayFile), e);
```
Comment (micheljung) [inline src/main/java/com/faforever/client/replay/ReplayServiceImpl.java]: The logger supports using both, string replacement and exceptions as stack traces;

```
 logger.warn("Could not read replay file '{}'", replayFile, e);
```

**Review by micheljung — CHANGES_REQUESTED** [review]

**Review by micheljung — APPROVED** [review]
