### PR TITLE
Fixed out of memory exception crash occurring by switching back-and-forth between replay tabs

### LINKED ISSUE #3380: [Bug]: OOM exception crash after switching between replay tabs
### Describe the Bug

The client crashes after switching between a tab and one of the replay tabs. There are no error messages  or notifications shown before the crash.

See attached partial log from the IntelliJ IDEA debugger.

### Log file or Error Message

java.lang.OutOfMemoryError: Java heap space
Dumping heap to java_pid171728.hprof ...
Heap dump file created [1214554862 bytes in 3.023 secs]
*** java.lang.instrument ASSERTION FAILED ***: "!errorOutstanding" with message can't create name string at s\src\java.instrument\share\native\libinstrument\JPLISAgent.c line: 838
*** java.lang.instrument ASSERTION FAILED ***: "!errorOutstanding" with message can't create name string at s\src\java.instrument\share\native\libinstrument\JPLISAgent.c line: 838
*** java.lang.instrument ASSERTION FAILED ***: "!errorOutstanding" with message can't create name string at s\src\java.instrument\share\native\libinstrument\JPLISAgent.c line: 838
*** java.lang.instrument ASSERTION FAILED ***: "!errorOutstanding" with message can't create name string at s\src\java.instrument\share\native\libinstrument\JPLISAgent.c line: 838

Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "ForkJoinPool.commonPool-worker-5"

Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "Discord RPC"
*** java.lang.instrument ASSERTION FAILED ***: "!errorOutstanding" with message can't create name string at s\src\java.instrument\share\native\libinstrument\JPLISAgent.c line: 838

Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "reactor-http-nio-1"

Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "ForkJoinPool.commonPool-worker-18"
2025-08-05T00:36:06.680+02:00 ERROR 171728 --- [FAF Client] [onPool-worker-6] c.f.c.exception.GlobalExceptionHandler   : Uncaught exception on Thread[186,ForkJoinPool.commonPool-worker-6,5,main]: 

java.lang.OutOfMemoryError: Java heap space

2025-08-05T00:36:06.680+02:00 ERROR 171728 --- [FAF Client] [nPool-worker-16] c.f.c.exception.GlobalExceptionHandler   : Uncaught exception on Thread[212,ForkJoinPool.commonPool-worker-16,5,main]: 

java.lang.OutOfMemoryError: Java heap space

2025-08-05T00:36:07.837+02:00 ERROR 171728 --- [FAF Client] [Queue (Unnamed)] c.f.c.exception.GlobalExceptionHandler   : Uncaught exception on Thread[152,KICL Immediate Sending Queue (Unnamed),5,main]: 

java.util.concurrent.RejectedExecutionException: event executor terminated
	at io.netty.util.concurrent.SingleThreadEventExecutor.reject(SingleThreadEventExecutor.java:934)
	at io.netty.util.concurrent.SingleThreadEventExecutor.offerTask(SingleThreadEventExecutor.java:353)
	at io.netty.util.concurrent.SingleThreadEventExecutor.addTask(SingleThreadEventExecutor.java:346)
	at io.netty.util.concurrent.SingleThreadEventExecutor.execute(SingleThreadEventExecutor.java:836)
	at io.netty.util.concurrent.SingleThreadEventExecutor.execute0(SingleThreadEventExecutor.java:827)
	at io.netty.util.concurrent.SingleThreadEventExecutor.execute(SingleThreadEventExecutor.java:817)
	at reactor.netty.channel.FluxReceive.lambda$new$0(FluxReceive.java:97)
	at reactor.netty.channel.FluxReceive.cancelReceiver(FluxReceive.java:199)
	at reactor.netty.channel.FluxReceive.doCancel(FluxReceive.java:205)
	at reactor.netty.channel.FluxReceive.cancel(FluxReceive.java:105)
	at reactor.core.publisher.FluxOnAssembly$OnAssemblySubscriber.cancel(FluxOnAssembly.java:654)
	at reactor.core.publisher.FluxOnAssembly$OnAssemblySubscriber.cancel(FluxOnAssembly.java:654)
	at reactor.core.publisher.FluxMapFuseable$MapFuseableConditionalSubscriber.cancel(FluxMapFuseable.java:365)
	at reactor.core.publisher.FluxOnAssembly$OnAssemblySubscriber.cancel(FluxOnAssembly.java:654)
	at reactor.core.publisher.FluxOnAssembly$OnAssemblySubscriber.cancel(FluxOnAssembly.java:654)
	at reactor.core.publisher.FluxHandleFuseable$HandleFuseableSubscriber.cancel(FluxHandleFuseable.java:265)
	at reactor.core.publisher.FluxOnAssembly$OnAssemblySubscriber.cancel(FluxOnAssembly.java:654)
	at reactor.core.publisher.FluxPeekFuseable$PeekFuseableSubscriber.cancel(FluxPeekFuseable.java:159)
	at reactor.core.publisher.FluxOnAssembly$OnAssemblySubscriber.cancel(FluxOnAssembly.java:654)
	at reactor.core.publisher.FluxPeekFuseable$PeekFuseableSubscriber.cancel(FluxPeekFuseable.java:159)
	at reactor.core.publisher.FluxOnAssembly$OnAssemblySubscriber.cancel(FluxOnAssembly.java:654)
	at reactor.core.publisher.MonoIgnoreElements$IgnoreElementsSubscriber.cancel(MonoIgnoreElements.java:104)
	at reactor.core.publisher.FluxOnAssembly$OnAssemblySubscriber.cancel(FluxOnAssembly.java:654)
	at reactor.core.publisher.Operators$DeferredSubscription.cancel(Operators.java:1695)
	at reactor.core.publisher.FluxFirstWithSignal$RaceCoordinator.tryWin(FluxFirstWithSignal.java:276)
	at reactor.core.publisher.FluxFirstWithSignal$FirstEmittingSubscriber.onError(FluxFirstWithSignal.java:342)
	at reactor.core.publisher.FluxOnAssembly$OnAssemblySubscriber.onError(FluxOnAssembly.java:544)
	at reactor.core.publisher.FluxOnAssembly$OnAssemblySubscriber.onError(FluxOnAssembly.java:544)
	at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.onError(MonoIgnoreThen.java:280)
	at reactor.core.publisher.FluxOnAssembly$OnAssemblySubscriber.onError(FluxOnAssembly.java:544)
	at reactor.core.publisher.FluxOnAssembly$OnAssemblySubscriber.onError(FluxOnAssembly.java:544)
	at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.onError(MonoIgnoreThen.java:280)
	at reactor.netty.channel.MonoSendMany$SendManyInner.trySchedule(MonoSendMany.java:442)
	at reactor.netty.channel.MonoSendMany$SendManyInner.onNext(MonoSendMany.java:223)
	at reactor.core.publisher.FluxOnAssembly$OnAssemblySubscriber.onNext(FluxOnAssembly.java:539)
	at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onNext(FluxMapFuseable.java:129)
	at reactor.core.publisher.FluxOnAssembly$OnAssemblySubscriber.onNext(FluxOnAssembly.java:539)
	at reactor.core.publisher.FluxOnAssembly$OnAssemblySubscriber.onNext(FluxOnAssembly.java:539)
	at reactor.core.publisher.FluxPeekFuseable$PeekFuseableSubscriber.onNext(FluxPeekFuseable.java:210)
	at reactor.core.publisher.FluxOnAssembly$OnAssemblySubscriber.onNext(FluxOnAssembly.java:539)
	at reactor.core.publisher.FluxPeekFuseable$PeekFuseableSubscriber.onNext(FluxPeekFuseable.java:210)
	at reactor.core.publisher.FluxOnAssembly$OnAssemblySubscriber.onNext(FluxOnAssembly.java:539)
	at reactor.core.publisher.FluxPublish$PublishSubscriber.drain(FluxPublish.java:571)
	at reactor.core.publisher.FluxPublish$PublishSubscriber.onNext(FluxPublish.java:310)
	at reactor.core.publisher.SinkManyUnicast.drainFused(SinkManyUnicast.java:321)
	at reactor.core.publisher.SinkManyUnicast.drain(SinkManyUnicast.java:363)
	at reactor.core.publisher.SinkManyUnicast.tryEmitNext(SinkManyUnicast.java:239)
	at reactor.core.publisher.SinkManySerialized.tryEmitNext(SinkManySerialized.java:100)
	at reactor.core.publisher.InternalManySink.emitNext(InternalManySink.java:27)
	at com.faforever.client.chat.kitteh.network.WebSocketConnection.lambda$new$0(WebSocketConnection.java:67)
	at org.kitteh.irc.client.library.feature.sending.QueueProcessingThreadSender.processElement(QueueProcessingThreadSender.java:68)
	at org.kitteh.irc.client.library.feature.sending.QueueProcessingThreadSender.processElement(QueueProcessingThreadSender.java:38)
	at org.kitteh.irc.client.library.util.QueueProcessingThread.run(QueueProcessingThread.java:63)

Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "InvokeLaterDispatcher"

Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "parallel-26"

Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "JNA Cleaner"

### Reproduce the bug

The easiest way I found to reproduce is switching between the FAF Replays and the Local Replays tabs, but any other tab works as long as you are switching to one of the replay tabs. This way it usually takes me 10 navigations to produce the crash.

### Expected Behavior

The application does not crash.

### Screenshots

_No response_

### Additional context

_No response_

### Which Operating System are you using?

Windows

### PR DESCRIPTION
**Pull request by Rogerstalker**
Fixes #3380 

Fixed out of memory exception that occurs after switching a few times between a replay tab and another tab. ReplayCardControllers were held in memory with the binding to the replay history. With each switch the navigation to the other tab was getting progressively slower.

-- Before Fix --
Path to GC roots for ReplayCardController.
kép

ReplayCardController Histogram right before final tab navigation to produce OOM exception crash. See excessive amounts of ReplayCardControllers held in memory after about 9 switches between FAF replays and Local Replays tabs.
kép

-- After Fix --
ReplayCardController Histogram after about 20 tab switches. Heap dump captured while the Local Replays Tab was selected.
kép

### CODE REVIEW

File: src/main/java/com/faforever/client/replay/ReplayCardController.java [hunk 1]
```diff
@@ -147,19 +147,27 @@ protected void onInitialize() {
...
+    teams.bind(entity.map(Replay::teamPlayerStats).when(showing));
+    teams.orElse(java.util.Map.of()).addListener(teamsListener);
+  }
+
+  @Override
+  protected void onAttached()
+  {
     isReplayWatched.bind(replayHistory.watchedReplaysProperty()
                                       .flatMap(watchedReplays -> entity.map(Replay::id).map(watchedReplays::contains))
                                       .orElse(false));
```
Comment (Sheikah45) [inline src/main/java/com/faforever/client/replay/ReplayCardController.java]: I think all that is needed is to add a .when(showing) to the derived value we are binding from the watchedReplaysProperty. I don't think the onAttached/onDetached is needed.

**Review by Sheikah45 — CHANGES_REQUESTED** [review]

File: src/main/java/com/faforever/client/replay/ReplayCardController.java (hunk 1 above)
Comment (Rogerstalker) [reply src/main/java/com/faforever/client/replay/ReplayCardController.java]: Replaced fix with suggestion. Did a brief manual test, seems to work just as well.

**Review by Sheikah45 — APPROVED** [review]
