### PR TITLE
fixes #1081 mark executable flag on exe file

### LINKED ISSUE #1081: make ForgedAlliance.exe executable on Linux
when starting a game on Linux the following error occures: 
```
2019-01-02 13:00:26.006  WARN 7291 --- [     Thread-627] com.faforever.client.game.GameService    : Game could not be started

java.util.concurrent.CompletionException: com.github.nocatch.NoCatchException: java.io.IOException: Cannot run program "~/.faforever/bin/ForgedAlliance.exe" (in directory "~/.faforever/bin"): error=13, Permission denied
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:314) ~[na:na]
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:319) ~[na:na]
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718) ~[na:na]
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506) ~[na:na]
	at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2073) ~[na:na]
	at com.faforever.client.replay.ReplayServerImpl.lambda$start$2(ReplayServerImpl.java:109) ~[downlords-faf-client-0.9.3-beta.jar:0.9.3-beta]
	at java.base/java.lang.Thread.run(Thread.java:844) ~[na:na]
Caused by: com.github.nocatch.NoCatchException: java.io.IOException: Cannot run program "/home/sws/.faforever/bin/ForgedAlliance.exe" (in directory "/home/sws/.faforever/bin"): error=13, Permission denied
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[na:na]
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:488) ~[na:na]
	at com.github.nocatch.NoCatch.wrapException(NoCatch.java:61) ~[nocatch-1.1.jar:na]
	at com.github.nocatch.NoCatch.noCatch(NoCatch.java:104) ~[nocatch-1.1.jar:na]
	at com.github.nocatch.NoCatch.noCatch(NoCatch.java:82) ~[nocatch-1.1.jar:na]
	at com.faforever.client.game.GameService.lambda$startGame$33(GameService.java:467) ~[downlords-faf-client-0.9.3-beta.jar:0.9.3-beta]
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:714) ~[na:na]
	... 4 common frames omitted
Caused by: java.io.IOException: Cannot run program "/home/sws/.faforever/bin/ForgedAlliance.exe" (in directory "/home/sws/.faforever/bin"): error=13, Permission denied
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1128) ~[na:na]
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1071) ~[na:na]
	at com.faforever.client.fa.ForgedAllianceService.launch(ForgedAllianceService.java:128) ~[downlords-faf-client-0.9.3-beta.jar:0.9.3-beta]
	at com.faforever.client.fa.ForgedAllianceService.startGame(ForgedAllianceService.java:73) ~[downlords-faf-client-0.9.3-beta.jar:0.9.3-beta]
	at com.faforever.client.game.GameService.lambda$startGame$32(GameService.java:467) ~[downlords-faf-client-0.9.3-beta.jar:0.9.3-beta]
	at com.github.nocatch.NoCatch.noCatch(NoCatch.java:100) ~[nocatch-1.1.jar:na]
	... 7 common frames omitted
Caused by: java.io.IOException: error=13, Permission denied
	at java.base/java.lang.ProcessImpl.forkAndExec(Native Method) ~[na:na]
	at java.base/java.lang.ProcessImpl.<init>(ProcessImpl.java:339) ~[na:na]
	at java.base/java.lang.ProcessImpl.start(ProcessImpl.java:270) ~[na:na]
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1107) ~[na:na]
	... 12 common frames omitted
```

Setting the executable bit on `~/.faforever/bin/ForgedAlliance.exe` fixes this error

### PR DESCRIPTION
**Pull request by johnhce**
Mark ForgedAlliance.exe as executable after download.
Fixes #1081

### CODE REVIEW

File: src/main/java/com/faforever/client/patch/GameBinariesUpdateTaskImpl.java [hunk 1]
```diff
@@ -107,11 +110,16 @@ private void downloadFafExeIfNecessary(Path exePath) throws IOException {
             .listener(this::updateProgress)
             .copy();
       }
+      makeSureExeIsExecutable(exePath);
     } finally {
       ResourceLocks.freeDownloadLock();
     }
   }
 
+  private void makeSureExeIsExecutable(Path exePath) {
```
Comment (Geosearchef) [inline src/main/java/com/faforever/client/patch/GameBinariesUpdateTaskImpl.java]: we're not making sure the executable is executable (not checking it before), we're just setting the executable bit (rename method pls)

File: src/main/java/com/faforever/client/patch/GameBinariesUpdateTaskImpl.java [hunk 2]
```diff
@@ -107,11 +110,16 @@ private void downloadFafExeIfNecessary(Path exePath) throws IOException {
...
+    exePath.toFile().setExecutable(true);
```
Comment (Geosearchef) [inline src/main/java/com/faforever/client/patch/GameBinariesUpdateTaskImpl.java]: converting paths->file, file->path is a bad practice, no need for that here, just use the util method from the Files class that takes a path as an argument:

`Files.setPosixFilePermissions(filePath, Sets.immutableEnumSet(PosixFilePermission.OWNER_READ, PosixFilePermission.OWNER_EXECUTE));`

Comment (Geosearchef) [reply src/main/java/com/faforever/client/patch/GameBinariesUpdateTaskImpl.java]: also, please check system is unix before setting the executable bit

**Review by Geosearchef — CHANGES_REQUESTED** [review]
I don't know if we really need a seperate method for that, but the Files.setPosixFilePerms... wouldn't be good to be duplicated.

**Review by Geosearchef — APPROVED** [review]
The client is so far not using SystemUtils for checking the OS, not sure if that's bad and we should use the same check as other services, but I think it'll work.

File: src/main/java/com/faforever/client/fx/PlatformService.java [hunk 3]
```diff
@@ -130,4 +136,13 @@ private String getForegroundWindowTitle() {
   public boolean isWindowFocused(String windowTitle) {
     return windowTitle.equals(getForegroundWindowTitle());
   }
+
+  public void setUnixExecutableBit(Path exePath) throws IOException {
+	// client needs executable bit for running and the writeable bit set to alter the version
```
Comment (1-alex98) [inline src/main/java/com/faforever/client/fx/PlatformService.java]: We dont do any comments, only if there is really something to explain. Better call your functions and varibles in a proper understandable way.
If for example you wanna lay enphasis on the writable part call the function setUnixExecutableAndWritableBit

File: src/main/java/com/faforever/client/update/ClientUpdateServiceImpl.java [hunk 4]
```diff
@@ -95,7 +95,12 @@ public ComparableVersion getCurrentVersion() {
   }
 
   private void install(Path binaryPath) {
-    // TODO probably need to make this executable on unix See #1026
+    // need to make this executable on unix See #1026
```
Comment (1-alex98) [inline src/main/java/com/faforever/client/update/ClientUpdateServiceImpl.java]: Same as above

File: src/main/java/com/faforever/client/update/ClientUpdateServiceImpl.java [hunk 5]
```diff
@@ -95,7 +95,12 @@ public ComparableVersion getCurrentVersion() {
...
+	try {
+      platformService.setUnixExecutableBit(binaryPath);
```
Comment (1-alex98) [inline src/main/java/com/faforever/client/update/ClientUpdateServiceImpl.java]: Formatting

File: src/test/java/com/faforever/client/patch/GameBinariesUpdateTaskTest.java [hunk 6]
```diff
@@ -38,7 +41,7 @@
   public void setUp() throws Exception {
     MockitoAnnotations.initMocks(this);
 
-    instance = new GameBinariesUpdateTaskImpl(i18n, preferencesService, new ClientProperties());
+    instance = new GameBinariesUpdateTaskImpl(i18n, preferencesService, platformService, new ClientProperties());
```
Comment (1-alex98) [inline src/test/java/com/faforever/client/patch/GameBinariesUpdateTaskTest.java:46]: That should be something that you can test super easy just check if the correct call on the PlatformService was made

**Review by 1-alex98 — CHANGES_REQUESTED** [review]

File: src/main/java/com/faforever/client/fx/PlatformService.java (hunk 3 above)
Comment (johnhce) [reply src/main/java/com/faforever/client/fx/PlatformService.java]: The comment explains why the writable bit is necessary which is not obvious.

File: src/test/java/com/faforever/client/patch/GameBinariesUpdateTaskTest.java (hunk 6 above)
Comment (johnhce) [reply src/test/java/com/faforever/client/patch/GameBinariesUpdateTaskTest.java:46]: I don't understand what the test would be.

Comment (1-alex98) [reply src/test/java/com/faforever/client/patch/GameBinariesUpdateTaskTest.java:46]: Sorry I mean in the ClientUpdateServiceImpl test

Comment (johnhce) [reply src/test/java/com/faforever/client/patch/GameBinariesUpdateTaskTest.java:46]: What specifically do you want me to test?  That a file's permissions really got set the way we specified in the call?  Since that's the only thing this method does, aren't we running a unit test that Apache Commons would have already run themselves?

Comment (1-alex98) [reply src/test/java/com/faforever/client/patch/GameBinariesUpdateTaskTest.java:46]: Yes I want to to check if platformService.setUnixExecutableBit(binaryPath); was called

**Review by Geosearchef — DISMISSED** [review]
Looks good to me, you should fix the formatting though.

File: src/main/java/com/faforever/client/update/ClientUpdateServiceImpl.java [hunk 7]
```diff
@@ -94,8 +94,13 @@ public ComparableVersion getCurrentVersion() {
     return currentVersion;
   }
 
-  private void install(Path binaryPath) {
-    // TODO probably need to make this executable on unix See #1026
+  @VisibleForTesting
+  void install(Path binaryPath) {
+  	try {
+      platformService.setUnixExecutableAndWritableBits(binaryPath);
```
Comment (1-alex98) [inline src/main/java/com/faforever/client/update/ClientUpdateServiceImpl.java:100]: Formatting

File: src/main/java/com/faforever/client/update/ClientUpdateServiceImpl.java [hunk 8]
```diff
@@ -94,8 +94,13 @@ public ComparableVersion getCurrentVersion() {
     return currentVersion;
   }
 
-  private void install(Path binaryPath) {
-    // TODO probably need to make this executable on unix See #1026
+  @VisibleForTesting
+  void install(Path binaryPath) {
```
Comment (1-alex98) [inline src/main/java/com/faforever/client/update/ClientUpdateServiceImpl.java:98]: Please tell me why would we need to set the Executable bit again while installing if we already did so while downloading.
Or other question do we need to set it while downloading if we do during install...

Comment (1-alex98) [reply src/main/java/com/faforever/client/update/ClientUpdateServiceImpl.java:98]: Even tho i am not sure what we are installing here? 🤔

Comment (1-alex98) [reply src/main/java/com/faforever/client/update/ClientUpdateServiceImpl.java:98]: It is no the faf exe right?

**Review by 1-alex98 — CHANGES_REQUESTED** [review]

File: src/main/java/com/faforever/client/update/ClientUpdateServiceImpl.java (hunk 8 above)
Comment (1-alex98) [reply src/main/java/com/faforever/client/update/ClientUpdateServiceImpl.java:98]: oh it is the client... XD ups... Well updating the client on linux does not work in the first place becasue it is a tar.gz and we treat it as a exe just so you know. Something that needs to be fixed as well ;) But yeah you can set the executable bit there i guess even tho I would assume a tar.gz does not need one :D

Comment (1-alex98) [reply src/main/java/com/faforever/client/update/ClientUpdateServiceImpl.java:98]: @tatsujb as a install script maybe one day we can somehow incorporate that

**Review by 1-alex98 — APPROVED** [review]
