### PR TITLE
Fix Updater taking wrong file

### LINKED ISSUE #1025: Updater picks first file form release instead of correct one
Fix updater

### PR DESCRIPTION
**Pull request by 1-alex98**
Fixes #1025

### CODE REVIEW

File: src/main/java/com/faforever/client/update/CheckForUpdateTask.java [hunk 1]
```diff
@@ -79,7 +80,13 @@ protected UpdateInfo call() throws Exception {
         return null;
       }
 
-      GitHubAsset gitHubAsset = gitHubRelease.getAssets()[0];
+      boolean windows = org.bridj.Platform.isWindows();
+
+      GitHubAsset gitHubAsset = Arrays.stream(gitHubRelease.getAssets())
+          .filter(asset -> windows ? asset.getName().endsWith(".exe") : asset.getName().endsWith("tar.gz"))
```
Comment (Geosearchef) [inline src/main/java/com/faforever/client/update/CheckForUpdateTask.java:86]: endsWith is case sensitive

**Review by Geosearchef — APPROVED** [review]

**Review by micheljung — APPROVED** [review]
