### PR TITLE
Load view before showing replay

### LINKED ISSUE #2099: Load view before showing replay
**Describe the bug**
If your game finished and you clcik on "rate game" in the notification after closing the replay you are left in an endless loading screen.

### PR DESCRIPTION
**Pull request by 1-alex98**
Fixes #2099

### CODE REVIEW

File: src/main/java/com/faforever/client/vault/VaultEntityController.java [hunk 1]
```diff
@@ -247,7 +247,6 @@ protected void onPageChange(SearchConfig searchConfig, boolean firstLoad) {
 
   protected void displaySearchResult(List<T> results) {
     JavaFxUtil.assertBackgroundThread();
-    enterSearchingState();
```
Comment (1-alex98) [inline src/main/java/com/faforever/client/vault/VaultEntityController.java:250]: That was just called a second time and was on the backgroup thread

**Comment by Sheikah45** [comment]
Hmm it is failing some tests

**Review by Sheikah45 — APPROVED** [review]
