### PR TITLE
Fix Load Ladder Maps

### LINKED ISSUE #1918: Show ladder 1v1 maps only works the second time you click on it
**Describe the bug**
The loading of the starting screen of the map vault covers the 1v1 maps if the vault was not loaded before the button clcik

it used to work but we must have broken it when @Sheikah45 and I refactored the vault

**Wanna have the bug fixed quickly?**
Visit Issue hunt...
[Issue hunt](https://issuehunt.io/r/FAForever/downlords-faf-client)

### PR DESCRIPTION
**Pull request by Sheikah45**
Fixes #1918 

Removes the change listener to the state as that seemed to not do anything and was overridden by the loadshowroom.
Does not cause the show user replays to break.

### CODE REVIEW

File: src/main/java/com/faforever/client/vault/VaultEntityController.java [hunk 1]
```diff
@@ -327,20 +325,7 @@ protected void onBackButtonClicked() {
...
-            if (newValue != State.UNINITIALIZED) {
-              state.removeListener(this);
-              handleSpecialNavigateEvent(navigateEvent);
-            }
-          }
-        });
-        loadShowRoom();
-      } else {
-        handleSpecialNavigateEvent(navigateEvent);
-      }
```
Comment (1-alex98) [inline src/main/java/com/faforever/client/vault/VaultEntityController.java:343]: Well I think you fixed it but now if you click the back button after the search it showroom is empty. That is why this code existed. Maybe easier would be check if state is uninitialized on back button click and call loadShowRoom then

**Review by 1-alex98 — CHANGES_REQUESTED** [review]

File: src/main/java/com/faforever/client/vault/VaultEntityController.java (hunk 1 above)
Comment (Sheikah45) [reply src/main/java/com/faforever/client/vault/VaultEntityController.java:343]: I don't get this error the show room always populates for me with the back button. How are you getting an empty showroom?

Comment (Sheikah45) [reply src/main/java/com/faforever/client/vault/VaultEntityController.java:343]: In the code the back button always loads the showroom

Comment (1-alex98) [reply src/main/java/com/faforever/client/vault/VaultEntityController.java:343]: Was just an assumption because in the old code that used to be the case

Comment (Sheikah45) [reply src/main/java/com/faforever/client/vault/VaultEntityController.java:343]: yeah if you test it and it happens let me know cause it isnt happening for me

**Review by 1-alex98 — APPROVED** [review]
