### PR TITLE
Change dns resolver of webclient

### LINKED ISSUE #2374: Some users cannot resolve api.faforever.com
**Describe the bug**
From the forum:
updated to 1.6 today, after having not played for a good while, however when i try to log in i get the following message

java.util.concurrent.CompletionException: org.springframework.web.reactive.function.client.WebClientRequestException: failed to resolve ' api.faforever.com ' after 2 queries ; nested exception is java.net.UnknownHostException: failed to resolve ' api.faforever.com ' after 2 queries 

**To Reproduce**
Some minority of users cannot resolve api.faforever.com using the webclient from spring

**Expected behavior**
Users should be able to easily connect to the api like they have with client 1.5.0

**Wanna have the bug fixed quickly?**
Visit Issue hunt...
[Issue hunt](https://issuehunt.io/r/FAForever/downlords-faf-client)

### PR DESCRIPTION
**Pull request by Sheikah45**
Closes #2374

### CODE REVIEW

**Comment by micheljung** [comment]
Your commit message should reference the issue like:

```
Increase timeout and dns queries per resolve

Fixes #2374
```

Assuming this is what this is about.

**Comment by Sheikah45** [comment]
This only seems to fix the issue for a small amount of users.

I will probably try using Apache's http client instead

**Comment by Sheikah45** [comment]
Trying to switch the default resolver to see if this resolves the issue as seen here https://github.com/reactor/reactor-netty/issues/1431

**Comment by Sheikah45** [comment]
It seems to be a known bug of the netty dns resolver and spring 2.4.0

**Comment by micheljung** [comment]
> It seems to be a known bug of the netty dns resolver and spring 2.4.0

Can you link this please

**Comment by Sheikah45** [comment]
I linked it above and here https://github.com/reactor/reactor-netty/issues/1431
I haven't been able to find where it is tracked on netty itself though. But lots of stack overflow saying this was a resolution as well https://stackoverflow.com/questions/67075057/unknowhhostexception-using-spring-cloud-starter-gateway-with-spring-boot-2-4-0-a

**Comment by Sheikah45** [comment]
Received confirmation from some users that this fixes the problem

File: src/main/java/com/faforever/client/config/WebClientConfigurer.java [hunk 1]
```diff
@@ -0,0 +1,31 @@
...
+@RequiredArgsConstructor
+public class WebClientConfigurer implements WebClientCustomizer {
+  private final JsonApiWriter jsonApiWriter;
+  private final JsonApiReader jsonApiReader;
+
+  @Override
+  public void customize(WebClient.Builder webClientBuilder) {
+    HttpClient httpClient = HttpClient.create().resolver(DefaultAddressResolverGroup.INSTANCE);
+    ClientHttpConnector clientHttpConnector = new ReactorClientHttpConnector(httpClient);
+    webClientBuilder.defaultHeader("User-Agent", "downlords-faf-client")
```
Comment (micheljung) [inline src/main/java/com/faforever/client/config/WebClientConfigurer.java:24]: We're debranding the client and here we hardcode the user agent? :) nonono

IIRC there's already a property to be read, and I'd include the client version as well.

Comment (Sheikah45) [reply src/main/java/com/faforever/client/config/WebClientConfigurer.java:24]: I change all the user agents in the debrand pr. Also I did not see a property but can double check and change in the debrand pr.

Comment (Sheikah45) [reply src/main/java/com/faforever/client/config/WebClientConfigurer.java:24]: Also apparently the user agent for the webviews can't change unless the website is also changed because that is used to stop the header and footer from appearing
