### PR TITLE
Fixes #644

### LINKED ISSUE #623: Fix and remember selected mods
In the "Create Game" dialog, there is a list of mods:
image

However, selected mods are not yet activated in the game. Their UIDs needs to be written into the `game.prefs`. I thought I implemented this already but apparently, it's not/no longer there, or broken (but I can't even find `game.prefs` in the code).

After this has been implemented, the "Create Game" dialog needs to read the game.prefs in order to figure out which mods had been enabled in the last game and preselect them (mods can also be enabled within the game, and the client should be aware of that). Make sure that the client doesn't fail if no game.prefs yet exists.

### LINKED ISSUE #644: Create Button Text not updated

### PR DESCRIPTION
**Pull request by axel1200**
Fixes #623
Fixes that games with mods can be joined
Fixes the create game button text
Fixes Matchmaker Message before Login

(cherry picked from commit df1ad11)

### CODE REVIEW

**Comment by axel1200** [comment]
Codacy does not Analyse my branch

File: src/main/java/com/faforever/client/mod/ModServiceImpl.java [hunk 1]
```diff
@@ -176,7 +176,11 @@ public void loadInstalledMods() {
 
   @Override
   public CompletableFuture<Void> downloadAndInstallMod(String uid) {
-    return fafService.getMod(uid).thenAccept(mod -> downloadAndInstallMod(mod, null, null));
+    return fafService.getMod(uid).thenAccept(mod -> downloadAndInstallMod(mod, null, null))
+        .exceptionally(throwable -> {
+          logger.warn("Mod for modupdate not found", throwable);
+          return null;
+        });
```
Comment (micheljung) [inline src/main/java/com/faforever/client/mod/ModServiceImpl.java]: Whoever calls this method will now know that it failed (only the first `exceptionally` is ever called) so the game will start even though the mod could not be installed.

The error must, therefore, be handled in the calling code.
Also, the assumption "not found" isn't correct as there can be other reasons why an exception was thrown, like disconnect, server down, disk space full, file system permission, out of memory, and so on.

File: src/main/java/com/faforever/client/mod/ModServiceImpl.java [hunk 2]
```diff
@@ -242,7 +246,7 @@ public void enableSimMods(Set<String> simMods) throws IOException {
 
   @Override
   public boolean isModInstalled(String uid) {
-    return getInstalledUiModsUids().contains(uid) || getInstalledModUids().contains(uid);
+    return getInstalledModUids().contains(uid);
```
Comment (micheljung) [inline src/main/java/com/faforever/client/mod/ModServiceImpl.java]: Are we sure that we don't need check the UI mods as well? Both are mods. Otherwise, we need to rename the method. And I expect that this method is being used from the mod vault as well, so now UI mods will probably never been detected as installed.

File: src/main/java/com/faforever/client/game/CreateGameController.java [hunk 3]
```diff
@@ -206,6 +207,12 @@ private void initModList() {
     modListView.getSelectionModel().setSelectionMode(SelectionMode.MULTIPLE);
     modListView.setCellFactory(modListCellFactory());
     modListView.getItems().setAll(modService.getInstalledMods());
+    try {
+      modService.getActivatedSimAndUIMods().forEach(mod -> modListView.getSelectionModel().select(mod));
+    } catch (IOException e) {
+      logger.error("Activated Mods could not be loaded", e);
```
Comment (micheljung) [inline src/main/java/com/faforever/client/game/CreateGameController.java]: `mods`

File: src/main/java/com/faforever/client/game/CreateGameController.java [hunk 4]
```diff
@@ -331,6 +338,12 @@ public void onRandomMapButtonClicked() {
   public void onCreateButtonClicked() {
     ObservableList<Mod> selectedMods = modListView.getSelectionModel().getSelectedItems();
 
+    try {
+      modService.overrideActivatedMods(modListView.getSelectionModel().getSelectedItems());
+    } catch (IOException e) {
+      logger.warn("Activated Mods could not be updated", e);
```
Comment (micheljung) [inline src/main/java/com/faforever/client/game/CreateGameController.java]: `mods`

File: src/main/java/com/faforever/client/game/GameServiceImpl.java [hunk 5]
```diff
@@ -229,6 +229,13 @@ public ReadOnlyBooleanProperty gameRunningProperty() {
 
     return modService.getFeaturedMod(game.getFeaturedMod())
         .thenCompose(featuredModBean -> updateGameIfNecessary(featuredModBean, null, featuredModVersions, simModUIds))
+        .thenAccept(aVoid -> {
+          try {
+            modService.enableSimMods(simModUIds);
+          } catch (IOException e) {
+            logger.warn("SimMods were not enabled", e);
```
Comment (micheljung) [inline src/main/java/com/faforever/client/game/GameServiceImpl.java]: `SimMods could not be enabled`

File: src/main/java/com/faforever/client/mod/ModServiceImpl.java (hunk 2 above)
Comment (axel1200) [reply src/main/java/com/faforever/client/mod/ModServiceImpl.java]: getInstalledUiModsUids is obsolute because all UI Mods are also in the getInstalledMods....

Comment (axel1200) [reply src/main/java/com/faforever/client/mod/ModServiceImpl.java]: it is not necessary to check if it is in the UI Mods because all UI mods are also mods.... See the code of both methods and you will notice ;)
