### PR TITLE
Fix no effect of show modded games

### LINKED ISSUE #1198: Sometimes clicking "show moded games" has no effect

### PR DESCRIPTION
**Pull request by 1-alex98**
Fixes #1198

### CODE REVIEW

File: src/main/java/com/faforever/client/game/GamesTilesContainerController.java [hunk 1]
```diff
@@ -65,7 +62,7 @@ public GamesTilesContainerController(UiService uiService, PreferencesService pre
     };
 
     gameListChangeListener = change -> {
-      Platform.runLater(() -> {
+      JavaFxUtil.assertApplicationThread();
```
Comment (1-alex98) [inline src/main/java/com/faforever/client/game/GamesTilesContainerController.java:65]: run Later made certain actions to be executed in the wrong order and it is on the Application thread anyways because game updates are only done on the application thread

Comment (1-alex98) [reply src/main/java/com/faforever/client/game/GamesTilesContainerController.java:65]: Race conditions caused a malfunction in checkboxes or them having no effect

**Review by Geosearchef — APPROVED** [review]
