### PR TITLE
Fix circular dependency ReplayService <-> GameService

### LINKED ISSUE #1396: Circular dependency GameService <-> ReplayService
Makes builds deployed via installer crash on startup.

### PR DESCRIPTION
**Pull request by Katharsas**
**Makes installers work again.**
Split ReplayService:
- `ReplayFileService` for the important stuff that has to do with handling replay files and starting replays; maybe this name should be changed back to `ReplayService`
- `ReplayRemoteService`; i really don't know why these 1-line-methods even need to exist if they just wrap `ReplayServer` and `FafService` but ok, the `GameService` just wanted to use these.

Untangle ReplayServer / GameService

Fixes #1396

### CODE REVIEW

**Comment by Katharsas** [comment]
Ok seems like the client doesnt even start locally now.

**Comment by Katharsas** [comment]
Ok so now there is still a circular dependency between `GameService` and `ReplayServer` (since `GameService` depends on `ReplayRemoteService`).

Does anybody have an idea how to refactor this?
`ReplayServer` needs to call only one method `public Game getByUid(int uid)`. But i have not clear understanding of what exactly is inside `uidToGameInfoBean` and when, so is see no clear way to refactor.

**Comment by Katharsas** [comment]
Btw since i replaced member injection with constructor injection in this branch the circular dependencies will now cause every startup to fail, including local ones, so anybody can reproduce.

**Comment by Katharsas** [comment]
First circular dependency (solved):
Thinking about renaming `ReplayFileService` back to `ReplayService` to keep git history more readable and prevent a bunch of variable renaming otherwise needed. Opinions?

Second circular dependency:
The ReplayServer circle can be resolved by passing game supplier function to ReplayServer instead of ReplayServer querying GameService. Not pretty but i don't see alternatives since it is called from a separate thread inside ReplayServer which makes other solutions not pretty as well. Opinions?

Once ReplayServer is changed, this issue is solved and client installer can be built (see branch `hotfix/homepage-download`, where i implemented above suggestion).

**Comment by 1-alex98** [comment]
> First circular dependency (solved):
> Thinking about renaming `ReplayFileService` back to `ReplayService` to keep git history more readable and prevent a bunch of variable renaming otherwise needed. Opinions?
> 
> Second circular dependency:
> The ReplayServer circle can be resolved by passing game supplier function to ReplayServer instead of ReplayServer querying GameService. Not pretty but i don't see alternatives since it is called from a separate thread inside ReplayServer which makes other solutions not pretty as well. Opinions?
> 
> Once ReplayServer is changed, this issue is solved and client installer can be built (see branch `hotfix/homepage-download`, where i implemented above suggestion).

You will need to explain that to me maybe discord?

**Review by 1-alex98 — APPROVED** [review]

File: src/main/java/com/faforever/client/replay/ReplayServerImpl.java [hunk 1]
```diff
@@ -179,12 +176,13 @@ private void recordAndRelay(int uid, ServerSocket serverSocket, @Nullable Output
...
     log.debug("FAF has disconnected, writing replay data to file");
-    finishReplayInfo();
+    finishReplayInfo(onGameInfoFinished);
     replayFileWriter.writeReplayDataToFile(replayData, replayInfo);
   }
 
-  private void finishReplayInfo() {
-    Game game = gameService.getByUid(replayInfo.getUid());
+  private void finishReplayInfo(Supplier<Game> onGameInfoFinished) {
+    // game needs to running or finished
```
Comment (1-alex98) [inline src/main/java/com/faforever/client/replay/ReplayServerImpl.java]: Remove

**Review by 1-alex98 — CHANGES_REQUESTED** [review]

**Comment by 1-alex98** [comment]
build it and tested it

**Review by 1-alex98 — APPROVED** [review]
