### PR TITLE
Fix executable decorator not being always applied

### LINKED ISSUE #1066: Launch command decorator is not always applied
When you try to launch a local replay on Linux for example, the client will bug out about 'no permission to run file' since the 'wine foo %s' decorator is not being applied. The problem stems from ForgedAllianceService not passing executableDecorator to LaunchCommandBuilder in some cases. The builder is intended to always require it, but the decorator is set to "%s"' rather than null in the constructor, so the check does nothing.

### PR DESCRIPTION
**Pull request by Wesmania**
Fixes #1066.

Signed-off-by: Igor Kotrasinski <i.kotrasinsk@gmail.com>

### CODE REVIEW

**Review by micheljung — APPROVED** [review]

File: src/main/java/com/faforever/client/fa/LaunchCommandBuilder.java [hunk 1]
```diff
@@ -36,7 +36,7 @@
   private Integer localReplayPort;
 
   private LaunchCommandBuilder() {
-    executableDecorator = "\"%s\"";
+    executableDecorator = null;
```
Comment (micheljung) [inline src/main/java/com/faforever/client/fa/LaunchCommandBuilder.java]: `null` is default, so this is redundant. Whole constructor can be removed

**Review by micheljung — DISMISSED** [review]

**Review by 1-alex98 — DISMISSED** [review]
