### PR TITLE
Show only unique players and add date column in coop tab

### LINKED ISSUE #2703: COOP Leaderboards Update
Update Leaderboard to only display users fastest time & the date of when this was completed on

- [ ] Add Date of completion
- [ ] Only display usres fasted time

image

### LINKED ISSUE #2705: Repair broken delimiter of list players in coop table
Try to open list with count of players more than 1
image

### LINKED ISSUE #2715: Repair broken delimiter of mods in live games
image

### PR DESCRIPTION
**Pull request by Marc-Spector**
At the request of `Rowey` Promotions Team Leader
Closes #2703
Closes #2705 
Closes #2715 

image

### CODE REVIEW

File: src/main/java/com/faforever/client/coop/CoopController.java [hunk 1]
```diff
@@ -172,9 +177,7 @@ private String coopMissionFromFolderNamer(List<CoopMissionBean> coopMaps, String
   }
 
   private String commaDelimitedPlayerList(CoopResultBean coopResult) {
-    return coopResult.getReplay().getTeams().values().stream()
-        .flatMap(List::stream)
-        .collect(Collectors.joining(i18n.get("textSeparator")));
+    return String.join(", ", coopResult.getReplay().getTeams().values().stream().flatMap(List::stream).toList());
```
Comment (Sheikah45) [inline src/main/java/com/faforever/client/coop/CoopController.java]: Why was this changed to not use the internationalized separator? Also the Collectors.joining is the preferred method since we are already using the stream api.

File: src/main/java/com/faforever/client/domain/CoopResultBean.java [hunk 2]
```diff
@@ -18,6 +18,7 @@
 public class CoopResultBean {
   @EqualsAndHashCode.Include
   ObjectProperty<Integer> id = new SimpleObjectProperty<>();
+  // TODO: Why returns `null` value?
```
Comment (Sheikah45) [inline src/main/java/com/faforever/client/domain/CoopResultBean.java]: Probably is just old data that doesn't have playerNames

File: src/main/java/com/faforever/client/coop/CoopController.java [hunk 3]
```diff
@@ -232,6 +236,12 @@ private void loadLeaderboard() {
         });
   }
 
+  private List<CoopResultBean> filterOnlyUniquePlayers(List<CoopResultBean> result) {
+    Set<String> uniquePlayerNames = new HashSet<>();
+    result.removeIf(coopResult -> !uniquePlayerNames.add(commaDelimitedPlayerList(coopResult)));
+    return result;
+  }
```
Comment (Sheikah45) [inline src/main/java/com/faforever/client/coop/CoopController.java]: This doesn't work if the players are in a different order. I would use something like an unmodifiable set as the key

**Review by Sheikah45 — CHANGES_REQUESTED** [review]

File: src/main/java/com/faforever/client/coop/CoopController.java (hunk 1 above)
Comment (Marc-Spector) [reply src/main/java/com/faforever/client/coop/CoopController.java]: > Why was this changed to not use the internationalized separator?

Usually this only applies to numbers, doesn't it?

> Also the Collectors.joining is the preferred method since we are already using the stream API.

Weird. The IDE suggested that it's better to use this instead. Ok, I will fix it

File: src/main/java/com/faforever/client/domain/CoopResultBean.java (hunk 2 above)
Comment (Marc-Spector) [reply src/main/java/com/faforever/client/domain/CoopResultBean.java]: Can I remove it?

File: src/main/java/com/faforever/client/coop/CoopController.java (hunk 3 above)
Comment (Marc-Spector) [reply src/main/java/com/faforever/client/coop/CoopController.java]: Yes, it won't work if we remove the sort rule:
https://github.com/FAForever/downlords-faf-client/blob/ccef5b08309528993f4ee2a4fdc6c778015d8413/src/main/java/com/faforever/client/coop/CoopService.java#L51

Comment (Sheikah45) [reply src/main/java/com/faforever/client/coop/CoopController.java]: That is sorting on the replay not on the players or the teams

File: src/main/java/com/faforever/client/domain/CoopResultBean.java (hunk 2 above)
Comment (Sheikah45) [reply src/main/java/com/faforever/client/domain/CoopResultBean.java]: is it used anywhere?

File: src/main/java/com/faforever/client/coop/CoopController.java (hunk 1 above)
Comment (Sheikah45) [reply src/main/java/com/faforever/client/coop/CoopController.java]: the text separator applies to text numbers is something different.

File: src/main/java/com/faforever/client/domain/CoopResultBean.java (hunk 2 above)
Comment (Marc-Spector) [reply src/main/java/com/faforever/client/domain/CoopResultBean.java]: Nope

**Review by Sheikah45 — APPROVED** [review]
