### PR TITLE
Local replay vault watching/reloading

### LINKED ISSUE #1141: Local replays not updating till client restarted
Can we at least have a refresh button for local replays as I don't think any local replays of games in the current session are shown. Client needs to be restarted.

### LINKED ISSUE #1506: Local Replay Vault not refreshed after games played
**Describe the bug**
After the local replay vault has been loaded once, it is never refreshed to include additional games. The only way to refresh it seems to be to restart the client, which does work reliably to display all recent replays.

**To Reproduce**
1. Open client
2. Show local replay vault
3. Play a game
4. Show local replay vault 

**Expected behavior**
The replays of all recent games should be displayed.

**OS / Version**
Windows 10, Client v1.0.0

### PR DESCRIPTION
**Pull request by andreasley**
Fixes #1141.

This patch implements lazy loading of the local replay vault and automatic updates when replays have been added to or removed from the local replay directory.

- Uses WatchEvents to detect changes in the local replay directory
- Works for both played games and manually added/removed replay files
- Updates the list accordingly and respects previous sorting
- Replays from played games are now written to the cache directory first and then moved atomically  to the replays directory to prevent parsing it before it is written
- No changes to UI

Test coverage is not great. What would you like to have tested exactly?

It's been 10 years or so since I've written any Java, so be gentle. ;)

### CODE REVIEW

File: src/main/java/com/faforever/client/replay/ReplayService.java [hunk 1]
```diff
@@ -111,6 +127,85 @@
...
+      localReplays.clear();
+      localReplays.addAll(replays);
+      eventBus.post(new LocalReplaysChangedEvent(replays, new ArrayList<Replay>()));
+    });
+
+    try {
+      Optional.ofNullable(directoryWatcherThread).ifPresent(Thread::interrupt);
+      directoryWatcherThread = startDirectoryWatcher(replaysDirectory);
+    } catch (IOException e) {
+      logger.debug("Failed to start watching the local replays directory");
```
Comment (Brutus5000) [inline src/main/java/com/faforever/client/replay/ReplayService.java]: Should be a warn at least, otherwise it will not end up in logs. Also append the exception as parameter to the logger, so it will print the stacktrace.

File: src/main/java/com/faforever/client/replay/ReplayService.java [hunk 2]
```diff
@@ -111,6 +127,85 @@
...
+
+    LoadLocalReplaysTask loadLocalReplaysTask = applicationContext.getBean(LoadLocalReplaysTask.class);
+    taskService.submitTask(loadLocalReplaysTask).getFuture().thenAccept( replays -> {
+      localReplays.clear();
+      localReplays.addAll(replays);
+      eventBus.post(new LocalReplaysChangedEvent(replays, new ArrayList<Replay>()));
+    });
+
+    try {
+      Optional.ofNullable(directoryWatcherThread).ifPresent(Thread::interrupt);
```
Comment (Brutus5000) [inline src/main/java/com/faforever/client/replay/ReplayService.java:148]: I am not entirely sure, when would this happen? Is this a regular case?

File: src/main/java/com/faforever/client/replay/ReplayService.java [hunk 3]
```diff
@@ -156,35 +251,59 @@ static String guessModByFileName(String fileName) {
...
-    }
+    DirectoryStream<Path> directoryStream = Files.newDirectoryStream(replaysDirectory, replayFileGlob);
+    List<CompletableFuture<Replay>> replayFutures = StreamSupport.stream(directoryStream.spliterator(), false)
+        .sorted(Comparator.comparing(path -> noCatch(() -> Files.getLastModifiedTime((Path) path))).reversed())
+        .limit(MAX_REPLAYS)
+        .map( replayFile -> {
+          try {
+            return loadLocalReplay(replayFile);
+          } catch (Exception e) {
+            // do nothing; notification should already be shown to user
```
Comment (Brutus5000) [inline src/main/java/com/faforever/client/replay/ReplayService.java]: Before doing nothing, trace-log it instead

File: src/test/java/com/faforever/client/vault/replay/ReplayVaultControllerTest.java [hunk 4]
```diff
@@ -78,24 +74,22 @@ public void testGetRoot() throws Exception {
 
   @Test
   public void testLoadLocalReplaysInBackground() throws Exception {
-    LoadLocalReplaysTask task = mock(LoadLocalReplaysTask.class);
-    when(task.getFuture()).thenReturn(CompletableFuture.completedFuture(Arrays.asList(
+
+    var replays = Arrays.asList(
```
Comment (Brutus5000) [inline src/test/java/com/faforever/client/vault/replay/ReplayVaultControllerTest.java]: We don't use var in this codebase.

File: src/main/java/com/faforever/client/replay/ReplayService.java [hunk 5]
```diff
@@ -156,35 +251,59 @@ static String guessModByFileName(String fileName) {
...
+            return null;
+          }
+        })
+        .filter(replay -> replay != null)
```
Comment (Brutus5000) [inline src/main/java/com/faforever/client/replay/ReplayService.java]: Objects::requireNonNull

**Review by Brutus5000 — CHANGES_REQUESTED** [review]
Did not look into that composing of CompletableFutures. The whole joining futures thing seems a bit odd, but I'm no expert on it and don't have the time to dig deeper into it right now.

File: src/main/java/com/faforever/client/replay/ReplayService.java (hunk 2 above)
Comment (andreasley) [reply src/main/java/com/faforever/client/replay/ReplayService.java:148]: In theory, never. In practice, some tests or future code might try to call the method multiple times. This line prevents multiple parallel threads with a watcher for this directory. I've borrowed this line from where another watcher was already implemented in the client.

File: src/main/java/com/faforever/client/replay/ReplayService.java (hunk 3 above)
Comment (andreasley) [reply src/main/java/com/faforever/client/replay/ReplayService.java]: The method `loadLocalReplay` already logs the exception, that's why I omitted it here.

File: src/main/java/com/faforever/client/replay/ReplayService.java (hunk 5 above)
Comment (andreasley) [reply src/main/java/com/faforever/client/replay/ReplayService.java]: Not the same thing though; this line filters out entries that are null from a stream. I'm personally not a big fan of chained method calls, but streams sometimes don't easily allow another way. A stream was already used here and I tried to limit my changes to a minimum for my first PR. :)

Comment (Brutus5000) [reply src/main/java/com/faforever/client/replay/ReplayService.java]: Sorry wrong method. Objects::nonNull does the same as the lambda

File: src/main/java/com/faforever/client/replay/ReplayService.java (hunk 1 above)
Comment (andreasley) [reply src/main/java/com/faforever/client/replay/ReplayService.java]: Fixed.

File: src/test/java/com/faforever/client/vault/replay/ReplayVaultControllerTest.java (hunk 4 above)
Comment (andreasley) [reply src/test/java/com/faforever/client/vault/replay/ReplayVaultControllerTest.java]: Fixed.

File: src/main/java/com/faforever/client/main/event/LocalReplaysChangedEvent.java [hunk 6]
```diff
@@ -0,0 +1,13 @@
+package com.faforever.client.main.event;
+
+import com.faforever.client.replay.Replay;
+import lombok.Data;
+
+import java.util.Collection;
+
+@Data
+public class LocalReplaysChangedEvent {
```
Comment (norraxx) [inline src/main/java/com/faforever/client/main/event/LocalReplaysChangedEvent.java]: Does data holder class represents `event`?

Comment (norraxx) [reply src/main/java/com/faforever/client/main/event/LocalReplaysChangedEvent.java]: I mean maybe we could give here better naming.

File: src/main/java/com/faforever/client/vault/replay/ReplayVaultController.java [hunk 7]
```diff
@@ -104,8 +114,22 @@ public void initialize() {
...
+      loadLocalReplaysInBackground();
+      isDisplayingForFirstTime = false;
+    }
 
-    loadLocalReplaysInBackground();
+    super.onDisplay(navigateEvent);
+  }
+
+  protected void loadLocalReplaysInBackground() {
+    // TODO: Display information that view contents are loading
```
Comment (norraxx) [inline src/main/java/com/faforever/client/vault/replay/ReplayVaultController.java]: Is something "blocking" us to not to have TODO? I mean, if we leave that todo here, this will stay for ages :-)

File: src/test/java/com/faforever/client/replay/ReplayServiceTest.java [hunk 8]
```diff
@@ -122,13 +139,17 @@
...
+  @Mock
+  private EventBus eventBus;
+  @Mock
+  private ExecutorService executorService;
 
   @Before
   public void setUp() throws Exception {
     MockitoAnnotations.initMocks(this);
 
     instance = new ReplayService(new ClientProperties(), preferencesService, replayFileReader, notificationService, gameService,
```
Comment (norraxx) [inline src/test/java/com/faforever/client/replay/ReplayServiceTest.java:151]: I would like to rename that `instance`... For example to that `replayService`

Comment (norraxx) [reply src/test/java/com/faforever/client/replay/ReplayServiceTest.java:151]: Same to below, but it's just nice to have :-)

File: src/main/java/com/faforever/client/vault/replay/ReplayVaultController.java [hunk 9]
```diff
@@ -53,12 +59,13 @@
...
 
 import static java.util.Arrays.asList;
+import static java.util.Arrays.setAll;
 
 @Component
 @Scope(ConfigurableBeanFactory.SCOPE_PROTOTYPE)
 @RequiredArgsConstructor
 // TODO reduce dependencies
-public class ReplayVaultController implements Controller<Node> {
+public class ReplayVaultController extends AbstractViewController<Node> {
```
Comment (norraxx) [inline src/main/java/com/faforever/client/vault/replay/ReplayVaultController.java:59]: 👍

File: src/main/java/com/faforever/client/replay/ReplayService.java (hunk 3 above)
Comment (norraxx) [reply src/main/java/com/faforever/client/replay/ReplayService.java]: Ok, then, why do we need to raise exception from `loadLocalReplay`? Maybe just ommit it, if everything is logged and "fixed"?

File: src/main/java/com/faforever/client/replay/ReplayService.java [hunk 10]
```diff
@@ -111,6 +127,85 @@
...
+          loadLocalReplay(fullPathToReplay)
+              .thenAccept(newReplay -> {
+                newReplays.add(newReplay);
+              });
+        } catch (Exception e) {
+          logger.warn("Failed to load local replay file '{}'", path, e);
+        }
+
+      } else if (watchEvent.kind() == ENTRY_DELETE) {
+        Optional<Replay> existingReplay = localReplays.stream().filter(replay -> replay.getReplayFile().compareTo(fullPathToReplay) == 0).findFirst();
```
Comment (norraxx) [inline src/main/java/com/faforever/client/replay/ReplayService.java]: IMHO too long line.

**Review by norraxx — COMMENTED** [review]
For me just "nice to have" small things.

**Comment by norraxx** [comment]
Good job! ;-)

File: src/main/java/com/faforever/client/main/event/LocalReplaysChangedEvent.java (hunk 6 above)
Comment (andreasley) [reply src/main/java/com/faforever/client/main/event/LocalReplaysChangedEvent.java]: Not sure what you mean. The `@Data` annotation is part of Lombok and automatically generates getters/setters etc.

File: src/main/java/com/faforever/client/vault/replay/ReplayVaultController.java (hunk 7 above)
Comment (andreasley) [reply src/main/java/com/faforever/client/vault/replay/ReplayVaultController.java]: :D 
I do believe that small incremental improvements are better than big changesets. That said, I'd promise to look at that TODO once the PR is merged. :)

File: src/test/java/com/faforever/client/replay/ReplayServiceTest.java (hunk 8 above)
Comment (andreasley) [reply src/test/java/com/faforever/client/replay/ReplayServiceTest.java:151]: This one is actually not from me. :) In all tests on this project, the respective object is stored in a property named `instance`.

Comment (norraxx) [reply src/test/java/com/faforever/client/replay/ReplayServiceTest.java:151]: Yes, i know.

File: src/main/java/com/faforever/client/replay/ReplayService.java (hunk 3 above)
Comment (andreasley) [reply src/main/java/com/faforever/client/replay/ReplayService.java]: Right you are.

File: src/main/java/com/faforever/client/main/event/LocalReplaysChangedEvent.java (hunk 6 above)
Comment (Brutus5000) [reply src/main/java/com/faforever/client/main/event/LocalReplaysChangedEvent.java]: To be more precise, the event is a value type right? (Create once, read only)
In this case @Value would be the better lombok annotation as it makes the variables final and the object immutable.

**Review by Geosearchef — DISMISSED** [review]
please squash commits

File: src/main/java/com/faforever/client/main/event/LocalReplaysChangedEvent.java (hunk 6 above)
Comment (andreasley) [reply src/main/java/com/faforever/client/main/event/LocalReplaysChangedEvent.java]: Changed.

File: src/main/java/com/faforever/client/vault/replay/ReplayVaultController.java (hunk 7 above)
Comment (andreasley) [reply src/main/java/com/faforever/client/vault/replay/ReplayVaultController.java]: Fixed.

File: src/main/java/com/faforever/client/replay/ReplayService.java [hunk 11]
```diff
@@ -155,36 +245,52 @@ static String guessModByFileName(String fileName) {
...
-
-              mapService.findByMapFolderName(replayInfo.getMapname())
-                  .thenAccept(mapBean -> replayInfos.add(new Replay(replayInfo, replayFile, featuredMod, mapBean.orElse(null))));
-            } catch (Exception e) {
-              logger.warn("Could not read replay file '{}'", replayFile, e);
-              moveCorruptedReplayFile(replayFile);
-            }
-          });
-    }
+    DirectoryStream<Path> directoryStream = Files.newDirectoryStream(replaysDirectory, replayFileGlob);
```
Comment (Brutus5000) [inline src/main/java/com/faforever/client/replay/ReplayService.java]: Why was try-with-resources removed? Now we have an unclosed stream.

File: src/main/java/com/faforever/client/replay/ReplayService.java [hunk 12]
```diff
@@ -111,6 +125,82 @@
   private final FafService fafService;
   private final ModService modService;
   private final MapService mapService;
+  private final EventBus eventBus;
```
Comment (1-alex98) [inline src/main/java/com/faforever/client/replay/ReplayService.java]: We try to not use EventBus any longer but use ApplicationPublisher from Spring for new changes / features etc.

**Review by 1-alex98 — CHANGES_REQUESTED** [review]

File: src/main/java/com/faforever/client/replay/ReplayService.java (hunk 12 above)
Comment (andreasley) [reply src/main/java/com/faforever/client/replay/ReplayService.java]: @Brutus5000 said the opposite in Zulip. Which one is it? :)

Comment (1-alex98) [reply src/main/java/com/faforever/client/replay/ReplayService.java]: EventBus is deprecated

Comment (1-alex98) [reply src/main/java/com/faforever/client/replay/ReplayService.java]: If he said the opposite he got it the wrong way arround

Comment (andreasley) [reply src/main/java/com/faforever/client/replay/ReplayService.java]: I misremembered; @Brutus5000 said to use Spring. @Geosearchef and @norraxx, however, seemed to prefer EventBus. I really don't mind either way, just want to be sure we're all on the same page.
I can't find anything about `EventBus` being deprecated. Where did you hear that?

Comment (1-alex98) [reply src/main/java/com/faforever/client/replay/ReplayService.java]: Sorry i meant unstable/Beta 
image

Comment (1-alex98) [reply src/main/java/com/faforever/client/replay/ReplayService.java]: I think it was even marked with unstable in older guava versions, also we wanna stay with Spring. In the beginning tho nobody knew Spring had an Event System as well.

Comment (andreasley) [reply src/main/java/com/faforever/client/replay/ReplayService.java]: I've replaced `EventBus` with Spring methods for this PR.
Since Spring's event system works a bit differently, I had to remove the `@Scope(ConfigurableBeanFactory.SCOPE_PROTOTYPE)` from the ReplayVaultController, because otherwise, Spring would instantiate a new controller whenever the Event was triggered.

**Review by Brutus5000 — CHANGES_REQUESTED** [review]

File: src/main/java/com/faforever/client/replay/ReplayService.java (hunk 11 above)
Comment (andreasley) [reply src/main/java/com/faforever/client/replay/ReplayService.java]: An oversight. Thanks for noticing!

**Review by Brutus5000 — APPROVED** [review]

File: src/main/java/com/faforever/client/main/event/LocalReplaysChangedEvent.java [hunk 13]
```diff
@@ -2,12 +2,27 @@
 
 import com.faforever.client.replay.Replay;
 import lombok.Value;
+import org.springframework.context.ApplicationEvent;
 
 import java.util.Collection;
 
-@Value
-public class LocalReplaysChangedEvent {
+public class LocalReplaysChangedEvent extends ApplicationEvent {
```
Comment (1-alex98) [inline src/main/java/com/faforever/client/main/event/LocalReplaysChangedEvent.java:9]: Extending Application Event is not needed

Comment (1-alex98) [reply src/main/java/com/faforever/client/main/event/LocalReplaysChangedEvent.java:9]: I mean u can for sure it won't hurt, we did not do this in any other cases :thinking: not sure whats best here

**Review by 1-alex98 — APPROVED** [review]
