### PR TITLE
Fix replays show wrong game quality

### LINKED ISSUE #738: Game quality not shown correctly in replays
image

### PR DESCRIPTION
**Pull request by micheljung**
Fixed it to show the proper quality. Added '%' for clarity.
Fixes #738

### CODE REVIEW

File: src/main/java/com/faforever/client/rating/JSkillsRatingService.java [hunk 1]
```diff
@@ -38,6 +38,6 @@ public double calculateQuality(Replay replay) {
           ));
           return team;
         })
-        .collect(Collectors.toList()));
+        .collect(Collectors.toList())) * 100;
```
Comment (micheljung) [inline src/main/java/com/faforever/client/rating/JSkillsRatingService.java]: Since this is an internal, technical value, we keep it 0.0 - 1.0. To display, this can be multiplied by 100.

File: src/main/java/com/faforever/client/replay/ReplayCardController.java [hunk 2]
```diff
@@ -85,7 +85,7 @@ public void setReplay(Replay replay) {
     timeLabel.setText(timeService.asShortTime(replay.getStartTime()));
     modLabel.setText(replay.getFeaturedMod().getDisplayName());
     playerCountLabel.setText(i18n.number(replay.getTeams().values().stream().mapToInt(List::size).sum()));
-    qualityLabel.setText(i18n.number((int) ((ratingService.calculateQuality(replay) * 10) / 10)));
+    qualityLabel.setText(i18n.number((int) ((ratingService.calculateQuality(replay) * 10) / 10)) + " %");
```
Comment (micheljung) [inline src/main/java/com/faforever/client/replay/ReplayCardController.java]: Instead of hard-coding `+ " %"` we use i18n which allows using different symbols and also different text directions (right-to-left).

There's already a key `percentage` (IIRC) that can be used.

**Comment by micheljung** [comment]
@20seven I saw this branch/commit and created a pull request for you :)
