### PR TITLE
Remove Exception on startup

### LINKED ISSUE #1021: Exception on startup
```
java.lang.RuntimeException: Exception in Application start method
    at javafx.graphics/com.sun.javafx.application.LauncherImpl.launchApplication1(Unknown Source)
    at javafx.graphics/com.sun.javafx.application.LauncherImpl.lambda$launchApplication$2(Unknown Source)
    at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NullPointerException
    at com.faforever.client.FafClientApplication.showMainWindow(FafClientApplication.java:92)
    at com.faforever.client.FafClientApplication.start(FafClientApplication.java:77)
    at javafx.graphics/com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$9(Unknown Source)
    at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runAndWait$11(Unknown Source)
    at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$9(Unknown Source)
    at java.base/java.security.AccessController.doPrivileged(Native Method)
    at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$10(Unknown Source)
    at javafx.graphics/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(Unknown Source)
    at javafx.graphics/com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
    at javafx.graphics/com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(Unknown Source)
    ... 1 more
```

### PR DESCRIPTION
**Pull request by 1-alex98**
Fixes #1021 see issue comments

### CODE REVIEW

**Review by micheljung — APPROVED** [review]

File: src/main/java/com/faforever/client/FafClientApplication.java [hunk 1]
```diff
@@ -64,10 +65,21 @@ public void init() {
...
+          .profiles(getAdditionalProfiles())
+          .bannerMode(Mode.OFF)
+          .run(getParameters().getRaw().toArray(new String[0]));
+      runAndWaitLatch.countDown();
+    });
+
+    try {
+      runAndWaitLatch.await();
+    } catch (InterruptedException e) {
+      e.printStackTrace();
```
Comment (micheljung) [inline src/main/java/com/faforever/client/FafClientApplication.java]: re-throw or log, but never printStacktrace()

**Review by micheljung — CHANGES_REQUESTED** [review]

File: src/main/java/com/faforever/client/FafClientApplication.java (hunk 1 above)
Comment (1-alex98) [reply src/main/java/com/faforever/client/FafClientApplication.java]: ok

**Review by micheljung — APPROVED** [review]
