### PR TITLE
Native window behavior and design brush-up

### LINKED ISSUE #1007: Win10 Window-snapping tools don't affect this program
I use Aquasnap. There is a free version if you wish to investigate.

### LINKED ISSUE #1033: Bottom bar text position
slack_2018-11-13_18-13-13

Text in the bottom bar () could be a (few) pixels higher, so it is in the center, currently it looks like its cut off a bit. (just my OCD kicking in...)

### LINKED ISSUE #1038: Resize problem
So I managed to resize the client to like 1px x 1px, and no way to get it back :D
I dont think it should allow you to resize under some reasonable size.

When I start the client, its maximized, but clickin this button changes it back to 1px 
downlords-faf-client_2018-11-14_17-57-25

### LINKED ISSUE #1075: Double clicking on FAF logo makes the client fullscreen
Not present in 0.8.0
In 0.9.0 upwards double clicking anywhere on the window makes it go fullscreen.
It's great, except when it conflicts with other commands and makes the client fullscreen when it was not intended. Double clicking on the FAF logo is the only way to access connection parameters.
Maybe either make the FAF logo single click, or remove the fullscreen on double click if the click is eaten by another command ?

### LINKED ISSUE #1685: Switching between Table and Tiles messes up layout
Custom game list:
If any column's size in the table view is manually adjusted, switching to tiles and back will lead to messed up column sizes.

https://www.youtube.com/watch?v=pNlpoudtSGo

### LINKED ISSUE #1751: Connection text doesn't scale right
Seems like if you shrink your window size, the "connected to faf" and "connected to chat" indicators don't consume the available space correctly. I feel like they should be able to take up more of that empty space. I guess the only question is what happens to the "downloading xxxxxxx" text?

image

**OS**
Linux
(this is on the TMM branch but I don't think that matters)

**Wanna have the bug fixed quickly?**
Visit Issue hunt...
[Issue hunt](https://issuehunt.io/r/FAForever/downlords-faf-client)

### LINKED ISSUE #1760: Immediate Notifications not working on java fx 14
**Describe the bug**
If there is an Exception and an Immediate Notification is supposed to be opened instead an Exception is throwen about being unable to open such a window.

**OS**
Linux or Windows

**Wanna have the bug fixed quickly?**
Visit Issue hunt...
[Issue hunt](https://issuehunt.io/r/FAForever/downlords-faf-client)

### LINKED ISSUE #1766: Layout issue in online replays
**Describe the bug**
The random faction icon (?) in the Line-Up seems to have a different margin then the other faction icons.

**To Reproduce**
Open the replays in the online replay vault.

**Expected behavior**
All users have the same space between them

**Screenshots**
Replay id #9621034
image

Replay id #10678526
image

**OS**
Linux (javafx 11 and 14)

**Wanna have the bug fixed quickly?**
Visit Issue hunt...
[Issue hunt](https://issuehunt.io/r/FAForever/downlords-faf-client)

### LINKED ISSUE #1815: Design brush-up
I guess nobody is a big fan of the current design. Also, the client uses JFoenix to implement Material design but the whole thing doesn't really look Materia Design-ish. Using JFoenix has prevented us from upgrading Java in the past, too.

Therefore:
- Brush-up the client design
- Replace JFoenix where easily possible (text input, buttons)

### LINKED ISSUE #1816: Native window behavior
The client currently uses an implementation of https://github.com/goxr3plus/FX-BorderlessScene for its window handling which is pretty ugly.
There's no native Aero snap and resizing is only possible *on* the window, not outside of it, interfering with e.g. scrollbars.

I was able to implement Windows-native Window behavior in JavaFX with https://github.com/micheljung/fxstage which is now ready to be used in the client.

Only for Windows 10.

On Linux and Windows 7, it falls back to an improved version of BorderlessScene (with shadow and improved resize border). However, it's not very well tested and still has some minor bugs.

### LINKED ISSUE #1817: Dropdown when not all navigation items can be shown
image

### PR DESCRIPTION
**Pull request by micheljung**
Fixes #1007
image

Fixes #1033
image

Fixes #1038
It's not visible on the screenshot, but the window can always be resized now:
image

Fixes #1075
Fixes #1685
Fixes #1751
image

Fixes #1760
Fixes #1766
image

Fixes #1815
image
image
image
image
image
image
image

Fixes #1816
Fixes #1817
image

### CODE REVIEW

File: src/main/java/com/faforever/client/FafClientApplication.java [hunk 1]
```diff
@@ -115,8 +117,12 @@ public PlatformService platformService() {
...
 
-  private void showMainWindow() {
-    MainController controller = applicationContext.getBean(UiService.class).loadFxml("theme/main.fxml");
+  private void showMainWindow(FxStage fxWindow) {
+    UiService uiService = applicationContext.getBean(UiService.class);
+
+    MainController controller = uiService.loadFxml("theme/main.fxml");
+
+    controller.setFxStage(fxWindow);
     controller.display();
```
Comment (Brutus5000) [inline src/main/java/com/faforever/client/FafClientApplication.java]: This seems like 2 calls  the UI service could do as well (or at least the setFxStage). What do you think?

File: src/main/java/com/faforever/client/FafClientApplication.java [hunk 2]
```diff
@@ -127,7 +133,7 @@ public void stop() throws Exception {
 
     Thread timeoutThread = new Thread(() -> {
       try {
-        Thread.sleep(Duration.ofSeconds(30).toMillis());
+        Thread.sleep(Duration.ofSeconds(10).toMillis());
       } catch (InterruptedException e) {
       }
```
Comment (Brutus5000) [inline src/main/java/com/faforever/client/FafClientApplication.java:137]: Unrelated question: Why is there no return here? Or at least a log statement to catch potential user problems?

File: src/main/java/com/faforever/client/fx/IconCell.java [hunk 3]
```diff
@@ -0,0 +1,49 @@
...
+
+  public IconCell(Function<T, String> iconCssClassFunction) {
+    this(iconCssClassFunction, Pos.CENTER_LEFT);
+  }
+
+  public IconCell(Function<T, String> iconCssClassFunction, Pos alignment, String... containerCssClasses) {
+    this.iconCssClassFunction = iconCssClassFunction;
+    this.alignment = alignment;
+    this.containerCssClasses = containerCssClasses;
+  }
```
Comment (Brutus5000) [inline src/main/java/com/faforever/client/fx/IconCell.java]: Could be replaced by Lomboks AllArgConstructor

File: src/main/java/com/faforever/client/main/MainController.java [hunk 4]
```diff
@@ -201,16 +205,33 @@ public void initialize() {
...
+
+    List<MenuItem> menuItems = leftMenuPane.getChildrenUnmodifiable().stream()
+        .filter(menuItem -> menuItem.getUserData() instanceof NavigationItem)
+        .map(menuButton -> {
+          MenuItem menuItem = new MenuItem(((Labeled) menuButton).getText());
+          menuItem.setOnAction(event -> eventBus.post(new NavigateEvent((NavigationItem) menuButton.getUserData())));
+          return menuItem;
+        })
+        .collect(Collectors.toList());
+    navigationDropdown.getItems().setAll(menuItems);
```
Comment (Brutus5000) [inline src/main/java/com/faforever/client/main/MainController.java]: Instead of collection and addAll you could do a foreach and add
Maybe extract the stream into a tiny method

File: src/main/java/com/faforever/client/preferences/ui/RemovableListCellController.java [hunk 5]
```diff
@@ -0,0 +1,36 @@
...
+
+  @Override
+  public Pane getRoot() {
+    return removableCellRoot;
+  }
+
+  public void setChannel(String channel) {
+    label.setText(channel);
+  }
+}
```
Comment (Brutus5000) [inline src/main/java/com/faforever/client/preferences/ui/RemovableListCellController.java]: The complexity of this class is very high and self-explanatory code is not given here anymore imho.
Either a Javadoc or some other kind of restructuring is necessary:

- The parent is implicitly expected to be a list cell - but you only see this from the cast in line 23.
- There is a onRemoveButtonClicked method, but nowhere is stated that this controller is supposed to contain a button. So the name is misleading here.
- Also the purpose of the label remains unclear. What is "channel" supposed to be?

File: src/main/java/com/faforever/client/ui/dialog/Dialog.java [hunk 6]
```diff
@@ -0,0 +1,540 @@
...
+    }
+
+    @Override
+    public Object getBean() {
+      return Dialog.this;
+    }
+
+    @Override
+    public String getName() {
+      return "onOpened";
```
Comment (Brutus5000) [inline src/main/java/com/faforever/client/ui/dialog/Dialog.java:92]: What is this value referring to? A translation code?

File: src/main/java/com/faforever/client/ui/dialog/Dialog.java [hunk 7]
```diff
@@ -0,0 +1,540 @@
...
+    initChangeListeners();
+  }
+
+  public Dialog(StackPane dialogContainer, Region content, DialogTransition transitionType, boolean overlayClose) {
+    setOverlayClose(overlayClose);
+    initialize();
+    setContent(content);
+    setDialogContainer(dialogContainer);
+    this.transitionType.set(transitionType);
+    // init change listeners
```
Comment (Brutus5000) [inline src/main/java/com/faforever/client/ui/dialog/Dialog.java]: Thanks captain! Comment can be removed

File: src/main/java/com/faforever/client/ui/dialog/DialogLayout.java [hunk 8]
```diff
@@ -0,0 +1,64 @@
...
+import javafx.collections.ObservableList;
+import javafx.scene.Node;
+import javafx.scene.layout.FlowPane;
+import javafx.scene.layout.Priority;
+import javafx.scene.layout.StackPane;
+import javafx.scene.layout.VBox;
+
+import java.util.List;
+
+public class DialogLayout extends VBox {
```
Comment (Brutus5000) [inline src/main/java/com/faforever/client/ui/dialog/DialogLayout.java:13]: A JavaDoc would be helpful here:
How is this different from a VBox?
When should this be used?
How to use this from SceneBuilder or fxml?

File: src/main/java/com/faforever/client/ui/transitions/CachedTransition.java [hunk 9]
```diff
@@ -0,0 +1,73 @@
...
+    statusProperty().addListener(observable -> {
+      switch (getStatus()) {
+        case RUNNING:
+          starting();
+          break;
+        default:
+          stopping();
+          break;
+      }
+    });
```
Comment (Brutus5000) [inline src/main/java/com/faforever/client/ui/transitions/CachedTransition.java]: If only one case is covered I'd prefer if/else

File: src/main/java/com/faforever/client/ui/transitions/CachedTransition.java [hunk 10]
```diff
@@ -0,0 +1,73 @@
...
+  }
+
+  protected void starting() {
+    if (mementos != null) {
+      for (CacheMemento memento : mementos) {
+        memento.cache();
+      }
+    }
+  }
```
Comment (Brutus5000) [inline src/main/java/com/faforever/client/ui/transitions/CachedTransition.java]: From what I see mementos can never be null.
Also I'd suggest `Arrays.stream(mementos).foreach(CacheMemento::cache)`

File: src/main/java/com/faforever/client/ui/transitions/CachedTransition.java [hunk 11]
```diff
@@ -0,0 +1,73 @@
...
+
+  protected void stopping() {
+    if (mementos != null) {
+      for (CacheMemento memento : mementos) {
+        memento.restore();
+      }
+    }
```
Comment (Brutus5000) [inline src/main/java/com/faforever/client/ui/transitions/CachedTransition.java]: From what I see mementos can never be null.
Also I'd suggest `Arrays.stream(mementos).foreach(CacheMemento::restore)`

File: src/main/java/com/faforever/client/ui/transitions/CachedTransition.java [hunk 12]
```diff
@@ -0,0 +1,73 @@
...
+    System.arraycopy(cacheMomentos, 0, mementos, node == null ? 0 : 1, cacheMomentos.length);
+    statusProperty().addListener(observable -> {
+      switch (getStatus()) {
+        case RUNNING:
+          starting();
+          break;
+        default:
+          stopping();
+          break;
+      }
```
Comment (Brutus5000) [inline src/main/java/com/faforever/client/ui/transitions/CachedTransition.java]: same here

File: src/main/java/com/faforever/client/FafClientApplication.java (hunk 1 above)
Comment (micheljung) [reply src/main/java/com/faforever/client/FafClientApplication.java]: How would that look like?

File: src/main/java/com/faforever/client/FafClientApplication.java (hunk 2 above)
Comment (micheljung) [reply src/main/java/com/faforever/client/FafClientApplication.java:137]: This code runs when the application is shutting down. Geosearchef added it to help finding which non-daemon threads keep the client alive. There isn't much to be handled

File: src/main/java/com/faforever/client/fx/IconCell.java (hunk 3 above)
Comment (micheljung) [reply src/main/java/com/faforever/client/fx/IconCell.java]: Unfortunately not, because of the varargs parameter

File: src/main/java/com/faforever/client/main/MainController.java (hunk 4 above)
Comment (micheljung) [reply src/main/java/com/faforever/client/main/MainController.java]: `ObservableList.setAll()` triggers one change event, repeatedly calling `add()` triggers multiple change events.

File: src/main/java/com/faforever/client/preferences/ui/RemovableListCellController.java (hunk 5 above)
Comment (micheljung) [reply src/main/java/com/faforever/client/preferences/ui/RemovableListCellController.java]: I was able to simplify this; it's now a ListCell that's a controller at the same time. Code is simpler and JavaDoc added.

File: src/main/java/com/faforever/client/ui/dialog/Dialog.java (hunk 6 above)
Comment (micheljung) [reply src/main/java/com/faforever/client/ui/dialog/Dialog.java:92]: `ReadOnlyProperty.getName()`:
> Returns the name of this property. If the property does not have a name, this method returns an empty String.

File: src/main/java/com/faforever/client/ui/dialog/Dialog.java (hunk 7 above)
Comment (micheljung) [reply src/main/java/com/faforever/client/ui/dialog/Dialog.java]: Dialog and Alert are ported from JFoenix. I cleaned up the code but didn't catch it all :-)

File: src/main/java/com/faforever/client/ui/dialog/DialogLayout.java (hunk 8 above)
Comment (micheljung) [reply src/main/java/com/faforever/client/ui/dialog/DialogLayout.java:13]: Ported from JFoenix. A DialogLayout has a header, a body and action buttons and is the content of a Dialog. Eventually, we might get rid of it but for now, we're transitioning away from JFoenix so we kept this class.

**Comment by norraxx** [comment]
Imho, there are too much changes at once.  141 files. Almost impossible to review.

File: src/main/java/com/faforever/client/main/MainController.java (hunk 4 above)
Comment (Brutus5000) [reply src/main/java/com/faforever/client/main/MainController.java]: Good to know

File: build.gradle [hunk 13]
```diff
@@ -300,7 +300,7 @@ dependencies {
 
   provided("com.install4j:install4j-runtime:${install4jRuntimeVersion}")
 
-  testCompile 'junit:junit:4.11'
+  testCompile 'junit:junit:4.13'
```
Comment (Brutus5000) [inline build.gradle:303]: Might to move to JUnit 5 which has full JUnit 4 backwards compatibility with junit-jupiter-vintage.
See API: https://github.com/FAForever/faf-java-api/blob/develop/build.gradle#L269
We should add an issue for that I guess.

**Review by Brutus5000 — DISMISSED** [review]

File: .travis.yml [hunk 14]
```diff
@@ -12,11 +12,11 @@ env:
     - secure: "UVIbeoJpx9n0KSWHbpdWZuR4zeZfXw3JQBq2Zb1h0/j4uREfXWiGFuNVQBPjsdtYi2+LkecjJ/MgKWo+SS0SjsvTa/ZPkOXt4408H1qYgwVnvWoeL/g1QQ6T8ADNysl/4ZtJLnSp0WXYEBkfHYZJD++vgDwkpVhnCLVzSFVAHls="
 
 before_install:
-  - export JDK="openjdk11"
+  - export JDK="openjdk14"
```
Comment (1-alex98) [inline .travis.yml:15]: How is changing to java 14 related to this.

File: src/main/java/com/faforever/client/replay/ReplayCardController.java [hunk 15]
```diff
@@ -101,7 +101,9 @@ public void setReplay(Replay replay) {
     Integer replayTicks = replay.getReplayTicks();
     if (replayTicks != null) {
       durationLabel.setText(timeService.shortDuration(Duration.ofMillis(replayTicks * 100)));
-      ((Label) durationLabel.getGraphic()).setText("");
+      // FIXME which icon was added in https://github.com/FAForever/downlords-faf-client/commit/58357c603eafead218ef7cceb8907e86c5d864b6#r40460680
+//      durationLabel.getGraphic().getStyleClass().remove("duration-icon");
+//      durationLabel.getGraphic().getStyleClass().remove("time-icon");
```
Comment (1-alex98) [inline src/main/java/com/faforever/client/replay/ReplayCardController.java:105]: Not sure what u mean here. But I guess u need to find out what icon corresponds to this unicode. I guess if u dont, then leave the old code and add the fix me

File: src/main/resources/i18n/messages.properties [hunk 16]
```diff
@@ -36,22 +31,18 @@ menu.revealLogFolder=Show log folder
...
 main.leaderboards=Leaderboards
 main.tournaments=Tournaments
-
 leaderboard.ranked1v1=1v1 Rating
 leaderboard.global=Global Rating
-
 play.custom=Custom games
 play.ranked1v1=1v1 ranked match
 play.coop=Co-Op
-
```
Comment (1-alex98) [inline src/main/resources/i18n/messages.properties:54]: Why delete?

File: src/main/resources/i18n/messages_es.properties [hunk 17]
```diff
@@ -649,12 +649,12 @@ map.couldNotUnrank = No se pudo desrankear el mapa.
...
-settings.appearance.backgoundImage = Imagen de fondo
+settings.appearance.backgroundImage = Imagen de fondo
 settings.appearance.useDefaultImage = Usar imagen por defecto
 settings.appearance.chooseImage = Elige una imagen
 settings.general.theme.useNoImage = Sin imagen
 query.notContains = no contiene
 coop.unknownMission = Misión desconocida
 game.couldNotJoin = No se pudo unir a la partida con el ID ''{0}''.
-discord.disallowJoins = No permitir a jugadores unirse a través de Discord
+settings.general.disallowDiscordJoins = No permitir a jugadores unirse a través de Discord
```
Comment (1-alex98) [inline src/main/resources/i18n/messages_es.properties:659]: Will be overwritten rename in poeeditor

File: src/main/resources/theme/icons.css [hunk 18]
```diff
@@ -0,0 +1,208 @@
...
+}
+
+.window-button .icon {
+  -fx-padding: 0;
+}
+
+.login-logo,
+.icon-faf {
+  -fx-shape: "M16 32c-8.837 0-16-7.163-16-16s7.163-16 16-16 16 7.163 16 16-7.163 16-16 16zM16 2.147c-7.651 0-13.853 6.202-13.853 13.853s6.202 13.853 13.853 13.853 13.853-6.202 13.853-13.853-6.202-13.853-13.853-13.853zM24.026 16.058l3.538 6.127h-2.256l-4.642-8.077h7.122l1.125 1.949h-4.886zM18.256 9.917h7.111l1.24 2.147h-7.117zM20.911 22.185l-1.684-2.917h-6.415l-1.684 2.917h-2.173l7.083-12.268h0.057l7.052 12.268h-2.235zM16.020 13.743l-1.78 3.083h3.56zM5.388 12.064l1.24-2.147h7.243l-1.24 2.147h-7.243zM6.787 22.185h-2.357l3.538-6.127h-4.886l1.125-1.949h7.243z";
+}
```
Comment (1-alex98) [inline src/main/resources/theme/icons.css:21]: Can u explain me how this works? How do I add anew icon?

**Review by 1-alex98 — CHANGES_REQUESTED** [review]
I should go test this

**Comment by 1-alex98** [comment]
Screenshot from 2020-07-10 20-25-24

**Comment by 1-alex98** [comment]
If we leave jdk 14 in we als need to test CI Pipeline building installers

File: build.gradle (hunk 13 above)
Comment (micheljung) [reply build.gradle:303]: Already there https://github.com/FAForever/downlords-faf-client/issues/305

File: .travis.yml (hunk 14 above)
Comment (micheljung) [reply .travis.yml:15]: Because I had various issues and tried if JavaFX 14 solves those. They didn't, but it seemed pointless to me to go back to 11 just to go forward to 14 later.

Plus, they fixed [Win: UNDECORATED windows are not minimized with the taskbar button](https://bugs.openjdk.java.net/browse/JDK-8088717) in 13 so I was able to remove our workaround (See #31).

File: src/main/java/com/faforever/client/replay/ReplayCardController.java (hunk 15 above)
Comment (micheljung) [reply src/main/java/com/faforever/client/replay/ReplayCardController.java:105]: Did you look at the discussion https://github.com/FAForever/downlords-faf-client/commit/58357c603eafead218ef7cceb8907e86c5d864b6#r40460680? An icon was added, but it was done by directly modifying the font rather than adding it via icomoon. This icon is lost in current client version and I wasn't even able to look it up using the font from his commit. So whether or not I leave the old code, there is no icon.

File: src/main/resources/i18n/messages.properties (hunk 16 above)
Comment (micheljung) [reply src/main/resources/i18n/messages.properties:54]: This was done by auto-formatting

File: src/main/resources/i18n/messages_es.properties (hunk 17 above)
Comment (micheljung) [reply src/main/resources/i18n/messages_es.properties:659]: Yes, unfortunately PoEditor won't detect the renames and the messages will have to be re-translated.
But it bothered me more that the naming convention wasn't followed ;-)

Comment (micheljung) [reply src/main/resources/i18n/messages_es.properties:659]: Or, mabye we can rename the message key in PoEditor before importing the the message.properties?

File: src/main/resources/theme/icons.css (hunk 18 above)
Comment (micheljung) [reply src/main/resources/theme/icons.css:21]: You can get the SVGPath string from icomoon:
95929fd1-1255-4f1c-89ab-f00733366a50

Or from the source code of SVGs. https://raw.githubusercontent.com/FAForever/Art-Assets/master/FAF-Logo.svg
Or build it yourself: https://yqnn.github.io/svg-path-editor/

`-fx-shape` will apply the shape to whatever component you choose. If it's a button, the button will have the SVG shape. We apply it to Regions like `<Region styleClass="icon,map-size-icon" />` and use this region as the graphic for the button.

The annoying thing about it is that either you set `-fx-scale-shape: false`, resulting in the "original" size being used (as specified in the SVGPath), which is rarely what you want. Or you set `-fx-scale-shape: true` resulting in the shape being adjusted to the region's size - without keeping the aspect ratio. So for each icon the dimensions must be specified.

However, the advantages are:
- No need to generate a font
- No need to keep the font and .json file in sync
- No dependency to icomoon
- Themes can easily replace individual icons. Right now, I don't even know how themes can set their own icons. The probably need to provide their own where the icons use the same unicode character, and set this font via CSS only for those nodes whose icon should be changed.
- It's a standard JavaFX mechanism

Comment (1-alex98) [reply src/main/resources/theme/icons.css:21]: Maybe we should turn this into a wiki page... ?

File: src/main/java/com/faforever/client/replay/ReplayCardController.java (hunk 15 above)
Comment (1-alex98) [reply src/main/java/com/faforever/client/replay/ReplayCardController.java:105]: ok

File: .travis.yml (hunk 14 above)
Comment (1-alex98) [reply .travis.yml:15]: Actually I could not find any issue so I think it is fine.

**Comment by 1-alex98** [comment]
Can we built an installer. Don't wanna merge it if it renders us unable to built releases and maybe it does... it changes the CI pipeline.

File: src/main/resources/theme/icons.css (hunk 18 above)
Comment (1-alex98) [reply src/main/resources/theme/icons.css:21]: https://github.com/FAForever/downlords-faf-client/wiki/Adding-Icons

**Comment by 1-alex98** [comment]
> Screenshot from 2020-07-10 20-25-24

What about this can u look into that what it comes from and make it look normal :D if we are already at it

**Review by 1-alex98 — DISMISSED** [review]
If we are still able to build installers like that

File: src/main/resources/i18n/messages.properties (hunk 16 above)
Comment (1-alex98) [reply src/main/resources/i18n/messages.properties:54]: Well so we leave it?

File: src/main/resources/i18n/messages_es.properties (hunk 17 above)
Comment (1-alex98) [reply src/main/resources/i18n/messages_es.properties:659]: Whatever will sort itself

**Comment by 1-alex98** [comment]
Rebased

**Comment by 1-alex98** [comment]
> > Screenshot from 2020-07-10 20-25-24
> 
> What about this can u look into that what it comes from and make it look normal :D if we are already at it

Added a fix for that

**Comment by 1-alex98** [comment]
Tell me if my change is ok and I am gonna merge

**Comment by 1-alex98** [comment]
I only ran this branch on Linux before but now I tested on windows:
```
Error:Abnormal build process termination: 
C:\Users\Alexander\.jdks\adopt-openj9-14.0.2\bin\java.exe -Xmx700m -Djava.awt.headless=true -Djdt.compiler.useSingleThread=true -Dpreload.project.path=C:/Users/Alexander/IdeaProjects/downlords-faf-client-2 -Dpreload.config.path=C:/Users/Alexander/AppData/Roaming/JetBrains/IntelliJIdea2020.1/options -Dcompile.parallel=false -Drebuild.on.dependency.change=true -Djava.net.preferIPv4Stack=true -Dio.netty.initialSeedUniquifier=6829968748887256284 -Dfile.encoding=windows-1252 -Duser.language=de -Duser.country=DE -Didea.paths.selector=IntelliJIdea2020.1 -Didea.home.path=C:\Users\Alexander\AppData\Local\JetBrains\Toolbox\apps\IDEA-U\ch-0\201.8538.31 -Didea.config.path=C:\Users\Alexander\AppData\Roaming\JetBrains\IntelliJIdea2020.1 -Didea.plugins.path=C:\Users\Alexander\AppData\Local\JetBrains\Toolbox\apps\IDEA-U\ch-0\201.8538.31.plugins -Djps.log.dir=C:/Users/Alexander/AppData/Local/JetBrains/IntelliJIdea2020.1/log/build-log -Djps.fallback.jdk.home=C:/Users/Alexander/AppData/Local/JetBrains/Toolbox/apps/IDEA-U/ch-0/201.8538.31/jbr -Djps.fallback.jdk.version=11.0.7 -Dio.netty.noUnsafe=true -Djava.io.tmpdir=C:/Users/Alexander/AppData/Local/JetBrains/IntelliJIdea2020.1/compile-server/downlords-faf-client_1736b4a8/_temp_ -Djps.backward.ref.index.builder=true -Dkotlin.incremental.compilation=true -Dkotlin.incremental.compilation.js=true -Dkotlin.daemon.enabled -Dkotlin.daemon.client.alive.path=\"C:\Users\ALEXAN~1\AppData\Local\Temp\kotlin-idea-8991772189271442946-is-running\" -classpath C:/Users/Alexander/AppData/Local/JetBrains/Toolbox/apps/IDEA-U/ch-0/201.8538.31/plugins/java/lib/jps-launcher.jar org.jetbrains.jps.cmdline.Launcher C:/Users/Alexander/AppData/Local/JetBrains/Toolbox/apps/IDEA-U/ch-0/201.8538.31/lib/lz4-java-1.7.1.jar;C:/Users/Alexander/AppData/Local/JetBrains/Toolbox/apps/IDEA-U/ch-0/201.8538.31/lib/jna-platform.jar;C:/Users/Alexander/AppData/Local/JetBrains/Toolbox/apps/IDEA-U/ch-0/201.8538.31/lib/maven-artifact-3.6.1.jar;C:/Users/Alexander/AppData/Local/JetBrains/Toolbox/apps/IDEA-U/ch-0/201.8538.31/plugins/java/lib/javac2.jar;C:/Users/Alexander/AppData/Local/JetBrains/Toolbox/apps/IDEA-U/ch-0/201.8538.31/plugins/java/lib/aether-dependency-resolver.jar;C:/Users/Alexander/AppData/Local/JetBrains/Toolbox/apps/IDEA-U/ch-0/201.8538.31/lib/protobuf-java-3.5.1.jar;C:/Users/Alexander/AppData/Local/JetBrains/Toolbox/apps/IDEA-U/ch-0/201.8538.31/plugins/java/lib/maven-resolver-transport-http-1.3.3.jar;C:/Users/Alexander/AppData/Local/JetBrains/Toolbox/apps/IDEA-U/ch-0/201.8538.31/lib/util.jar;C:/Users/Alexander/AppData/Local/JetBrains/Toolbox/apps/IDEA-U/ch-0/201.8538.31/lib/netty-buffer-4.1.47.Final.jar;C:/Users/Alexander/AppData/Local/JetBrains/Toolbox/apps/IDEA-U/ch-0/201.8538.31/lib/guava-28.2-jre.jar;C:/Users/Alexander/AppData/Local/JetBrains/Toolbox/apps/IDEA-U/ch-0/201.8538.31/plugins/java/lib/maven-resolver-connector-basic-1.3.3.jar;C:/Users/Alexander/AppData/Local/JetBrains/Toolbox/apps/IDEA-U/ch-0/201.8538.31/lib/maven-resolver-provider-3.6.1.jar;C:/Users/Alexander/AppData/Local/JetBrains/Toolbox/apps/IDEA-U/ch-0/201.8538.31/plugins/java/lib/maven-resolver-transport-file-1.3.3.jar;C:/Users/Alexander/AppData/Local/JetBrains/Toolbox/apps/IDEA-U/ch-0/201.8538.31/lib/netty-common-4.1.47.Final.jar;C:/Users/Alexander/AppData/Local/JetBrains/Toolbox/apps/IDEA-U/ch-0/201.8538.31/lib/netty-resolver-4.1.47.Final.jar;C:/Users/Alexander/AppData/Local/JetBrains/Toolbox/apps/IDEA-U/ch-0/201.8538.31/lib/maven-resolver-api-1.3.3.jar;C:/Users/Alexander/AppData/Local/JetBrains/Toolbox/apps/IDEA-U/ch-0/201.8538.31/lib/gson-2.8.6.jar;C:/Users/Alexander/AppData/Local/JetBrains/Toolbox/apps/IDEA-U/ch-0/201.8538.31/lib/trove4j.jar;C:/Users/Alexander/AppData/Local/JetBrains/Toolbox/apps/IDEA-U/ch-0/201.8538.31/lib/maven-resolver-impl-1.3.3.jar;C:/Users/Alexander/AppData/Local/JetBrains/Toolbox/apps/IDEA-U/ch-0/201.8538.31/lib/httpclient-4.5.12.jar;C:/Users/Alexander/AppData/Local/JetBrains/Toolbox/apps/IDEA-U/ch-0/201.8538.31/lib/resources_en.jar;C:/Users/Alexander/AppData/Local/JetBrains/Toolbox/apps/IDEA-U/ch-0/201.8538.31/lib/maven-resolver-util-1.3.3.jar;C:/Users/Alexander/AppData/Local/JetBrains/Toolbox/apps/IDEA-U/ch-0/201.8538.31/lib/jps-model.jar;C:/Users/Alexander/AppData/Local/JetBrains/Toolbox/apps/IDEA-U/ch-0/201.8538.31/lib/netty-codec-4.1.47.Final.jar;C:/Users/Alexander/AppData/Local/JetBrains/Toolbox/apps/IDEA-U/ch-0/201.8538.31/lib/maven-builder-support-3.6.1.jar;C:/Users/Alexander/AppData/Local/JetBrains/Toolbox/apps/IDEA-U/ch-0/201.8538.31/lib/maven-model-builder-3.6.1.jar;C:/Users/Alexander/AppData/Local/JetBrains/Toolbox/apps/IDEA-U/ch-0/201.8538.31/lib/commons-logging-1.2.jar;C:/Users/Alexander/AppData/Local/JetBrains/Toolbox/apps/IDEA-U/ch-0/201.8538.31/plugins/java/lib/jps-builders-6.jar;C:/Users/Alexander/AppData/Local/JetBrains/Toolbox/apps/IDEA-U/ch-0/201.8538.31/lib/maven-resolver-spi-1.3.3.jar;C:/Users/Alexander/AppData/Local/JetBrains/Toolbox/apps/IDEA-U/ch-0/201.8538.31/lib/nanoxml-2.2.3.jar;C:/Users/Alexander/AppData/Local/JetBrains/Toolbox/apps/IDEA-U/ch-0/201.8538.31/lib/asm-all-7.0.1.jar;C:/Users/Alexander/AppData/Local/JetBrains/Toolbox/apps/IDEA-U/ch-0/201.8538.31/lib/qdox-2.0-M10.jar;C:/Users/Alexander/AppData/Local/JetBrains/Toolbox/apps/IDEA-U/ch-0/201.8538.31/lib/commons-lang3-3.9.jar;C:/Users/Alexander/AppData/Local/JetBrains/Toolbox/apps/IDEA-U/ch-0/201.8538.31/lib/annotations.jar;C:/Users/Alexander/AppData/Local/JetBrains/Toolbox/apps/IDEA-U/ch-0/201.8538.31/lib/plexus-interpolation-1.25.jar;C:/Users/Alexander/AppData/Local/JetBrains/Toolbox/apps/IDEA-U/ch-0/201.8538.31/lib/netty-transport-4.1.47.Final.jar;C:/Users/Alexander/AppData/Local/JetBrains/Toolbox/apps/IDEA-U/ch-0/201.8538.31/lib/slf4j-api-1.7.25.jar;C:/Users/Alexander/AppData/Local/JetBrains/Toolbox/apps/IDEA-U/ch-0/201.8538.31/lib/log4j.jar;C:/Users/Alexander/AppData/Local/JetBrains/Toolbox/apps/IDEA-U/ch-0/201.8538.31/lib/plexus-utils-3.2.0.jar;C:/Users/Alexander/AppData/Local/JetBrains/Toolbox/apps/IDEA-U/ch-0/201.8538.31/lib/plexus-component-annotations-1.7.1.jar;C:/Users/Alexander/AppData/Local/JetBrains/Toolbox/apps/IDEA-U/ch-0/201.8538.31/lib/jna.jar;C:/Users/Alexander/AppData/Local/JetBrains/Toolbox/apps/IDEA-U/ch-0/201.8538.31/lib/jdom.jar;C:/Users/Alexander/AppData/Local/JetBrains/Toolbox/apps/IDEA-U/ch-0/201.8538.31/lib/forms-1.1-preview.jar;C:/Users/Alexander/AppData/Local/JetBrains/Toolbox/apps/IDEA-U/ch-0/201.8538.31/lib/httpcore-4.4.13.jar;C:/Users/Alexander/AppData/Local/JetBrains/Toolbox/apps/IDEA-U/ch-0/201.8538.31/lib/platform-api.jar;C:/Users/Alexander/AppData/Local/JetBrains/Toolbox/apps/IDEA-U/ch-0/201.8538.31/lib/oro-2.0.8.jar;C:/Users/Alexander/AppData/Local/JetBrains/Toolbox/apps/IDEA-U/ch-0/201.8538.31/lib/maven-model-3.6.1.jar;C:/Users/Alexander/AppData/Local/JetBrains/Toolbox/apps/IDEA-U/ch-0/201.8538.31/plugins/java/lib/jps-builders.jar;C:/Users/Alexander/AppData/Local/JetBrains/Toolbox/apps/IDEA-U/ch-0/201.8538.31/lib/maven-repository-metadata-3.6.1.jar;C:/Users/Alexander/AppData/Local/JetBrains/Toolbox/apps/IDEA-U/ch-0/201.8538.31/lib/idea_rt.jar;C:/Users/Alexander/AppData/Local/JetBrains/Toolbox/apps/IDEA-U/ch-0/201.8538.31/plugins/gradle/lib/gradle-api-6.1.1.jar;C:/Users/Alexander/AppData/Local/JetBrains/Toolbox/apps/IDEA-U/ch-0/201.8538.31/plugins/gradle/lib/gradle-api-impldep-6.1.1.jar;C:/Users/Alexander/AppData/Local/JetBrains/Toolbox/apps/IDEA-U/ch-0/201.8538.31/lib/ant/lib/ant.jar;C:/Users/Alexander/AppData/Local/JetBrains/Toolbox/apps/IDEA-U/ch-0/201.8538.31/lib/groovy-all-2.4.17.jar;C:/Users/Alexander/AppData/Local/JetBrains/Toolbox/apps/IDEA-U/ch-0/201.8538.31/lib/gson-2.8.6.jar;C:/Users/Alexander/AppData/Local/JetBrains/Toolbox/apps/IDEA-U/ch-0/201.8538.31/lib/slf4j-api-1.7.25.jar;C:/Users/Alexander/AppData/Local/JetBrains/Toolbox/apps/IDEA-U/ch-0/201.8538.31/lib/slf4j-log4j12-1.7.25.jar;C:/Users/Alexander/AppData/Local/JetBrains/Toolbox/apps/IDEA-U/ch-0/201.8538.31/plugins/JavaEE/lib/jasper-v2-rt.jar;C:/Users/Alexander/AppData/Local/JetBrains/Toolbox/apps/IDEA-U/ch-0/201.8538.31/lib/gson-2.8.6.jar;C:/Users/Alexander/AppData/Local/JetBrains/Toolbox/apps/IDEA-U/ch-0/201.8538.31/plugins/android/lib/jarutils.jar;C:/Users/Alexander/AppData/Local/JetBrains/Toolbox/apps/IDEA-U/ch-0/201.8538.31/lib/guava-28.2-jre.jar;C:/Users/Alexander/AppData/Local/JetBrains/Toolbox/apps/IDEA-U/ch-0/201.8538.31/plugins/android/lib/common-26.6.0.2.jar;C:/Users/Alexander/AppData/Local/JetBrains/Toolbox/apps/IDEA-U/ch-0/201.8538.31/plugins/gradle/lib/gradle-api-6.1.1.jar;C:/Users/Alexander/AppData/Local/JetBrains/Toolbox/apps/IDEA-U/ch-0/201.8538.31/lib/gson-2.8.6.jar;C:/Users/Alexander/AppData/Local/JetBrains/Toolbox/apps/IDEA-U/ch-0/201.8538.31/plugins/android/lib/jarutils.jar;C:/Users/Alexander/AppData/Local/JetBrains/Toolbox/apps/IDEA-U/ch-0/201.8538.31/lib/guava-28.2-jre.jar;C:/Users/Alexander/AppData/Local/JetBrains/Toolbox/apps/IDEA-U/ch-0/201.8538.31/plugins/android/lib/common-26.6.0.2.jar;C:/Users/Alexander/AppData/Local/JetBrains/Toolbox/apps/IDEA-U/ch-0/201.8538.31/plugins/gradle/lib/gradle-api-6.1.1.jar;C:/Users/Alexander/AppData/Local/JetBrains/Toolbox/apps/IDEA-U/ch-0/201.8538.31/plugins/IntelliLang/lib/intellilang-jps-plugin.jar;C:/Users/Alexander/AppData/Local/JetBrains/Toolbox/apps/IDEA-U/ch-0/201.8538.31/plugins/eclipse/lib/eclipse-jps-plugin.jar;C:/Users/Alexander/AppData/Local/JetBrains/Toolbox/apps/IDEA-U/ch-0/201.8538.31/plugins/eclipse/lib/common-eclipse-util.jar;C:/Users/Alexander/AppData/Local/JetBrains/Toolbox/apps/IDEA-U/ch-0/201.8538.31/plugins/ant/lib/ant-jps-plugin.jar;C:/Users/Alexander/AppData/Local/JetBrains/Toolbox/apps/IDEA-U/ch-0/201.8538.31/plugins/Groovy/lib/groovy-jps-plugin.jar;C:/Users/Alexander/AppData/Local/JetBrains/Toolbox/apps/IDEA-U/ch-0/201.8538.31/plugins/Groovy/lib/groovy-rt-constants.jar;C:/Users/Alexander/AppData/Local/JetBrains/Toolbox/apps/IDEA-U/ch-0/201.8538.31/plugins/maven/lib/maven-jps-plugin.jar;C:/Users/Alexander/AppData/Local/JetBrains/Toolbox/apps/IDEA-U/ch-0/201.8538.31/plugins/osmorc/lib/osmorc-jps-plugin.jar;C:/Users/Alexander/AppData/Local/JetBrains/Toolbox/apps/IDEA-U/ch-0/201.8538.31/plugins/osmorc/lib/biz.aQute.bndlib-5.0.0.jar;C:/Users/Alexander/AppData/Local/JetBrains/Toolbox/apps/IDEA-U/ch-0/201.8538.31/plugins/osmorc/lib/biz.aQute.repository-5.0.0.jar;C:/Users/Alexander/AppData/Local/JetBrains/Toolbox/apps/IDEA-U/ch-0/201.8538.31/plugins/osmorc/lib/biz.aQute.resolve-5.0.0.jar;C:/Users/Alexander/AppData/Local/JetBrains/Toolbox/apps/IDEA-U/ch-0/201.8538.31/plugins/osmorc/lib/bundlor-all.jar;C:/Users/Alexander/AppData/Local/JetBrains/Toolbox/apps/IDEA-U/ch-0/201.8538.31/plugins/aspectj/lib/aspectj-jps-plugin.jar;C:/Users/Alexander/AppData/Local/JetBrains/Toolbox/apps/IDEA-U/ch-0/201.8538.31/plugins/gradle-java/lib/gradle-jps-plugin.jar;C:/Users/Alexander/AppData/Local/JetBrains/Toolbox/apps/IDEA-U/ch-0/201.8538.31/plugins/javaFX/lib/javaFX-jps-plugin.jar;C:/Users/Alexander/AppData/Local/JetBrains/Toolbox/apps/IDEA-U/ch-0/201.8538.31/plugins/javaFX/lib/common-javaFX-plugin.jar;C:/Users/Alexander/AppData/Local/JetBrains/Toolbox/apps/IDEA-U/ch-0/201.8538.31/plugins/uiDesigner/lib/jps/ui-designer-jps-plugin.jar;C:/Users/Alexander/AppData/Local/JetBrains/Toolbox/apps/IDEA-U/ch-0/201.8538.31/plugins/devkit/lib/devkit-jps-plugin.jar;C:/Users/Alexander/AppData/Local/JetBrains/Toolbox/apps/IDEA-U/ch-0/201.8538.31/plugins/flex/lib/flex-jps-plugin.jar;C:/Users/Alexander/AppData/Local/JetBrains/Toolbox/apps/IDEA-U/ch-0/201.8538.31/plugins/flex/lib/flex-shared.jar;C:/Users/Alexander/AppData/Local/JetBrains/Toolbox/apps/IDEA-U/ch-0/201.8538.31/plugins/JavaEE/lib/javaee-jps-plugin.jar;C:/Users/Alexander/AppData/Local/JetBrains/Toolbox/apps/IDEA-U/ch-0/201.8538.31/plugins/JavaEE/lib/jps/jpa-jps-plugin.jar;C:/Users/Alexander/AppData/Local/JetBrains/Toolbox/apps/IDEA-U/ch-0/201.8538.31.plugins/Kotlin/lib/jps/kotlin-jps-plugin.jar;C:/Users/Alexander/AppData/Local/JetBrains/Toolbox/apps/IDEA-U/ch-0/201.8538.31.plugins/Kotlin/lib/kotlin-stdlib.jar;C:/Users/Alexander/AppData/Local/JetBrains/Toolbox/apps/IDEA-U/ch-0/201.8538.31.plugins/Kotlin/lib/kotlin-reflect.jar;C:/Users/Alexander/AppData/Local/JetBrains/Toolbox/apps/IDEA-U/ch-0/201.8538.31.plugins/Kotlin/lib/kotlin-plugin.jar;C:/Users/Alexander/AppData/Local/JetBrains/Toolbox/apps/IDEA-U/ch-0/201.8538.31/plugins/android/lib/jps/android-jps-plugin.jar;C:/Users/Alexander/AppData/Local/JetBrains/Toolbox/apps/IDEA-U/ch-0/201.8538.31/plugins/android/lib/android-common.jar;C:/Users/Alexander/AppData/Local/JetBrains/Toolbox/apps/IDEA-U/ch-0/201.8538.31/plugins/android/lib/build-common.jar;C:/Users/Alexander/AppData/Local/JetBrains/Toolbox/apps/IDEA-U/ch-0/201.8538.31/plugins/android/lib/android-rt.jar;C:/Users/Alexander/AppData/Local/JetBrains/Toolbox/apps/IDEA-U/ch-0/201.8538.31/plugins/android/lib/android-extensions-ide.jar;C:/Users/Alexander/AppData/Local/JetBrains/Toolbox/apps/IDEA-U/ch-0/201.8538.31/plugins/android/lib/sdk-common-26.6.0.2.jar;C:/Users/Alexander/AppData/Local/JetBrains/Toolbox/apps/IDEA-U/ch-0/201.8538.31/plugins/android/lib/common-26.6.0.2.jar;C:/Users/Alexander/AppData/Local/JetBrains/Toolbox/apps/IDEA-U/ch-0/201.8538.31/plugins/android/lib/repository-26.6.0.2.jar;C:/Users/Alexander/AppData/Local/JetBrains/Toolbox/apps/IDEA-U/ch-0/201.8538.31/plugins/android/lib/sdklib-26.6.0.2.jar;C:/Users/Alexander/AppData/Local/JetBrains/Toolbox/apps/IDEA-U/ch-0/201.8538.31/plugins/android/lib/jarutils.jar;C:/Users/Alexander/AppData/Local/JetBrains/Toolbox/apps/IDEA-U/ch-0/201.8538.31/plugins/android/lib/layoutlib-api-26.6.0.2.jar;C:/Users/Alexander/AppData/Local/JetBrains/Toolbox/apps/IDEA-U/ch-0/201.8538.31/plugins/android/lib/manifest-merger-26.6.0.2.jar;C:/Users/Alexander/AppData/Local/JetBrains/Toolbox/apps/IDEA-U/ch-0/201.8538.31/plugins/webSphereIntegration/lib/jps/webSphere-jps-plugin.jar;C:/Users/Alexander/AppData/Local/JetBrains/Toolbox/apps/IDEA-U/ch-0/201.8538.31/plugins/weblogicIntegration/lib/jps/weblogic-jps-plugin.jar;C:/Users/Alexander/AppData/Local/JetBrains/Toolbox/apps/IDEA-U/ch-0/201.8538.31/plugins/dmServer/lib/dmServer-jps-plugin.jar;C:/Users/Alexander/AppData/Local/JetBrains/Toolbox/apps/IDEA-U/ch-0/201.8538.31/plugins/GwtStudio/lib/gwt-jps-plugin.jar;C:/Users/Alexander/AppData/Local/JetBrains/Toolbox/apps/IDEA-U/ch-0/201.8538.31/plugins/Grails/lib/grails-jps-plugin.jar;C:/Users/Alexander/AppData/Local/JetBrains/Toolbox/apps/IDEA-U/ch-0/201.8538.31/plugins/Grails/lib/grails-compiler-patch.jar org.jetbrains.jps.cmdline.BuildMain 127.0.0.1 53090 6298b19b-6314-4b33-9914-9bf03f8d4686 C:/Users/Alexander/AppData/Local/JetBrains/IntelliJIdea2020.1/compile-server
Build process started. Classpath: C:/Users/Alexander/AppData/Local/JetBrains/Toolbox/apps/IDEA-U/ch-0/201.8538.31/plugins/java/lib/jps-launcher.jar
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.google.protobuf.UnsafeUtil (file:/C:/Users/Alexander/AppData/Local/JetBrains/Toolbox/apps/IDEA-U/ch-0/201.8538.31/lib/protobuf-java-3.5.1.jar) to field java.nio.Buffer.address
WARNING: Please consider reporting this to the maintainers of com.google.protobuf.UnsafeUtil
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
Unhandled exception
Type=Segmentation error vmState=0x00000000
Windows_ExceptionCode=c0000005 J9Generic_Signal=00000004 ExceptionAddress=00007FFB87670F44 ContextFlags=0010005f
Handler1=00007FFB8DE6EF90 Handler2=00007FFB8E63AB80 InaccessibleReadAddress=0000000000000001
RDI=0000000000000000 RSI=000000000009E600 RAX=000000000009E600 RBX=00000000D57BB658
RCX=00000000005B5500 RDX=0000000000000001 R8=000000000009E600 R9=00000000D57BB658
R10=00000000020E0002 R11=0000006757DFF7D0 R12=00000000FF4A0580 R13=00000000FF1B1548
R14=00000000D58B2F50 R15=0000000000006CBF
RIP=00007FFB87670F44 RSP=00000000005E0080 RBP=00000000005B5500 GS=002B
FS=0053 ES=002B DS=002B
XMM0 0000000000000005 (f: 5.000000, d: 2.470328e-323)
XMM1 0000000000000000 (f: 0.000000, d: 0.000000e+00)
XMM2 0000000000000000 (f: 0.000000, d: 0.000000e+00)
XMM3 0000000000000000 (f: 0.000000, d: 0.000000e+00)
XMM4 0000000000000000 (f: 0.000000, d: 0.000000e+00)
XMM5 0000000000000000 (f: 0.000000, d: 0.000000e+00)
XMM6 0000000000000000 (f: 0.000000, d: 0.000000e+00)
```
Windows 10 
AMD Processor
Nothing speical really
Using ADOPT OPEN JDK 14

**Comment by 1-alex98** [comment]
image

**Comment by 1-alex98** [comment]
Was fixed by deleting cache

**Comment by Katharsas** [comment]
Seeing the changes made to IntelliJ-specific files, please make sure the client still works correctly when running gradle from command line without using IntelliJ, when the necessary vm options are added.

**Comment by 1-alex98** [comment]
I rebased and fixed all major issues

**Comment by 1-alex98** [comment]
I plan on merging this in soon TM, so that it does not lie here forever.

**Comment by 1-alex98** [comment]
After I fixed the tests

**Review by 1-alex98 — DISMISSED** [review]
good if test run through

**Comment by 1-alex98** [comment]
It seems we can not package a jre 14 with Install4j 7 and we would probably need intsall4j 8

**Comment by 1-alex98** [comment]
https://github.com/FAForever/downlords-faf-client/releases/tag/v1.2.0-RC1

**Review by Sheikah45 — COMMENTED** [review]
Screenshot (40)

I noticed a few small visual details that could be fixed. that are shown in the image. Note the X is not there on any of the detail cards for map, mods, or replays.

Also it seems that all the replays are being reported as not rate and I am not sure if some change here affected that.

**Comment by Sheikah45** [comment]
Screenshot (41)
 Error messages take over the entire window

**Comment by 1-alex98** [comment]
https://github.com/FAForever/downlords-faf-client/issues/1860

**Comment by 1-alex98** [comment]
coop mission icons are missing

**Comment by 1-alex98** [comment]
Now coop icons are there and have colour

**Comment by 1-alex98** [comment]
@Sheikah45 @micheljung seems like we fixed most of it right?

What is missing is that the dialogs span over the whole window.

> image

**Comment by 1-alex98** [comment]
grafik
Only thing left I know is the scroll bar in the alert dialogs

**Review by Sheikah45 — COMMENTED** [review]
Looks good to me. I was not able to find any issues beyond the known one with the scrollbar for the text in the error

**Comment by 1-alex98** [comment]
Also gotta figure out why the pipline fails

**Comment by 1-alex98** [comment]
@Sheikah45 I think me and @micheljung will try fix the error with the users having scale 125%. If you want to u can probably join us. 20:00 MEST

**Comment by Sheikah45** [comment]
Ah sorry I missed it was at work. Also as note I am trying with the fix but get an error that it cant find ch.micheljung.fxstage:fxstage:0.7.3 for compilation

**Comment by micheljung** [comment]
@axel1200 said there's still something wrong

**Comment by 1-alex98** [comment]
Posted it on Zulip

**Comment by 1-alex98** [comment]
grafik

**Comment by 1-alex98** [comment]
@micheljung maybe we can llok at it together I already looked at it. I know what's wong but I am not to sure how it should be done
