### PR TITLE
Show the correct rating in replay detail

### LINKED ISSUE #704: Wrong kind of ratings in replay detail
In the replay detail view the custom game ratings are shown even if it is a 1v1 game. Also the current Rating is shown and not the one at the time of the game. Change that.... You can calculate the correct rating from the playerstats of tht game ;)

### PR DESCRIPTION
**Pull request by 20seven**
Changed teamcard so that it displays the ratings of each player during that particular replay.
Fixes #704

### CODE REVIEW

**Review by 1-alex98 — DISMISSED** [review]
Well done

**Comment by 1-alex98** [comment]
Did you check if the teamcards still work correctly in the Play Tab?

**Comment by 20seven** [comment]
@axel1200 Yeah it did however show the exact rating instead of rounding it. Thought it was fine first but it looks a lot cleaner with rounded ratings in play tab. I'd still want exact rating in replaydetails because it makes the ratingchangelabel more useful imo. So last commit just allows us to define if we want to use exact or rounded ratings when showing teams.

**Review by 1-alex98 — DISMISSED** [review]
🔝

**Comment by 1-alex98** [comment]
@micheljung your turn

**Comment by micheljung** [comment]
To make sure the code is properly formatted, please enable the following options in the commit dialog:
image

For now, you'll have to manually format them (CTRL+ALT+L) :)

**Comment by 1-alex98** [comment]
or  make soft reset and recommit

**Comment by 20seven** [comment]
I think that should've fixed the formatting. @micheljung

**Review by 1-alex98 — DISMISSED** [review]

File: src/main/java/com/faforever/client/game/PlayerCardTooltipController.java [hunk 1]
```diff
@@ -31,12 +31,16 @@ public PlayerCardTooltipController(CountryFlagService countryFlagService, I18n i
   }
 
   public void setPlayer(Player player) {
+    setPlayerWithRating(player, RatingUtil.getRoundedGlobalRating(player));
+  }
+
+  public void setPlayerWithRating(Player player, int rating) {
```
Comment (micheljung) [inline src/main/java/com/faforever/client/game/PlayerCardTooltipController.java]: I suggest that we remove `setPlayer()` and introduce an enum `RatingMode` with values `EXACT` and `ROUNDED`.
This can then be passed to this method instead of `rating`, reducing the complexity and putting the rating calculation into one place.

File: src/main/java/com/faforever/client/game/TeamCardController.java [hunk 2]
```diff
@@ -59,25 +59,31 @@ public static void createAndAdd(ObservableMap<? extends String, ? extends List<S
...
       TeamCardController teamCardController = uiService.loadFxml("theme/team_card.fxml");
       teamCardController.setPlayersInTeam(entry.getKey(), players,
-          player -> new Rating(player.getGlobalRatingMean(), player.getGlobalRatingDeviation()));
+          player -> new Rating(player.getGlobalRatingMean(), player.getGlobalRatingDeviation()), true);
       teamsPane.getChildren().add(teamCardController.getRoot());
     }
   }
 
-  public void setPlayersInTeam(String team, List<Player> playerList, Function<Player, Rating> ratingProvider) {
+  public void setPlayersInTeam(String team, List<Player> playerList, Function<Player, Rating> ratingProvider, boolean useRoundedRating) {
```
Comment (micheljung) [inline src/main/java/com/faforever/client/game/TeamCardController.java]: `useRoundedRating` can then be replaced by the new enum. Note also how the enum allows multiple values while boolean only allow two, and how passing `RatingMode.ROUNDED` is more expressive than passing `true`.

File: src/main/java/com/faforever/client/game/TeamCardController.java [hunk 3]
```diff
@@ -59,25 +59,31 @@ public static void createAndAdd(ObservableMap<? extends String, ? extends List<S
...
         continue;
       }
       PlayerCardTooltipController playerCardTooltipController = uiService.loadFxml("theme/player_card_tooltip.fxml");
-      playerCardTooltipController.setPlayer(player);
+      int playerRating = RatingUtil.getRating(ratingProvider.apply(player));
+      if (useRoundedRating) {
+        playerCardTooltipController.setPlayer(player);
+      } else {
+        playerCardTooltipController.setPlayerWithRating(player, playerRating);
+      }
```
Comment (micheljung) [inline src/main/java/com/faforever/client/game/TeamCardController.java]: This `if` assumes that `setPlayer` will round the rating, but that might not be true. Neither is the assumption that `setPlayerWithRating` will not round it.

By passing the new enum parameter, we fix this.

**Review by micheljung — CHANGES_REQUESTED** [review]

**Review by micheljung — APPROVED** [review]
