### PR TITLE
Fix that player info was not displayed on side window when opening a private channel

### LINKED ISSUE #3423: [Bug]: No information about a player on side window in private channel
### Describe the Bug

Description in the issue title

### Log file or Error Message

No error in log file

### Reproduce the bug

Open a private channel with any player

### Expected Behavior

All information about a player are visible on side window

### Screenshots

_No response_

### Additional context

_No response_

### Which Operating System are you using?

Windows

### PR DESCRIPTION
**Pull request by Marc-Spector**
Closes #3423 

## Summary by CodeRabbit

* **Refactor**
  * Private chat now uses live player data, improving avatar, online-status, rating and achievement displays.
  * UI now reacts to player updates directly, so info refreshes reliably when the other player’s state changes.
* **Tests**
  * Tests updated to validate the new player-driven behavior and UI updates, including online player lookup and rating/achievement scenarios.

### CODE REVIEW

File: src/main/java/com/faforever/client/player/PrivatePlayerInfoController.java [hunk 1]
```diff
@@ -63,7 +63,8 @@ public class PrivatePlayerInfoController extends NodeController<Node> {
   public Label unlockedAchievementsLabel;
   public Separator separator;
 
-  private final ObjectProperty<ChatChannelUser> chatUser = new SimpleObjectProperty<>();
+  @Getter
```
Comment (Sheikah45) [inline src/main/java/com/faforever/client/player/PrivatePlayerInfoController.java]: This can't use lombok getter as that is the wrong convention. Thee property method is just playerProperty and the field is just player

**Comment by Marc-Spector** [comment]
@coderabbitai review

**Comment by Marc-Spector** [comment]
@coderabbitai resolve

**Review by Sheikah45 — COMMENTED** [review]
Do you know why the player property in chatUser was unreliable?

**Comment by Marc-Spector** [comment]
The `player` property works reliably.
The problem is exactly how private chat works.  When you open the chat (for example, with `qwerty` player), you are completely alone in the list of users.
https://github.com/FAForever/downlords-faf-client/blob/9e640109d7c423cea732c286f2973e83214e87f0/src/main/java/com/faforever/client/chat/ChatChannel.java#L38-L43

The `qwerty` player name is not on the map or in the list. That's why you don't get the `ChatChannelUser` object.

https://github.com/FAForever/downlords-faf-client/blob/9e640109d7c423cea732c286f2973e83214e87f0/src/main/java/com/faforever/client/chat/PrivateChatTabController.java#L49-L50

https://github.com/FAForever/downlords-faf-client/blob/9e640109d7c423cea732c286f2973e83214e87f0/src/main/java/com/faforever/client/chat/ChatChannel.java#L144-L146

The player will be on the list when he responds to your messages or you have a message history (I have not tested this case)

**Review by Sheikah45 — APPROVED** [review]
