### PR TITLE
Avoid selecting invalid SortProperty

### LINKED ISSUE #1194: Vault replay search criteria not working
The search criteria are not working for the online replay section of the Vault.

There is a least two problems 

* Search button doesn't work, nothing happens when we click on it.
* Sort by doesn't work, it doesn't expand when we click on it.

Edit:
It seems to happen because somehow the value I had stored in my configuration for the sort field isn't present anymore in the sort choices. I don't know how I managed to do that.

Still I have a fix that could prevent such case, is it necessary ?

### PR DESCRIPTION
**Pull request by CyrilPaulus**
Fixes #1194

### CODE REVIEW

**Review by 1-alex98 — APPROVED** [review]

File: src/main/java/com/faforever/client/vault/search/SearchController.java [hunk 1]
```diff
@@ -126,7 +126,14 @@ public void setSearchableProperties(Map<String, String> searchableProperties) {
   public void setSortConfig(ObjectProperty<SortConfig> sortConfigObjectProperty) {
     sortPropertyComboBox.getItems().addAll(searchableProperties.values());
     sortOrderChoiceBox.getSelectionModel().select(sortConfigObjectProperty.get().getSortOrder());
-    sortPropertyComboBox.getSelectionModel().select(searchableProperties.get(sortConfigObjectProperty.get().getSortProperty()));
+
+    String savedSortProperty = searchableProperties.get(sortConfigObjectProperty.get().getSortProperty());
+    
+    if (savedSortProperty == null)
+        savedSortProperty = searchableProperties.values().iterator().next();
```
Comment (micheljung) [inline src/main/java/com/faforever/client/vault/search/SearchController.java:133]: Please enable automatic source code formatting in the commit dialog.

Comment (micheljung) [reply src/main/java/com/faforever/client/vault/search/SearchController.java:133]: Also, there's no need to explicitly select something. The following code would've been simpler and not abuse the variable:

```suggestion
    if (savedSortProperty != null) {
      sortPropertyComboBox.getSelectionModel().select(savedSortProperty);
    }
```
