### PR TITLE
Fix game listeners in game detail in private chat of player

### LINKED ISSUE #2665: The button has empty text in a private channel of an user
**To Reproduce**
1. Open private chat with any host.
2. Wait when host run a game.

**Expected behavior**
I think the button should have `Watchable in %time%` text

**Screenshots**
image

**OS**
Windows

### LINKED ISSUE #2666: A private chat of an user continues to show an already finished game
**To Reproduce**
1. Open private chat with any player that playing a game now.
2. Wait when player finish the game

**OS**
Windows

Client Version: 2022.4.0-alpha1

### LINKED ISSUE #2675: Game detail do not clear after FAF reconnecting (auto or manual) in custom games tab

### PR DESCRIPTION
**Pull request by Marc-Spector**
Closes #2665
Closes #2666
Closes #2675

### CODE REVIEW

File: src/main/java/com/faforever/client/game/GameDetailController.java [hunk 1]
```diff
@@ -167,6 +146,22 @@ public void resetListeners() {
...
+        .map(GameBean::getStartTime)
+        .ifPresentOrElse(startTime -> JavaFxUtil.runLater(() -> {
+              watchButtonController.setGame(game.get());
+              joinButton.setVisible(false);
+              watchButton.setVisible(true);
+            }),
+            () -> JavaFxUtil.runLater(() -> {
+              joinButton.setVisible(game.get() != null && game.get().getStatus() == GameStatus.OPEN);
+              watchButton.setVisible(false);
+            }));
```
Comment (Sheikah45) [inline src/main/java/com/faforever/client/game/GameDetailController.java]: There is no real reason to put this inside an optional. I would just do a null check at the beginning and just return if null rather than wrapping in an optional as this just creates an object for little benefit.

**Review by Sheikah45 — CHANGES_REQUESTED** [review]

**Comment by Marc-Spector** [comment]
`testCharacterLimit` test fixed in #2668

**Review by Sheikah45 — APPROVED** [review]
